


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapTonTN')
   
exec('CREATE PROCEDURE spCapNhapTonTN AS BEGIN SET NOCOUNT ON; END')

GO

--SELECT * FROM dbo.VTPT_TON
ALTER PROC spCapNhapTonTN 
    @NgayHT DATE = '01/21/2021'
AS
BEGIN

SET NOCOUNT ON;
BEGIN TRY

   
   
DECLARE @sSql NVARCHAR(MAX)
CREATE TABLE #VTTonTmp   (
	[NGAY_VTPT] DATE,
	[MS_VTPT] NVARCHAR(255) ,
	[TEN_VTPT] [NVARCHAR](255) ,
	[DVT] [NVARCHAR](255) ,
	[SL_TON] [FLOAT] ,
	[GT_TON] [FLOAT] 
)

--insert du lieu từ excel vào table tam
set @sSql = N'INSERT INTO #VTTonTmp(NGAY_VTPT, MS_VTPT, TEN_VTPT, DVT, SL_TON, GT_TON)
SELECT ''' + CONVERT(NVARCHAR(10),@NgayHT,101) + N''' AS NGAY,LTRIM(RTRIM(STR([Mã VTPT]))), [Tên VTPT], ĐVT, [Số Lượng tồn], [Giá trị tồn]  
FROM OPENROWSET(''Microsoft.ACE.OLEDB.12.0'',''Excel 12.0;DATABASE=D:\TON' + REPLACE(convert(NVARCHAR(10), @NgayHT, 120), '-', '')  + N'.xlsx; HDR=YES;IMEX=1'', 
''Select * from  [Sheet1$] WHERE [Số Lượng tồn] > 0 '')'
EXEC (@sSql)

--insert du lieu từ table tam vào table tồn TN theo đúng ngày
DELETE dbo.VTPT_TON WHERE CONVERT(DATE,NGAY) = CONVERT(DATE,@NgayHT)
INSERT INTO dbo.VTPT_TON(ID,NGAY, VTPT, TEN_VTPT, DVT, SL_TON, GIA_TRI_TON,DG,MS_PT)
SELECT DISTINCT  ROW_NUMBER() OVER(PARTITION BY NGAY_VTPT ORDER BY NGAY_VTPT,T1.MS_VTPT) AS STT , 
T1.NGAY_VTPT, T1.MS_VTPT, T1.TEN_VTPT, T1.DVT, T1.SL_TON, T1.GT_TON, ISNULL(T1.SL_TON,0) * ISNULL(T1.GT_TON,0) AS DG,T2.MS_PT
FROM #VTTonTmp T1 LEFT JOIN dbo.IC_PHU_TUNG T2 ON T1.MS_VTPT = T2.MS_PT_CTY
ORDER BY NGAY_VTPT,T1.MS_VTPT

--cập nhập vào table đơn hàng nhập
DECLARE @MsDHN NVARCHAR(50)
SELECT TOP 1 @MsDHN = MS_DH_NHAP_PT FROM dbo.IC_DON_HANG_NHAP WHERE GHI_CHU = 'CNTon' ORDER BY MS_DH_NHAP_PT ASC

DECLARE	@TiGia FLOAT,@TiGiaUSD FLOAT,@MsVT INT

SELECT TOP 1 @MsVT= MS_VI_TRI FROM dbo.VI_TRI_KHO WHERE MS_KHO = (SELECT MS_KHO FROM dbo.IC_DON_HANG_NHAP WHERE MS_DH_NHAP_PT = @MsDHN)

SELECT @TiGia = T1.TI_GIA, @TiGiaUSD = T1.TI_GIA_USD FROM dbo.TI_GIA_NT T1 INNER JOIN (
SELECT NGOAI_TE, MAX(NGAY) AS  NGAY_MAX FROM dbo.TI_GIA_NT WHERE NGOAI_TE = 'VND' AND NGAY < = GETDATE() GROUP BY NGOAI_TE) T2 ON T1.NGOAI_TE = T2.NGOAI_TE AND T1.NGAY = T2.NGAY_MAX

--Xoa du lieu nhập + tồn theo đúng PN
DELETE dbo.VI_TRI_KHO_VAT_TU WHERE MS_DH_NHAP_PT = @MsDHN
DELETE dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET WHERE MS_DH_NHAP_PT = @MsDHN
DELETE dbo.IC_DON_HANG_NHAP_VAT_TU WHERE MS_DH_NHAP_PT = @MsDHN

--Insert du lieu mới  PN
INSERT INTO	dbo.IC_DON_HANG_NHAP_VAT_TU(MS_DH_NHAP_PT, MS_PT, ID, SO_LUONG_CTU, SL_THUC_NHAP, DON_GIA, NGOAI_TE, TY_GIA, TY_GIA_USD, MS_VT_NCC, THANH_TIEN, GHI_CHU, MS_PT_CT, TEN_PT_CT, MS_DH_NHAP_PT_GOC, ID_GOC, DON_GIA_GOC)
SELECT @MsDHN AS MS_DH_NHAP_PT,T1.MS_PT AS MS_PT, ID, T1.SL_TON AS SO_LUONG_CTU, T1.SL_TON AS SL_THUC_NHAP, T1.GIA_TRI_TON AS DON_GIA, 'VND' AS NGOAI_TE ,@TiGia AS TY_GIA ,@TiGiaUSD AS TY_GIA_USD, T1.VTPT AS MS_VT_NCC,  ISNULL(T1.SL_TON,0) * ISNULL(T1.GIA_TRI_TON,0) AS THANH_TIEN, 'Cập nhật tồn ngày ' +  CONVERT(NVARCHAR(10),@NgayHT,103) AS GHI_CHU,T1.VTPT AS MS_PT_CT,T1.TEN_VTPT AS TEN_PT_CT, @MsDHN AS MS_DH_NHAP_PT_GOC,  ID AS ID_GOC,T1.GIA_TRI_TON AS DON_GIA_GOC
FROM dbo.VTPT_TON T1 WHERE ISNULL(T1.MS_PT,'') <> ''  AND  CONVERT(DATE,T1.NGAY) = CONVERT(DATE,@NgayHT)


INSERT INTO	dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET(MS_DH_NHAP_PT, MS_PT, MS_VI_TRI, ID, SL_VT)
SELECT @MsDHN AS MS_DH_NHAP_PT,T1.MS_PT AS MS_PT,@MsVT AS MS_VI_TRI, ID, T1.SL_TON AS SL_VT
FROM dbo.VTPT_TON T1  WHERE ISNULL(T1.MS_PT,'') <> '' AND  CONVERT(DATE,T1.NGAY) = CONVERT(DATE,@NgayHT)

	RAISERROR(N'Done.' , 0, 1);
	
END TRY
BEGIN CATCH
	RAISERROR('Not OK.', 0, 1);

END CATCH

END