

CREATE TABLE [dbo].[VTPT_TON](
	[NGAY] [DATE] NOT NULL,
	[MS_PT] [NVARCHAR](50) NULL,
	[ID] [INT] NULL,
	[VTPT] [NVARCHAR](50) NULL,
	[TEN_VTPT] [NVARCHAR](500) NULL,
	[DVT] [NVARCHAR](50) NULL,
	[SL_TON] [FLOAT] NULL,
	[GIA_TRI_TON] [FLOAT] NULL,
	[DG] [FLOAT] NULL
) ON [PRIMARY]
GO


