IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDuyetSanXuat' AND KEYWORD =N'msgVuiLongNhapYKiemKhongDuyet') UPDATE LANGUAGES SET VIETNAM=N'Vui lòng nhập lý do không duyệt', ENGLISH=N'Vui lòng nhập lý do không duyệt',CHINESE=N'Vui lòng nhập lý do không duyệt', VIETNAM_OR=N'Vui lòng nhập lý do không duyệt', ENGLISH_OR=N'Vui lòng nhập lý do không duyệt' , CHINESE_OR=N'Vui lòng nhập lý do không duyệt' WHERE FORM=N'frmDuyetSanXuat' AND KEYWORD=N'msgVuiLongNhapYKiemKhongDuyet' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDuyetSanXuat',N'msgVuiLongNhapYKiemKhongDuyet',N'Vui lòng nhập lý do không duyệt',N'Vui lòng nhập lý do không duyệt',N'Vui lòng nhập lý do không duyệt',N'Vui lòng nhập lý do không duyệt',N'Vui lòng nhập lý do không duyệt',N'Vui lòng nhập lý do không duyệt','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauBT' AND KEYWORD =N'msgNhapYKienBoQua') UPDATE LANGUAGES SET VIETNAM=N'Vui lòng nhập lý do bỏ qua', ENGLISH=N'Vui lòng nhập lý do bỏ qua',CHINESE=N'Vui lòng nhập lý do bỏ qua', VIETNAM_OR=N'Vui lòng nhập lý do bỏ qua', ENGLISH_OR=N'Vui lòng nhập lý do bỏ qua' , CHINESE_OR=N'Vui lòng nhập lý do bỏ qua' WHERE FORM=N'frmYeuCauBT' AND KEYWORD=N'msgNhapYKienBoQua' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeuCauBT',N'msgNhapYKienBoQua',N'Vui lòng nhập lý do bỏ qua',N'Vui lòng nhập lý do bỏ qua',N'Vui lòng nhập lý do bỏ qua',N'Vui lòng nhập lý do bỏ qua',N'Vui lòng nhập lý do bỏ qua',N'Vui lòng nhập lý do bỏ qua','ECOMAIN')


UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'1-GĐ chưa duyệt' WHERE MS_TTRANG = 0
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'2-GĐ không thuận duyệt' WHERE MS_TTRANG = 1
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'3-GĐ đã duyệt, chờ BT giải quyết' WHERE MS_TTRANG = 2
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'4-BT hủy yêu cầu' WHERE MS_TTRANG = 3
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'5-BT chờ do thiếu VTPT, NS, PP, KH, …' WHERE MS_TTRANG = 4
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'6-BT kết hợp với KH BT sắp tới' WHERE MS_TTRANG = 5
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'7-BT đang thực hiện sữa chữa' WHERE MS_TTRANG = 6
UPDATE TINH_TRANG_YCSD SET TEN_TTRANG = N'8-BT đã hoàn thành y/c' WHERE MS_TTRANG = 7




IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThongtinthietbi' AND KEYWORD =N'lblTenMay') UPDATE LANGUAGES SET VIETNAM=N'Tên thiết bị', ENGLISH=N'Equipment name',CHINESE=N'Equipment name', VIETNAM_OR=N'Tên thiết bị', ENGLISH_OR=N'Equipment name' , CHINESE_OR=N'Equipment name' WHERE FORM=N'frmThongtinthietbi' AND KEYWORD=N'lblTenMay' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmThongtinthietbi',N'lblTenMay',N'Tên thiết bị',N'Equipment name',N'Equipment name',N'Tên thiết bị',N'Equipment name',N'Equipment name','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThongtinthietbi' AND KEYWORD =N'lblMSMAY') UPDATE LANGUAGES SET VIETNAM=N'Mã thiết bị', ENGLISH=N'Equipment ID',CHINESE=N'Equipment ID', VIETNAM_OR=N'Mã thiết bị', ENGLISH_OR=N'Equipment ID' , CHINESE_OR=N'Equipment ID' WHERE FORM=N'frmThongtinthietbi' AND KEYWORD=N'lblMSMAY' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmThongtinthietbi',N'lblMSMAY',N'Mã thiết bị',N'Equipment ID',N'Equipment ID',N'Mã thiết bị',N'Equipment ID',N'Equipment ID','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThongtinthietbi' AND KEYWORD =N'lblDNgay') UPDATE LANGUAGES SET VIETNAM=N'Đến ngày', ENGLISH=N'To',CHINESE=N'To', VIETNAM_OR=N'Đến ngày', ENGLISH_OR=N'To' , CHINESE_OR=N'To' WHERE FORM=N'frmThongtinthietbi' AND KEYWORD=N'lblDNgay' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmThongtinthietbi',N'lblDNgay',N'Đến ngày',N'To',N'To',N'Đến ngày',N'To',N'To','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThongtinthietbi' AND KEYWORD =N'lblTNgay') UPDATE LANGUAGES SET VIETNAM=N'Từ ngày', ENGLISH=N'From',CHINESE=N'From', VIETNAM_OR=N'Từ ngày', ENGLISH_OR=N'From' , CHINESE_OR=N'From' WHERE FORM=N'frmThongtinthietbi' AND KEYWORD=N'lblTNgay' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmThongtinthietbi',N'lblTNgay',N'Từ ngày',N'From',N'From',N'Từ ngày',N'From',N'From','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThongtinthietbi' AND KEYWORD =N'sTDLSTB') UPDATE LANGUAGES SET VIETNAM=N'LỊCH SỬ THIẾT BỊ', ENGLISH=N'LỊCH SỬ THIẾT BỊ',CHINESE=N'LỊCH SỬ THIẾT BỊ', VIETNAM_OR=N'LỊCH SỬ THIẾT BỊ', ENGLISH_OR=N'LỊCH SỬ THIẾT BỊ' , CHINESE_OR=N'LỊCH SỬ THIẾT BỊ' WHERE FORM=N'frmThongtinthietbi' AND KEYWORD=N'sTDLSTB' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmThongtinthietbi',N'sTDLSTB',N'LỊCH SỬ THIẾT BỊ',N'LỊCH SỬ THIẾT BỊ',N'LỊCH SỬ THIẾT BỊ',N'LỊCH SỬ THIẾT BỊ',N'LỊCH SỬ THIẾT BỊ',N'LỊCH SỬ THIẾT BỊ','ECOMAIN')



IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDeXuatMuaHang_New' AND KEYWORD =N'lblTongDeXuat') UPDATE LANGUAGES SET VIETNAM=N'Tổng vật tư đề xuất : ', ENGLISH=N'Tổng vật tư đề xuất : ',CHINESE=N'Tổng vật tư đề xuất : ', VIETNAM_OR=N'Tổng vật tư đề xuất : ', ENGLISH_OR=N'Tổng vật tư đề xuất : ' , CHINESE_OR=N'Tổng vật tư đề xuất : ' WHERE FORM=N'frmDeXuatMuaHang_New' AND KEYWORD=N'lblTongDeXuat' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDeXuatMuaHang_New',N'lblTongDeXuat',N'Tổng vật tư đề xuất : ',N'Tổng vật tư đề xuất : ',N'Tổng vật tư đề xuất : ',N'Tổng vật tư đề xuất : ',N'Tổng vật tư đề xuất : ',N'Tổng vật tư đề xuất : ','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDeXuatMuaHang_New' AND KEYWORD =N'lblTongHoanThanh') UPDATE LANGUAGES SET VIETNAM=N'Tổng vật tư hoàn thành : ', ENGLISH=N'Tổng vật tư hoàn thành : ',CHINESE=N'Tổng vật tư hoàn thành : ', VIETNAM_OR=N'Tổng vật tư hoàn thành : ', ENGLISH_OR=N'Tổng vật tư hoàn thành : ' , CHINESE_OR=N'Tổng vật tư hoàn thành : ' WHERE FORM=N'frmDeXuatMuaHang_New' AND KEYWORD=N'lblTongHoanThanh' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDeXuatMuaHang_New',N'lblTongHoanThanh',N'Tổng vật tư hoàn thành : ',N'Tổng vật tư hoàn thành : ',N'Tổng vật tư hoàn thành : ',N'Tổng vật tư hoàn thành : ',N'Tổng vật tư hoàn thành : ',N'Tổng vật tư hoàn thành : ','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDeXuatMuaHang_New' AND KEYWORD =N'lblPhanTramHT') UPDATE LANGUAGES SET VIETNAM=N'Phần trăm hoàn thành : ', ENGLISH=N'Phần trăm hoàn thành : ',CHINESE=N'Phần trăm hoàn thành : ', VIETNAM_OR=N'Phần trăm hoàn thành : ', ENGLISH_OR=N'Phần trăm hoàn thành : ' , CHINESE_OR=N'Phần trăm hoàn thành : ' WHERE FORM=N'frmDeXuatMuaHang_New' AND KEYWORD=N'lblPhanTramHT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDeXuatMuaHang_New',N'lblPhanTramHT',N'Phần trăm hoàn thành : ',N'Phần trăm hoàn thành : ',N'Phần trăm hoàn thành : ',N'Phần trăm hoàn thành : ',N'Phần trăm hoàn thành : ',N'Phần trăm hoàn thành : ','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmBCYeuCauNSD' AND KEYWORD =N'lblTYCSC') UPDATE LANGUAGES SET VIETNAM=N'Tổng số yêu cầu', ENGLISH=N'Tổng số yêu cầu',CHINESE=N'Tổng số yêu cầu', VIETNAM_OR=N'Tổng số yêu cầu', ENGLISH_OR=N'Tổng số yêu cầu' , CHINESE_OR=N'Tổng số yêu cầu' WHERE FORM=N'frmBCYeuCauNSD' AND KEYWORD=N'lblTYCSC' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmBCYeuCauNSD',N'lblTYCSC',N'Tổng số yêu cầu',N'Tổng số yêu cầu',N'Tổng số yêu cầu',N'Tổng số yêu cầu',N'Tổng số yêu cầu',N'Tổng số yêu cầu','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'' AND KEYWORD =N'') UPDATE LANGUAGES SET VIETNAM=N'', ENGLISH=N'',CHINESE=N'', VIETNAM_OR=N'', ENGLISH_OR=N'' , CHINESE_OR=N'' WHERE FORM=N'' AND KEYWORD=N'' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'',N'',N'',N'',N'',N'',N'',N'','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'TIEU_DE') UPDATE LANGUAGES SET VIETNAM=N'BIÊN BẢN NGHIỆM THU VẬT TƯ', ENGLISH=N'BIÊN BẢN NGHIỆM THU VẬT TƯ',CHINESE=N'BIÊN BẢN NGHIỆM THU VẬT TƯ', VIETNAM_OR=N'BIÊN BẢN NGHIỆM THU VẬT TƯ', ENGLISH_OR=N'BIÊN BẢN NGHIỆM THU VẬT TƯ' , CHINESE_OR=N'BIÊN BẢN NGHIỆM THU VẬT TƯ' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'TIEU_DE' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'TIEU_DE',N'BIÊN BẢN NGHIỆM THU VẬT TƯ',N'BIÊN BẢN NGHIỆM THU VẬT TƯ',N'BIÊN BẢN NGHIỆM THU VẬT TƯ',N'BIÊN BẢN NGHIỆM THU VẬT TƯ',N'BIÊN BẢN NGHIỆM THU VẬT TƯ',N'BIÊN BẢN NGHIỆM THU VẬT TƯ','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'NGUOI_NHAP') UPDATE LANGUAGES SET VIETNAM=N'Nhà cung cấp', ENGLISH=N'Nhà cung cấp',CHINESE=N'Nhà cung cấp', VIETNAM_OR=N'Nhà cung cấp', ENGLISH_OR=N'Nhà cung cấp' , CHINESE_OR=N'Nhà cung cấp' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'NGUOI_NHAP' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'NGUOI_NHAP',N'Nhà cung cấp',N'Nhà cung cấp',N'Nhà cung cấp',N'Nhà cung cấp',N'Nhà cung cấp',N'Nhà cung cấp','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'NGAY_NHAP_KHO') UPDATE LANGUAGES SET VIETNAM=N'Ngày giao hàng : ', ENGLISH=N'Ngày giao hàng : ',CHINESE=N'Ngày giao hàng : ', VIETNAM_OR=N'Ngày giao hàng : ', ENGLISH_OR=N'Ngày giao hàng : ' , CHINESE_OR=N'Ngày giao hàng : ' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'NGAY_NHAP_KHO' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'NGAY_NHAP_KHO',N'Ngày giao hàng : ',N'Ngày giao hàng : ',N'Ngày giao hàng : ',N'Ngày giao hàng : ',N'Ngày giao hàng : ',N'Ngày giao hàng : ','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'NO') UPDATE LANGUAGES SET VIETNAM=N'Mã số : F/P2/QA-02', ENGLISH=N'Mã số : F/P2/QA-02',CHINESE=N'Mã số : F/P2/QA-02', VIETNAM_OR=N'Mã số : F/P2/QA-02', ENGLISH_OR=N'Mã số : F/P2/QA-02' , CHINESE_OR=N'Mã số : F/P2/QA-02' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'NO' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'NO',N'Mã số : F/P2/QA-02',N'Mã số : F/P2/QA-02',N'Mã số : F/P2/QA-02',N'Mã số : F/P2/QA-02',N'Mã số : F/P2/QA-02',N'Mã số : F/P2/QA-02','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'SO_ISO') UPDATE LANGUAGES SET VIETNAM=N'Ngày hiệu lực : 15/06/2017', ENGLISH=N'Ngày hiệu lực : 15/06/2017',CHINESE=N'Ngày hiệu lực : 15/06/2017', VIETNAM_OR=N'Ngày hiệu lực : 15/06/2017', ENGLISH_OR=N'Ngày hiệu lực : 15/06/2017' , CHINESE_OR=N'Ngày hiệu lực : 15/06/2017' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'SO_ISO' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'SO_ISO',N'Ngày hiệu lực : 15/06/2017',N'Ngày hiệu lực : 15/06/2017',N'Ngày hiệu lực : 15/06/2017',N'Ngày hiệu lực : 15/06/2017',N'Ngày hiệu lực : 15/06/2017',N'Ngày hiệu lực : 15/06/2017','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'CO') UPDATE LANGUAGES SET VIETNAM=N'Phiên bản : 1.4', ENGLISH=N'Phiên bản : 1.4',CHINESE=N'Phiên bản : 1.4', VIETNAM_OR=N'Phiên bản : 1.4', ENGLISH_OR=N'Phiên bản : 1.4' , CHINESE_OR=N'Phiên bản : 1.4' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'CO' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'CO',N'Phiên bản : 1.4',N'Phiên bản : 1.4',N'Phiên bản : 1.4',N'Phiên bản : 1.4',N'Phiên bản : 1.4',N'Phiên bản : 1.4','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'DON_GIA') UPDATE LANGUAGES SET VIETNAM=N'Kết quả kiểm tra', ENGLISH=N'Kết quả kiểm tra',CHINESE=N'Kết quả kiểm tra', VIETNAM_OR=N'Kết quả kiểm tra', ENGLISH_OR=N'Kết quả kiểm tra' , CHINESE_OR=N'Kết quả kiểm tra' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'DON_GIA' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'DON_GIA',N'Kết quả kiểm tra',N'Kết quả kiểm tra',N'Kết quả kiểm tra',N'Kết quả kiểm tra',N'Kết quả kiểm tra',N'Kết quả kiểm tra','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'THANH_TIEN') UPDATE LANGUAGES SET VIETNAM=N'Ghi chú', ENGLISH=N'Note',CHINESE=N'Note', VIETNAM_OR=N'Ghi chú', ENGLISH_OR=N'Note' , CHINESE_OR=N'Note' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'THANH_TIEN' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'THANH_TIEN',N'Ghi chú',N'Note',N'Note',N'Ghi chú',N'Note',N'Note','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'TRUONG_DON_VI') UPDATE LANGUAGES SET VIETNAM=N'Trưởng đơn vị sử dụng', ENGLISH=N'Trưởng đơn vị sử dụng',CHINESE=N'Trưởng đơn vị sử dụng', VIETNAM_OR=N'Trưởng đơn vị sử dụng', ENGLISH_OR=N'Trưởng đơn vị sử dụng' , CHINESE_OR=N'Trưởng đơn vị sử dụng' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'TRUONG_DON_VI' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'TRUONG_DON_VI',N'Trưởng đơn vị sử dụng',N'Trưởng đơn vị sử dụng',N'Trưởng đơn vị sử dụng',N'Trưởng đơn vị sử dụng',N'Trưởng đơn vị sử dụng',N'Trưởng đơn vị sử dụng','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'NGUOI_LAP') UPDATE LANGUAGES SET VIETNAM=N'Tổ nghiệm thu', ENGLISH=N'Tổ nghiệm thu',CHINESE=N'Tổ nghiệm thu', VIETNAM_OR=N'Tổ nghiệm thu', ENGLISH_OR=N'Tổ nghiệm thu' , CHINESE_OR=N'Tổ nghiệm thu' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'NGUOI_LAP' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'NGUOI_LAP',N'Tổ nghiệm thu',N'Tổ nghiệm thu',N'Tổ nghiệm thu',N'Tổ nghiệm thu',N'Tổ nghiệm thu',N'Tổ nghiệm thu','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'SO_PHIEU_NHAP') UPDATE LANGUAGES SET VIETNAM=N'Số phiếu nhập :', ENGLISH=N'Goods receipt No :',CHINESE=N'Goods receipt No :', VIETNAM_OR=N'Số phiếu nhập :', ENGLISH_OR=N'Goods receipt No :' , CHINESE_OR=N'Goods receipt No :' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'SO_PHIEU_NHAP' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'SO_PHIEU_NHAP',N'Số phiếu nhập :',N'Goods receipt No :',N'Goods receipt No :',N'Số phiếu nhập :',N'Goods receipt No :',N'Goods receipt No :','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'NGUOI_NHAP') UPDATE LANGUAGES SET VIETNAM=N'Nhà cung cấp : ', ENGLISH=N'Vendor :',CHINESE=N'Vendor :', VIETNAM_OR=N'Nhà cung cấp : ', ENGLISH_OR=N'Vendor :' , CHINESE_OR=N'Vendor :' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'NGUOI_NHAP' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'NGUOI_NHAP',N'Nhà cung cấp : ',N'Vendor :',N'Vendor :',N'Nhà cung cấp : ',N'Vendor :',N'Vendor :','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'SO_CHUNG_TU') UPDATE LANGUAGES SET VIETNAM=N'Số chứng từ :', ENGLISH=N'Document No :',CHINESE=N'Document No :', VIETNAM_OR=N'Số chứng từ :', ENGLISH_OR=N'Document No :' , CHINESE_OR=N'Document No :' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'SO_CHUNG_TU' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'SO_CHUNG_TU',N'Số chứng từ :',N'Document No :',N'Document No :',N'Số chứng từ :',N'Document No :',N'Document No :','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'DANG_NHAP') UPDATE LANGUAGES SET VIETNAM=N'Dạng nhập : ', ENGLISH=N'Type of receipt :',CHINESE=N'Type of receipt :', VIETNAM_OR=N'Dạng nhập : ', ENGLISH_OR=N'Type of receipt :' , CHINESE_OR=N'Type of receipt :' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'DANG_NHAP' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'DANG_NHAP',N'Dạng nhập : ',N'Type of receipt :',N'Type of receipt :',N'Dạng nhập : ',N'Type of receipt :',N'Type of receipt :','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'GHI_CHU_DH_NHAP_PT') UPDATE LANGUAGES SET VIETNAM=N'Ghi chú : ', ENGLISH=N'Note : ',CHINESE=N'Note : ', VIETNAM_OR=N'Ghi chú : ', ENGLISH_OR=N'Note : ' , CHINESE_OR=N'Note : ' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'GHI_CHU_DH_NHAP_PT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'GHI_CHU_DH_NHAP_PT',N'Ghi chú : ',N'Note : ',N'Note : ',N'Ghi chú : ',N'Note : ',N'Note : ','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD =N'TEN_KHO') UPDATE LANGUAGES SET VIETNAM=N'Kho :', ENGLISH=N'Warehouse :',CHINESE=N'Warehouse :', VIETNAM_OR=N'Kho :', ENGLISH_OR=N'Warehouse :' , CHINESE_OR=N'Warehouse :' WHERE FORM=N'rptPhieuNhapKhoNew' AND KEYWORD=N'TEN_KHO' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPhieuNhapKhoNew',N'TEN_KHO',N'Kho :',N'Warehouse :',N'Warehouse :',N'Kho :',N'Warehouse :',N'Warehouse :','ECOMAIN')
