
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spInLichSuThietBi')
   
exec('CREATE PROCEDURE spInLichSuThietBi AS BEGIN SET NOCOUNT ON; END')

GO

ALTER PROCEDURE spInLichSuThietBi
	@MsMay NVARCHAR(50) = '-1',
    @TNgay DATETIME = '01/01/2000',
	@DNgay DATETIME = '01/01/2022'
AS
BEGIN
   


SELECT CONVERT(DATE,NGAY_BD_KH) AS NGAY_BD_KH, T1.MS_PHIEU_BAO_TRI, T2.TEN_LOAI_BT, 
 dbo.MGetListAllCNhanPBT (MS_PHIEU_BAO_TRI) AS NVBT, 
T3.TEN_TINH_TRANG, T1.TT_SAU_BT AS GHI_CHU	 FROM dbo.PHIEU_BAO_TRI T1 INNER JOIN dbo.LOAI_BAO_TRI T2 ON T2.MS_LOAI_BT = T1.MS_LOAI_BT INNER JOIN dbo.TINH_TRANG_PBT T3 ON T3.STT = T1.TINH_TRANG_PBT
WHERE (CONVERT(DATE,NGAY_BD_KH) BETWEEN @TNgay AND @DNgay) AND (T1.MS_MAY = @MsMay OR @MsMay = '-1')
UNION

SELECT CONVERT(DATE,T1.NGAY_HC) AS NGAY_HC, '' AS MS_PHIEU_BAO_TRI, N'Hiệu chuẩn máy' AS TEN_LOAI_BT, T1.CO_QUAN_HIEU_CHUAN, T1.GIAY_CHUNG_NHAN AS TEN_TINH_TRANG, T1.DANH_GIA  FROM dbo.HIEU_CHUAN_MAY T1
WHERE (CONVERT(DATE,T1.NGAY_HC) BETWEEN @TNgay AND @DNgay) AND (T1.MS_MAY = @MsMay OR @MsMay = '-1')
--UNION
--SELECT CONVERT(DATE,T1.NGAY) AS NGAY_HC, '' AS MS_PHIEU_BAO_TRI, N'Hiệu chuẩn dụng cụ đo' AS TEN_LOAI_BT, T1.CO_QUAN_HIEU_CHUAN, T1.GIAY_CHUNG_NHAN AS TEN_TINH_TRANG, T1.DANH_GIA  FROM dbo.HIEU_CHUAN_DHD T1
--WHERE (CONVERT(DATE,T1.NGAY) BETWEEN @TNgay AND @DNgay) AND (T1.MS_MAY = @MsMay OR @MsMay = '-1')
ORDER BY NGAY_BD_KH

--SELECT * FROM dbo.HIEU_CHUAN_DHD

END
