
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spUpdateAutoXuatDeXuat')
   exec('CREATE PROCEDURE spUpdateAutoXuatDeXuat AS BEGIN SET NOCOUNT ON; END')
 GO
ALTER PROCEDURE [dbo].[spUpdateAutoXuatDeXuat]
  @MS_DH_XUAT_PT NVARCHAR(14) ='PX-2105-0001',
  @MS_DH_NHAP_PT NVARCHAR(14) ='PN-2105-0003'
AS
BEGIN
DELETE dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET WHERE  MS_DH_XUAT_PT =@MS_DH_XUAT_PT
DELETE dbo.IC_DON_HANG_XUAT_VAT_TU WHERE  MS_DH_XUAT_PT =@MS_DH_XUAT_PT
DELETE dbo.IC_DON_HANG_XUAT WHERE  MS_DH_XUAT_PT =@MS_DH_XUAT_PT
---insert phiếu xuất kho
INSERT INTO dbo.IC_DON_HANG_XUAT(MS_DH_XUAT_PT,SO_PHIEU_XN,GIO,NGAY,MS_KHO,MS_DANG_XUAT,NGUOI_NHAN,NGAY_CHUNG_TU,SO_CHUNG_TU,MS_PHIEU_BAO_TRI,
GHI_CHU,LOCK,LY_DO_XUAT,THU_KHO,MS_BP_CHIU_PHI,MS_MAY,NGUOI_LAP,CAN_CU,THU_KHO_KY,MS_KHO_DEN)
SELECT @MS_DH_XUAT_PT,@MS_DH_XUAT_PT,GIO,NGAY,MS_KHO,3,NGUOI_NHAP,NGAY_CHUNG_TU,ISNULL(SO_CHUNG_TU,''),''
,ISNULL(GHI_CHU,''),1,ISNULL(LY_DO,''),THU_KHO,'','',NGUOI_NHAP,ISNULL(CAN_CU,''),ISNULL(THU_KHO_KY,''),-1
FROM dbo.IC_DON_HANG_NHAP WHERE MS_DH_NHAP_PT = @MS_DH_NHAP_PT  

INSERT INTO dbo.IC_DON_HANG_XUAT_VAT_TU(MS_DH_XUAT_PT,MS_PT,SO_LUONG_CTU,SO_LUONG_THUC_XUAT,GHI_CHU,TG_PB,CHI_PHI,MS_PT_CT,TEN_PT_CT)
SELECT @MS_DH_XUAT_PT,MS_PT,SO_LUONG_CTU,SL_THUC_NHAP,GHI_CHU,0,0,MS_PT_CT,TEN_PT_CT FROM dbo.IC_DON_HANG_NHAP_VAT_TU WHERE MS_DH_NHAP_PT = @MS_DH_NHAP_PT

INSERT INTO dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET(MS_DH_XUAT_PT,MS_PT,STT,MS_DH_NHAP_PT,MS_VI_TRI,SL_VT,ID_XUAT)
SELECT @MS_DH_XUAT_PT,MS_PT,1,MS_DH_NHAP_PT,MS_VI_TRI,SL_VT,ID FROM dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET WHERE MS_DH_NHAP_PT =@MS_DH_NHAP_PT
END




