
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spUpdateAutoNhap')
   exec('CREATE PROCEDURE spUpdateAutoNhap AS BEGIN SET NOCOUNT ON; END')
 GO
ALTER PROCEDURE [dbo].[spUpdateAutoNhap]
  @MS_DH_XUAT_PT NVARCHAR(14) ='PX-2101-0004',
  @MS_DH_NHAP_PT NVARCHAR(14) ='PN-2105-0016'
AS
BEGIN

DELETE dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET WHERE  MS_DH_NHAP_PT = @MS_DH_NHAP_PT
DELETE dbo.IC_DON_HANG_NHAP_VAT_TU WHERE  MS_DH_NHAP_PT = @MS_DH_NHAP_PT
DELETE dbo.IC_DON_HANG_NHAP WHERE  MS_DH_NHAP_PT = @MS_DH_NHAP_PT


INSERT INTO dbo.IC_DON_HANG_NHAP(MS_DH_NHAP_PT,SO_PHIEU_XN,GIO,NGAY,MS_KHO,MS_DANG_NHAP,NGUOI_NHAP,NGAY_CHUNG_TU,SO_CHUNG_TU,GHI_CHU,LOCK,THU_KHO,LY_DO,CAN_CU,THU_KHO_KY,NGUOI_LAP,MS_DH_XUAT_PT,MS_DHX)
SELECT @MS_DH_NHAP_PT,@MS_DH_NHAP_PT,GIO,NGAY,MS_KHO,2,NGUOI_NHAN,NGAY_CHUNG_TU,SO_CHUNG_TU,GHI_CHU,1,THU_KHO,LY_DO_XUAT,CAN_CU,THU_KHO_KY,NGUOI_LAP,MS_DH_XUAT_PT,@MS_DH_XUAT_PT FROM dbo.IC_DON_HANG_XUAT WHERE MS_DH_XUAT_PT = @MS_DH_XUAT_PT


INSERT INTO dbo.IC_DON_HANG_NHAP_VAT_TU (MS_DH_NHAP_PT,MS_PT,ID,SO_LUONG_CTU,SL_THUC_NHAP,DON_GIA,NGOAI_TE,TY_GIA,TY_GIA_USD,MS_VT_NCC,THANH_TIEN,GHI_CHU,MS_PT_CT,TEN_PT_CT,TAX,MS_DH_NHAP_PT_GOC,ID_GOC,DON_GIA_GOC)
SELECT  @MS_DH_NHAP_PT,MS_PT,(ROW_NUMBER() OVER(ORDER BY MS_PT)) + (SELECT MAX(ID) FROM dbo.IC_DON_HANG_NHAP_VAT_TU),SO_LUONG_CTU,SO_LUONG_THUC_XUAT,(SELECT TOP 1  DON_GIA FROM IC_DON_HANG_NHAP_VAT_TU WHERE MS_PT = A.MS_PT ORDER BY MS_DH_NHAP_PT  DESC) as DON_GIA,'VND',1,5.72E-05,
(SELECT TOP 1  MS_PT_CTY FROM dbo.IC_PHU_TUNG WHERE MS_PT = A.MS_PT ),ROUND(A.SO_LUONG_CTU * (SELECT TOP 1  DON_GIA FROM IC_DON_HANG_NHAP_VAT_TU WHERE MS_PT = A.MS_PT ORDER BY MS_DH_NHAP_PT  DESC),2) ,GHI_CHU,MS_PT_CT,
TEN_PT_CT,0, (SELECT MS_DH_NHAP_PT FROM dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET WHERE MS_PT = A.MS_PT AND MS_DH_XUAT_PT = @MS_DH_XUAT_PT) ,(ROW_NUMBER() OVER(ORDER BY MS_PT)) + (SELECT MAX(ID) FROM dbo.IC_DON_HANG_NHAP_VAT_TU),(SELECT TOP 1  DON_GIA FROM IC_DON_HANG_NHAP_VAT_TU WHERE MS_PT = A.MS_PT ORDER BY MS_DH_NHAP_PT  DESC)  FROM dbo.IC_DON_HANG_XUAT_VAT_TU A WHERE MS_DH_XUAT_PT = @MS_DH_XUAT_PT

INSERT INTO dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET(MS_DH_NHAP_PT,MS_PT,MS_VI_TRI,ID,SL_VT)
SELECT @MS_DH_NHAP_PT,MS_PT,MS_VI_TRI,(SELECT ID FROM IC_DON_HANG_NHAP_VAT_TU WHERE MS_DH_NHAP_PT = @MS_DH_NHAP_PT AND MS_PT = A.MS_PT ),SL_VT FROM dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET A WHERE A.MS_DH_XUAT_PT = @MS_DH_XUAT_PT
END


