IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetTRANSFER_TO')
   exec('CREATE PROCEDURE GetTRANSFER_TO AS BEGIN SET NOCOUNT ON; END')
GO

ALTER proc GetTRANSFER_TO
AS

select * FROM TRANSFER_TO