


IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'IN_DOWNTIME') and Object_ID = Object_ID(N'NGUYEN_NHAN_DUNG_MAY'))
BEGIN
		ALTER TABLE NGUYEN_NHAN_DUNG_MAY ADD  IN_DOWNTIME INT DEFAULT 0
END

GO

update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 1 WHERE MS_NGUYEN_NHAN = 2
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 2 WHERE MS_NGUYEN_NHAN = 3
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 3 WHERE MS_NGUYEN_NHAN = 6
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 4 WHERE MS_NGUYEN_NHAN = 1
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 5 WHERE MS_NGUYEN_NHAN = 4
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 6 WHERE MS_NGUYEN_NHAN = 5
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 7 WHERE MS_NGUYEN_NHAN = 7
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 8 WHERE MS_NGUYEN_NHAN = 15
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 9 WHERE MS_NGUYEN_NHAN = 16
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 10 WHERE MS_NGUYEN_NHAN = 17
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 11 WHERE MS_NGUYEN_NHAN = 8
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 12 WHERE MS_NGUYEN_NHAN = 10
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 13 WHERE MS_NGUYEN_NHAN = 9
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 14 WHERE MS_NGUYEN_NHAN = 11
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 15 WHERE MS_NGUYEN_NHAN = 12
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 16 WHERE MS_NGUYEN_NHAN = 13
update NGUYEN_NHAN_DUNG_MAY SET IN_DOWNTIME = 17 WHERE MS_NGUYEN_NHAN = 14

