--
-- spBaoCaoDownTime 0,'06/01/2017','06/30/2017', '15' , -1,-1, 'ADMIN',0
ALTER proc [dbo].[spBaoCaoDownTime]
	@Loai INT,
	@TNgay DATETIME,
	@DNgay DATETIME,
	@MS_NHA_XUONG nvarchar(50),
	@MsHThong INT,
	@MS_LOAI_MAY nvarchar(50),
	@USERNAME  nvarchar(50),
	@NNgu int
AS
begin

CREATE TABLE #MAY_USER
(
	MS_MAY NVARCHAR(50),
	TEN_MAY NVARCHAR(500) NULL
)
IF(@MS_NHA_XUONG <> '-1')
BEGIN
		INSERT INTO #MAY_USER SELECT DISTINCT MS_MAY, TEN_MAY FROM dbo.MGetMayUserNgay(@DNgay, @USERNAME, '-1', @MsHThong, -1,@MS_LOAI_MAY, -1,-1, @NNgu) WHERE MS_N_XUONG IN (SELECT Item FROM dbo.UDF_ConvertListItem2Table(@MS_NHA_XUONG,','))
END
ELSE
BEGIN
		INSERT INTO #MAY_USER SELECT DISTINCT MS_MAY, TEN_MAY FROM dbo.MGetMayUserNgay(@DNgay, @USERNAME, '-1', @MsHThong, -1,@MS_LOAI_MAY, -1,-1, @NNgu) 
END


SELECT DISTINCT T1.NGAY, CASE @Loai WHEN 0 THEN SUM(T1.THOI_GIAN_SUA_CHUA) ELSE SUM(T1.THOI_GIAN_SUA) END AS TONG_DT INTO #TONG_DT
FROM            dbo.THOI_GIAN_NGUNG_MAY AS T1 INNER JOIN
                         dbo.MAY AS T4 ON T1.MS_MAY = T4.MS_MAY INNER JOIN
                         dbo.THOI_GIAN_NGUNG_MAY_SO_LAN AS T2 ON T1.MS_LAN = T2.MS_LAN
WHERE CONVERT(DATE,T1.NGAY) BETWEEN @TNgay AND @DNgay
GROUP BY T1.NGAY

SELECT DISTINCT T1.NGAY, COUNT (T1.NGAY) AS SLDT INTO #TONG_SL
FROM            dbo.THOI_GIAN_NGUNG_MAY_SO_LAN AS T1 INNER JOIN
                         #MAY_USER AS T4 ON T1.MS_MAY = T4.MS_MAY
WHERE CONVERT(DATE,T1.NGAY) BETWEEN @TNgay AND @DNgay
GROUP BY T1.NGAY


SELECT DISTINCT DAY(T1.NGAY) AS STT,
CONVERT(DATE, T1.NGAY, 101) NGAY ,CONVERT(FLOAT,TONG_DT) AS TONG_DT, T2.CA, T1.TRUONG_CA, T1.NGUOI_GIAI_QUYET, CONVERT(TIME,T1.TU_GIO) AS TU_GIO, CONVERT(TIME,T1.DEN_GIO) AS DEN_GIO,
CASE @Loai WHEN 0 THEN T1.THOI_GIAN_SUA_CHUA ELSE T1.THOI_GIAN_SUA END AS THOI_GIAN_SUA_CHUA
,   T1.MS_MAY, TEN_MAY, T3.TEN_NGUYEN_NHAN, 
                         T1.HIEN_TUONG, T1.NGUYEN_NHAN_CU_THE, T1.NGUYEN_NHAN,
						 SLDT
FROM            dbo.THOI_GIAN_NGUNG_MAY AS T1 INNER JOIN
                         dbo.CA AS T2 ON T1.CaID = T2.STT INNER JOIN
                         dbo.NGUYEN_NHAN_DUNG_MAY AS T3 ON T1.MS_NGUYEN_NHAN = T3.MS_NGUYEN_NHAN INNER JOIN
                         #MAY_USER AS T4 ON T1.MS_MAY = T4.MS_MAY LEFT JOIN #TONG_DT T5 ON T1.NGAY = T5.NGAY
						 LEFT JOIN #TONG_SL T6 ON T1.NGAY = T6.NGAY
WHERE CONVERT(DATE,T1.NGAY, 101) BETWEEN @TNgay AND @DNgay
ORDER BY NGAY, T2.CA, MS_MAY

END