
-- spBaoCaoDownTime 0,'05/01/2017','05/30/2017', '10' , -1,-1, 'ADMIN',0
ALTER proc [dbo].[spBaoCaoDownTime]
 @Loai INT,
 @TNgay DATETIME,
 @DNgay DATETIME,
 @MS_NHA_XUONG nvarchar(50),
 @MsHThong INT,
 @MS_LOAI_MAY nvarchar(50),
 @USERNAME  nvarchar(50),
 @NNgu int
AS
begin



CREATE TABLE #MAY_USER
(
 MS_MAY NVARCHAR(50),
 TEN_MAY NVARCHAR(500) NULL
)
IF(@MS_NHA_XUONG <> '-1')
BEGIN
  INSERT INTO #MAY_USER SELECT DISTINCT MS_MAY, TEN_MAY FROM dbo.MGetMayUserNgay(@DNgay, @USERNAME, '-1', @MsHThong, -1,@MS_LOAI_MAY, -1,-1, @NNgu) WHERE MS_N_XUONG IN (SELECT Item FROM dbo.UDF_ConvertListItem2Table(@MS_NHA_XUONG,','))
END
ELSE
BEGIN
  INSERT INTO #MAY_USER SELECT DISTINCT MS_MAY, TEN_MAY FROM dbo.MGetMayUserNgay(@DNgay, @USERNAME, '-1', @MsHThong, -1,@MS_LOAI_MAY, -1,-1, @NNgu) 
END


SELECT   

CONVERT(DATETIME,
CASE ISNULL(T2.CA_DEM,0) WHEN 0 THEN CONVERT(DATE, T1.NGAY, 101)  ELSE 
 CASE WHEN CONVERT(TIME,T1.TU_GIO) BETWEEN '00:00:00' AND '06:00:00' THEN
  DATEADD(DAY,-1, CONVERT(DATE, T1.NGAY, 101)) 
 ELSE
  CONVERT(DATE, T1.NGAY, 101)  
 END
END) AS NGAY,T1.MS_MAY,  T1.TU_GIO, T1.DEN_NGAY, T1.DEN_GIO, T1.MS_NGUYEN_NHAN, T1.GHI_CHU, T1.TRUONG_CA, T1.NGUOI_GIAI_QUYET, T1.DUNG, T1.MS_HE_THONG, T1.THOI_GIAN_SUA_CHUA, T1.MS_N_XUONG, 
                         T1.MS_LAN, T1.THOI_GIAN_SUA, T1.NGUYEN_NHAN, T1.NGUYEN_NHAN_CU_THE, T1.HIEN_TUONG, T1.CaID,TEN_MAY,T2.CA 
,
CASE ISNULL(T2.CA_DEM,0) WHEN 0 THEN DATEDIFF(MINUTE, 0, CONVERT(TIME, T1.TU_GIO))  
ELSE 
 CASE WHEN CONVERT(TIME,T1.TU_GIO) BETWEEN '00:00:00' AND '06:00:00' THEN
  DATEDIFF(MINUTE, 0, CONVERT(TIME, T1.TU_GIO)) + 1440
 ELSE
  DATEDIFF(MINUTE, 0, CONVERT(TIME, T1.TU_GIO))
 END 
END AS SO_PHUT_TU_GIO
 						 
INTO #TGNM_TMP
FROM            dbo.THOI_GIAN_NGUNG_MAY AS T1 INNER JOIN
                         dbo.CA AS T2 ON  T1.CaID = T2.STT INNER JOIN
                         #MAY_USER AS T3 ON T1.MS_MAY = T3.MS_MAY
WHERE 
CONVERT(DATE,
CASE ISNULL(T2.CA_DEM,0) WHEN 0 THEN CONVERT(DATE, T1.NGAY, 101)  ELSE 
 CASE WHEN CONVERT(TIME,T1.TU_GIO) BETWEEN '00:00:00' AND '06:00:00' THEN
  DATEADD(DAY,-1, CONVERT(DATE, T1.NGAY, 101)) 
 ELSE
  CONVERT(DATE, T1.NGAY, 101)  
 END
END)  BETWEEN CONVERT(DATE, @TNgay)  AND CONVERT(DATE, @DNgay )


--
SELECT        
CONVERT(DATETIME,
CASE ISNULL(T2.CA_DEM,0) WHEN 0 THEN CONVERT(DATE, T1.NGAY, 101)  ELSE 
 CASE WHEN CONVERT(TIME,T1.TU_GIO) BETWEEN '00:00:00' AND '06:00:00' THEN
  DATEADD(DAY,-1, CONVERT(DATE, T1.NGAY, 101)) 
 ELSE
  CONVERT(DATE, T1.NGAY, 101)  
 END
END) AS NGAY,T1.MS_MAY,  T1.TU_GIO, T1.MS_NGUYEN_NHAN, T1.TRUONG_CA, T1.NGUOI_GIAI_QUYET, T1.MS_LAN, T1.NGUYEN_NHAN, T1.NGUYEN_NHAN_CU_THE, T1.HIEN_TUONG, T1.CaID INTO #TGNMLAN_TMP
FROM            dbo.THOI_GIAN_NGUNG_MAY_SO_LAN AS T1 INNER JOIN
                         dbo.CA AS T2 ON T1.CaID = T2.STT INNER JOIN
                         #MAY_USER AS T3 ON T1.MS_MAY = T3.MS_MAY
WHERE 
CONVERT(DATE,
CASE ISNULL(T2.CA_DEM,0) WHEN 0 THEN CONVERT(DATE, T1.NGAY, 101)  ELSE 
 CASE WHEN CONVERT(TIME,T1.TU_GIO) BETWEEN '00:00:00' AND '06:00:00' THEN
  DATEADD(DAY,-1, CONVERT(DATE, T1.NGAY, 101)) 
 ELSE
  CONVERT(DATE, T1.NGAY, 101)  
 END
END) BETWEEN CONVERT(DATE, @TNgay)  AND CONVERT(DATE, @DNgay)



SELECT DISTINCT T1.NGAY, CASE @Loai WHEN 0 THEN SUM(T1.THOI_GIAN_SUA_CHUA) ELSE SUM(T1.THOI_GIAN_SUA) END AS TONG_DT INTO #TONG_DT
FROM            #TGNM_TMP AS T1 INNER JOIN
                         dbo.THOI_GIAN_NGUNG_MAY_SO_LAN AS T2 ON T1.MS_LAN = T2.MS_LAN 
GROUP BY T1.NGAY


--SELECT DISTINCT T1.NGAY, COUNT (T1.NGAY) AS SLDT INTO #TONG_SL
--FROM            #TGNMLAN_TMP T1
--GROUP BY T1.NGAY


SELECT DISTINCT DAY(T1.NGAY) AS STT,
CONVERT(DATE, T1.NGAY, 101) NGAY ,CONVERT(FLOAT,TONG_DT) AS TONG_DT, T1.CA, T1.TRUONG_CA, T1.NGUOI_GIAI_QUYET, CONVERT(TIME,T1.TU_GIO) AS TU_GIO, CONVERT(TIME,T1.DEN_GIO) AS DEN_GIO,
CASE @Loai WHEN 0 THEN T1.THOI_GIAN_SUA_CHUA ELSE T1.THOI_GIAN_SUA END AS THOI_GIAN_SUA_CHUA
,   T1.MS_MAY, TEN_MAY, T3.TEN_NGUYEN_NHAN, 
                         T1.HIEN_TUONG, T1.NGUYEN_NHAN_CU_THE, T1.NGUYEN_NHAN,
       SO_PHUT_TU_GIO AS SLDT
FROM            #TGNM_TMP AS T1 INNER JOIN
                         dbo.NGUYEN_NHAN_DUNG_MAY AS T3 ON T1.MS_NGUYEN_NHAN = T3.MS_NGUYEN_NHAN 
       LEFT JOIN #TONG_DT T5 ON T1.NGAY = T5.NGAY
       --LEFT JOIN #TONG_SL T6 ON T1.NGAY = T6.NGAY

ORDER BY NGAY, T1.CA, 

SLDT

END