IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_TINH_TRANG]') AND type in (N'U'))
	RETURN
ELSE



IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PHIEU_BAO_TRI_TINH_TRANG_DON_VI_DO]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_TINH_TRANG]'))
ALTER TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG] DROP CONSTRAINT [FK_PHIEU_BAO_TRI_TINH_TRANG_DON_VI_DO]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PHIEU_BAO_TRI_TINH_TRANG_PHIEU_BAO_TRI]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_TINH_TRANG]'))
ALTER TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG] DROP CONSTRAINT [FK_PHIEU_BAO_TRI_TINH_TRANG_PHIEU_BAO_TRI]
GO


/****** Object:  Table [dbo].[PHIEU_BAO_TRI_TINH_TRANG]    Script Date: 06/30/2015 08:54:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_TINH_TRANG]') AND type in (N'U'))
DROP TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG]
GO

/****** Object:  Table [dbo].[PHIEU_BAO_TRI_TINH_TRANG]    Script Date: 06/30/2015 08:54:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG](
	[ID] [int] NOT NULL,
	[MS_PHIEU_BAO_TRI] [nvarchar](20) NOT NULL,
	[THONG_SO_DO] [nvarchar](500) NULL,
	[THIET_BI_DO] [nvarchar](500) NULL,
	[TT_TRUOC_BT] [nvarchar](500) NULL,
	[TT_SAU_BT] [nvarchar](500) NULL,
	[MS_DV_DO] [smallint] NULL,
	[XAC_NHAN] [bit] NULL,
	[GHI_CHU] [nvarchar](500) NULL,
	[USER_XN] [nvarchar](50) NULL,
 CONSTRAINT [PK_PHIEU_BAO_TRI_TINH_TRANG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[MS_PHIEU_BAO_TRI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG]  WITH CHECK ADD  CONSTRAINT [FK_PHIEU_BAO_TRI_TINH_TRANG_DON_VI_DO] FOREIGN KEY([MS_DV_DO])
REFERENCES [dbo].[DON_VI_DO] ([MS_DV_DO])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG] CHECK CONSTRAINT [FK_PHIEU_BAO_TRI_TINH_TRANG_DON_VI_DO]
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG]  WITH CHECK ADD  CONSTRAINT [FK_PHIEU_BAO_TRI_TINH_TRANG_PHIEU_BAO_TRI] FOREIGN KEY([MS_PHIEU_BAO_TRI])
REFERENCES [dbo].[PHIEU_BAO_TRI] ([MS_PHIEU_BAO_TRI])
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_TINH_TRANG] CHECK CONSTRAINT [FK_PHIEU_BAO_TRI_TINH_TRANG_PHIEU_BAO_TRI]
GO


