IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'FN' AND name = 'GetGiaTriThongSoGSTT')
   exec('CREATE FUNCTION  dbo.GetGiaTriThongSoGSTT () RETURNS  nvarchar(50) as Begin return null end')
GO
--SELECT dbo.GetGiaTriThongSoGSTT ('CLF250-01','1.2','35','05/13/2015') AS TS

ALTER FUNCTION  GetGiaTriThongSoGSTT
(
	@MS_MAY nvarchar(50), 
	@MS_BO_PHAN nvarchar(50), 
	@MS_TS_GSTT nvarchar(50),
	@NGAY DATETIME
) 
RETURNS   nvarchar(1)
as 
BEGIN

DECLARE @TSO NVARCHAR(1)
DECLARE @LoaiTS bit
--
SELECT @LoaiTS = ISNULL(LOAI_TS,0) FROM THONG_SO_GSTT WHERE MS_TS_GSTT = @MS_TS_GSTT

IF @LoaiTS = 1
BEGIN
	IF NOT EXISTS (
		SELECT * FROM dbo.GIAM_SAT_TINH_TRANG_TS T1 INNER JOIN GIAM_SAT_TINH_TRANG T2 ON  T1.STT = T2.STT
		WHERE     (T1.MS_MAY = @MS_MAY) AND (T1.MS_BO_PHAN = @MS_BO_PHAN) AND T1.MS_TS_GSTT = @MS_TS_GSTT AND (NGAY_KT = @NGAY)
				   )
	BEGIN 
		SELECT  @TSO =  'X'
	END        
	ELSE
	BEGIN
		SELECT @TSO = CASE WHEN DAT = 1 THEN 'Y' 
					WHEN DAT = 0 THEN 'N' ELSE NULL END 
		FROM         dbo.GIAM_SAT_TINH_TRANG_TS AS T1 INNER JOIN
							  dbo.GIAM_SAT_TINH_TRANG_TS_DT AS T3 ON T1.STT = T3.STT AND T1.MS_MAY = T3.MS_MAY AND T1.MS_TS_GSTT = T3.MS_TS_GSTT AND T1.MS_BO_PHAN = T3.MS_BO_PHAN AND 
							  T1.MS_TT = T3.MS_TT INNER JOIN
							  dbo.GIA_TRI_TS_GSTT AS T2 ON T3.STT_GT = T2.STT AND T3.MS_TS_GSTT = T2.MS_TS_GSTT INNER JOIN
							  dbo.GIAM_SAT_TINH_TRANG AS T4 ON T1.STT = T4.STT
		WHERE     (T1.MS_MAY = @MS_MAY) AND (T1.MS_BO_PHAN = @MS_BO_PHAN) AND T1.MS_TS_GSTT = @MS_TS_GSTT AND (T4.NGAY_KT = @NGAY)

	END  
END
ELSE
BEGIN
	IF NOT EXISTS (
		SELECT * FROM dbo.GIAM_SAT_TINH_TRANG_TS T1 INNER JOIN GIAM_SAT_TINH_TRANG T2 ON  T1.STT = T2.STT
		WHERE     (T1.MS_MAY = @MS_MAY) AND (T1.MS_BO_PHAN = @MS_BO_PHAN) AND T1.MS_TS_GSTT = @MS_TS_GSTT AND (NGAY_KT = @NGAY)
				   )
	BEGIN 
		SELECT  @TSO =  'X'
	END        
	ELSE
	BEGIN
		SELECT @TSO = CASE WHEN DAT = 1 THEN 'Y' 
					WHEN DAT = 0 THEN 'N' ELSE NULL END 
		FROM         dbo.GIAM_SAT_TINH_TRANG_TS AS T1 INNER JOIN
							  dbo.GIAM_SAT_TINH_TRANG AS T2 ON T1.STT = T2.STT INNER JOIN
							  dbo.THONG_SO_GSTT AS T3 ON T1.MS_TS_GSTT = T3.MS_TS_GSTT INNER JOIN
							  dbo.CAU_TRUC_THIET_BI_TS_GSTT AS T4 ON T1.MS_MAY = T4.MS_MAY AND T1.MS_BO_PHAN = T4.MS_BO_PHAN AND T1.MS_TS_GSTT = T4.MS_TS_GSTT AND T1.MS_TT = T4.MS_TT

		WHERE     (T1.MS_MAY = @MS_MAY) AND (T1.MS_BO_PHAN = @MS_BO_PHAN) AND T1.MS_TS_GSTT = @MS_TS_GSTT AND (T2.NGAY_KT = @NGAY) AND (T3.LOAI_TS = 0)

	END  
END



RETURN @TSO
END       
--           )           
-- RETURN @TSO 
  
              
                      
