
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'LOAI_YEU_CAU_BAO_TRI') AND type in (N'U'))
BEGIN	
	CREATE TABLE [dbo].[LOAI_YEU_CAU_BAO_TRI](
		[MS_LOAI_YEU_CAU_BT] INT NOT NULL,
		[TEN_LOAI_YEU_CAU_BT] [nvarchar](250) NULL,
		[GHI_CHU] [nvarchar](250) NULL,
	 CONSTRAINT [PK_LOAI_YEU_CAU_BAO_TRI] PRIMARY KEY CLUSTERED 
	(
		[MS_LOAI_YEU_CAU_BT] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END 

GO

if not exists(select * from sys.columns where Name = N'MS_LOAI_YEU_CAU_BT' and Object_ID = Object_ID(N'YEU_CAU_NSD_CHI_TIET'))
begin
    ALTER TABLE YEU_CAU_NSD_CHI_TIET ADD MS_LOAI_YEU_CAU_BT INT
END    



	
GO


