IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetKhoUser')
   exec('CREATE PROCEDURE [dbo].[GetKhoUser] AS BEGIN SET NOCOUNT ON; END')
GO


-- EXEC GetKhoUser 1, '-1'
ALTER PROC [dbo].[GetKhoUser]
	@COALL BIT,
	@UserName NVARCHAR(50) 
AS
IF @COALL = 0 
	--SELECT MS_KHO , TEN_KHO FROM IC_KHO A INNER JOIN NHOM_KHO ON   ORDER BY TEN_KHO
	SELECT A.MS_KHO , TEN_KHO FROM IC_KHO A INNER JOIN NHOM_KHO B ON A.MS_KHO = B.MS_KHO INNER JOIN USERS C ON B.GROUP_ID = C.GROUP_ID
		WHERE (USERNAME = @UserName OR @UserName = '-1')
	ORDER BY TEN_KHO
ELSE
	SELECT A.MS_KHO , TEN_KHO FROM IC_KHO A INNER JOIN NHOM_KHO B ON A.MS_KHO = B.MS_KHO INNER JOIN USERS C ON B.GROUP_ID = C.GROUP_ID
		WHERE (USERNAME = @UserName OR @UserName = '-1')
	UNION SELECT -1 , N' < ALL > '	ORDER BY TEN_KHO
