

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetDSDMVT')
   exec('CREATE PROCEDURE [dbo].[GetDSDMVT] AS BEGIN SET NOCOUNT ON; END')
GO


-- exec GetDSDMVT 0, 'admin','WO-201507001049'
ALTER PROCEDURE GetDSDMVT
	@TYPE INT,
	@USERNAME NVARCHAR(50),	
	@MS_PHIEU_BAO_TRI NVARCHAR(50)
AS

CREATE TABLE #PTUNG (
		[MS_PT] NVARCHAR(255),		
		[MS_BO_PHAN] NVARCHAR(50),
		[MS_CV] INT)
DECLARE @sSQL NVARCHAR(4000)
SET @sSQL = 'INSERT INTO #PTUNG (MS_PT,[MS_BO_PHAN],[MS_CV] ) SELECT DISTINCT MS_PT,[MS_BO_PHAN],[MS_CV] FROM PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_TMP' +  @USERNAME  + ' WHERE MS_PHIEU_BAO_TRI = ''' + @MS_PHIEU_BAO_TRI + ''''
EXEC (@sSQL)

CREATE TABLE #BTCVIEC(
	[MS_BO_PHAN] NVARCHAR(50),
	[MS_CV] INT)
SET @sSQL = 'INSERT INTO #BTCVIEC ([MS_BO_PHAN],[MS_CV]) SELECT DISTINCT [MS_BO_PHAN],[MS_CV] FROM PHIEU_BAO_TRI_CONG_VIEC_TMP' +  @USERNAME + ' WHERE MS_PHIEU_BAO_TRI = ''' + @MS_PHIEU_BAO_TRI + ''''
EXEC (@sSQL)


SELECT T1.MS_PT INTO #LPT_USER FROM IC_PHU_TUNG_LOAI_PHU_TUNG T1 INNER JOIN NHOM_LOAI_PHU_TUNG T2 ON T1.MS_LOAI_PT = T2.MS_LOAI_PT 
	INNER JOIN USERS T3 ON T2.GROUP_ID = T3.GROUP_ID WHERE USERNAME = @USERNAME
SELECT T1.MS_PT INTO #LM_USER FROM IC_PHU_TUNG_LOAI_MAY T1 INNER JOIN NHOM_LOAI_MAY T2 ON T1.MS_LOAI_MAY = T2.MS_LOAI_MAY 
	INNER JOIN USERS T3 ON T2.GROUP_ID = T3.GROUP_ID WHERE USERNAME = @USERNAME

	
SELECT DISTINCT A.MS_PT, A.TEN_PT, A.TEN_PT_VIET, A.QUY_CACH, A.MS_PT_NCC, A.MS_PT_CTY, 1 AS SL_KH, 
	CASE 0 WHEN 0 THEN B.TEN_LOAI_VT_TV WHEN 1 THEN B.TEN_LOAI_VT_TA ELSE B.TEN_LOAI_VT_TV END AS TEN_LOAI_VT_TV, 
	CASE 0 WHEN 0 THEN C.TEN_1 WHEN 1 THEN C.TEN_2 ELSE C.TEN_3 END AS TEN_1
INTO #BT1                      
FROM         dbo.IC_PHU_TUNG AS A INNER JOIN
                      dbo.LOAI_VT AS B ON A.MS_LOAI_VT = B.MS_LOAI_VT INNER JOIN
                      dbo.DON_VI_TINH AS C ON A.DVT = C.DVT  INNER JOIN
                      #LPT_USER AS D ON D.MS_PT = A.MS_PT INNER JOIN
                      #LM_USER AS E ON E.MS_PT = A.MS_PT 
WHERE ACTIVE_PT = 1                      
ORDER BY A.MS_PT, A.TEN_PT

SELECT A.MS_PT, A.TEN_PT, A.TEN_PT_VIET, A.QUY_CACH, A.MS_PT_NCC, A.MS_PT_CTY, 1 AS SL_KH, TEN_LOAI_VT_TV, TEN_1 , 
	MS_BO_PHAN, MS_CV,@MS_PHIEU_BAO_TRI AS MS_PHIEU_BAO_TRI,
	CONVERT(NVARCHAR(250),MS_CV) +  CONVERT(NVARCHAR(250),MS_BO_PHAN) AS MSCVBT 
INTO #BT2
FROM #BT1 A , #BTCVIEC B
	
SELECT DISTINCT
CONVERT(BIT,CASE ISNULL(T2.MS_PT,'') WHEN '' THEN 0 ELSE 1 END) AS CHON,T1.MS_PT, TEN_PT,
	TEN_PT_VIET,QUY_CACH ,SL_KH, TEN_LOAI_VT_TV,   MS_PT_NCC, MS_PT_CTY, TEN_1,
	T1.MS_BO_PHAN, T1.MS_CV,@MS_PHIEU_BAO_TRI AS MS_PHIEU_BAO_TRI,MSCVBT
FROM #BT2  T1 LEFT JOIN #PTUNG T2 ON T1.MS_PT = T2.MS_PT AND T1.MS_BO_PHAN = T2.MS_BO_PHAN AND T1.MS_CV = T2.MS_CV
ORDER BY MS_PHIEU_BAO_TRI, MS_BO_PHAN,MS_CV,MS_PT,TEN_PT

