IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CapNhapNghiemThuSLTT')
   exec('CREATE PROCEDURE CapNhapNghiemThuSLTT AS BEGIN SET NOCOUNT ON; END')
GO


-- exec S_PHIEU_BAO_TRI 'administrator' , '01/01/2015','12/31/2015',0, '-1', '-1', 'MIX-0008', 'GF-01', '-1', '-1', '-1', -1,-1, '-1', '-1', -1
ALTER PROC CapNhapNghiemThuSLTT
	@PBT NVARCHAR(50)
AS
INSERT INTO [dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO]
([MS_PHIEU_BAO_TRI],[MS_CV],[MS_BO_PHAN],[MS_PT],[STT],[MS_DH_XUAT_PT],[MS_DH_NHAP_PT],[MS_PTTT],[ID],[SL_TT],[DON_GIA],[NGOAI_TE],[TI_GIA],[TI_GIA_USD],[GHI_CHU])
SELECT DISTINCT 
                         A.MS_PHIEU_BAO_TRI, A.MS_CV, A.MS_BO_PHAN, A.MS_PT, A.STT, C.MS_DH_XUAT_PT, D.MS_DH_NHAP_PT, D.MS_PT AS MS_PTTT, 
						 CASE ISNULL(X.ID, '')  WHEN '' THEN C.ID_XUAT ELSE X.ID END AS ID, 
						 CASE WHEN C.SL_VT < A.SL_KH THEN C.SL_VT ELSE A.SL_KH END AS SL_TT,
						 D.DON_GIA, D.NGOAI_TE, D.TY_GIA, D.TY_GIA_USD, X.GHI_CHU
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET AS A INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU AS B INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS C ON B.MS_DH_XUAT_PT = C.MS_DH_XUAT_PT AND B.MS_PT = C.MS_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS D ON C.MS_DH_NHAP_PT = D.MS_DH_NHAP_PT AND C.MS_PT = D.MS_PT AND C.ID_XUAT = D.ID INNER JOIN
                         dbo.IC_DON_HANG_XUAT AS E ON B.MS_DH_XUAT_PT = E.MS_DH_XUAT_PT ON A.MS_PHIEU_BAO_TRI = E.MS_PHIEU_BAO_TRI INNER JOIN
                             (SELECT        T1.MS_PT, T2.MS_PT1
								FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET AS T1 INNER JOIN
														 dbo.IC_PHU_TUNG_THAY_THE AS T2 ON T1.MS_PT = T2.MS_PT
								WHERE        (T1.MS_PHIEU_BAO_TRI = @PBT)

							UNION
							SELECT        MS_PT, MS_PT AS MS_PT1
								FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET
								WHERE        (MS_PHIEU_BAO_TRI = @PBT)							   
							   ) AS T1 ON A.MS_PT = T1.MS_PT AND D.MS_PT = T1.MS_PT1 LEFT OUTER JOIN
                         dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO X ON D.ID = X.ID AND 
                         B.MS_DH_XUAT_PT = X.MS_DH_XUAT_PT AND 
                         D.MS_DH_NHAP_PT = X.MS_DH_NHAP_PT AND T1.MS_PT = X.MS_PT AND 
                         T1.MS_PT1 = X.MS_PTTT AND C.MS_DH_NHAP_PT = X.MS_DH_NHAP_PT AND 
                         A.MS_PHIEU_BAO_TRI = X.MS_PHIEU_BAO_TRI AND A.MS_CV = X.MS_CV AND 
                         A.MS_BO_PHAN = X.MS_BO_PHAN AND A.MS_PT = X.MS_PT AND 
                         A.STT = X.STT
WHERE        (A.MS_PHIEU_BAO_TRI = @PBT) AND (ISNULL(A.SL_TT, 0) = 0) AND (ISNULL(A.GHI_CHU, N'') = N'')
AND EXISTS (SELECT        T1.MS_PHIEU_BAO_TRI, T1.MS_CV, T1.MS_BO_PHAN, T1.MS_PT, T2.STT
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG AS T1 INNER JOIN
                         dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET AS T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI AND T1.MS_CV = T2.MS_CV AND T1.MS_PT = T2.MS_PT AND 
                         T1.MS_BO_PHAN = T2.MS_BO_PHAN
WHERE        (T1.MS_PHIEU_BAO_TRI = @PBT) AND (ISNULL(T1.SL_TT, 0) = 0) AND (ISNULL(T1.GHI_CHU, N'') = N'')
AND (A.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI) AND (A.MS_CV = T2.MS_CV) AND (A.MS_BO_PHAN = T2.MS_BO_PHAN) 
AND (A.MS_PT = T2.MS_PT) AND (A.STT = T2.STT) 

)




UPDATE [PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET]
   SET  [SL_TT] = SLTT
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET AS T1 INNER JOIN
(
SELECT        MS_PHIEU_BAO_TRI, MS_CV, MS_BO_PHAN, MS_PT, STT, MS_PTTT, SUM(SL_TT) AS SLTT
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO
WHERE        (MS_PHIEU_BAO_TRI = @PBT)
GROUP BY MS_PHIEU_BAO_TRI, MS_CV, MS_BO_PHAN, MS_PT, STT, MS_PTTT
)                         						 
						  AS T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI AND T1.MS_CV = T2.MS_CV AND T1.MS_BO_PHAN = T2.MS_BO_PHAN AND 
                         T1.MS_PT = T2.MS_PT AND T1.STT = T2.STT
WHERE T1.MS_PHIEU_BAO_TRI = @PBT



UPDATE PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG
   SET  [SL_TT] = SLTT
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG AS T1 INNER JOIN
(
SELECT        MS_PHIEU_BAO_TRI, MS_CV, MS_BO_PHAN, MS_PT,  MS_PTTT, SUM(SL_TT) AS SLTT
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO
WHERE        (MS_PHIEU_BAO_TRI = @PBT)
GROUP BY MS_PHIEU_BAO_TRI, MS_CV, MS_BO_PHAN, MS_PT, STT, MS_PTTT
)                         						 
						  AS T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI AND T1.MS_CV = T2.MS_CV AND T1.MS_BO_PHAN = T2.MS_BO_PHAN AND 
                         T1.MS_PT = T2.MS_PT
WHERE T1.MS_PHIEU_BAO_TRI = @PBT
