ALTER procedure [dbo].[GetDSThietBiDenHanHC]
@TU_NGAY DATETIME,
@DEN_NGAY DATETIME,
@USERNAME NVARCHAR(50),
@MS_LOAI_MAY NVARCHAR(30)
AS
IF @MS_LOAI_MAY='-1'
 SELECT DISTINCT MAY.MS_MAY, MAY.TEN_MAY,HIEU_CHUAN_MAY.NGAY_KH, HIEU_CHUAN_MAY.NGAY_HC, CONVERT(NVARCHAR(30),MAY.CHU_KY_HC_TB) +  ' Ngày' AS CHU_KY_HC,DATEADD(DAY,CHU_KY_HC_TB,NGAY_HC) AS NGAY_HC_KE
 FROM         MAY INNER JOIN
                       HIEU_CHUAN_MAY ON MAY.MS_MAY = HIEU_CHUAN_MAY.MS_MAY INNER JOIN
                       NHOM_MAY ON MAY.MS_NHOM_MAY = NHOM_MAY.MS_NHOM_MAY INNER JOIN
                       LOAI_MAY ON NHOM_MAY.MS_LOAI_MAY = LOAI_MAY.MS_LOAI_MAY INNER JOIN
                       NHOM_LOAI_MAY ON LOAI_MAY.MS_LOAI_MAY = NHOM_LOAI_MAY.MS_LOAI_MAY INNER JOIN
                       USERS ON NHOM_LOAI_MAY.GROUP_ID = USERS.GROUP_ID
 WHERE     (USERS.USERNAME = @USERNAME) AND (DATEADD(DAY,CHU_KY_HC_TB,NGAY_HC) BETWEEN @TU_NGAY AND @DEN_NGAY)
ELSE
 SELECT DISTINCT MAY.MS_MAY, MAY.TEN_MAY, HIEU_CHUAN_MAY.NGAY_HC,HIEU_CHUAN_MAY.NGAY_KH, CONVERT(NVARCHAR(30),MAY.CHU_KY_HC_TB) +  ' Ngày' AS CHU_KY_HC,DATEADD(DAY,CHU_KY_HC_TB,NGAY_HC) AS NGAY_HC_KE
 FROM         MAY INNER JOIN
                       HIEU_CHUAN_MAY ON MAY.MS_MAY = HIEU_CHUAN_MAY.MS_MAY INNER JOIN
                       NHOM_MAY ON MAY.MS_NHOM_MAY = NHOM_MAY.MS_NHOM_MAY INNER JOIN
                       LOAI_MAY ON NHOM_MAY.MS_LOAI_MAY = LOAI_MAY.MS_LOAI_MAY INNER JOIN
                       NHOM_LOAI_MAY ON LOAI_MAY.MS_LOAI_MAY = NHOM_LOAI_MAY.MS_LOAI_MAY INNER JOIN
                       USERS ON NHOM_LOAI_MAY.GROUP_ID = USERS.GROUP_ID
 WHERE     (USERS.USERNAME = @USERNAME) AND (DATEADD(DAY,CHU_KY_HC_TB,NGAY_HC) BETWEEN @TU_NGAY AND @DEN_NGAY) AND LOAI_MAY.MS_LOAI_MAY=@MS_LOAI_MAY

