IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spKeHoachCongViecBaoTri')
   exec('CREATE PROCEDURE spKeHoachCongViecBaoTri AS BEGIN SET NOCOUNT ON; END')
GO
-- DROP TABLE MAY_KHCVBT_TMPADMIN
-- SELECT CONVERT(BIT,1) AS CHON, * INTO MAY_KHCVBT_TMPA00DMIN FROM MAY GO EXEC spKeHoachCongViecBaoTri 'MAY_KHCVBT_TMPA00DMIN', -1, N'LBTRI', '01/01/2015', '01/01/2016',0
ALTER PROC spKeHoachCongViecBaoTri
	@MayTmp NVARCHAR(50),
	@MsLBTri INT,
	@TenLBTri NVARCHAR(50),
	@TNgay DATETIME,
	@DNgay DATETIME,
	@NNgu INT
AS

DECLARE @sSql NVARCHAR(4000)


CREATE TABLE #MAY_TMP (MS_MAY NVARCHAR(250) NULL, TEN_MAY NVARCHAR(500) NULL)  

SET @sSql = ' INSERT INTO #MAY_TMP SELECT MS_MAY, TEN_MAY FROM ' + @MayTmp + ' WHERE ISNULL(CHON,0) = 1'
EXEC (@sSql)

SET @sSql = ' DROP TABLE ' + @MayTmp
EXEC (@sSql)





SELECT * FROM
(
SELECT  NGAY,A.MS_MAY, TEN_MAY, D.TEN_LOAI_BT,X.TEN_BO_PHAN,
	  CASE @NNgu WHEN 0 THEN E.MO_TA_CV WHEN 1 THEN E.MO_TA_CV_ANH ELSE E.MO_TA_CV_HOA END AS TEN_CV, A.THOI_GIAN_DU_KIEN, A.GHI_CHU
	FROM KE_HOACH_TONG_CONG_VIEC A INNER JOIN #MAY_TMP B ON A.MS_MAY = B.MS_MAY INNER JOIN KE_HOACH_TONG_THE C ON A.HANG_MUC_ID = C.HANG_MUC_ID 
	INNER JOIN LOAI_BAO_TRI D ON C.MS_LOAI_BT = D.MS_LOAI_BT 
	INNER JOIN CONG_VIEC E ON A.MS_CV = E.MS_CV 
	INNER JOIN CAU_TRUC_THIET_BI X ON A.MS_MAY = X.MS_MAY AND A.MS_BO_PHAN = X.MS_BO_PHAN
WHERE CONVERT(DATETIME,CONVERT(NVARCHAR(10),C.NGAY,101)) BETWEEN @TNgay AND @DNgay AND ISNULL(A.MS_PHIEU_BAO_TRI,'') = ''
AND (C.MS_LOAI_BT = @MsLBTri  OR @MsLBTri = -1)

UNION
SELECT  A.NGAY_BD_KH AS NGAY, A.MS_MAY, TEN_MAY,D.TEN_LOAI_BT, X.TEN_BO_PHAN,
		CASE @NNgu WHEN 0 THEN E.MO_TA_CV WHEN 1 THEN E.MO_TA_CV_ANH ELSE E.MO_TA_CV_HOA END AS TEN_CV,B.SO_GIO_KH, B.GHI_CHU
	FROM PHIEU_BAO_TRI A INNER JOIN PHIEU_BAO_TRI_CONG_VIEC B ON A.MS_PHIEU_BAO_TRI = B.MS_PHIEU_BAO_TRI 
	INNER JOIN #MAY_TMP C ON A.MS_MAY = C.MS_MAY INNER JOIN LOAI_BAO_TRI D ON A.MS_LOAI_BT = D.MS_LOAI_BT
	INNER JOIN CONG_VIEC E ON B.MS_CV = E.MS_CV
	INNER JOIN CAU_TRUC_THIET_BI X ON A.MS_MAY = X.MS_MAY AND B.MS_BO_PHAN = X.MS_BO_PHAN
WHERE CONVERT(DATETIME,CONVERT(NVARCHAR(10),A.NGAY_BD_KH,101)) BETWEEN @TNgay AND @DNgay AND ISNULL(TINH_TRANG_PBT,0) < 3
	AND (A.MS_LOAI_BT = @MsLBTri  OR @MsLBTri = -1)
UNION
SELECT  A.NGAY, NULL AS MS_MAY, NULL AS TEN_MAY,@TenLBTri AS TEN_LOAI_BT,NULL AS TEN_BO_PHAN,
		A.TEN_CONG_VIEC,  ISNULL(THOI_GIAN_DK,0) * 60  AS THOI_GIAN_DU_KIEN, A.GHI_CHU
FROM KE_HOACH_THUC_HIEN A
WHERE CONVERT(DATETIME,CONVERT(NVARCHAR(10),A.NGAY,101))  BETWEEN @TNgay AND @DNgay AND ISNULL(A.DA_XONG,0) = 0
	AND (A.MS_CONG_NHAN = @MsLBTri  OR @MsLBTri = -2)
) T1
ORDER BY NGAY, MS_MAY, TEN_MAY, TEN_LOAI_BT,TEN_BO_PHAN,TEN_CV

