


ALTER procedure [dbo].[AddHIEU_CHUAN_MAY]
	@MS_MAY  NVARCHAR(30),
	@NGAY_TMP  NVARCHAR(10),
	@GIAY_CN  NVARCHAR(50),
	@CO_QUAN_HC NVARCHAR(50),
	@DANH_GIA NVARCHAR(255),
	@LOAI_HIEU_CHUAN INT,
	@TAI_LIEU NVARCHAR(255),
	@GHI_CHU NVARCHAR(255),
	@NGAY_KH_TMP  NVARCHAR(10)
 AS
DECLARE @NGAY_HC DATETIME
DECLARE @NGAY_KH DATETIME
IF @NGAY_TMP ='' 
 SET @NGAY_HC=NULL
ELSE
 SET @NGAY_HC=CONVERT(DATETIME,@NGAY_TMP,103)
 
IF @NGAY_KH_TMP ='' 
 SET @NGAY_KH=NULL
ELSE
 SET @NGAY_KH=CONVERT(DATETIME,@NGAY_KH_TMP,103)
INSERT INTO HIEU_CHUAN_MAY(MS_MAY,NGAY_HC,GIAY_CHUNG_NHAN,CO_QUAN_HIEU_CHUAN,DANH_GIA,TAI_LIEU, GHI_CHU,MS_LOAI_HIEU_CHUAN,NGAY_KH)
VALUES(
 @MS_MAY,
 @NGAY_HC,
 @GIAY_CN,
 @CO_QUAN_HC,
 @DANH_GIA,@TAI_LIEU,@GHI_CHU,@LOAI_HIEU_CHUAN,
 @NGAY_KH
)
