ALTER procedure [dbo].[GetHIEU_CHUAN_DHDs]
 AS
 SELECT dbo.HIEU_CHUAN_DHD.MS_MAY, dbo.HIEU_CHUAN_DHD.MS_PT, dbo.IC_PHU_TUNG.TEN_PT, 
        dbo.HIEU_CHUAN_DHD.MS_VI_TRI, dbo.HIEU_CHUAN_DHD.NGAY_KH, dbo.HIEU_CHUAN_DHD.NGAY, 
        dbo.LOAI_HIEU_CHUAN.TEN_LOAI_HIEU_CHUAN, dbo.HIEU_CHUAN_DHD.GIAY_CHUNG_NHAN, dbo.HIEU_CHUAN_DHD.CO_QUAN_HIEU_CHUAN, 
        dbo.HIEU_CHUAN_DHD.DANH_GIA, dbo.HIEU_CHUAN_DHD.NOI, dbo.HIEU_CHUAN_DHD.DUONG_DAN, dbo.HIEU_CHUAN_DHD.GHI_CHU, 
        dbo.HIEU_CHUAN_DHD.MS_LOAI_HIEU_CHUAN, dbo.HIEU_CHUAN_DHD.DD_GOC
 FROM         dbo.HIEU_CHUAN_DHD INNER JOIN
        dbo.CHU_KY_HIEU_CHUAN ON dbo.HIEU_CHUAN_DHD.MS_MAY = dbo.CHU_KY_HIEU_CHUAN.MS_MAY AND 
        dbo.HIEU_CHUAN_DHD.MS_PT = dbo.CHU_KY_HIEU_CHUAN.MS_PT AND 
        dbo.HIEU_CHUAN_DHD.MS_VI_TRI = dbo.CHU_KY_HIEU_CHUAN.MS_VI_TRI INNER JOIN
        dbo.IC_PHU_TUNG ON dbo.HIEU_CHUAN_DHD.MS_PT = dbo.IC_PHU_TUNG.MS_PT INNER JOIN
        dbo.LOAI_HIEU_CHUAN ON dbo.HIEU_CHUAN_DHD.MS_LOAI_HIEU_CHUAN = dbo.LOAI_HIEU_CHUAN.MS_LOAI_HIEU_CHUAN
 ORDER BY NGAY DESC, HIEU_CHUAN_DHD.MS_MAY,IC_PHU_TUNG.TEN_PT
