
ALTER procedure [dbo].[GetHIEU_CHUAN_MAYs_Moi] 

AS
 
 SELECT     dbo.HIEU_CHUAN_MAY.MS_MAY,dbo.HIEU_CHUAN_MAY.NGAY_KH, dbo.HIEU_CHUAN_MAY.NGAY_HC, DATEADD(MONTH,CONVERT(INT,(CASE WHEN dbo.HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN=2 THEN DBO.MAY.CHU_KY_HIEU_CHUAN_TB_NGOAI
          ELSE CASE WHEN dbo.HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN=1 THEN DBO.MAY.CHU_KY_HC_TB
          ELSE DBO.MAY.CHU_KY_KD_TB
          END
          END)),DBO.HIEU_CHUAN_MAY.NGAY_HC)AS NGAY_KT,
    dbo.HIEU_CHUAN_MAY.GIAY_CHUNG_NHAN, 
                dbo.HIEU_CHUAN_MAY.CO_QUAN_HIEU_CHUAN, dbo.HIEU_CHUAN_MAY.DANH_GIA, dbo.LOAI_HIEU_CHUAN_MAY.TEN_LOAI_HIEU_CHUAN, dbo.HIEU_CHUAN_MAY.TAI_LIEU, 
                dbo.HIEU_CHUAN_MAY.GHI_CHU, dbo.LOAI_HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN
 FROM dbo.HIEU_CHUAN_MAY 
 LEFT OUTER JOIN dbo.LOAI_HIEU_CHUAN_MAY ON dbo.HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN = dbo.LOAI_HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN
 INNER JOIN dbo.MAY on dbo.HIEU_CHUAN_MAY.MS_MAY=dbo.MAY.MS_MAY
 ORDER BY NGAY_HC DESC, MS_MAY

