ALTER procedure [dbo].[UpdateHIEU_CHUAN_MAY]
 @MS_MAY_MOI   NVARCHAR(30),
 @MS_MAY    NVARCHAR(30),
 @NGAY_HC_MOI_TMP  NVARCHAR(10),
 @NGAY_HC_TMP           NVARCHAR(10),
 @GIAY_CN    NVARCHAR(50),
 @CO_QUAN_HC  NVARCHAR(50),
 @DANH_GIA   NVARCHAR(255),
 @LOAI_HIEU_CHUAN int,
 @TAI_LIEU NVARCHAR(255),
 @GHI_CHU NVARCHAR(255),
 @NGAY_KH_TMP NVARCHAR(10)
 AS
 DECLARE @NGAY_HC_MOI DATETIME
 DECLARE @NGAY_HC DATETIME
 DECLARE @NGAY_KH DATETIME
 
 SET @NGAY_HC_MOI=CONVERT(DATETIME,@NGAY_HC_MOI_TMP,103)
 SET @NGAY_HC=CONVERT(DATETIME,@NGAY_HC_TMP,103)
 SET @NGAY_KH=CONVERT(DATETIME,@NGAY_KH_TMP,103)
 
 UPDATE HIEU_CHUAN_MAY SET
  MS_MAY=@MS_MAY_MOI,
  NGAY_HC=@NGAY_HC_MOI,
  GIAY_CHUNG_NHAN=@GIAY_CN,
  CO_QUAN_HIEU_CHUAN=@CO_QUAN_HC,
  DANH_GIA=@DANH_GIA,MS_LOAI_HIEU_CHUAN=@LOAI_HIEU_CHUAN,TAI_LIEU=@TAI_LIEU,GHI_CHU=@GHI_CHU,NGAY_KH=@NGAY_KH
 WHERE MS_MAY=@MS_MAY AND NGAY_HC=@NGAY_HC

