--EXEC CreateTHOI_GIAN_HU_HONG_DATA '02/01/2016','02/28/2016'
ALTER procedure [dbo].[CreateTHOI_GIAN_HU_HONG_DATA]
	@TU_NGAY NVARCHAR(10),
	@DEN_NGAY NVARCHAR(10)
 AS
	IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'THOI_GIAN_NGUNG_MAY_DO_HU_HONG_TMP')
	BEGIN
   		DROP TABLE THOI_GIAN_NGUNG_MAY_DO_HU_HONG_TMP
	END


SELECT     dbo.MAY_HE_THONG.MS_MAY, dbo.MAY_HE_THONG.MS_HE_THONG, dbo.HE_THONG.TEN_HE_THONG, CONVERT(DATETIME, 
	                      CONVERT(NVARCHAR(10), dbo.MAY_HE_THONG.NGAY_NHAP, 103), 103) AS NGAY_NHAP, CONVERT(DATETIME, CONVERT(NVARCHAR(10), 
	                      dbo.MAY_HE_THONG.NGAY_NHAP, 103), 103) AS DEN_NGAY, CONVERT(DATETIME, CONVERT(NVARCHAR(10), @TU_NGAY, 103), 103) AS TU_NGAY, 
	                      dbo.THOI_GIAN_NGUNG_MAY.THOI_GIAN_SUA_CHUA, dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.HU_HONG
	INTO THOI_GIAN_NGUNG_MAY_DO_HU_HONG_TMP
	FROM         dbo.MAY_HE_THONG INNER JOIN
	                      dbo.HE_THONG ON dbo.HE_THONG.MS_HE_THONG = dbo.MAY_HE_THONG.MS_HE_THONG INNER JOIN
	                      dbo.THOI_GIAN_NGUNG_MAY ON dbo.MAY_HE_THONG.MS_MAY = dbo.THOI_GIAN_NGUNG_MAY.MS_MAY INNER JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY ON 
	                      dbo.THOI_GIAN_NGUNG_MAY.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN
	--WHERE     (CONVERT(DATETIME, CONVERT(NVARCHAR(10), dbo.MAY_HE_THONG.NGAY_NHAP, 103), 103) <= CONVERT(DATETIME, @DEN_NGAY, 103))
	WHERE     (CONVERT(DATETIME, CONVERT(NVARCHAR(10), THOI_GIAN_NGUNG_MAY.NGAY, 103), 103) BETWEEN  CONVERT(DATETIME, CONVERT(NVARCHAR(10), @TU_NGAY, 103), 103) AND  CONVERT(DATETIME, @DEN_NGAY, 103) )
	AND ISNULL(HU_HONG,0) = 1

	IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'rptTHOI_GIAN_HU_HONG')
	BEGIN
   		DROP TABLE rptTHOI_GIAN_HU_HONG
	END

	SELECT *,0 AS SO_LAN_HU_HONG,0 AS THOI_GIAN_NGUNG_MAY,0 AS THOI_GIAN_HU_HONG,0 AS THOI_GIAN_CHAY_MAY
	INTO rptTHOI_GIAN_HU_HONG
	FROM HE_THONG
