

--exec MBieuDoChiPhiNhaXuongTheoXuong  '02/01/2016', '02/29/2016',1,1,1,1,1,'BARI'
--exec MBieuDoChiPhiNhaXuongTheoXuong  '01/01/2000', '01/01/2015',1,1,1,1,1,'nx002'
--exec MBieuDoChiPhiNhaXuongTheoXuong  '01/01/2000', '01/01/2015',1,1,1,1,1,'nx008'
ALTER procedure [dbo].[MBieuDoChiPhiNhaXuongTheoXuong]
	@TNgay DATETIME,
	@DNgay DATETIME,
	@PhuTung bit,
	@VatTu bit,
	@NhanCong bit,
	@DichVu bit,
	@Khac bit,
	@MSNX nvarchar(100)


AS

SELECT * INTO #MAY FROM dbo.MGetMayUserNgay(@DNgay,'ADMIN',@MSNX,-1,-1,'-1','-1','-1',0) 	

SELECT     X.MS_N_XUONG,
	(CASE @PhuTung WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_PHU_TUNG), 0) ELSE 0 END + 
	CASE @VatTu WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_VAT_TU), 0)  ELSE 0 END + 
	CASE @NhanCong WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_NHAN_CONG), 0) ELSE 0 END +  
	CASE @DichVu WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_DV), 0) ELSE 0 END + 
	CASE @Khac WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_KHAC), 0) ELSE 0 END ) AS CHI_PHI_BT
INTO #CP_BT
FROM         dbo.PHIEU_BAO_TRI_CHI_PHI INNER JOIN
					  dbo.PHIEU_BAO_TRI ON dbo.PHIEU_BAO_TRI_CHI_PHI.MS_PHIEU_BAO_TRI = dbo.PHIEU_BAO_TRI.MS_PHIEU_BAO_TRI INNER JOIN
					  dbo.LOAI_BAO_TRI ON dbo.PHIEU_BAO_TRI.MS_LOAI_BT = dbo.LOAI_BAO_TRI.MS_LOAI_BT 
					  INNER JOIN #MAY X ON PHIEU_BAO_TRI.MS_MAY = X.MS_MAY
WHERE     (LOAI_BAO_TRI.HU_HONG = 0) AND (NGAY_BD_KH BETWEEN @TNgay AND @DNgay)
	AND (TINH_TRANG_PBT > 2) 
GROUP BY X.MS_N_XUONG
			


SELECT  X.MS_N_XUONG , 
	(CASE @NhanCong WHEN 1 THEN ISNULL(SUM(CHI_PHI_NC), 0)  ELSE 0 END +  CASE @VatTu WHEN 1 THEN ISNULL(SUM(CHI_PHI_VT), 0)  ELSE 0 END) AS CHI_PHI_HN
INTO #CP_HN				
FROM    dbo.CONG_VIEC_HANG_NGAY_THIET_BI INNER JOIN
		dbo.CONG_VIEC_HANG_NGAY ON dbo.CONG_VIEC_HANG_NGAY_THIET_BI.STT_CV = dbo.CONG_VIEC_HANG_NGAY.STT_CV
		INNER JOIN #MAY X ON CONG_VIEC_HANG_NGAY_THIET_BI.MS_MAY = X.MS_MAY
WHERE (dbo.CONG_VIEC_HANG_NGAY.NGAY_TH BETWEEN @TNgay AND @DNgay)	
GROUP BY X.MS_N_XUONG

SELECT  X.MS_N_XUONG, 
	(CASE @PhuTung WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_PHU_TUNG), 0) ELSE 0 END +  
	CASE @VatTu WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_VAT_TU), 0) ELSE 0 END +  
	CASE @NhanCong WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_NHAN_CONG), 0) ELSE 0 END + 
	CASE @DichVu WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_DV), 0) ELSE 0 END +  
	CASE @Khac WHEN 1 THEN ISNULL(SUM(dbo.PHIEU_BAO_TRI_CHI_PHI.CHI_PHI_KHAC), 0) ELSE 0 END )		AS CHI_PHI
INTO #CHI_PHI
FROM         dbo.PHIEU_BAO_TRI_CHI_PHI INNER JOIN
						dbo.PHIEU_BAO_TRI ON dbo.PHIEU_BAO_TRI_CHI_PHI.MS_PHIEU_BAO_TRI = dbo.PHIEU_BAO_TRI.MS_PHIEU_BAO_TRI INNER JOIN
						dbo.LOAI_BAO_TRI ON dbo.PHIEU_BAO_TRI.MS_LOAI_BT = dbo.LOAI_BAO_TRI.MS_LOAI_BT 
		INNER JOIN #MAY X ON PHIEU_BAO_TRI.MS_MAY = X.MS_MAY
WHERE     (LOAI_BAO_TRI.HU_HONG = 1) AND (NGAY_BD_KH BETWEEN @TNgay AND @DNgay)	AND (TINH_TRANG_PBT > 2)
GROUP BY X.MS_N_XUONG




SELECT CONVERT(INT,NULL) AS STT ,* FROM 
(
	SELECT A.TEN_N_XUONG , SUM(ROUND(ISNULL(CHI_PHI_BT,0) + ISNULL(CHI_PHI_HN,0),2)) AS CHI_PHI_CO_KH,   
		SUM(ROUND(ISNULL(CHI_PHI,0),2)) AS CHI_PHI_KHO_KH, SUM(ROUND(ISNULL(CHI_PHI_BT,0) + ISNULL(CHI_PHI_HN,0) +  ISNULL(CHI_PHI,0),2)) AS TONG_CP
	FROM NHA_XUONG A LEFT JOIN  #CP_BT B ON A.MS_N_XUONG = B.MS_N_XUONG
	LEFT JOIN #CP_HN C ON A.MS_N_XUONG = C.MS_N_XUONG
	LEFT JOIN #CHI_PHI D ON A.MS_N_XUONG = D.MS_N_XUONG
	GROUP BY A.MS_N_XUONG,A.TEN_N_XUONG
) G ORDER BY TONG_CP DESC

