
-- EXEC Get_lstDanhsachbaocao 'ADMINISTRATOR' , 3,0, 1
ALTER proc [dbo].[Get_lstDanhsachbaocao]
	@USERLOG NVARCHAR(50),
	@LOAI_REPORT INT,
	@NGON_NGU INT,
	@REPORT_MAIL INT
AS
	SELECT RP.REPORT_NAME,CASE @NGON_NGU
	 WHEN 0 THEN RP.TEN_REPORT_VIET 
	 WHEN 1 THEN RP.TEN_REPORT_ANH
	 ELSE RP.TEN_REPORT_HOA END AS TEN_REPORT,NOTE, NAMES,[TYPE], STT
	FROM DS_REPORT RP INNER JOIN NHOM_REPORT ON RP.REPORT_NAME=NHOM_REPORT.REPORT_NAME
				INNER JOIN NHOM ON NHOM.GROUP_ID=NHOM_REPORT.GROUP_ID
				INNER JOIN USERS ON USERS.GROUP_ID=NHOM.GROUP_ID
	WHERE (LOAI_REPORT=@LOAI_REPORT OR @LOAI_REPORT = -1) AND (USERS.USERNAME=@USERLOG) AND (QUYEN='Access') AND (RP.STT IS NULL OR RP.STT>0) 
		AND (REPORT_MAIL = @REPORT_MAIL) AND (RP.STT <100)
	ORDER BY RP.STT,CASE @NGON_NGU
	 WHEN 0 THEN RP.TEN_REPORT_VIET 
	 WHEN 1 THEN RP.TEN_REPORT_ANH
	 ELSE RP.TEN_REPORT_HOA END
