

--EXEC [SP_Y_GET_TBDHHC] 'ADMIN',0,'01-01-2014','04-18-2016','-1','-1','-1','-1','-1','-1','-1',-1
--SELECT * FROM IC_DUONG 
ALTER procedure [dbo].[SP_Y_GET_TBDHHC]
(
	@USERNAME NVARCHAR (64), 
	@LANGUAGE INT,
	@TU_NGAY DATETIME,
	@DEN_NGAY DATETIME,
	@MS_NHA_XUONG NVARCHAR(50), 
	@MS_HE_THONG INT ,
	@MS_LOAI_MAY NVARCHAR(30),
	@MS_MAY NVARCHAR (30),
	@MS_TINH NVARCHAR(100),
	@MS_QUAN NVARCHAR(100),
	@MS_DUONG NVARCHAR(100),
	@MSLHC INT
)
AS

SELECT * INTO #MAY_USER
	FROM [dbo].[MGetMayUserNgay](@DEN_NGAY,@USERNAME,@MS_NHA_XUONG,@MS_HE_THONG,-1,@MS_LOAI_MAY,'-1',@MS_MAY,@LANGUAGE)


SELECT TEMP.MS_MAY,TEMP.TEN_MAY,CONVERT(NVARCHAR(10),TEMP.NGAY_HC,103) NGAY_HC,TEMP.CHU_KY_HC,
	CONVERT(NVARCHAR(10),TEMP.NGAY_HC_KE,103) NGAY_HC_KE,TEMP.TEN_LOAI_HIEU_CHUAN,TEMP.MS_TINH,TEMP.MS_QUAN,TEMP.MS_DUONG
FROM
(
SELECT DISTINCT T1.MS_MAY,
                T1.TEN_MAY,T6.NGAY_HC, 
--1 NOI 2 NGOAI 3 KIEM DINH 
--CHU_KY_HC_TB, CHU_KY_HIEU_CHUAN_TB_NGOAI, CHU_KY_KD_TB,
                CASE T6.MS_LOAI_HIEU_CHUAN 
					WHEN 1 THEN CONVERT(NVARCHAR(10),T1.CHU_KY_HC_TB) 
					WHEN 2 THEN CONVERT(NVARCHAR(10),T1.CHU_KY_HIEU_CHUAN_TB_NGOAI) 
					ELSE CONVERT(NVARCHAR(10),T1.CHU_KY_KD_TB) END 
					+ ' ' + 
					(CASE @LANGUAGE  WHEN 0 THEN DON_VI_THOI_GIAN.TEN_DV_TG ELSE DON_VI_THOI_GIAN.TEN_DV_TG_ANH END) AS CHU_KY_HC, 

CASE T6.MS_LOAI_HIEU_CHUAN
WHEN 1 THEN 
        CASE T1.DON_VI_THOI_GIAN WHEN 1 THEN
			DATEADD(DAY, T1.CHU_KY_HC_TB, T6.NGAY_HC)
        WHEN 2 THEN
			DATEADD(WEEK, T1.CHU_KY_HC_TB, T6.NGAY_HC) 
        WHEN 3 THEN
			DATEADD(MONTH, T1.CHU_KY_HC_TB, T6.NGAY_HC) 
        WHEN 4 THEN
			DATEADD(YEAR, T1.CHU_KY_HC_TB, T6.NGAY_HC) 
        END
WHEN 2 THEN 
        CASE T1.DON_VI_THOI_GIAN WHEN 1 THEN
			DATEADD(DAY, T1.CHU_KY_HIEU_CHUAN_TB_NGOAI, T6.NGAY_HC)
        WHEN 2 THEN
			DATEADD(WEEK, T1.CHU_KY_HIEU_CHUAN_TB_NGOAI, T6.NGAY_HC) 
        WHEN 3 THEN
			DATEADD(MONTH, T1.CHU_KY_HIEU_CHUAN_TB_NGOAI, T6.NGAY_HC) 
        WHEN 4 THEN
			DATEADD(YEAR, T1.CHU_KY_HIEU_CHUAN_TB_NGOAI, T6.NGAY_HC) 
        END
ELSE
        CASE T1.DON_VI_THOI_GIAN WHEN 1 THEN
			DATEADD(DAY, T1.CHU_KY_KD_TB, T6.NGAY_HC)
        WHEN 2 THEN
			DATEADD(WEEK, T1.CHU_KY_KD_TB, T6.NGAY_HC) 
        WHEN 3 THEN
			DATEADD(MONTH, T1.CHU_KY_KD_TB, T6.NGAY_HC) 
        WHEN 4 THEN
			DATEADD(YEAR, T1.CHU_KY_KD_TB, T6.NGAY_HC) 
        END
END AS NGAY_HC_KE,
				
				
TEN_LOAI_HIEU_CHUAN,MS_TINH=[dbo].[Get_CityCode](T2.MS_QG),MS_QUAN = T2.MS_QG,T2.MS_DUONG
                
FROM  #MAY_USER AS T1 INNER JOIN DON_VI_THOI_GIAN ON T1.DON_VI_THOI_GIAN = DON_VI_THOI_GIAN.MS_DV_TG INNER JOIN
(SELECT HIEU_CHUAN_MAY.* FROM 
	(SELECT MS_MAY, MAX(NGAY_HC) NGAY_MAX, MS_LOAI_HIEU_CHUAN FROM HIEU_CHUAN_MAY  GROUP BY MS_MAY,MS_LOAI_HIEU_CHUAN) T2 INNER JOIN 
	dbo.HIEU_CHUAN_MAY ON T2.MS_MAY = dbo.HIEU_CHUAN_MAY.MS_MAY AND HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN = T2.MS_LOAI_HIEU_CHUAN AND HIEU_CHUAN_MAY.NGAY_HC = T2.NGAY_MAX
) T6 ON T1.MS_MAY = T6.MS_MAY 
 
INNER JOIN
LOAI_HIEU_CHUAN_MAY ON T6.MS_LOAI_HIEU_CHUAN = LOAI_HIEU_CHUAN_MAY.MS_LOAI_HIEU_CHUAN 
INNER JOIN 
NHA_XUONG T2 ON T1.MS_N_XUONG = T2.MS_N_XUONG
WHERE 
CASE T6.MS_LOAI_HIEU_CHUAN 
		WHEN 1 THEN T1.CHU_KY_HC_TB
		WHEN 2 THEN T1.CHU_KY_HIEU_CHUAN_TB_NGOAI
		ELSE T1.CHU_KY_KD_TB END > 0		
AND (T6.MS_LOAI_HIEU_CHUAN = @MSLHC OR @MSLHC = -1)

)TEMP WHERE 
 (NGAY_HC_KE >=  CONVERT (NVARCHAR (10),@TU_NGAY , 102))
AND (NGAY_HC_KE <= CONVERT (NVARCHAR (10),@DEN_NGAY , 102))

ORDER BY TEMP.MS_MAY,TEMP.TEN_MAY