IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'FN' AND name = 'KiemNSHoanThanhPBT')
   exec('CREATE FUNCTION  dbo.KiemNSHoanThanhPBT () RETURNS  nvarchar(50) as Begin return null end')
GO

--SELECT dbo.KiemNSHoanThanhPBT ('WO-201501000531')
ALTER function [dbo].[KiemNSHoanThanhPBT]
(
	@MsPBT NVARCHAR(50)
)
RETURNS INT
as 
begin
DECLARE @iCV INT


IF EXISTS(SELECT PRIVATE FROM THONG_TIN_CHUNG WHERE PRIVATE = 'GREENFEED')
BEGIN
	SELECT @iCV = ISNULL(COUNT(*),0) FROM (SELECT ISNULL(COUNT(*),0) AS STT FROM (SELECT MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC WHERE MS_PHIEU_BAO_TRI = @MsPBT
	UNION SELECT MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CV_PHU_TRO WHERE MS_PHIEU_BAO_TRI = @MsPBT ) A ) A

	IF @iCV > 0 
	BEGIN
		SELECT @iCV = ISNULL(COUNT(*),0) FROM (SELECT MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET WHERE MS_PHIEU_BAO_TRI = @MsPBT UNION 
			SELECT MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO WHERE MS_PHIEU_BAO_TRI = @MsPBT ) A 
	END
END
ELSE
	SET @iCV = 1

RETURN @iCV

END