
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sBCKeHoachBaoTriTuan')
   exec('CREATE PROCEDURE sBCKeHoachBaoTriTuan AS BEGIN SET NOCOUNT ON; END')
GO



--	exec [sBCKeHoachBaoTriTuan] '11/14/2010','11/20/2018',-1,'TRUNGNV'

--EXEC sBCKeHoachBaoTriTuan
ALTER procedure sBCKeHoachBaoTriTuan
	@UserName NVARCHAR(50) = 'ADMIN',
	@NNgu int = 0,
	@MsNX NVARCHAR(5) = '-1', 
	@MS_LOAI_MAY NVARCHAR(20) = '-1',
	@MS_LOAI_CV INT = -1
AS

DECLARE @DEN_NGAY DATETIME
SET @DEN_NGAY = GETDATE()

SELECT DISTINCT MS_MAY,TEN_MAY, TEN_LOAI_MAY,MS_LOAI_MAY,TEN_NHOM_MAY,Ten_N_XUONG,MS_N_XUONG,MS_NHOM_MAY INTO #MAY_USER 
	FROM dbo.MGetMayUserNgay(@DEN_NGAY,@UserName,@MsNX,-1,-1,@MS_LOAI_MAY,'-1','-1',@NNgu) A


SELECT DISTINCT T1.MS_N_XUONG,Ten_N_XUONG,
          T1.MS_LOAI_MAY,T1.MS_MAY, CONG_VIEC.MO_TA_CV, MAY_LOAI_BTPN_CHU_KY.MS_LOAI_BT,TEN_LOAI_BT, LOAI_BAO_TRI.THU_TU, NGAY_CUOI,NGAY_CUOI AS NGAY_KE, CHU_KY,MS_DV_TG, 
		  '' AS N1, '' AS N2, '' AS N3, '' AS N4, '' AS N5, '' as N6, '' AS N7
           FROM   #MAY_USER T1 INNER JOIN
                  MAY_LOAI_BTPN ON T1.MS_MAY = MAY_LOAI_BTPN.MS_MAY INNER JOIN
                  MAY_LOAI_BTPN_CHU_KY ON MAY_LOAI_BTPN.MS_MAY = MAY_LOAI_BTPN_CHU_KY.MS_MAY AND 
                  MAY_LOAI_BTPN.MS_LOAI_BT = MAY_LOAI_BTPN_CHU_KY.MS_LOAI_BT INNER JOIN
                  MAY_LOAI_BTPN_CONG_VIEC ON MAY_LOAI_BTPN.MS_MAY = MAY_LOAI_BTPN_CONG_VIEC.MS_MAY AND 
                  MAY_LOAI_BTPN.MS_LOAI_BT = MAY_LOAI_BTPN_CONG_VIEC.MS_LOAI_BT INNER JOIN
                  CONG_VIEC ON MAY_LOAI_BTPN_CONG_VIEC.MS_CV = CONG_VIEC.MS_CV INNER JOIN
                  LOAI_BAO_TRI ON LOAI_BAO_TRI.MS_LOAI_BT = MAY_LOAI_BTPN.MS_LOAI_BT
WHERE MS_LOAI_CV = @MS_LOAI_CV OR @MS_LOAI_CV = -1
