
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetDonViUserAll')
   exec('CREATE PROCEDURE GetDonViUserAll AS BEGIN SET NOCOUNT ON; END')
GO


--EXEC GetDonViUserAll 1,'TRUNGNV'
ALTER proc [dbo].[GetDonViUserAll]
	@CoALL bit = 1,
	@Username NVARCHAR(50) = 'Admin'
AS


SELECT DISTINCT T2.MS_DON_VI INTO #PB_USER
FROM            dbo.NHOM_TO_PHONG_BAN AS T1 INNER JOIN
                         dbo.TO_PHONG_BAN AS T2 ON T1.MS_TO = T2.MS_TO INNER JOIN
                         dbo.USERS AS T3 ON T1.GROUP_ID = T3.GROUP_ID
WHERE        (T3.USERNAME = @Username)

if @CoALL = 0
	SELECT T1.MS_DON_VI, TEN_DON_VI, TEN_NGAN FROM DON_VI T1 INNER JOIN #PB_USER T2 ON T1.MS_DON_VI = T2.MS_DON_VI   ORDER BY TEN_DON_VI 
else
	SELECT T1.MS_DON_VI, TEN_DON_VI, TEN_NGAN FROM DON_VI T1 INNER JOIN #PB_USER T2 ON T1.MS_DON_VI = T2.MS_DON_VI
	UNION
	SELECT '-1', '< ALL >', '< ALL >'
	ORDER BY TEN_DON_VI 



