UPDATE MENU SET MENU_PARENT = NULL, AN_HIEN = 0 WHERE        (MENU_TEXT LIKE '%2.11%')


UPDATE MENU SET MENU_PARENT = 'mnuMasterData' , FUNCTION_NAME = 'ShowChiuPhi', AN_HIEN =1  WHERE MENU_ID = 'mnuBoPhanChiuPhiTong'
