IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spINSERT_TINH_TRANG_PBT_CT')
   exec('CREATE PROCEDURE spINSERT_TINH_TRANG_PBT_CT AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC [dbo].[spINSERT_TINH_TRANG_PBT_CT]
	@TEN_TIENG_VIET NVARCHAR(50),
	@TEN_TIENG_ANH NVARCHAR(255),
	@TEN_TIENG_HOA NVARCHAR(255),
	@MA_SO NVARCHAR(50),
	@STT INT,
	@GHI_CHU NVARCHAR(255),
	@MAC_DINH BIT

AS
BEGIN
		IF NOT EXISTS (SELECT * FROM TINH_TRANG_PBT_CT WHERE STT = @STT AND MAC_DINH = 1)
		BEGIN
				SET @MAC_DINH = 1;				
		END
			
		IF(@MAC_DINH = 1)
		BEGIN
				UPDATE TINH_TRANG_PBT_CT 
				SET MAC_DINH = 0
				WHERE STT = @STT	
		END

		INSERT INTO TINH_TRANG_PBT_CT (TEN_TIENG_VIET ,MA_SO , TEN_TIENG_ANH , TEN_TIENG_HOA , GHI_CHU, STT, MAC_DINH)
		VALUES (@TEN_TIENG_VIET, @MA_SO, @TEN_TIENG_ANH, @TEN_TIENG_HOA, @GHI_CHU, @STT, @MAC_DINH )
		SELECT SCOPE_IDENTITY()
		RETURN;
END