IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spINSERT_PHIEU_BAO_TRI_HINH')
   exec('CREATE PROCEDURE spINSERT_PHIEU_BAO_TRI_HINH AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC [dbo].[spINSERT_PHIEU_BAO_TRI_HINH]
	@MS_PHIEU_BAO_TRI NVARCHAR(50),
	@TEN_TAI_LIEU NVARCHAR(255),
	@DUONG_DAN NVARCHAR(255)

AS
BEGIN

		INSERT INTO PHIEU_BAO_TRI_HINH (MS_PHIEU_BAO_TRI, TEN_TAI_LIEU, DUONG_DAN)
		VALUES (@MS_PHIEU_BAO_TRI, @TEN_TAI_LIEU, @DUONG_DAN)
		RETURN;
END