IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spUPDATE_TINH_TRANG_PBT_CT')
   exec('CREATE PROCEDURE spUPDATE_TINH_TRANG_PBT_CT AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC [dbo].[spUPDATE_TINH_TRANG_PBT_CT]
	@TEN_TIENG_VIET NVARCHAR(50),
	@TEN_TIENG_ANH NVARCHAR(255),
	@TEN_TIENG_HOA NVARCHAR(255),
	@MA_SO NVARCHAR(50),
	@STT INT,
	@GHI_CHU NVARCHAR(255),
	@MS_TT_CT INT,
	@MAC_DINH BIT
AS
BEGIN
		IF(@MAC_DINH = 1)
		BEGIN
				UPDATE TINH_TRANG_PBT_CT 
				SET MAC_DINH = 0
				WHERE STT = @STT	
		END
		
		UPDATE TINH_TRANG_PBT_CT 
		SET
			TEN_TIENG_VIET = @TEN_TIENG_VIET,
			TEN_TIENG_ANH = @TEN_TIENG_ANH,
			TEN_TIENG_HOA = @TEN_TIENG_HOA ,
			MA_SO = @MA_SO,			
			STT = @STT,
			GHI_CHU = @GHI_CHU,
			MAC_DINH = @MAC_DINH
		WHERE
			MS_TT_CT = @MS_TT_CT 			
		RETURN;
END