INSERT INTO PHIEU_BAO_TRI_TINH_TRANG_CHI_TIET (MS_PHIEU_BAO_TRI,STT,MS_TT_CT,THOI_GIAN,USERNAME)
SELECT A.MS_PHIEU_BAO_TRI,1,B.MS_TT_CT,A.NGAY_BD_KH, USERNAME_NGUOI_LAP
FROM PHIEU_BAO_TRI A INNER JOIN 
(SELECT * FROM TINH_TRANG_PBT_CT WHERE MAC_DINH = 1) B ON A.TINH_TRANG_PBT = B.STT
WHERE MS_PHIEU_BAO_TRI NOT IN( SELECT MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_TINH_TRANG_CHI_TIET)