IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spUPDATE_PBT_TINH_TRANG_CT')
   exec('CREATE PROCEDURE spUPDATE_PBT_TINH_TRANG_CT AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC [dbo].[spUPDATE_PBT_TINH_TRANG_CT]
	@MS_PHIEU_BAO_TRI NVARCHAR(50),
	@MS_TT_CT INT
	
AS
BEGIN
		
		UPDATE PHIEU_BAO_TRI 
		SET MS_TT_CT = @MS_TT_CT
		WHERE MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI	
		
		RETURN;
END