IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spTinhTrangPBT_GET')
   exec('CREATE PROCEDURE spTinhTrangPBT_GET AS BEGIN SET NOCOUNT ON; END')
 Go
--exec [spTinhTrangPBTCT_GET] 1
ALTER PROC [dbo].[spTinhTrangPBT_GET]

	@NNgu int	
AS

select STT , CASE @NNgu WHEN 0 THEN TEN_TINH_TRANG WHEN 1 THEN TEN_TINH_TRANG_ANH ELSE TEN_TINH_TRANG_HOA END AS TEN_TINH_TRANG from TINH_TRANG_PBT
