

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'MGetCNUsersAll')
   exec('CREATE PROCEDURE MGetCNUsersAll AS BEGIN SET NOCOUNT ON; END')
GO

--EXEC MGetCNUsersAll
alter proc [dbo].[MGetCNUsersAll]
	@CoALL bit = 0,
	@MS_DV NVARCHAR(50) = '-1',
	@MS_TO NVARCHAR(50) = '-1',
	@Username NVARCHAR(50) = 'Admin'
AS	
	SELECT Distinct MS_DON_VI, MS_TO INTO #TO_USER FROM [dbo].[MGetDonViPhongBanUser](@Username) 
	WHERE (MS_TO = @MS_TO OR @MS_TO = '-1') AND (MS_DON_VI = @MS_DV OR	@MS_DV = '-1')

	IF(@CoALL = 1)
	BEGIN
			SELECT A.MS_CONG_NHAN, (HO + ' ' +  TEN)  AS HO_TEN_CONG_NHAN,TEN FROM CONG_NHAN A 
			INNER JOIN TO_PHONG_BAN T1 ON T1.MS_TO = A.MS_TO
			INNER JOIN #TO_USER T ON T1.MS_TO = T.MS_TO	AND T.MS_DON_VI = T1.MS_DON_VI 
			UNION
			SELECT '-1', ' < ALL > ', '-1'	
			ORDER BY TEN  , A.MS_CONG_NHAN 
	END
	ELSE
	BEGIN
			SELECT A.MS_CONG_NHAN, (HO + ' ' +  TEN)  AS HO_TEN_CONG_NHAN, TEN FROM CONG_NHAN A 
			INNER JOIN TO_PHONG_BAN T1 ON T1.MS_TO = A.MS_TO
			INNER JOIN #TO_USER T ON T1.MS_TO = T.MS_TO	AND T.MS_DON_VI = T1.MS_DON_VI 			
			ORDER BY HO  , TEN 
	END


