ALTER PROCEDURE [dbo].[COPY_CAU_TRUC_TB] 
@MS_MAY_ODD NVARCHAR (50) , 
@MS_MAY_NEW NVARCHAR (50)
 AS
BEGIN 
select * from CAU_TRUC_THIET_BI
INSERT INTO CAU_TRUC_THIET_BI  
SELECT @MS_MAY_NEW AS MS_MAY , 
MS_BO_PHAN,
 TEN_BO_PHAN,
  MS_PT , 
  SO_LUONG, 
MS_BO_PHAN_CHA = CASE MS_BO_PHAN_CHA WHEN @MS_MAY_ODD THEN @MS_MAY_NEW ELSE MS_BO_PHAN_CHA END  ,
 GHI_CHU ,
  RUN_TIME, 
  MS_DVT_RT , HINH, CLASS_ID, '' AS  STT, null as ten_bo_phan_anh, null as ten_bo_phan_hoa
 FROM dbo.CAU_TRUC_THIET_BI WHERE dbo.CAU_TRUC_THIET_BI.MS_MAY = @MS_MAY_ODD 
 AND ((case when MS_BO_PHAN_CHA = MS_MAY then @MS_MAY_NEW else MS_BO_PHAN_CHA end) + MS_BO_PHAN NOT IN (SELECT MS_BO_PHAN_CHA + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI WHERE dbo.CAU_TRUC_THIET_BI.MS_MAY = @MS_MAY_NEW ))




INSERT INTO [CAU_TRUC_THIET_BI_CONG_VIEC]([MS_MAY],[MS_BO_PHAN],[MS_CV],[GHI_CHU],[ACTIVE],[TG_KH])
SELECT @MS_MAY_NEW AS MS_MAY , MS_BO_PHAN, MS_CV , GHI_CHU,ACTIVE,[TG_KH]
 FROM dbo.CAU_TRUC_THIET_BI_CONG_VIEC  WHERE dbo.CAU_TRUC_THIET_BI_CONG_VIEC.MS_MAY = @MS_MAY_ODD
 AND (MS_BO_PHAN + CONVERT(NVARCHAR(10),MS_CV) NOT IN (SELECT MS_BO_PHAN + CONVERT(NVARCHAR(10),MS_CV) 
 FROM dbo.CAU_TRUC_THIET_BI_CONG_VIEC WHERE MS_MAY = @MS_MAY_NEW))


INSERT INTO dbo.CAU_TRUC_THIET_BI_PHU_TUNG  SELECT @MS_MAY_NEW AS MS_MAY , MS_BO_PHAN, MS_PT ,MS_VI_TRI_PT , SO_LUONG,ACTIVE,CHUC_NANG
 FROM dbo.CAU_TRUC_THIET_BI_PHU_TUNG  WHERE dbo.CAU_TRUC_THIET_BI_PHU_TUNG.MS_MAY = @MS_MAY_ODD
 AND (MS_BO_PHAN + MS_PT + MS_VI_TRI_PT NOT IN (SELECT MS_BO_PHAN + MS_PT + MS_VI_TRI_PT FROM dbo.CAU_TRUC_THIET_BI_PHU_TUNG WHERE MS_MAY = @MS_MAY_NEW))
 
select * from CAU_TRUC_THIET_BI_TS_GSTT

INSERT INTO dbo.CAU_TRUC_THIET_BI_TS_GSTT  SELECT @MS_MAY_NEW AS MS_MAY , MS_BO_PHAN, MS_TS_GSTT ,MS_TT, TEN_GT, GIA_TRI_TREN, GIA_TRI_DUOI,CHU_KY_DO , MS_DV_TG,DAT,GHI_CHU,ACTIVE, null, null, null, null, null, null
 FROM dbo.CAU_TRUC_THIET_BI_TS_GSTT  WHERE dbo.CAU_TRUC_THIET_BI_TS_GSTT.MS_MAY = @MS_MAY_ODD
 AND (MS_BO_PHAN + MS_TS_GSTT +  CONVERT(NVARCHAR(10),MS_TT)  
 NOT IN (SELECT MS_BO_PHAN + MS_TS_GSTT + CONVERT(NVARCHAR(10),MS_TT) FROM dbo.CAU_TRUC_THIET_BI_TS_GSTT WHERE MS_MAY = @MS_MAY_NEW))
 

INSERT INTO dbo.MAY_LOAI_BTPN  SELECT @MS_MAY_NEW AS MS_MAY , MS_LOAI_BT , NGAY_CUOI, SO_NGAY, THUC_HIEN_BOI, GHI_CHU
 FROM dbo.MAY_LOAI_BTPN  WHERE dbo.MAY_LOAI_BTPN.MS_MAY = @MS_MAY_ODD
 AND ( MS_LOAI_BT NOT IN (SELECT MS_LOAI_BT FROM dbo.MAY_LOAI_BTPN  WHERE MS_MAY = @MS_MAY_NEW))

INSERT INTO dbo.MAY_LOAI_BTPN_CHU_KY  SELECT @MS_MAY_NEW AS MS_MAY , MS_LOAI_BT , NGAY_AD, CHU_KY, MS_DV_TG, RUN_TIME, MS_DVT_RT,MOVEMENT 
 FROM  dbo.MAY_LOAI_BTPN_CHU_KY  WHERE  dbo.MAY_LOAI_BTPN_CHU_KY.MS_MAY = @MS_MAY_ODD
 AND ( MS_LOAI_BT NOT IN (SELECT MS_LOAI_BT FROM dbo.MAY_LOAI_BTPN_CHU_KY  WHERE MS_MAY = @MS_MAY_NEW))




INSERT INTO dbo.MAY_LOAI_BTPN_CONG_VIEC  SELECT @MS_MAY_NEW AS MS_MAY , MS_LOAI_BT ,MS_CV, MS_BO_PHAN
 FROM  dbo.MAY_LOAI_BTPN_CONG_VIEC  WHERE  dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_MAY = @MS_MAY_ODD
 AND ( CONVERT(NVARCHAR(10),MS_LOAI_BT) + CONVERT(NVARCHAR(10),MS_CV) + MS_BO_PHAN NOT IN (SELECT  CONVERT(NVARCHAR(10),MS_LOAI_BT) + CONVERT(NVARCHAR(10),MS_CV) + MS_BO_PHAN FROM dbo.MAY_LOAI_BTPN_CONG_VIEC  WHERE MS_MAY = @MS_MAY_NEW))



INSERT INTO dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG 
SELECT @MS_MAY_NEW AS MS_MAY , MS_LOAI_BT ,MS_CV, MS_BO_PHAN,MS_PT,SO_LUONG,QUI_CACH,GHI_CHU_BTPN
FROM   dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG  WHERE  dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_MAY = @MS_MAY_ODD
AND ( CONVERT(NVARCHAR(10),MS_LOAI_BT) + CONVERT(NVARCHAR(10),MS_CV) + MS_BO_PHAN + MS_PT NOT IN (SELECT   CONVERT(NVARCHAR(10),MS_LOAI_BT) +  CONVERT(NVARCHAR(10),MS_CV) + MS_BO_PHAN + MS_PT FROM dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG  WHERE MS_MAY = @MS_MAY_NEW))
END



