IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_rptDANH_SACH_BP_CP_THIET_BI')
   exec('CREATE PROCEDURE GET_rptDANH_SACH_BP_CP_THIET_BI AS BEGIN SET NOCOUNT ON; END')
GO
alter procedure [dbo].[GET_rptDANH_SACH_BP_CP_THIET_BI] 
	@MS_MAY NVARCHAR(30)
AS
SELECT     ROW_NUMBER() OVER(ORDER BY MAY_BO_PHAN_CHIU_PHI.ms_may DESC) AS STT, dbo.MAY_BO_PHAN_CHIU_PHI.NGAY_NHAP, 
                      dbo.BO_PHAN_CHIU_PHI.TEN_BP_CHIU_PHI, dbo.DON_VI.TEN_DON_VI
FROM         dbo.MAY_BO_PHAN_CHIU_PHI INNER JOIN
                      dbo.BO_PHAN_CHIU_PHI ON dbo.MAY_BO_PHAN_CHIU_PHI.MS_BP_CHIU_PHI = dbo.BO_PHAN_CHIU_PHI.MS_BP_CHIU_PHI INNER JOIN
                      dbo.DON_VI ON dbo.BO_PHAN_CHIU_PHI.MSDV = dbo.DON_VI.MS_DON_VI INNER JOIN
                      dbo.MAY INNER JOIN
                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY ON 
                      dbo.MAY_BO_PHAN_CHIU_PHI.MS_MAY = dbo.MAY.MS_MAY
WHERE   dbo.MAY.MS_MAY =@MS_MAY

