
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_rptLICH_BAO_TRI_DINH_KI')
   exec('CREATE PROCEDURE GET_rptLICH_BAO_TRI_DINH_KI AS BEGIN SET NOCOUNT ON; END')
GO

alter procedure [dbo].[GET_rptLICH_BAO_TRI_DINH_KI] 
	@MS_MAY NVARCHAR(30),
	@NNgu nvarchar(1)
AS


SELECT     ROW_NUMBER() OVER(ORDER BY MAY_LOAI_BTPN_CONG_VIEC.ms_may DESC) AS STT, dbo.CONG_VIEC.MO_TA_CV, 
				dbo.LOAI_BAO_TRI.TEN_LOAI_BT,    
                dbo.IC_PHU_TUNG.TEN_PT, dbo.CAU_TRUC_THIET_BI.TEN_BO_PHAN,
                dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.SO_LUONG ,CASE 0 when 0 then dbo.DON_VI_TINH.TEN_1 when 1 then dbo.DON_VI_TINH.TEN_2 end as DVT 
         FROM         dbo.DON_VI_TINH INNER JOIN 
                dbo.IC_PHU_TUNG ON dbo.DON_VI_TINH.DVT = dbo.IC_PHU_TUNG.DVT RIGHT OUTER JOIN 
                dbo.MAY_LOAI_BTPN_CHU_KY INNER JOIN 
                dbo.MAY_LOAI_BTPN_CONG_VIEC ON dbo.MAY_LOAI_BTPN_CHU_KY.MS_MAY = dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_MAY AND
                dbo.MAY_LOAI_BTPN_CHU_KY.MS_LOAI_BT = dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_LOAI_BT INNER JOIN 
                dbo.CONG_VIEC ON dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_CV = dbo.CONG_VIEC.MS_CV INNER JOIN 
                dbo.CAU_TRUC_THIET_BI ON dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_MAY = dbo.CAU_TRUC_THIET_BI.MS_MAY AND 
                dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_BO_PHAN = dbo.CAU_TRUC_THIET_BI.MS_BO_PHAN INNER JOIN 
                dbo.LOAI_BAO_TRI ON dbo.MAY_LOAI_BTPN_CHU_KY.MS_LOAI_BT = dbo.LOAI_BAO_TRI.MS_LOAI_BT INNER JOIN
                dbo.MAY ON dbo.MAY_LOAI_BTPN_CHU_KY.MS_MAY = dbo.MAY.MS_MAY INNER JOIN 
                dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN 
                dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY LEFT OUTER JOIN 
                dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG ON 
                dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_MAY = dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_MAY And
                dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_LOAI_BT = dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_LOAI_BT And
                dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_CV = dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_CV And 
                dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_BO_PHAN = dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_BO_PHAN ON 
                dbo.IC_PHU_TUNG.MS_PT = dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_PT
        GROUP BY dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_MAY, dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_CV, dbo.CONG_VIEC.MO_TA_CV,
                dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_LOAI_BT, dbo.LOAI_BAO_TRI.TEN_LOAI_BT, dbo.MAY_LOAI_BTPN_CONG_VIEC.MS_BO_PHAN,
                dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.MS_PT, dbo.IC_PHU_TUNG.MS_PT_NCC, dbo.IC_PHU_TUNG.TEN_PT,
                dbo.CAU_TRUC_THIET_BI.TEN_BO_PHAN, dbo.NHOM_MAY.TEN_NHOM_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY, 
                dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG.SO_LUONG, CASE 0 when 0 then dbo.DON_VI_TINH.TEN_1 when 1 then dbo.DON_VI_TINH.TEN_2 end, dbo.LOAI_BAO_TRI.THU_TU having MAY_LOAI_BTPN_CONG_VIEC.MS_MAY = @MS_MAY ORDER BY dbo.LOAI_BAO_TRI.THU_TU DESC