
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_rptDanhsach_VTPT_TheoMay')
   exec('CREATE PROCEDURE GET_rptDanhsach_VTPT_TheoMay AS BEGIN SET NOCOUNT ON; END')
GO
alter procedure [dbo].[GET_rptDanhsach_VTPT_TheoMay] 
	@MS_MAY NVARCHAR(30),
	@NNgu nvarchar(1)
AS

SELECT ROW_NUMBER() OVER(ORDER BY MAY.ms_may DESC) AS STT, CAU_TRUC_THIET_BI_PHU_TUNG.MS_PT, dbo.IC_PHU_TUNG.MS_PT_NCC as PART_NO, dbo.IC_PHU_TUNG.TEN_PT,dbo.IC_PHU_TUNG.MS_PT_CTY,dbo.IC_PHU_TUNG.QUY_CACH, SUM(CAU_TRUC_THIET_BI_PHU_TUNG.SO_LUONG) AS SO_LUONG,		case @NNgu when 0 then dbo.DON_VI_TINH.TEN_1 when 1 then dbo.DON_VI_TINH.TEN_2 end as DVT
FROM dbo.IC_PHU_TUNG INNER JOIN dbo.DON_VI_TINH ON dbo.IC_PHU_TUNG.DVT = dbo.DON_VI_TINH.DVT 
					INNER JOIN dbo.CAU_TRUC_THIET_BI INNER JOIN dbo.CAU_TRUC_THIET_BI_PHU_TUNG ON dbo.CAU_TRUC_THIET_BI.MS_MAY =						dbo.CAU_TRUC_THIET_BI_PHU_TUNG.MS_MAY AND dbo.CAU_TRUC_THIET_BI.MS_BO_PHAN = dbo.CAU_TRUC_THIET_BI_PHU_TUNG.MS_BO_PHAN 
					INNER JOIN dbo.MAY ON dbo.CAU_TRUC_THIET_BI.MS_MAY = dbo.MAY.MS_MAY ON dbo.IC_PHU_TUNG.MS_PT =										dbo.CAU_TRUC_THIET_BI_PHU_TUNG.MS_PT 
WHERE (dbo.MAY.MS_MAY= @MS_MAY)
GROUP BY MAY.MS_MAY,CAU_TRUC_THIET_BI_PHU_TUNG.MS_PT,MS_PT_NCC,MS_PT_CTY,TEN_PT,QUY_CACH,TEN_1,TEN_2
order by CAU_TRUC_THIET_BI_PHU_TUNG.MS_PT
