
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetCaTheoGio')
   exec('CREATE PROCEDURE GetCaTheoGio AS BEGIN SET NOCOUNT ON; END')
GO
--EXEC GetCaTheoGio '11/3/2016 09:51:39', 0
ALTER PROC GetCaTheoGio
	@TGio DATETIME,
	@NNGU BIT
AS
BEGIN
		SELECT STT, (CASE @NNGU WHEN 0 THEN CA ELSE CA_ANH END) +
		' (' + CONVERT(NVARCHAR(5),CAST(TU_GIO AS TIME),108) + ' - ' +  CONVERT(NVARCHAR(5),CAST(DEN_GIO AS TIME),108) + ')'
		
		 AS TEN_CA FROM CA WHERE CONVERT(DATETIME,CAST(@TGio AS TIME) , 108) BETWEEN CONVERT(DATETIME, CAST(TU_GIO AS TIME), 108) AND CONVERT(DATETIME, CAST(DEN_GIO AS TIME), 108) 
END
