IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CheckCATheoGio')
   exec('CREATE PROCEDURE CheckCATheoGio AS BEGIN SET NOCOUNT ON; END')
GO



ALTER procedure [dbo].[CheckCATheoGio]
	@TGio DATETIME
 AS
BEGIN
SELECT STT, TU_GIO , DEN_GIO FROM CA WHERE CONVERT(DATETIME,CAST(@TGio AS TIME) , 108) BETWEEN CONVERT(DATETIME, CAST(TU_GIO AS TIME), 108) AND CONVERT(DATETIME, CAST(DEN_GIO AS TIME), 108) 
END
