UPDATE THOI_GIAN_NGUNG_MAY_SO_LAN 
SET MS_NGUYEN_NHAN = B.MS_NGUYEN_NHAN, NGUOI_GIAI_QUYET = B.NGUOI_GIAI_QUYET, NGUYEN_NHAN = B.NGUYEN_NHAN ,
HIEN_TUONG = B.HIEN_TUONG, NGUYEN_NHAN_CU_THE = B.NGUYEN_NHAN_CU_THE 
FROM THOI_GIAN_NGUNG_MAY_SO_LAN A INNER JOIN THOI_GIAN_NGUNG_MAY B ON A.MS_LAN = B.MS_LAN  

