IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'MTinhTonKhoTheoViTri')
   exec('CREATE PROCEDURE MTinhTonKhoTheoViTri AS BEGIN SET NOCOUNT ON; END')
GO

--exec MTinhTonKhoTheoViTri '01/01/2016','12/31/2017','-1',-1,'ADMIN',0
-- 
--DECLARE @TonKho AS TypeInventory; INSERT INTO @TonKho  exec MTinhTonKhoTheoViTri '01/01/2016','12/31/2017','-1',-1,'ADMIN',0 SELECT * FROM @TonKho


--DECLARE @TonKho AS TypeInventory;
--INSERT INTO @TonKho 
--exec MTinhTonKhoTheoViTri '01/01/2016','12/31/2017','-1',-1,'ADMIN',0
--SELECT * FROM @TonKho

alter proc [dbo].MTinhTonKhoTheoViTri
(
	@TNgay DATE = '01/01/2016',
	@DNgay DATE = '12/31/2017',
	@MsLoaiVT NVARCHAR (50) = '-1',
	@MSKho INT = -1,
	@UserName NVARCHAR(50) = 'ADMIN',
	@NNgu int = 0
)

AS 
BEGIN




SELECT DISTINCT T5.MS_PT,CASE @NNgu WHEN 0 THEN T5.TEN_PT WHEN 1 THEN T5.TEN_PT_ANH ELSE T5.TEN_PT_HOA END AS TEN_PT,
	T4.MS_LOAI_VT, CASE @NNgu WHEN 0 THEN T4.TEN_LOAI_VT_TV WHEN 1 THEN T4.TEN_LOAI_VT_TA ELSE T4.TEN_LOAI_VT_TH END AS TEN_LOAI_VT 
INTO #PhuTung 
FROM dbo.USERS AS T1 INNER JOIN
dbo.NHOM_LOAI_PHU_TUNG AS T2 ON T1.GROUP_ID = T2.GROUP_ID INNER JOIN
dbo.LOAI_PHU_TUNG AS T3 ON T2.MS_LOAI_PT = T3.MS_LOAI_PT INNER JOIN
dbo.LOAI_VT AS T4 INNER JOIN
dbo.IC_PHU_TUNG AS T5 ON T4.MS_LOAI_VT = T5.MS_LOAI_VT INNER JOIN
dbo.IC_PHU_TUNG_LOAI_PHU_TUNG AS T6 ON T5.MS_PT = T6.MS_PT ON T3.MS_LOAI_PT = T6.MS_LOAI_PT 						 
WHERE (T1.USERNAME =@UserName) AND (T4.MS_LOAI_VT = @MsLoaiVT OR @MsLoaiVT = '-1') AND (T5.ACTIVE_PT = 1)


SELECT A.MS_KHO 
INTO #KHO_TMP
FROM IC_KHO A INNER JOIN NHOM_KHO B ON A.MS_KHO = B.MS_KHO INNER JOIN USERS C ON B.GROUP_ID = C.GROUP_ID
		WHERE (USERNAME = @UserName) AND (A.MS_KHO = @MSKho OR @MSKho = -1)
----------		

--tồn hiện tại

SELECT T1.MS_PT,T1.MS_KHO, MS_VI_TRI,  SUM(SL_VT) AS SL_TON_HT,SUM(SL_VT * DON_GIA * TY_GIA) AS GT_TON_HT 
INTO #TON_HT
FROM VI_TRI_KHO_VAT_TU T1 
INNER JOIN #PhuTung T2 ON T1.MS_PT = T2.MS_PT 
INNER JOIN #KHO_TMP T3 ON T1.MS_KHO = T3.MS_KHO INNER JOIN
dbo.IC_DON_HANG_NHAP_VAT_TU AS T4 ON T1.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT AND T1.MS_PT = T4.MS_PT AND T1.ID = T4.ID 
GROUP BY T1.MS_KHO, MS_VI_TRI, T1.MS_PT
 
--số lượng xuất từ đến ngày đến hiện tại DNHT A

SELECT        T3.MS_PT,T1.MS_KHO, T3.MS_VI_TRI, SUM(T3.SL_VT) AS SL_XUAT_ADNHT, SUM(T3.SL_VT * T5.DON_GIA * T5.TY_GIA) AS GT_XUAT_ADNHT
INTO #XUAT_ADNHT
FROM            dbo.IC_DON_HANG_XUAT AS T1 INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU AS T4 ON T1.MS_DH_XUAT_PT = T4.MS_DH_XUAT_PT INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS T3 ON T4.MS_DH_XUAT_PT = T3.MS_DH_XUAT_PT AND T4.MS_PT = T3.MS_PT INNER JOIN
                         #KHO_TMP T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T5 ON T3.MS_PT = T5.MS_PT AND T3.MS_DH_NHAP_PT = T5.MS_DH_NHAP_PT AND T3.ID_XUAT = T5.ID 
						 INNER JOIN #PhuTung PT ON T3.MS_PT = PT.MS_PT
WHERE (CONVERT(DATE,T1.NGAY) > @DNgay)
GROUP BY T3.MS_PT,T1.MS_KHO, T3.MS_VI_TRI

--Lấy số lượng xuất trong khoảng từ ngày đến ngày TNDN B

SELECT        T3.MS_PT,T1.MS_KHO, T3.MS_VI_TRI, SUM(T3.SL_VT) AS SL_XUAT_BTNDN, SUM(T3.SL_VT * T5.DON_GIA * T5.TY_GIA) AS GT_XUAT_BTNDN
INTO #XUAT_BTNDN
FROM            dbo.IC_DON_HANG_XUAT AS T1 INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU AS T4 ON T1.MS_DH_XUAT_PT = T4.MS_DH_XUAT_PT INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS T3 ON T4.MS_DH_XUAT_PT = T3.MS_DH_XUAT_PT AND T4.MS_PT = T3.MS_PT INNER JOIN
                         #KHO_TMP T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T5 ON T3.MS_PT = T5.MS_PT AND T3.MS_DH_NHAP_PT = T5.MS_DH_NHAP_PT AND T3.ID_XUAT = T5.ID 
						 INNER JOIN #PhuTung PT ON T3.MS_PT = PT.MS_PT
WHERE CONVERT(DATE,T1.NGAY) >= @TNgay AND CONVERT(DATE,T1.NGAY) <= @DNgay
GROUP BY T3.MS_PT,T1.MS_KHO, T3.MS_VI_TRI

--Lấy số lượng nhập từ đến ngày đến hiện tại DNHT A

SELECT        T4.MS_PT,T1.MS_KHO, T4.MS_VI_TRI, SUM(T4.SL_VT) AS SL_NHAP_ADNHT, SUM(T4.SL_VT * T3.DON_GIA * T3.TY_GIA) AS GT_NHAP_ADNHT
INTO #NHAP_ADNHT
FROM            dbo.IC_DON_HANG_NHAP AS T1 INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET AS T4 ON T3.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT AND T3.MS_PT = T4.MS_PT AND T3.ID = T4.ID INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO 
						 INNER JOIN #PhuTung PT ON T4.MS_PT = PT.MS_PT
WHERE        (CONVERT(DATE,T1.NGAY) > @DNgay)
GROUP BY T4.MS_PT,T1.MS_KHO, T4.MS_VI_TRI

--Lấy số lượng nhập từ ngày đến ngày TNDN B

SELECT        T4.MS_PT,T1.MS_KHO, T4.MS_VI_TRI, SUM(T4.SL_VT) AS SL_NHAP_BTNDN, SUM(T4.SL_VT * T3.DON_GIA * T3.TY_GIA) AS GT_NHAP_BTNDN
INTO #NHAP_BTNDN
FROM            dbo.IC_DON_HANG_NHAP AS T1 INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET AS T4 ON T3.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT AND T3.MS_PT = T4.MS_PT AND T3.ID = T4.ID INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO 
						 INNER JOIN #PhuTung PT ON T4.MS_PT = PT.MS_PT
WHERE CONVERT(DATE,T1.NGAY) >= @TNgay AND CONVERT(DATE,T1.NGAY) <= @DNgay
GROUP BY T4.MS_PT,T1.MS_KHO, T4.MS_VI_TRI

--Lấy số lượng di chuyển đi từ đến ngày đến hiện tại DNHT A

SELECT        T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI, SUM(T1.SL_CHUYEN) AS SL_CHUYEN_DI_ADNHT,SUM(T1.SL_CHUYEN * T3.DON_GIA * T3.TY_GIA) AS GT_CHUYEN_DI_ADNHT
INTO #CHUYEN_DI_ADNHT
FROM            dbo.DI_CHUYEN_VI_TRI_TRONG_KHO AS T1 INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T1.MS_PT = T3.MS_PT AND T1.ID_DC = T3.ID
						 INNER JOIN #PhuTung PT ON T1.MS_PT = PT.MS_PT
WHERE        (CONVERT(DATE,T1.NGAY_CHUYEN) > @DNgay)
GROUP BY T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI

--Lấy số lượng di chuyển đi từ ngày đến ngày TNDN B

SELECT        T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI, SUM(T1.SL_CHUYEN) AS SL_CHUYEN_DI_BTNDN,SUM(T1.SL_CHUYEN * T3.DON_GIA * T3.TY_GIA) AS GT_CHUYEN_DI_BTNDN
INTO #CHUYEN_DI_BTNDN
FROM            dbo.DI_CHUYEN_VI_TRI_TRONG_KHO AS T1 INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T1.MS_PT = T3.MS_PT AND T1.ID_DC = T3.ID
						 INNER JOIN #PhuTung PT ON T1.MS_PT = PT.MS_PT
WHERE CONVERT(DATE,T1.NGAY_CHUYEN) >= @TNgay AND CONVERT(DATE,T1.NGAY_CHUYEN) <= @DNgay 
GROUP BY T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI

--Lấy số lượng di chuyển đến từ đến ngày đến hiện tại DNHT A

SELECT        T1.MS_PT,T1.MS_KHO_1 AS MS_KHO, T1.MS_VI_TRI_1 AS MS_VI_TRI, SUM(T1.SL_CHUYEN) AS SL_CHUYEN_DEN_ADNHT,
	SUM(T1.SL_CHUYEN * T3.DON_GIA * T3.TY_GIA) AS GT_CHUYEN_DEN_ADNHT 
INTO #CHUYEN_DEN_ADNHT
FROM            dbo.DI_CHUYEN_VI_TRI_TRONG_KHO AS T1 INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN						 
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T1.MS_PT = T3.MS_PT AND T1.ID_DC = T3.ID
						 INNER JOIN #PhuTung PT ON T1.MS_PT = PT.MS_PT
WHERE        (CONVERT(DATE,T1.NGAY_CHUYEN) > @DNgay)
GROUP BY T1.MS_PT,T1.MS_KHO_1, T1.MS_VI_TRI_1

--Lấy số lượng di chuyển đến từ ngày đến ngày TNDN B

SELECT        T1.MS_PT,T1.MS_KHO_1 AS MS_KHO, T1.MS_VI_TRI_1 AS MS_VI_TRI, SUM(T1.SL_CHUYEN) AS SL_CHUYEN_DEN_BTNDN,
SUM(T1.SL_CHUYEN * T3.DON_GIA * T3.TY_GIA) AS GT_CHUYEN_DEN_BTNDN
INTO #CHUYEN_DEN_BTNDN
FROM            dbo.DI_CHUYEN_VI_TRI_TRONG_KHO AS T1 INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T1.MS_PT = T3.MS_PT AND T1.ID_DC = T3.ID
						 INNER JOIN #PhuTung PT ON T1.MS_PT = PT.MS_PT
WHERE CONVERT(DATE,T1.NGAY_CHUYEN) >= @TNgay AND CONVERT(DATE,T1.NGAY_CHUYEN) <= @DNgay 
GROUP BY T1.MS_PT,T1.MS_KHO_1, T1.MS_VI_TRI_1

--Tính chênh lệch kiểm kê từ đến ngày đến hiện tại DNHT A

SELECT        T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI, SUM(T1.SL_CHUNG_TU - T1.SL_KK_CT) AS CHENH_LECH_KIEM_KE_ADNHT,
	SUM((T1.SL_CHUNG_TU - T1.SL_KK_CT) * T3.DON_GIA * T3.TY_GIA) AS GT_KIEM_KE_ADNHT
INTO #KIEM_KE_ADNHT
FROM            dbo.KIEM_KE_VAT_TU_CHI_TIET AS T1 INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T1.MS_PT = T3.MS_PT AND T1.ID_KK = T3.ID
						 INNER JOIN #PhuTung PT ON T1.MS_PT = PT.MS_PT
WHERE        CONVERT(DATE,T1.NGAY) > @DNgay
GROUP BY T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI

--Tính chênh lệch kiểm kê từ ngày đến ngày TNDN B

SELECT        T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI, SUM(T1.SL_CHUNG_TU - T1.SL_KK_CT) AS CHENH_LECH_KIEM_KE_BTNDN,
	SUM((T1.SL_CHUNG_TU - T1.SL_KK_CT) * T3.DON_GIA * T3.TY_GIA) AS GT_KIEM_KE_BTNDN
INTO #KIEM_KE_BTNDN
FROM            dbo.KIEM_KE_VAT_TU_CHI_TIET AS T1 INNER JOIN
                         #KHO_TMP AS T2 ON T1.MS_KHO = T2.MS_KHO INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T1.MS_PT = T3.MS_PT AND T1.ID_KK = T3.ID
						 INNER JOIN #PhuTung PT ON T1.MS_PT = PT.MS_PT
WHERE CONVERT(DATE,T1.NGAY) >= @TNgay AND CONVERT(DATE,T1.NGAY) <= @DNgay
GROUP BY T1.MS_PT,T1.MS_KHO, T1.MS_VI_TRI




--Tồn cuối kỳ được tính bằng công thức
--= Tồn hiện tại + Xuất khỏi kho trong giai đoạn A – Nhập vào kho trong giai đoạn A – Chuyển đến trong giai đoạn A + 
	--Chuyển đi trong giai đoạn A + chênh lệch kiểm kê kho trong giai đoạn A

--Tồn đầu kỳ = Tồn cuối kỳ  + Xuất khỏi kho trong giai đoạn B – Nhập vào kho trong giai đoạn B – 
	--		Chuyển đến trong giai đoạn B + Chuyển đi trong giai đoạn B + chênh lệch kiểm kê kho trong giai đoạn B


SELECT        T1.MS_PT, T1.MS_KHO, T1.MS_VI_TRI,
(ISNULL(T1.SL_TON_HT,0) + ISNULL(T2.SL_XUAT_ADNHT,0) - ISNULL(T4.SL_NHAP_ADNHT,0) - ISNULL(T8.SL_CHUYEN_DEN_ADNHT,0) + 
	ISNULL(T6.SL_CHUYEN_DI_ADNHT,0) + ISNULL(T10.CHENH_LECH_KIEM_KE_ADNHT,0)) +
ISNULL(T3.SL_XUAT_BTNDN,0) - ISNULL(T5.SL_NHAP_BTNDN,0) - ISNULL(T9.SL_CHUYEN_DEN_BTNDN,0) + 
	ISNULL(T7.SL_CHUYEN_DI_BTNDN,0) + ISNULL(T11.CHENH_LECH_KIEM_KE_BTNDN,0) AS TON_DAU_KY,

(ISNULL(T1.GT_TON_HT,0) + ISNULL(T2.GT_XUAT_ADNHT,0) - ISNULL(T4.GT_NHAP_ADNHT,0) - ISNULL(T8.GT_CHUYEN_DEN_ADNHT,0) + 
	ISNULL(T6.GT_CHUYEN_DI_ADNHT,0) + ISNULL(T10.CHENH_LECH_KIEM_KE_ADNHT,0)) +
ISNULL(T3.GT_XUAT_BTNDN,0) - ISNULL(T5.GT_NHAP_BTNDN,0) - ISNULL(T9.GT_CHUYEN_DEN_BTNDN,0) + 
	ISNULL(T7.GT_CHUYEN_DI_BTNDN,0) + ISNULL(T11.GT_KIEM_KE_BTNDN,0) AS GT_DAU_KY,

ISNULL(T5.SL_NHAP_BTNDN,0) AS SL_NHAP_TNDN,
ISNULL(T5.GT_NHAP_BTNDN,0) AS GT_NHAP_TNDN,

ISNULL(T3.SL_XUAT_BTNDN,0) AS SL_XUAT_TNDN,
ISNULL(T3.GT_XUAT_BTNDN,0) AS GT_XUAT_TNDN,

ISNULL(T7.SL_CHUYEN_DI_BTNDN,0) AS  SL_CHUYEN_DI_TNDN,
ISNULL(T7.GT_CHUYEN_DI_BTNDN,0) AS  GT_CHUYEN_DI_TNDN,

ISNULL(T9.SL_CHUYEN_DEN_BTNDN,0) AS  SL_CHUYEN_DEN_TNDN,
ISNULL(T9.GT_CHUYEN_DEN_BTNDN,0) AS  GT_CHUYEN_DEN_TNDN,

ISNULL(T11.CHENH_LECH_KIEM_KE_BTNDN,0) AS CHENH_LECH_KIEM_KE_TNDN,
ISNULL(T11.GT_KIEM_KE_BTNDN,0) AS GT_KIEM_KE_TNDN,

ISNULL(T1.SL_TON_HT,0) + ISNULL(T2.SL_XUAT_ADNHT,0) - ISNULL(T4.SL_NHAP_ADNHT,0) - ISNULL(T8.SL_CHUYEN_DEN_ADNHT,0) + 
	ISNULL(T6.SL_CHUYEN_DI_ADNHT,0) + ISNULL(T10.CHENH_LECH_KIEM_KE_ADNHT,0) AS TON_CUOI_KY,

ISNULL(T1.GT_TON_HT,0) + ISNULL(T2.GT_XUAT_ADNHT,0) - ISNULL(T4.GT_NHAP_ADNHT,0) - ISNULL(T8.GT_CHUYEN_DEN_ADNHT,0) + 
	ISNULL(T6.GT_CHUYEN_DI_ADNHT,0) + ISNULL(T10.GT_KIEM_KE_ADNHT,0) AS GT_CUOI_KY

FROM #TON_HT AS T1 LEFT OUTER JOIN
#XUAT_ADNHT AS T2 ON T1.MS_PT = T2.MS_PT AND T1.MS_KHO = T2.MS_KHO AND T1.MS_VI_TRI = T2.MS_VI_TRI LEFT OUTER JOIN
#XUAT_BTNDN AS T3 ON T1.MS_PT = T3.MS_PT AND T1.MS_KHO = T3.MS_KHO AND T1.MS_VI_TRI = T3.MS_VI_TRI LEFT OUTER JOIN
#NHAP_ADNHT AS T4 ON T1.MS_PT = T4.MS_PT AND T1.MS_KHO = T4.MS_KHO AND T1.MS_VI_TRI = T4.MS_VI_TRI LEFT OUTER JOIN
#NHAP_BTNDN AS T5 ON T1.MS_PT = T5.MS_PT AND T1.MS_KHO = T5.MS_KHO AND T1.MS_VI_TRI = T5.MS_VI_TRI LEFT OUTER JOIN
#CHUYEN_DI_ADNHT AS T6 ON T1.MS_PT = T6.MS_PT AND T1.MS_KHO = T6.MS_KHO AND T1.MS_VI_TRI = T6.MS_VI_TRI LEFT OUTER JOIN
#CHUYEN_DI_BTNDN AS T7 ON T1.MS_PT = T7.MS_PT AND T1.MS_KHO = T7.MS_KHO AND T1.MS_VI_TRI = T7.MS_VI_TRI LEFT OUTER JOIN
#CHUYEN_DEN_ADNHT AS T8 ON T1.MS_PT = T8.MS_PT AND T1.MS_KHO = T8.MS_KHO AND T1.MS_VI_TRI = T8.MS_VI_TRI LEFT OUTER JOIN
#CHUYEN_DEN_BTNDN AS T9 ON T1.MS_PT = T9.MS_PT AND T1.MS_KHO = T9.MS_KHO AND T1.MS_VI_TRI = T9.MS_VI_TRI LEFT OUTER JOIN
#KIEM_KE_ADNHT AS T10 ON T1.MS_PT = T10.MS_PT AND T1.MS_KHO = T10.MS_KHO AND T1.MS_VI_TRI = T10.MS_VI_TRI LEFT OUTER JOIN
#KIEM_KE_BTNDN AS T11 ON T1.MS_PT = T11.MS_PT AND T1.MS_KHO = T11.MS_KHO AND T1.MS_VI_TRI = T11.MS_VI_TRI

ORDER BY  T1.MS_PT, T1.MS_KHO, T1.MS_VI_TRI


end