IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spInsertUpdateChuyenMonBacTho')
   exec('CREATE PROCEDURE spInsertUpdateChuyenMonBacTho AS BEGIN SET NOCOUNT ON; END')
GO
-----------------
ALTER PROCEDURE [dbo].[spInsertUpdateChuyenMonBacTho]
	@MS_CONG_NHAN int,
	@MS_CHUYEN_MON int,
	@MS_BAC_THO INT ,
	@NGAY DATE,
	@DEL int


AS
	IF(@DEL = 1)
	BEGIN
		DELETE CONG_NHAN_CHUYEN_MON_BAC_THO WHERE MS_CONG_NHAN = @MS_CONG_NHAN 
				AND MS_CHUYEN_MON = @MS_CHUYEN_MON AND MS_BAC_THO = @MS_BAC_THO		
	END
	ELSE IF(@DEL = 2)
	BEGIN 
		DELETE CONG_NHAN_CHUYEN_MON_BAC_THO WHERE MS_CONG_NHAN = @MS_CONG_NHAN 
				AND MS_CHUYEN_MON = @MS_CHUYEN_MON 
		DELETE CONG_NHAN_CHUYEN_MON WHERE MS_CONG_NHAN = @MS_CONG_NHAN AND MS_CHUYEN_MON = @MS_CHUYEN_MON
	END
	ELSE
	BEGIN
			IF NOT EXISTS (SELECT * FROM CONG_NHAN_CHUYEN_MON WHERE MS_CONG_NHAN = @MS_CONG_NHAN 
							AND MS_CHUYEN_MON = @MS_CHUYEN_MON)
			BEGIN	
					
					INSERT INTO CONG_NHAN_CHUYEN_MON (MS_CONG_NHAN, MS_CHUYEN_MON)VALUES
					(@MS_CONG_NHAN, @MS_CHUYEN_MON)
			END

			IF(@MS_BAC_THO <> -1)
			BEGIN
				IF NOT EXISTS (SELECT * FROM CONG_NHAN_CHUYEN_MON_BAC_THO WHERE MS_CONG_NHAN = @MS_CONG_NHAN 
								AND MS_CHUYEN_MON = @MS_CHUYEN_MON AND MS_BAC_THO = @MS_BAC_THO)
				BEGIN
						INSERT INTO CONG_NHAN_CHUYEN_MON_BAC_THO (MS_CONG_NHAN, MS_CHUYEN_MON, 
						MS_BAC_THO, NGAY)VALUES	(@MS_CONG_NHAN, @MS_CHUYEN_MON, @MS_BAC_THO, @NGAY)
				END
				ELSE
				BEGIN
						UPDATE CONG_NHAN_CHUYEN_MON_BAC_THO SET NGAY = @NGAY 
						WHERE MS_CONG_NHAN = @MS_CONG_NHAN			
						AND	MS_CHUYEN_MON = @MS_CHUYEN_MON AND MS_BAC_THO = @MS_BAC_THO
				END
			END
	END