
ALTER FUNCTION [dbo].[MGetSLanNgungMay] ( 
	@TNgay DATETIME ,
	@DNgay DATETIME ,
	@MS_MAY NVARCHAR(30)
)

RETURNS INT AS BEGIN

declare @TGian INT

SELECT @TGian = ISNULL(COUNT(MS_LAN),0) FROM (SELECT DISTINCT MS_LAN, MS_MAY FROM dbo.THOI_GIAN_NGUNG_MAY AS A 
LEFT JOIN NGUYEN_NHAN_DUNG_MAY B ON B.MS_NGUYEN_NHAN = A.MS_NGUYEN_NHAN
WHERE ISNULL(A.MS_NGUYEN_NHAN, 0) <> 0 AND B.HU_HONG = 1 AND
 (A.NGAY BETWEEN @TNgay AND @DNgay ) AND (MS_MAY = @MS_MAY)) A 


RETURN @TGian
END

