
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetCaTheoGio')
   exec('CREATE PROCEDURE GetCaTheoGio AS BEGIN SET NOCOUNT ON; END')
GO
--EXEC GetCaTheoGio '11/3/2016 23:51:39', 0
ALTER PROC GetCaTheoGio
	@TGio DATETIME,
	@NNGU BIT
AS
BEGIN
		SELECT TOP 1 STT, (CASE @NNGU WHEN 0 THEN CA ELSE CA_ANH END) +
		' (' + CONVERT(NVARCHAR(5),CAST(TU_GIO AS TIME),108) + ' - ' +  CONVERT(NVARCHAR(5),CAST(DEN_GIO AS TIME),108) + ')' AS TEN_CA into #tmp FROM CA WHERE CONVERT(DATETIME,CAST(@TGio AS TIME) , 108)< CONVERT(DATETIME, CAST(DEN_GIO AS TIME), 108)  
		ORDER BY DEN_GIO

		declare @count as int = 0

		SELECT @COUNT = count(*) from #tmp 
		if(@count = 0)
		begin
				SELECT TOP 1  STT, (CASE @NNGU WHEN 0 THEN CA ELSE CA_ANH END) + ' (' + CONVERT(NVARCHAR(5),CAST(TU_GIO AS TIME),108) + ' - ' +  CONVERT(NVARCHAR(5),CAST(DEN_GIO AS TIME),108) + ')'
					AS TEN_CA FROM CA
					WHERE  DATEDIFF(MINUTE, DATEADD(DAY, DATEDIFF(DAY, 0, @TGio), 0), @TGio)  < DEN_PHUT
						ORDER BY TU_GIO					
		end
		ELSE
			SELECT * FROM #tmp

END
