

--exec SP_GET_PT_XUAT_PTSD  N'WO-201703000001'


ALTER procedure [dbo].[SP_GET_PT_XUAT_PTSD] 
 @MS_PHIEU_BAO_TRI NVARCHAR (20)
AS
BEGIN


SELECT        T1.MS_PHIEU_BAO_TRI, T3.MS_DH_NHAP_PT, T1.MS_DH_XUAT_PT, T3.ID_XUAT, T3.MS_PT, SUM(T3.SL_VT) AS SL_VT INTO #TMP_XUAT
FROM            dbo.IC_DON_HANG_XUAT AS T1 INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU AS T2 ON T1.MS_DH_XUAT_PT = T2.MS_DH_XUAT_PT INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS T3 ON T2.MS_DH_XUAT_PT = T3.MS_DH_XUAT_PT AND T2.MS_PT = T3.MS_PT
GROUP BY T1.MS_PHIEU_BAO_TRI, T1.MS_DH_XUAT_PT, T3.MS_PT, T3.MS_DH_NHAP_PT, T3.ID_XUAT
HAVING        (T1.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI) 


SELECT        MS_PHIEU_BAO_TRI, MS_DH_NHAP_PT, MS_DH_XUAT_PT, ID, MS_PT, SUM(SL_TT) AS SL_TT INTO #TMP_PBTKHO
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO AS T2
WHERE        (MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI) 
GROUP BY MS_PHIEU_BAO_TRI, MS_PT, MS_DH_XUAT_PT, MS_DH_NHAP_PT, ID

SELECT        T3.MS_PHIEU_BAO_TRI,  T3.MS_DH_XUAT_PT, T2.ID_GOC, T2.MS_DH_NHAP_PT_GOC, T4.MS_PT AS MS_PT_GOC, SUM(T4.SL_VT) AS SL_TRA  INTO #TMP_TRA
FROM            dbo.IC_DON_HANG_NHAP AS T1 INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T2 ON T1.MS_DH_NHAP_PT = T2.MS_DH_NHAP_PT INNER JOIN
                         dbo.IC_DON_HANG_XUAT AS T3 ON T1.MS_DHX = T3.MS_DH_XUAT_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET AS T4 ON T2.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT AND T2.MS_PT = T4.MS_PT AND T2.ID = T4.ID 
WHERE        (T1.MS_DANG_NHAP = 6) AND (T3.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI)
GROUP BY T3.MS_PHIEU_BAO_TRI, T3.MS_DH_XUAT_PT,T2.ID_GOC, T2.MS_DH_NHAP_PT_GOC,T4.MS_PT 


--SELECT DISTINCT * FROM (
SELECT DISTINCT B.MS_PT AS PT_GOC, D.TEN_PT, B.MS_PT, D.TEN_PT AS TEN_PT_SD, B.MS_DH_XUAT_PT, B.MS_DH_NHAP_PT, CONVERT(NVARCHAR(50), '') AS MS_DH_NHAP_TRA, SUM(ISNULL(A_1.SL_TT, 0)) AS SL_TT, 
                      SUM(ISNULL(B.SL_VT, 0)) - SUM(ISNULL(C.SL_TRA, 0)) AS SL_VT,  ISNULL(B.SL_VT, 0) AS SL_VT_THUC_XUAT, ISNULL(C.SL_TRA, 0) SL_TRA
into #tmp FROM         #TMP_XUAT AS B INNER JOIN dbo.LOAI_VT AS E INNER JOIN
                      dbo.IC_PHU_TUNG AS D ON E.MS_LOAI_VT = D.MS_LOAI_VT ON B.MS_PT = D.MS_PT LEFT OUTER JOIN
                         #TMP_PBTKHO AS A_1 ON B.MS_PHIEU_BAO_TRI = A_1.MS_PHIEU_BAO_TRI AND B.MS_PT = A_1.MS_PT AND 
                      B.ID_XUAT = A_1.ID AND B.MS_DH_XUAT_PT = A_1.MS_DH_XUAT_PT AND B.MS_DH_NHAP_PT = A_1.MS_DH_NHAP_PT LEFT OUTER JOIN
                          #TMP_TRA AS C  ON B.MS_PHIEU_BAO_TRI = C.MS_PHIEU_BAO_TRI AND B.MS_PT = C.MS_PT_GOC AND B.ID_XUAT = C.ID_GOC
        AND B.MS_DH_XUAT_PT = C.MS_DH_XUAT_PT AND B.MS_DH_NHAP_PT = C.MS_DH_NHAP_PT_GOC 
   
WHERE     (ISNULL(E.VAT_TU, 0) = 0) AND (B.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI)
GROUP BY D.TEN_PT, B.MS_PT, B.MS_DH_XUAT_PT, B.MS_DH_NHAP_PT, SL_TRA, B.SL_VT, C.MS_DH_NHAP_PT_GOC
        
--) X WHERE   X.SL_VT_XUAT <>   X.SL_TT
ORDER BY MS_PT, TEN_PT   





UPDATE #tmp
SET MS_DH_NHAP_TRA = T.MS_DH_NHAP_PT 
FROM #tmp t3 
 INNER JOIN IC_DON_HANG_NHAP T on t3.MS_DH_XUAT_PT = t.MS_DHX 
INNER JOIN IC_DON_HANG_NHAP_VAT_TU T1 ON T1.MS_DH_NHAP_PT = T.MS_DH_NHAP_PT 
INNER JOIN IC_DON_HANG_NHAP_VAT_TU_CHI_TIET T2 ON T2.MS_DH_NHAP_PT = T1.MS_DH_NHAP_PT AND T1.MS_PT = T2.MS_PT AND T1.ID = T2.ID 
where  t2.MS_PT = t3.MS_PT 
and t3.SL_TRA <> 0

SELECT  * , '' AS ID_XUAT, '' AS ID FROM #tmp 
 


END