--exec GET_TONG_CHI_PHI_VT 'WO-201704000005'
ALTER proc [dbo].[GET_TONG_CHI_PHI_VT]
	@MS_PBT NVARCHAR(50)
AS

SELECT        T3.MS_PHIEU_BAO_TRI,  T3.MS_DH_XUAT_PT, T2.ID_GOC, T2.MS_DH_NHAP_PT_GOC, T4.MS_PT AS MS_PT_GOC, SUM(T4.SL_VT) AS SL_TRA INTO #TMP_TRA
FROM            dbo.IC_DON_HANG_NHAP AS T1 INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T2 ON T1.MS_DH_NHAP_PT = T2.MS_DH_NHAP_PT INNER JOIN
                         dbo.IC_DON_HANG_XUAT AS T3 ON T1.MS_DHX = T3.MS_DH_XUAT_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET AS T4 ON T2.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT AND T2.MS_PT = T4.MS_PT AND T2.ID = T4.ID 
WHERE        (T1.MS_DANG_NHAP = 6) AND (T3.MS_PHIEU_BAO_TRI = @MS_PBT)
GROUP BY T3.MS_PHIEU_BAO_TRI, T3.MS_DH_XUAT_PT,T2.ID_GOC, T2.MS_DH_NHAP_PT_GOC,T4.MS_PT 


SELECT  SUM((ISNULL(dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.SL_VT, 0) - ISNULL(T.SL_TRA,0)) * ISNULL(dbo.IC_DON_HANG_NHAP_VAT_TU.DON_GIA, 0) 
                      ) AS CHI_PHI_VT, 
                      
                      SUM((ISNULL(dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.SL_VT, 0) - ISNULL(T.SL_TRA,0))
                      * ISNULL(dbo.IC_DON_HANG_NHAP_VAT_TU.DON_GIA, 0) * dbo.IC_DON_HANG_NHAP_VAT_TU.TY_GIA_USD / dbo.IC_DON_HANG_NHAP_VAT_TU.TY_GIA) AS CHI_PHI_VT_USD
                      
FROM         dbo.IC_DON_HANG_NHAP_VAT_TU INNER JOIN
                      dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET ON 
                      dbo.IC_DON_HANG_NHAP_VAT_TU.MS_DH_NHAP_PT = dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.MS_DH_NHAP_PT AND 
                      dbo.IC_DON_HANG_NHAP_VAT_TU.MS_PT = dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.MS_PT INNER JOIN
                      dbo.IC_DON_HANG_XUAT ON 
                      dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.MS_DH_XUAT_PT = dbo.IC_DON_HANG_XUAT.MS_DH_XUAT_PT INNER JOIN
                      dbo.IC_PHU_TUNG ON dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.MS_PT = dbo.IC_PHU_TUNG.MS_PT INNER JOIN
                      dbo.LOAI_VT ON dbo.IC_PHU_TUNG.MS_LOAI_VT = dbo.LOAI_VT.MS_LOAI_VT
                      LEFT JOIN #TMP_TRA T ON IC_DON_HANG_NHAP_VAT_TU.MS_DH_NHAP_PT = T.MS_DH_NHAP_PT_GOC
                      AND IC_DON_HANG_XUAT_VAT_TU_CHI_TIET.MS_PT = T.MS_PT_GOC AND IC_DON_HANG_XUAT.MS_DH_XUAT_PT = T.MS_DH_XUAT_PT
                      AND dbo.IC_DON_HANG_XUAT.MS_PHIEU_BAO_TRI = T.MS_PHIEU_BAO_TRI
WHERE     (dbo.IC_DON_HANG_XUAT.MS_PHIEU_BAO_TRI = @MS_PBT) AND (dbo.LOAI_VT.VAT_TU = 1)