--exec sp_getKHTT 3578,	'10-05-CVM-009-00',	3903
ALTER PROC [dbo].[sp_getKHTT]
	@STT INT,
	@MS_MAY NVARCHAR(50),
	@STT_VAN_DE INT
AS
BEGIN
	declare @NGAY_DSX datetime
	set @NGAY_DSX =(SELECT CONVERT(DATETIME,CONVERT(NVARCHAR(10),YEU_CAU_NSD_CHI_TIET.THOI_GIAN_DSX,101)) 
			FROM YEU_CAU_NSD_CHI_TIET where STT=@STT AND MS_MAY=@MS_MAY AND STT_VAN_DE =@STT_VAN_DE )
				
	
	SELECT DISTINCT A.TEN_HANG_MUC AS TEN,CONVERT(NVARCHAR,A.HANG_MUC_ID) AS MA 
		FROM dbo.KE_HOACH_TONG_THE AS A 
		WHERE A.MS_MAY = @MS_MAY 		--AND NGAY_DK_HT >=  @NGAY_DSX 
		AND A.HANG_MUC_ID NOT IN (SELECT DISTINCT HANG_MUC_ID FROM KE_HOACH_TONG_CONG_VIEC WHERE 
		(ISNULL(MS_PHIEU_BAO_TRI,'') <> ''  AND ISNULL(KHONG_GQ,0) = 0)) AND MS_MAY = @MS_MAY
	union select '...New' , '-1'
	union select '','' 
	ORDER BY TEN
	
END	
	