alter procedure [dbo].[GetMS_MAY_HIEU_CHUAN_DHD] 
	@USERLOGED NVARCHAR(50)
AS

	DECLARE @NgayHT AS DATETIME
	SET @NgayHT = GETDATE()

	SELECT A.* INTO #MAY FROM dbo.MGetMayUserNgay(@NgayHT,@USERLOGED,'-1',-1,-1,'-1','-1','-1',0) A 
	
	
SELECT  DISTINCT  HIEU_CHUAN_DHD.MS_MAY , HIEU_CHUAN_DHD.MS_MAY AS TEN_MAY FROM HIEU_CHUAN_DHD INNER JOIN #MAY ON #MAY.MS_MAY=HIEU_CHUAN_DHD.MS_MAY