--Printlylichcongnhan 1486, NULL
ALTER procedure [dbo].[Printlylichcongnhan]
@MS_CONG_NHAN nvarchar(100),
@HINH_MAY image
AS

DECLARE @DDHINH NVARCHAR(500)
select TOP 1 TEN_CHUC_VU, MS_CONG_NHAN INTO #CV  from chuc_vu     where  ms_cong_nhan=@MS_CONG_NHAN   order by ngay desc

select  TOP 1 LUONG_CO_BAN , MS_CONG_NHAN INTO #LCB    from    LUONG_CO_BAN  where ms_cong_nhan =@MS_CONG_NHAN order by ngay_ky desc 


SELECT  TOP 1   CN.MS_CONG_NHAN,CN.HO,CN.TEN,CN.NGAY_SINH,CN.NOI_SINH,CN.PHAI,CN.DIA_CHI_THUONG_TRU, 
	CN.SO_CMND,CN.NGAY_CAP,CN.NOI_CAP,DON_VI.MS_DON_VI,TO_PHONG_BAN.MS_TO AS MS_PHONG_BAN, CN.MS_TO ,CN.NGAY_VAO_LAM, 
	CN.BO_VIEC,CN.NGAY_NGHI_VIEC,CN.LY_DO_NGHI,TRINH_DO_VAN_HOA.TEN_GOI,CN.NGOAI_NGU, 
	CN.HINH_CN,CN.GHI_CHU,CN.MS_THE_CC,CN.SO_DT_NHA_RIENG,CN.SO_DTDD,CN.TEN_NGUOI_THAN,CN.QUAN_HE,CN.BANG_CAP,TO_PHONG_BAN.ten_to as ban,
[TO].ten_to ,DON_VI.ten_don_vi  ,cast('anh' as image)as anh ,cast('ip' as nvarchar(100)) as ip  ,dbo.Gettenchuyenmon( CN.MS_CONG_NHAN) as chuyenmon ,
 dbo.Getnhantenbactho(CN.MS_CONG_NHAN) as bactho,dbo.Getainan(CN.MS_CONG_NHAN) as tainan   ,
 T1.TEN_CHUC_VU, T2.LUONG_CO_BAN,

 CONVERT(IMAGE,@HINH_MAY) AS HINH_MAY
 
  
FROM CONG_NHAN  CN INNER JOIN [TO] ON CN.MS_TO = [TO].MS_TO1 
	LEFT JOIN TRINH_DO_VAN_HOA ON CN.MS_TRINH_DO = TRINH_DO_VAN_HOA.MS_TRINH_DO 
	INNER JOIN TO_PHONG_BAN ON [TO].MS_TO=TO_PHONG_BAN.MS_TO
	INNER JOIN DON_VI ON TO_PHONG_BAN.MS_DON_VI = DON_VI.MS_DON_VI 
	LEFT JOIN #CV T1 ON T1.MS_CONG_NHAN = CN.MS_CONG_NHAN 
	LEFT JOIN #LCB T2 ON T2.MS_CONG_NHAN = CN.MS_CONG_NHAN 

WHERE    CN.MS_CONG_NHAN =@MS_CONG_NHAN  and   CN.MS_TO IN (SELECT DISTINCT [TO].MS_TO1 FROM [TO] 
	LEFT JOIN TO_PHONG_BAN ON [TO].MS_TO = TO_PHONG_BAN.MS_TO
	LEFT JOIN DON_VI ON TO_PHONG_BAN.MS_DON_VI = DON_VI.MS_DON_VI) 
return
