
ALTER proc [dbo].[DeleteTO_PHONG_BAN]
	@MS_TO INT
AS


DELETE FROM NHOM_TO_PHONG_BAN WHERE MS_TO=@MS_TO
DELETE FROM TO_PHONG_BAN
WHERE MS_TO=@MS_TO

DBCC CHECKIDENT (TO_PHONG_BAN,RESEED,0)
DBCC CHECKIDENT (TO_PHONG_BAN,RESEED)
