IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_IC_KHO')
   exec('CREATE PROCEDURE SP_IC_KHO AS BEGIN SET NOCOUNT ON; END')
GO




ALTER PROC SP_IC_KHO
(
	@ACTION NVARCHAR(200)=NULL,
	@MS_KHO int=NULL,
	@TBVTKHO TVT_VI_TRI_KHO READONLY,
	@TBKHO TVT_IC_KHO READONLY
)
AS
BEGIN
	IF @ACTION ='GET_DS_KHO'
	BEGIN
		SELECT MS_KHO, TEN_KHO, DIA_CHI, SO_DO, ISIT, MS_CONG_NHAN, NGAY_LOCK, GIO_LOCK, UNAME, SN_CANH_BAO, 
			KHO_DD  , CONVERT(NVARCHAR(10),MS_KHO_CHINH) AS MS_KHO_CHINH ,[MS_DON_VI] ,CONVERT(BIT,0) IS_UPDATE
		FROM IC_KHO ORDER BY TEN_KHO
	END
	IF @ACTION ='GET_DS_VI_TRI_KHO'
	BEGIN
		SELECT T1.MS_VI_TRI, T1.TEN_VI_TRI,T1.GHI_CHU ,T1.MS_KHO,T2.TEN_KHO
		,CONVERT(BIT,0) IS_UPDATE
		FROM VI_TRI_KHO T1 INNER JOIN IC_KHO T2 ON T1.MS_KHO=T2.MS_KHO
		WHERE T1.MS_KHO=@MS_KHO ORDER BY T1.TEN_VI_TRI
	END
	IF @ACTION ='SAVE'
	BEGIN
		UPDATE T1
		SET T1.[TEN_KHO] = T2.[TEN_KHO]
			  ,T1.[DIA_CHI] = T2.[DIA_CHI]
			  ,T1.[SO_DO] = T2.[SO_DO]
			  ,T1.[ISIT] = T2.[ISIT]
			  ,T1.[MS_CONG_NHAN] = T2.[MS_CONG_NHAN]
			  ,T1.[NGAY_LOCK]= T2.NGAY_LOCK
			  ,T1.[GIO_LOCK] = T2.GIO_LOCK
			  ,T1.[UNAME] = T2.UNAME
			  ,T1.[SN_CANH_BAO] = T2.SN_CANH_BAO
			  ,T1.[KHO_DD] = T2.KHO_DD
			  ,T1.[MS_KHO_CHINH] = T2.MS_KHO_CHINH
			  ,T1.[MS_DON_VI] = T2.MS_DON_VI
		FROM  [dbo].[IC_KHO] T1 INNER JOIN @TBKHO T2 ON  T1.MS_KHO=T2.MS_KHO
		
		INSERT INTO [dbo].[IC_KHO]
           ([TEN_KHO]
           ,[DIA_CHI]
           ,[SO_DO]
           ,[ISIT]
           ,[MS_CONG_NHAN]
           ,[NGAY_LOCK]
           ,[GIO_LOCK]
           ,[UNAME]
           ,[SN_CANH_BAO]
           ,[KHO_DD]
           ,[MS_KHO_CHINH]
           ,[MS_DON_VI]
           
         )
         
         SELECT [TEN_KHO]
			   ,[DIA_CHI]
			   ,[SO_DO]
			   ,[ISIT]
			   ,[MS_CONG_NHAN]
			   ,[NGAY_LOCK]
			   ,[GIO_LOCK]
			   ,[UNAME]
			   ,[SN_CANH_BAO]
			   ,[KHO_DD]
			   ,[MS_KHO_CHINH]
			   ,[MS_DON_VI]
         FROM @TBKHO WHERE MS_KHO NOT IN(SELECT DISTINCT MS_KHO FROM [dbo].[IC_KHO])
          
      
         
         SELECT T2.[MS_VI_TRI] ,T2.[TEN_VI_TRI] ,T2.[GHI_CHU],T1.[MS_KHO],T1.[TEN_KHO] INTO ##TVT_TBVTKHO
         FROM [IC_KHO] T1 INNER JOIN @TBVTKHO T2 ON T1.TEN_KHO=T2.TEN_KHO
         
         UPDATE T1
		 SET T1.TEN_VI_TRI = T2.TEN_VI_TRI,
			 T1.GHI_CHU = T2.GHI_CHU
		 FROM  [dbo].[VI_TRI_KHO] T1 INNER JOIN ##TVT_TBVTKHO T2 ON  T1.MS_KHO=T2.MS_KHO AND T1.MS_VI_TRI=T2.MS_VI_TRI
		 
		 INSERT INTO [dbo].[VI_TRI_KHO]
         (
			[MS_KHO]
           ,[TEN_VI_TRI]
           ,[GHI_CHU]
         )
         SELECT [MS_KHO]           ,[TEN_VI_TRI]           ,[GHI_CHU] 
         FROM ##TVT_TBVTKHO T1 
         WHERE T1.MS_VI_TRI NOT IN (SELECT DISTINCT T2.MS_VI_TRI FROM [dbo].[VI_TRI_KHO] T2 WHERE T2.MS_KHO=T1.MS_KHO)
	END
END
