

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetThoiGianChayMayChiTiet')
   exec('CREATE PROCEDURE spGetThoiGianChayMayChiTiet AS BEGIN SET NOCOUNT ON; END')
GO
--spGetThoiGianChayMayChiTiet 'aic-1504', '07/17/2016', '07/18/2017'
ALTER PROCEDURE spGetThoiGianChayMayChiTiet
	@MS_MAY NVARCHAR(50),
	@TNGAY DATETIME,
	@DNGAY DATETIME
AS
BEGIN

	SELECT MS_MAY, NGAY, CHI_SO_DONG_HO, MS_PBT, SO_MOVEMENT,SO_GIO_LUY_KE FROM THOI_GIAN_CHAY_MAY WHERE MS_MAY = @MS_MAY AND NGAY  BETWEEN  @TNGAY AND @DNGAY

END