
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetThoiGianChayMayTheoRange')
   exec('CREATE PROCEDURE spGetThoiGianChayMayTheoRange AS BEGIN SET NOCOUNT ON; END')
GO
--spGetThoiGianChayMayTheoRange 'AIC-1504', '07/17/2016', '12/17/2022', N'5|9|10', '-1'
--spGetThoiGianChayMayTheoRange 'AIC-1504', '07/17/2016', '07/18/2017', N'-1', '-1'
ALTER PROCEDURE spGetThoiGianChayMayTheoRange
	@MS_MAY NVARCHAR(50),
	@TNGAY DATETIME,
	@DNGAY DATETIME, 
	@VALUE NVARCHAR(20) = '-1',
	@LISTMAY NVARCHAR(MAX) = '-1'
AS
BEGIN

DECLARE @NUMBER INT = 0

IF 	@VALUE = '-1'
BEGIN
	SELECT DISTINCT @MS_MAY  AS MS_MAY, DATEADD(DAY,NUMBER,@TNGAY) AS NGAY, T1.MS_PBT, ISNULL(T1.CHI_SO_DONG_HO,0) CHI_SO_DONG_HO,
	ISNULL(T1.SO_GIO_LUY_KE,0) SO_GIO_LUY_KE, T1.SO_MOVEMENT,CONVERT(BIT, CASE ISNULL(T1.CHI_SO_DONG_HO,0) WHEN 0 THEN 0 ELSE 1 END) IS_UPDATE FROM MASTER..spt_values T 
	LEFT JOIN THOI_GIAN_CHAY_MAY T1 ON T1.NGAY = DATEADD(DAY,number,@TNGAY) AND T1.MS_MAY = @MS_MAY
	WHERE NUMBER BETWEEN 0 AND DATEDIFF(DAY, @TNGAY, @DNGAY)
END
ELSE
BEGIN
	IF @LISTMAY = '-1'
	BEGIN
		SELECT DISTINCT @MS_MAY AS MS_MAY, DATEADD(DAY,NUMBER,@TNGAY) AS NGAY, T1.MS_PBT,  	
		CASE DATEPART(DW, DATEADD(DAY,number,@TNGAY))
		WHEN 7 THEN (SELECT Item FROM UDF_ConvertListItem2Table(@VALUE, N'|') WHERE Id = 2) 
		WHEN 1 THEN (SELECT Item FROM UDF_ConvertListItem2Table(@VALUE, N'|') WHERE Id = 3) 
		ELSE (SELECT Item FROM UDF_ConvertListItem2Table(@VALUE, N'|') WHERE Id = 1) END	
		CHI_SO_DONG_HO , ISNULL(T1.SO_GIO_LUY_KE,0) SO_GIO_LUY_KE, T1.SO_MOVEMENT
		,CONVERT(BIT, CASE ISNULL(T1.CHI_SO_DONG_HO,0) WHEN 0 THEN 0 ELSE 1 END) IS_UPDATE 
		 FROM MASTER..spt_values T 
		LEFT JOIN THOI_GIAN_CHAY_MAY T1 ON T1.NGAY = DATEADD(DAY,number,@TNGAY) AND T1.MS_MAY = @MS_MAY
		WHERE NUMBER BETWEEN 0 AND DATEDIFF(DAY, @TNGAY, @DNGAY)
	END
	ELSE
	BEGIN
		SELECT DISTINCT T.MS_MAY, DATEADD(DAY,NUMBER,@TNGAY) AS NGAY, T2.MS_PBT,  	
		CASE DATEPART(DW, DATEADD(DAY,number,@TNGAY))
		WHEN 7 THEN (SELECT Item FROM UDF_ConvertListItem2Table(@VALUE, N'|') WHERE Id = 2) 
		WHEN 1 THEN (SELECT Item FROM UDF_ConvertListItem2Table(@VALUE, N'|') WHERE Id = 3) 
		ELSE (SELECT Item FROM UDF_ConvertListItem2Table(@VALUE, N'|') WHERE Id = 1) END	
		CHI_SO_DONG_HO , ISNULL(T2.SO_GIO_LUY_KE,0) SO_GIO_LUY_KE, T2.SO_MOVEMENT,
		CONVERT(BIT, CASE ISNULL(T2.CHI_SO_DONG_HO,0) WHEN 0 THEN 0 ELSE 1 END) IS_UPDATE 
		 FROM 
		(SELECT Item AS MS_MAY FROM UDF_ConvertListItem2Table(@LISTMAY, N'|')) T, MASTER..spt_values T1 
		LEFT JOIN THOI_GIAN_CHAY_MAY T2 ON T2.NGAY = DATEADD(DAY,number,@TNGAY) AND T2.MS_MAY = @MS_MAY
		WHERE T1.NUMBER BETWEEN 0 AND DATEDIFF(DAY, @TNGAY, @DNGAY)
	END
	
		

END
END

