
--exec get_rptMAY_THONG_SO_CHINH_MAY 'a'
ALTER procedure [dbo].[get_rptMAY_THONG_SO_CHINH_MAY] 
 @MS_MAY NVARCHAR(30)
AS

IF EXISTS(SELECT * FROM THONG_SO_CHINH_MAY WHERE MS_MAY = @MS_MAY) 
BEGIN
SELECT ROW_NUMBER() OVER(ORDER BY TEN_THONG_SO_MAY DESC) as STT,
TEN_THONG_SO_MAY,THONG_SO_CHINH_MAY.GIA_TRI,TEN_DV_DO ,THONG_SO_CHINH_MAY.GHI_CHU 
 FROM THONG_SO_CHINH_MAY INNER JOIN THONG_SO_MAY ON THONG_SO_CHINH_MAY.MS_THONG_SO_MAY=THONG_SO_MAY.MS_THONG_SO_MAY INNER JOIN DON_VI_DO ON THONG_SO_MAY.MS_DV_DO=DON_VI_DO.MS_DV_DO  WHERE MS_MAY= @MS_MAY
END 
SELECT ROW_NUMBER() OVER(ORDER BY TEN_THONG_SO_MAY DESC) as STT,
TEN_THONG_SO_MAY,THONG_SO_CHINH_MAY.GIA_TRI,TEN_DV_DO ,THONG_SO_CHINH_MAY.GHI_CHU 
 FROM THONG_SO_CHINH_MAY INNER JOIN THONG_SO_MAY ON THONG_SO_CHINH_MAY.MS_THONG_SO_MAY=THONG_SO_MAY.MS_THONG_SO_MAY INNER JOIN DON_VI_DO ON THONG_SO_MAY.MS_DV_DO=DON_VI_DO.MS_DV_DO  WHERE MS_MAY= @MS_MAY
UNION
SELECT NULL, NULL, NULL, NULL, NULL
