

	--EXEC SP_Y_GET_DON_HANG_NHAP_VAT_TU_CHI_TIET
alter procedure [dbo].[SP_Y_GET_DON_HANG_NHAP_VAT_TU_CHI_TIET]
	@MsDHN NVARCHAR(14)
as
begin

      select MS_DH_NHAP_PT,MS_PT,T.MS_VI_TRI, T1.TEN_VI_TRI, SL_VT, ID
      from IC_DON_HANG_NHAP_VAT_TU_CHI_TIET T
	  INNER JOIN VI_TRI_KHO T1 ON T.MS_VI_TRI = T1.MS_VI_TRI 
	        WHERE MS_DH_NHAP_PT = @MsDHN 

      ORDER BY MS_VI_TRI

    
end
