IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetHE_THONGs')
   exec('CREATE PROCEDURE GetHE_THONGs AS BEGIN SET NOCOUNT ON; END')
GO
-- EXEC GetHE_THONGs 'ADMIN'

ALTER PROC [dbo].[GetHE_THONGs]
	@UserName NVARCHAR(50)
AS
	SELECT T1.MS_HE_THONG INTO #HTHONG
	FROM NHOM_HE_THONG T1 INNER JOIN USERS T2 ON T1.GROUP_ID = T2.GROUP_ID 
	WHERE T2.USERNAME = @UserName 

	DECLARE @TenDC NVARCHAR(250)
	DECLARE @TenDCAnh NVARCHAR(250)
	DECLARE @TenDCHoa NVARCHAR(250)

	SELECT @TenDC = VIETNAM, @TenDCAnh = ENGLISH,@TenDCHoa = CHINESE FROM LANGUAGES WHERE FORM = N'ctrlNgungMay' AND KEYWORD = N'TEN_HE_THONG'

	SELECT * 
	FROM
	(
		SELECT T1.MS_HE_THONG,T1.MA_HE_THONG,ISNULL(NO_LINE,0) AS NO_LINE,STT,TEN_HE_THONG, TEN_HE_THONG_ANH, TEN_HE_THONG_HOA,TAI_LIEU, GHI_CHU, ISNULL(MS_CHA,-1) AS MS_CHA
		FROM dbo.HE_THONG T1 --INNER JOIN #HTHONG T2 ON T1.MS_HE_THONG = T2.MS_HE_THONG	
		UNION
		SELECT -1 AS MS_HE_THONG,'-1' AS MA_HE_THONG, 0 AS NO_LINE,-1 AS STT , @TenDC AS  TEN_HE_THONG, @TenDCAnh AS TEN_HE_THONG_ANH, @TenDCHoa AS TEN_HE_THONG_HOA,NULL AS TAI_LIEU, NULL AS GHI_CHU, NULL AS MS_CHA
	) A
	ORDER BY ISNULL(STT,9999),TEN_HE_THONG


	
	