
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'AddEditHE_THONG')
   exec('CREATE PROCEDURE AddEditHE_THONG AS BEGIN SET NOCOUNT ON; END')
GO




--EXEC AddEditHE_THONG -1,'ddd',NULL,'TRUE','DDDD',NULL,NULL,16,NULL,-1,'ADMIN'
ALTER proc AddEditHE_THONG
	@MS_HE_THONG int,
	@TEN_HE_THONG nvarchar(250) ,
	@GHI_CHU nvarchar(255) ,
	@NO_LINE bit ,
	@MA_HE_THONG nvarchar(50) ,
	@TEN_HE_THONG_ANH nvarchar(250) ,
	@TEN_HE_THONG_HOA nvarchar(250) ,
	@MS_CHA int ,
	@TAI_LIEU nvarchar(250) ,
	@STT int ,
	@UserName nvarchar(250)
AS
DECLARE @MsHT INT

IF @STT = -1 
	SET @STT = NULL

IF @MS_CHA = -1
	SET @MS_CHA = NULL

IF @TEN_HE_THONG_ANH = ''
	SET @TEN_HE_THONG_ANH = NULL

IF @TEN_HE_THONG_HOA = ''
	SET @TEN_HE_THONG_HOA = NULL


IF(@MS_HE_THONG = -1)
BEGIN
	INSERT INTO [HE_THONG]([TEN_HE_THONG],[GHI_CHU],[NO_LINE],[MA_HE_THONG],[TEN_HE_THONG_ANH],[TEN_HE_THONG_HOA],[MS_CHA],[TAI_LIEU],[STT])
	VALUES (@TEN_HE_THONG,@GHI_CHU,@NO_LINE,@MA_HE_THONG,@TEN_HE_THONG_ANH,@TEN_HE_THONG_HOA,@MS_CHA,@TAI_LIEU,@STT)
	SET @MsHT = SCOPE_IDENTITY()

	INSERT INTO NHOM_HE_THONG (GROUP_ID,MS_HE_THONG)
	SELECT DISTINCT GROUP_ID,MS_HE_THONG FROM(
	SELECT GROUP_ID, @MsHT AS MS_HE_THONG FROM USERS WHERE USERNAME = @UserName
	UNION SELECT GROUP_ID, @MsHT AS MS_HE_THONG FROM USERS WHERE USERNAME = 'ADMIN') T1
	WHERE NOT EXISTS (SELECT * FROM NHOM_HE_THONG T2 WHERE T1.MS_HE_THONG = T2.MS_HE_THONG AND T1.GROUP_ID = T2.GROUP_ID)

END
ELSE
BEGIN
	UPDATE [HE_THONG] SET [TEN_HE_THONG] = @TEN_HE_THONG,
				[GHI_CHU] = @GHI_CHU,
				[NO_LINE] = @NO_LINE,
				[MA_HE_THONG] = @MA_HE_THONG,
				[TEN_HE_THONG_ANH] = @TEN_HE_THONG_ANH,
				[TEN_HE_THONG_HOA] = @TEN_HE_THONG_HOA,
				[MS_CHA] = @MS_CHA,
				[TAI_LIEU] = @TAI_LIEU,
				[STT] = @STT
	WHERE MS_HE_THONG = @MS_HE_THONG
	SET @MsHT = @MS_HE_THONG
END

select @MsHT