
-- SELECT * INTO AAA_HT FROM HE_THONG   
--	EXEC spBCBaoTriThang 'ADMIN','-1','AAA_HT','11/01/2017','11/30/2017',0

ALTER proc [dbo].[spBCBaoTriThang]
	@UserName NVARCHAR(50),
	@MsNX NVARCHAR(250),
	@HThong NVARCHAR(250),
	@TuNgay DATETIME,
	@DenNgay DATETIME,
	@NNgu int
AS



if exists (select * from dbo.sysobjects  where [NAME]='BTDK_TMP' AND [XTYPE] = 'U' )
	drop table [dbo].[BTDK_TMP]

CREATE TABLE BTDK_TMP 
(
	MS_MAY NVARCHAR(30),
	MS_LOAI_BT NVARCHAR(30),
	NGAY_CUOI DATETIME,
	NGAYKE DATETIME,
	CHU_KY INT,
	MS_DV_TG INT,
	MS_HE_THONG INT  
) 

CREATE TABLE  #HTHONG_TMP  (
	[MS_HE_THONG] INT NULL,
	[TEN_HE_THONG] [nvarchar] (100) NOT NULL)

	--CREATE TABLE #MAY_TMP ([MS_MAY] [nvarchar](30)  NULL)  

	
DECLARE @sSql NVARCHAR(4000)
SET @sSql = 'INSERT INTO #HTHONG_TMP ([MS_HE_THONG],[TEN_HE_THONG] ) SELECT [MS_HE_THONG],[TEN_HE_THONG] FROM ' + @HThong
exec	 (@sSql)

SELECT DISTINCT MS_MAY, A.TEN_HE_THONG, A.MS_HE_THONG
INTO #MAY_USER 
FROM dbo.MGetMayUserNgay(@DenNgay,@UserName,@MsNX,-1,-1,'-1','-1','-1',0) A INNER JOIN #HTHONG_TMP B ON A.MS_HE_THONG = B.MS_HE_THONG

--@NgayBD DATETIME,
--	@NgayKT DATETIME,
--	@UserName NVARCHAR(255),
--	@MsNXuong nvarchar(50),
--	@NHeThong int,
--	@LoaiMay NVARCHAR (20),
--	@NhomMay NVARCHAR (20),
--	@MLoai bit

SELECT DISTINCT A.MS_MAY, A.MS_LOAI_BT, A.NGAY_HC_CUOI  , A.CHU_KY, A.MS_DV_TG, A.NGAY_KE AS NGAY_BTKT INTO #HIEU_CHUAN_KE
FROM         dbo.MGetNgayHieuChuanKeBaoTri(@TuNgay, @DenNgay, @UserName, @MsNX, -1, '-1', '-1', 1) AS A 
ORDER BY A.MS_MAY, A.MS_LOAI_BT, A.NGAY_HC_CUOI, A.CHU_KY, A.MS_DV_TG, A.NGAY_KE

--Xóa dữ liệu quan hệ trong khoảng 1/4 chu kỳ của bảo trì con
DELETE T1
FROM         dbo.LOAI_BAO_TRI_QH INNER JOIN #HIEU_CHUAN_KE AS T1 ON dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CD = T1.MS_LOAI_BT INNER JOIN
                      #HIEU_CHUAN_KE AS T2 ON T1.MS_MAY = T2.MS_MAY AND dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CT = T2.MS_LOAI_BT 
WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY_BTKT 
AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY_BTKT 
 

 --2
--Xóa dữ liệu quan hệ trong khoảng 1/4 chu kỳ của bảo trì con trong PBT
----------DELETE T1
----------FROM         dbo.LOAI_BAO_TRI_QH INNER JOIN
----------                      #HIEU_CHUAN_KE AS T1 ON dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CD = T1.MS_LOAI_BT INNER JOIN
----------                      PHIEU_BAO_TRI AS T2 ON T1.MS_MAY = T2.MS_MAY AND dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CT = T2.MS_LOAI_BT 
----------WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY_BD_KH 
----------AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY_BD_KH


SELECT        T1.MS_MAY, T1.MS_LOAI_BT AS MS_LOAI_BT_CD, T1.NGAY_HC_CUOI, T1.CHU_KY, T1.MS_DV_TG, T1.NGAY_BTKT, T2.MS_LOAI_BT AS MS_LOAI_BT_CT INTO #PBTTMP
FROM            #HIEU_CHUAN_KE AS T1 INNER JOIN dbo.PHIEU_BAO_TRI AS T2 ON T1.MS_MAY = T2.MS_MAY 
WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY_BD_KH 
	AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) 
                         <= T2.NGAY_BD_KH
DELETE T1 FROM #PBTTMP T1 INNER JOIN LOAI_BAO_TRI_QH T2 ON T1.MS_LOAI_BT_CD = T2.MS_LOAI_BT_CD AND T1.MS_LOAI_BT_CT = T2.MS_LOAI_BT_CT




----1
--Xóa dữ liệu quan hệ trong khoảng 1/4 chu kỳ của bảo trì con trong KHTT 
----------DELETE T1
----------FROM         dbo.LOAI_BAO_TRI_QH INNER JOIN
----------                      #HIEU_CHUAN_KE AS T1 ON dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CD = T1.MS_LOAI_BT INNER JOIN
----------                      KE_HOACH_TONG_THE AS T2 ON T1.MS_MAY = T2.MS_MAY AND dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CT = T2.MS_LOAI_BT 
----------WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY
----------AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY
SELECT        T1.MS_MAY, T1.MS_LOAI_BT AS MS_LOAI_BT_CD, T1.NGAY_HC_CUOI, T1.CHU_KY, T1.MS_DV_TG, T1.NGAY_BTKT, T2.MS_LOAI_BT AS MS_LOAI_BT_CT INTO #KHTTTMP
FROM            #HIEU_CHUAN_KE AS T1 INNER JOIN
                         dbo.KE_HOACH_TONG_THE AS T2 ON T1.MS_MAY = T2.MS_MAY 
WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY 
	AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY
DELETE T1 FROM #KHTTTMP T1 INNER JOIN LOAI_BAO_TRI_QH T2 ON T1.MS_LOAI_BT_CD = T2.MS_LOAI_BT_CD AND T1.MS_LOAI_BT_CT = T2.MS_LOAI_BT_CT




 --Xóa bảo trì định kỳ đã lập bên kế hoạch tổng thể và phiếu bảo trì TRONG 1/4 CHU KY
DELETE T
FROM #HIEU_CHUAN_KE T INNER JOIN
dbo.KE_HOACH_TONG_THE T1 ON T.MS_MAY = T1.MS_MAY AND 
T.MS_LOAI_BT = T1.MS_LOAI_BT 
WHERE DATEADD(DAY,  CASE T.MS_DV_TG WHEN 2 THEN T.CHU_KY * 7 WHEN 3 THEN T.CHU_KY * 30 WHEN 4 THEN T.CHU_KY * 365 ELSE T.CHU_KY END / 4, T.NGAY_BTKT) >= T1.NGAY 
	AND DATEADD(DAY, - (CASE T.MS_DV_TG WHEN 2 THEN T.CHU_KY * 7 WHEN 3 THEN T.CHU_KY * 30 WHEN 4 THEN T.CHU_KY * 365 ELSE T.CHU_KY END / 4), T.NGAY_BTKT) <= T1.NGAY 


DELETE T
FROM #HIEU_CHUAN_KE T INNER JOIN dbo.PHIEU_BAO_TRI T1 ON T.MS_MAY = T1.MS_MAY AND T.MS_LOAI_BT = T1.MS_LOAI_BT 
WHERE DATEADD(DAY,  CASE T.MS_DV_TG WHEN 2 THEN T.CHU_KY * 7 WHEN 3 THEN T.CHU_KY * 30 WHEN 4 THEN T.CHU_KY * 365 ELSE T.CHU_KY END / 4, T.NGAY_BTKT) >= T1.NGAY_BD_KH 
AND DATEADD(DAY, - (CASE T.MS_DV_TG WHEN 2 THEN T.CHU_KY * 7 WHEN 3 THEN T.CHU_KY * 30 WHEN 4 THEN T.CHU_KY * 365 ELSE T.CHU_KY END / 4), T.NGAY_BTKT) <= T1.NGAY_BD_KH 
	

INSERT INTO BTDK_TMP (MS_MAY,MS_LOAI_BT,NGAY_CUOI,NGAYKE,CHU_KY,MS_DV_TG,MS_HE_THONG)
SELECT A.MS_MAY,MS_LOAI_BT,NGAY_HC_CUOI AS NGAY_CUOI,NGAY_BTKT AS NGAYKE,CHU_KY,MS_DV_TG, B.MS_HE_THONG
FROM #HIEU_CHUAN_KE A INNER JOIN #MAY_USER B ON A.MS_MAY = B.MS_MAY
WHERE NGAY_BTKT BETWEEN @TuNgay AND @DenNgay
ORDER BY MS_MAY,MS_LOAI_BT,NGAY_CUOI,CHU_KY,MS_DV_TG,NGAY_BTKT
