
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetDieuDoCVVP')
   exec('CREATE PROCEDURE spGetDieuDoCVVP AS BEGIN SET NOCOUNT ON; END')
GO
--spGetDieuDoPBT
-- spGetDieuDoCVVP

ALTER PROC [dbo].spGetDieuDoCVVP
	@IdDD bigint = 1,  
	@UName NVARCHAR(50) = 'admin',
	@TNgay DATE = '04/01/2015',
	@DNgay DATE = '05/01/2017',
	@NNgu INT = 0,
	@MsNXuong NVARCHAR(50) = '-1',
	@MsHeThong INT = -1,
	@Action INT = 0
AS
BEGIN 

SELECT        D.TEN_DON_VI, C.TEN_TO AS PB, B.TEN_TO, A.MS_CONG_NHAN, A.HO, A.TEN, D.MS_DON_VI, C.MS_TO AS MS_PB, B.MS_TO1 AS MS_TO INTO #CONG_NHAN
FROM            dbo.CONG_NHAN AS A INNER JOIN
                         dbo.[TO] AS B ON A.MS_TO = B.MS_TO1 INNER JOIN
                         dbo.TO_PHONG_BAN AS C ON B.MS_TO = C.MS_TO INNER JOIN
                         dbo.DON_VI AS D ON C.MS_DON_VI = D.MS_DON_VI


IF @Action = 0
BEGIN
SELECT        CHON, MS_CONG_NHAN, HO_TEN, TEN_UU_TIEN, TEN_CONG_VIEC, THOI_GIAN_DK, NGAY, THOI_HAN, SO_NGUOI_DD, NGAY_DD, STT, MS_UU_TIEN, K1, K2, K3, K4, K5, K6,HO,TEN,
	CONVERT(INT,ROW_NUMBER() OVER (ORDER BY NGAY,STT,MS_CONG_NHAN,TEN_UU_TIEN,TEN_CONG_VIEC)) AS TK, MS_DON_VI, MS_PB,MS_TO
FROM (
	SELECT   CONVERT(BIT,1) AS CHON,T1.MS_CONG_NHAN,T3.HO + ' ' + T3.TEN AS HO_TEN, 
	CASE @NNgu WHEN 0 THEN T4.TEN_UU_TIEN ELSE T4.TEN_TA END AS TEN_UU_TIEN,
	T2.TEN_CONG_VIEC, T2.THOI_GIAN_DK,
	 T1.NGAY, T2.THOI_HAN, T1.SO_NGUOI_DD, T1.NGAY_DD,  T1.STT,T2.MS_UU_TIEN, @IdDD AS K1,@UName AS K2, @TNgay AS K3, @DNgay AS K4, @MsNXuong AS K5, @MsHeThong AS K6 , HO,TEN, MS_DON_VI, MS_PB,MS_TO
	FROM            dbo.DIEU_DO_CVVP AS T1 INNER JOIN
							 dbo.KE_HOACH_THUC_HIEN AS T2 ON T1.MS_CONG_NHAN = T2.MS_CONG_NHAN AND T1.NGAY = T2.NGAY AND T1.STT = T2.STT INNER JOIN
							 #CONG_NHAN AS T3 ON T2.MS_CONG_NHAN = T3.MS_CONG_NHAN 
							 LEFT JOIN dbo.MUC_UU_TIEN AS T4 ON T2.MS_UU_TIEN = T4.MS_UU_TIEN
	WHERE T1.ID_DD = @IdDD) A
	ORDER BY NGAY,STT,MS_CONG_NHAN,TEN_UU_TIEN,TEN_CONG_VIEC
END
IF @Action = 1
BEGIN
SELECT        CHON, MS_CONG_NHAN, HO_TEN, TEN_UU_TIEN, TEN_CONG_VIEC, THOI_GIAN_DK, NGAY, THOI_HAN, SO_NGUOI_DD, NGAY_DD, STT, MS_UU_TIEN, K1, K2, K3, K4, K5, K6,HO,TEN,
	CONVERT(INT,ROW_NUMBER() OVER (ORDER BY NGAY,STT,MS_CONG_NHAN,TEN_UU_TIEN,TEN_CONG_VIEC)) AS TK, MS_DON_VI, MS_PB,MS_TO
FROM (
	SELECT   CONVERT(BIT,0) AS CHON,T1.MS_CONG_NHAN, T2.HO + ' ' +  T2.TEN AS HO_TEN, 
	CASE @NNgu WHEN 0 THEN T3.TEN_UU_TIEN ELSE T3.TEN_TA END AS TEN_UU_TIEN,
	T1.TEN_CONG_VIEC, T1.THOI_GIAN_DK, T1.NGAY, T1.THOI_HAN, CONVERT(INT, NULL) AS SO_NGUOI_DD,
	CONVERT(DATE,NULL) AS NGAY_DD, STT,T1.MS_UU_TIEN,@IdDD AS K1,@UName AS K2, @TNgay AS K3, @DNgay AS K4, @MsNXuong AS K5, @MsHeThong AS K6,HO,TEN, MS_DON_VI, MS_PB,MS_TO
	FROM            dbo.KE_HOACH_THUC_HIEN AS T1 INNER JOIN
							 #CONG_NHAN AS T2 ON T1.MS_CONG_NHAN = T2.MS_CONG_NHAN 
							 LEFT JOIN dbo.MUC_UU_TIEN AS T3 ON T1.MS_UU_TIEN = T3.MS_UU_TIEN				
	WHERE (NGAY BETWEEN @TNgay AND @DNgay)	AND ISNULL(DA_XONG,0) = 0
	) A
	ORDER BY NGAY,STT,MS_CONG_NHAN,TEN_UU_TIEN,TEN_CONG_VIEC
END

END
