--spGetSoPhutDDTheoNgayDD

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetSoPhutDDTheoNgayDD')
   exec('CREATE PROCEDURE spGetSoPhutDDTheoNgayDD AS BEGIN SET NOCOUNT ON; END')
GO

-- spGetSoPhutDDTheoNgayDD

ALTER PROC [dbo].spGetSoPhutDDTheoNgayDD
	@UserName NVARCHAR(100)
AS

CREATE TABLE #TB_TMP(
    [MA_SO] [int] NULL,
	[KHOA] [int] NULL,
	[NGAY_KH] [datetime] NULL,
	[NGAY_TRUOC] [datetime] NULL,
	[NGAY_SAU] [datetime] NULL,
	[TG_KH] [float] NOT NULL,
	[NGAY_DD] [datetime] NULL,
	[MS_UU_TIEN] [int] NULL,
	[LOAI] [int] NULL
)

DECLARE @sSql NVARCHAR(4000)
SET @sSql = 'INSERT INTO #TB_TMP([MA_SO],[KHOA],[NGAY_KH],[NGAY_TRUOC],[NGAY_SAU],[TG_KH],[NGAY_DD],[MS_UU_TIEN],[LOAI]) SELECT [MA_SO],[KHOA],[NGAY_KH],[NGAY_TRUOC],[NGAY_SAU],[TG_KH],[NGAY_DD],[MS_UU_TIEN],[LOAI] FROM DD_TT_TMP' + @UserName

EXEC (@sSql)

SELECT NGAY, SUM(S_PHUT) AS S_PHUT,TUAN,THANG,NAM,first_day,last_day INTO #DD_TMP
FROM
(
SELECT CONVERT(DATE,NGAY_DD,103) AS NGAY,SUM(TG_KH) AS S_PHUT,
DATEPART( WK, NGAY_DD) AS TUAN, MONTH(NGAY_DD) AS THANG, YEAR(NGAY_DD) AS NAM,
DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NGAY_DD), DATEDIFF(dd, 0, NGAY_DD))) as first_day  , --first day current week
DATEADD(wk, 1, DATEADD(DAY, 0-DATEPART(WEEKDAY, NGAY_DD), DATEDIFF(dd, 0, NGAY_DD))) as last_day 
FROM #TB_TMP GROUP BY NGAY_DD

) T
GROUP BY NGAY, TUAN,THANG,NAM,first_day,last_day


SELECT CONVERT(NVARCHAR(100), NGAY,103) AS [DATA],  S_PHUT, 1 AS LOAI, NAM AS ORD1 ,MONTH(NGAY) ORD2 FROM #DD_TMP 
--ORDER BY NAM,ORD1
UNION

SELECT CONVERT(NVARCHAR(10),TUAN) + '/' + CONVERT(NVARCHAR(10),NAM) + ' - (' +  CONVERT(NVARCHAR(10),first_day,103) + ' - ' +  CONVERT(NVARCHAR(10),last_day,103) + ')', SUM(S_PHUT) AS S_PHUT,2 AS LOAI, NAM,TUAN FROM #DD_TMP 
GROUP BY TUAN,NAM,first_day,last_day
--ORDER BY NAM,TUAN
UNION
SELECT  CONVERT(NVARCHAR(10),THANG) + '/' + CONVERT(NVARCHAR(10),NAM) , SUM(S_PHUT) AS S_PHUT,3 AS LOAI, NAM,THANG FROM #DD_TMP 
GROUP BY THANG,NAM
ORDER BY LOAI,ORD1,ORD2