--spGetSoPhutDD

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetSoPhutDD')
   exec('CREATE PROCEDURE spGetSoPhutDD AS BEGIN SET NOCOUNT ON; END')
GO

-- spGetSoPhutDD

ALTER PROC [dbo].spGetSoPhutDD
	--@TNgay DATE = '01/01/2018',
	--@DNgay DATE = '02/01/2018',
	--@MsTo NVARCHAR(50) = '-1',
	--@MsDV NVARCHAR(50) = '-1',
	--@HSuat FLOAT = 80,
	--@GioLV FLOAT = 8
AS


SELECT NGAY, SUM(S_PHUT) AS S_PHUT,TUAN,THANG,NAM,first_day,last_day INTO #DD_TMP
FROM
(
SELECT CONVERT(DATE,NGAY_KH,103) AS NGAY,SUM(TG_KH) AS S_PHUT,
DATEPART( WK, NGAY_KH) AS TUAN, MONTH(NGAY_KH) AS THANG, YEAR(NGAY_KH) AS NAM,
DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NGAY_KH), DATEDIFF(dd, 0, NGAY_KH))) as first_day  , --first day current week
DATEADD(wk, 1, DATEADD(DAY, 0-DATEPART(WEEKDAY, NGAY_KH), DATEDIFF(dd, 0, NGAY_KH))) as last_day 
FROM            dbo.DD_TT_TMPADMIN GROUP BY NGAY_KH
--------UNION

--------SELECT CONVERT(DATE,NGAY_BD_KH,103) ,SUM(THOI_GIAN_DU_KIEN) AS S_PHUT,
--------DATEPART( WK, NGAY_BD_KH) AS TUAN, MONTH(NGAY_BD_KH) AS THANG, YEAR(NGAY_BD_KH) AS NAM,
--------DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NGAY_BD_KH), DATEDIFF(dd, 0, NGAY_BD_KH))) as first_day  , --first day current week
--------DATEADD(wk, 1, DATEADD(DAY, 0-DATEPART(WEEKDAY, NGAY_BD_KH), DATEDIFF(dd, 0, NGAY_BD_KH))) as last_day 
--------FROM            dbo.DD_NS_TMPKHTTadmin GROUP BY NGAY_BD_KH
--------UNION


--------SELECT CONVERT(DATE,NGAY_KT_KE,103) ,SUM(ISNULL(THOI_GIAN,0)) AS S_PHUT,
--------DATEPART( WK, NGAY_KT_KE) AS TUAN, MONTH(NGAY_KT_KE) AS THANG, YEAR(NGAY_KT_KE) AS NAM,
--------DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NGAY_KT_KE), DATEDIFF(dd, 0, NGAY_KT_KE))) as first_day  , --first day current week
--------DATEADD(wk, 1, DATEADD(DAY, 0-DATEPART(WEEKDAY, NGAY_KT_KE), DATEDIFF(dd, 0, NGAY_KT_KE))) as last_day 
--------FROM            dbo.DD_NS_TMPGSTTadmin GROUP BY NGAY_KT_KE
--------UNION


--------SELECT CONVERT(DATE,NGAY,103) ,SUM(THOI_GIAN_DK) AS S_PHUT,
--------DATEPART( WK, NGAY) AS TUAN, MONTH(NGAY) AS THANG, YEAR(NGAY) AS NAM,
--------DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NGAY), DATEDIFF(dd, 0, NGAY))) as first_day  , --first day current week
--------DATEADD(wk, 1, DATEADD(DAY, 0-DATEPART(WEEKDAY, NGAY), DATEDIFF(dd, 0, NGAY))) as last_day 
--------FROM            dbo.DD_NS_TMPCVVPadmin GROUP BY NGAY
) T
GROUP BY NGAY, TUAN,THANG,NAM,first_day,last_day


SELECT CONVERT(NVARCHAR(100), NGAY,103) AS [DATA],  S_PHUT, 1 AS LOAI, NAM AS ORD1 ,MONTH(NGAY) ORD2 FROM #DD_TMP 
--ORDER BY NAM,ORD1
UNION

SELECT CONVERT(NVARCHAR(10),TUAN) + '/' + CONVERT(NVARCHAR(10),NAM) + ' - (' +  CONVERT(NVARCHAR(10),first_day,103) + ' - ' +  CONVERT(NVARCHAR(10),last_day,103) + ')', SUM(S_PHUT) AS S_PHUT,2 AS LOAI, NAM,TUAN FROM #DD_TMP 
GROUP BY TUAN,NAM,first_day,last_day
--ORDER BY NAM,TUAN
UNION
SELECT  CONVERT(NVARCHAR(10),THANG) + '/' + CONVERT(NVARCHAR(10),NAM) , SUM(S_PHUT) AS S_PHUT,3 AS LOAI, NAM,THANG FROM #DD_TMP 
GROUP BY THANG,NAM
ORDER BY LOAI,ORD1,ORD2