IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetDieuDoGSTT')
   exec('CREATE PROCEDURE spGetDieuDoGSTT AS BEGIN SET NOCOUNT ON; END')
GO

-- spGetDieuDoGSTT

ALTER PROC [dbo].spGetDieuDoGSTT
	@IdDD bigint = 14,  
	@UName NVARCHAR(50) = 'admin',
	@TNgay DATE = '01/01/2015',
	@DNgay DATE = '01/01/2020',
	@NNgu INT = 0,
	@MsNXuong NVARCHAR(50) = '-1',
	@MsHeThong INT = -1,
	@Action INT = 0
AS

SELECT DISTINCT MS_MAY,MS_N_XUONG,MS_HE_THONG,MS_LOAI_MAY,MS_NHOM_MAY, MUC_UU_TIEN,Ten_N_XUONG,TEN_HE_THONG,TEN_BP_CHIU_PHI INTO #MAY_USER FROM dbo.MGetMayUserNgay(@DNgay, @UName, @MsNXuong, @MsHeThong,-1, '-1', '-1', '-1', @NNgu)

IF @Action = 0
BEGIN 
SELECT CHON, SO_PHIEU, TEN_UU_TIEN, MS_MAY, TEN_BO_PHAN, TEN_TS_GSTT, SO_GIO_KH, NGAY_KT, SO_NGUOI_DD, NGAY_DD, MS_BO_PHAN, MS_TS_GSTT, MS_N_XUONG, MS_HE_THONG, MS_LOAI_MAY, 
                         MS_NHOM_MAY, STT, MS_TT, MUC_UU_TIEN, K1, K2, K3, K4, K5, K6,
						 CONVERT(INT,ROW_NUMBER() OVER (ORDER BY NGAY_KT,STT,SO_PHIEU, TEN_UU_TIEN,MS_MAY, TEN_BO_PHAN, TEN_TS_GSTT)) AS TK,Ten_N_XUONG,TEN_HE_THONG,TEN_BP_CHIU_PHI
FROM 
(
	SELECT   CONVERT(BIT,1) AS CHON,T6.SO_PHIEU,CASE @NNgu WHEN 0 THEN T5.TEN_UU_TIEN ELSE T5.TEN_TA END AS TEN_UU_TIEN,	
	T1.MS_MAY, 	
	CASE @NNgu WHEN 0 THEN T2.TEN_BO_PHAN WHEN 1 THEN  ISNULL(NULLIF(T2.TEN_BO_PHAN_ANH, ''), T2.TEN_BO_PHAN)   ELSE ISNULL(NULLIF(T2.TEN_BO_PHAN_HOA, ''), T2.TEN_BO_PHAN) END AS TEN_BO_PHAN, 
	CASE @NNgu WHEN 0 THEN T3.TEN_TS_GSTT WHEN 1 THEN  ISNULL(NULLIF(T3.TEN_TS_GSTT_ANH, ''), T3.TEN_TS_GSTT)   ELSE ISNULL(NULLIF(T3.TEN_TS_GSTT_HOA, ''), T3.TEN_TS_GSTT) END AS TEN_TS_GSTT,
	T1.SO_GIO_KH,T6.NGAY_KT ,  T1.SO_NGUOI_DD,T1.NGAY_DD, 
	T1.MS_BO_PHAN, T1.MS_TS_GSTT,MS_N_XUONG,MS_HE_THONG, MS_LOAI_MAY, MS_NHOM_MAY, T1.STT, T1.MS_TT,T4.MUC_UU_TIEN,
	@IdDD AS K1,@UName AS K2, @TNgay AS K3, @DNgay AS K4, @MsNXuong AS K5, @MsHeThong AS K6 ,Ten_N_XUONG,TEN_HE_THONG,TEN_BP_CHIU_PHI
	FROM            dbo.DIEU_DO_GSTT AS T1 INNER JOIN
				GIAM_SAT_TINH_TRANG T6 ON T6.STT = T1.STT INNER JOIN
							 dbo.CAU_TRUC_THIET_BI AS T2 ON T1.MS_MAY = T2.MS_MAY AND T1.MS_BO_PHAN = T2.MS_BO_PHAN INNER JOIN
							 dbo.THONG_SO_GSTT AS T3 ON T1.MS_TS_GSTT = T3.MS_TS_GSTT INNER JOIN
							 #MAY_USER AS T4 ON T2.MS_MAY = T4.MS_MAY LEFT JOIN
							 dbo.MUC_UU_TIEN AS T5 ON T4.MUC_UU_TIEN = T5.MS_UU_TIEN
	WHERE T1.ID_DD = @IdDD) A
	ORDER BY NGAY_KT,STT,SO_PHIEU, TEN_UU_TIEN,MS_MAY, TEN_BO_PHAN, TEN_TS_GSTT
END

IF @Action = 1
BEGIN 
SELECT CHON, SO_PHIEU, TEN_UU_TIEN, MS_MAY, TEN_BO_PHAN, TEN_TS_GSTT, THOI_GIAN, NGAY_KT, SO_NGUOI_DD, NGAY_DD, MS_BO_PHAN, MS_TS_GSTT, MS_N_XUONG, MS_HE_THONG, MS_LOAI_MAY, 
                         MS_NHOM_MAY, STT, MS_TT, MUC_UU_TIEN, K1, K2, K3, K4, K5, K6,
						 CONVERT(INT,ROW_NUMBER() OVER (ORDER BY NGAY_KT,STT,SO_PHIEU, TEN_UU_TIEN,MS_MAY, TEN_BO_PHAN, TEN_TS_GSTT)) AS TK,Ten_N_XUONG,TEN_HE_THONG,TEN_BP_CHIU_PHI
FROM 
(
	SELECT CONVERT(BIT,0) AS CHON,T1.SO_PHIEU, T2.MS_MAY, T3.TEN_BO_PHAN, T4.TEN_TS_GSTT, T1.NGAY_KT, T2.THOI_GIAN, CONVERT(INT, NULL) AS SO_NGUOI_DD, T6.TEN_UU_TIEN, CONVERT(DATE, NULL) AS NGAY_DD, T2.MS_BO_PHAN, T2.MS_TS_GSTT, T5.MS_N_XUONG, T5.MS_HE_THONG, T5.MS_LOAI_MAY, T5.MS_NHOM_MAY, T1.STT, T2.MS_TT, T5.MUC_UU_TIEN, @IdDD AS K1,@UName AS K2, @TNgay AS K3, @DNgay AS K4, @MsNXuong AS K5, @MsHeThong AS K6,Ten_N_XUONG,TEN_HE_THONG,TEN_BP_CHIU_PHI
	FROM            dbo.GIAM_SAT_TINH_TRANG AS T1 INNER JOIN
							 dbo.GIAM_SAT_TINH_TRANG_TS AS T2 ON T1.STT = T2.STT INNER JOIN
							 dbo.CAU_TRUC_THIET_BI AS T3 ON T2.MS_MAY = T3.MS_MAY AND T2.MS_BO_PHAN = T3.MS_BO_PHAN INNER JOIN
							 dbo.THONG_SO_GSTT AS T4 ON T2.MS_TS_GSTT = T4.MS_TS_GSTT INNER JOIN
							 #MAY_USER AS T5 ON T3.MS_MAY = T5.MS_MAY INNER JOIN
							 dbo.MUC_UU_TIEN AS T6 ON T5.MUC_UU_TIEN = T6.MS_UU_TIEN
	WHERE T1.HOAN_THANH = 0) A
	ORDER BY NGAY_KT,STT,SO_PHIEU, TEN_UU_TIEN,MS_MAY, TEN_BO_PHAN, TEN_TS_GSTT
END
