

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetNgayLV')
   exec('CREATE PROCEDURE spGetNgayLV AS BEGIN SET NOCOUNT ON; END')
GO

-- spGetNgayLV

ALTER PROC [dbo].spGetNgayLV
	@TNgay DATE = '01/01/2018',
	@DNgay DATE = '02/02/2018',
	@MsTo NVARCHAR(50) = '-1',
	@MsDV NVARCHAR(50) = '-1',
	@HSuat FLOAT = 100,
	@GioLV FLOAT = 8,
	@SNV FLOAT = 1
AS




--SELECT     @SNV =  COUNT(*)  
--FROM            dbo.CONG_NHAN AS T1 INNER JOIN
--                         dbo.[TO] AS T2 ON T1.MS_TO = T2.MS_TO1 INNER JOIN
--                         dbo.TO_PHONG_BAN AS T3 ON T2.MS_TO = T3.MS_TO
--WHERE (T3.MS_TO = @MsTo OR @MsTo  = '-1') AND (T3.MS_DON_VI = @MsDV OR @MsDV = '-1')

SELECT *,
NV * GIO_LV * 60 * (HIEU_SUAT/100) AS SO_PHUT_NGAY,
 @SNV AS NHANSU
INTO #DD
 FROM
(
SELECT NGAY ,  DATENAME(DW, NGAY) NGAY_THU , 
CASE WHEN NGAY_TUAN = 1 THEN 0 ELSE @SNV END AS NV,
CASE WHEN NGAY_TUAN = 1 THEN 0 ELSE @GioLV END AS GIO_LV, 
CASE WHEN NGAY_TUAN = 1 THEN 0 ELSE @HSuat END AS HIEU_SUAT,
CASE WHEN NGAY_TUAN = 1 THEN 1 ELSE 0 END AS NGAY_NGHI,
NGAY_TUAN
FROM 
(
SELECT DATEADD(DAY, NUMBER, @TNgay) AS NGAY , DATEPART(DW, DATEADD(DAY, NUMBER, @TNgay)) AS NGAY_TUAN
FROM 
    (SELECT DISTINCT NUMBER FROM MASTER.DBO.SPT_VALUES
     WHERE NAME IS NULL
    ) N
WHERE DATEADD(DAY, NUMBER, @TNgay) <= @DNgay
) A
) T1
ORDER BY NGAY

UPDATE #DD SET NV = 0,GIO_LV = 0, HIEU_SUAT = 0,NGAY_NGHI=1,SO_PHUT_NGAY = 0
FROM NGAY_NGHI T1 INNER JOIN #DD T2 ON T1.NGAY = T2.NGAY

SELECT * FROM #DD ORDER BY NGAY