
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapDieuDoNhom')
   exec('CREATE PROCEDURE spCapNhapDieuDoNhom AS BEGIN SET NOCOUNT ON; END')
GO



ALTER PROC [dbo].[spCapNhapDieuDoNhom]
	 @ID_NHOM_DD BIGINT,
	 @TEN_NHOM NVARCHAR(250),
	 @TEN_NHOM_ANH NVARCHAR(250),
	 @TEN_NHOM_HOA NVARCHAR(250),
	 @GHI_CHU NVARCHAR(500),
	 @BTMAY NVARCHAR(100),
	 @BTCN NVARCHAR(100)
AS


CREATE TABLE #MAY_SEL (
	[MS_MAY] [nvarchar](100) NULL
) 

DECLARE @sSql nvarchar(4000)
set @sSql = ' IF EXISTS (SELECT * FROM sys.objects WHERE type = ''U'' AND name = ''' + @BTMAY + ''' ) INSERT INTO #MAY_SEL SELECT [MS_MAY] FROM ' + @BTMAY
EXEC (@sSql)


set @sSql = ' IF EXISTS (SELECT * FROM sys.objects WHERE type = ''U'' AND name = ''' + @BTMAY + ''' ) DROP TABLE ' + @BTMAY
EXEC (@sSql)


CREATE TABLE #CN_SEL (
	[MS_CONG_NHAN] [nvarchar](100) NULL
) 

set @sSql = ' IF EXISTS (SELECT * FROM sys.objects WHERE type = ''U'' AND name = ''' + @BTCN + ''' ) INSERT INTO #CN_SEL SELECT [MS_CONG_NHAN] FROM ' + @BTCN
EXEC (@sSql)


set @sSql = ' IF EXISTS (SELECT * FROM sys.objects WHERE type = ''U'' AND name = ''' + @BTCN + ''' ) DROP TABLE ' + @BTCN
EXEC (@sSql)



IF EXISTS(SELECT * FROM DIEU_DO_NHOM WHERE ID_NHOM_DD = @ID_NHOM_DD)
BEGIN
	UPDATE DIEU_DO_NHOM SET 
			TEN_NHOM = @TEN_NHOM,
			TEN_NHOM_ANH = CASE ISNULL(NULLIF(@TEN_NHOM_ANH, NULL), '') WHEN '' THEN @TEN_NHOM ELSE @TEN_NHOM_ANH END,
			TEN_NHOM_HOA = CASE ISNULL(NULLIF(@TEN_NHOM_HOA, NULL), '') WHEN '' THEN @TEN_NHOM ELSE @TEN_NHOM_HOA END,
			GHI_CHU = @GHI_CHU 
	WHERE ID_NHOM_DD = @ID_NHOM_DD
END
ELSE
BEGIN
	INSERT INTO [DIEU_DO_NHOM]([TEN_NHOM],[TEN_NHOM_ANH],[TEN_NHOM_HOA],[GHI_CHU])
	VALUES (@TEN_NHOM ,CASE ISNULL(NULLIF(@TEN_NHOM_ANH, NULL), '') WHEN '' THEN @TEN_NHOM ELSE @TEN_NHOM_ANH END ,
		CASE ISNULL(NULLIF(@TEN_NHOM_HOA, NULL), '') WHEN '' THEN @TEN_NHOM ELSE @TEN_NHOM_HOA END ,@GHI_CHU)

	SET @ID_NHOM_DD = SCOPE_IDENTITY()
END


DELETE FROM DIEU_DO_NHOM_MAY WHERE ID_NHOM_DD = @ID_NHOM_DD
INSERT INTO DIEU_DO_NHOM_MAY(ID_NHOM_DD,MS_MAY)
SELECT @ID_NHOM_DD, MS_MAY FROM #MAY_SEL

DELETE FROM DIEU_DO_NHOM_CN WHERE ID_NHOM_DD = @ID_NHOM_DD
INSERT INTO DIEU_DO_NHOM_CN(ID_NHOM_DD,MS_CONG_NHAN)
SELECT @ID_NHOM_DD, MS_CONG_NHAN FROM #CN_SEL

SELECT @ID_NHOM_DD
