

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetDieuDoNhomCongNhan')
   exec('CREATE PROCEDURE spGetDieuDoNhomCongNhan AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROC [dbo].[spGetDieuDoNhomCongNhan]
	@ID_NHOM_DD BIGINT = 1,
	@UserName NVARCHAR(255) = 'Admin',
	@NNGU INT = 0
AS

BEGIN
SELECT MS_CONG_NHAN,HOTEN,TEN_DON_VI,[TEN_PHONG_BAN],TEN_TO, MS_TO,MS_PHONG_BAN,MS_DON_VI,HO,TEN INTO #CN FROM dbo.MGetCongNhanToPhongBan(@UserName ,'-1','-1',-1,-1,@NNGU)

SELECT        T1.MS_CONG_NHAN,HOTEN,TEN_DON_VI, TEN_PHONG_BAN, TEN_TO,HO, TEN, MS_TO,MS_PHONG_BAN,MS_DON_VI
FROM            dbo.DIEU_DO_NHOM_CN AS T1 INNER JOIN
                         #CN AS T2 ON T1.MS_CONG_NHAN = T2.MS_CONG_NHAN 
WHERE (T1.ID_NHOM_DD = @ID_NHOM_DD)
ORDER BY T1.MS_CONG_NHAN

END