
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spImportNhapKhoTheoNgay')
   exec('CREATE PROCEDURE spImportNhapKhoTheoNgay AS BEGIN SET NOCOUNT ON; END')
GO



ALTER PROC spImportNhapKhoTheoNgay
	@sBT NVARCHAR(100) = 'ICDHN_TMPAdmin',
	@UserName NVARCHAR(50) = 'admin'
AS


DECLARE @NguoiLap NVARCHAR(250)

SELECT @NguoiLap = HO + ' ' + TEN FROM USERS T1 INNER JOIN CONG_NHAN T2 ON T1.MS_CONG_NHAN = T2.MS_CONG_NHAN WHERE USERNAME = @UserName

IF ISNULL(@NguoiLap,'') = ''
	SET @NguoiLap  = 'admin'

CREATE TABLE  #BTImport (
	[NGAY_NHAP] [datetime] NULL,
	[TEN_KHO] [nvarchar](500) NULL,
	[VI_TRI_KHO] [nvarchar](500) NULL,
	[TEN_NN] [nvarchar](500) NULL,
	[MS_PT] [nvarchar](500) NULL,
	[SO_LUONG] [float] NULL,
	[DON_GIA_GOC] [float] NULL,
	[NGOAI_TE] [nvarchar](500) NULL,
	[TI_GIA] [float] NULL,
	[TI_GIA_USD] [float] NULL,
	[TAX] [float] NULL,
	[GHI_CHU] [nvarchar](500) NULL,
	[MS_KHO] [int] NULL,
	[NGUOI_NHAP] [nvarchar](50) NULL,
	[MA_SO_VT] [int] NULL
) 

DECLARE @sSql NVARCHAR(4000)
SET @sSql = 'INSERT INTO #BTImport (NGAY_NHAP, TEN_KHO, VI_TRI_KHO, TEN_NN, MS_PT, SO_LUONG, DON_GIA_GOC, NGOAI_TE, TI_GIA, TI_GIA_USD, TAX, GHI_CHU, MS_KHO, NGUOI_NHAP, MA_SO_VT) SELECT NGAY_NHAP, TEN_KHO, VI_TRI_KHO, TEN_NN, MS_PT, SO_LUONG, DON_GIA_GOC, NGOAI_TE, TI_GIA, TI_GIA_USD, TAX, GHI_CHU, MS_KHO, NGUOI_NHAP, MA_SO_VT FROM ' + @sBT + ' WHERE ISNULL(SO_LUONG,0) <> 0 AND ISNULL(TEN_KHO,'''') <> '''' AND ISNULL(VI_TRI_KHO,'''') <> '''' AND ISNULL(TEN_NN,'''') <> '''' AND ISNULL(NGOAI_TE,'''') <> '''' ' 
EXEC(@sSql)

EXEC('DROP TABLE ' + @sBT)


--2-- Cap nhap nha cung cap va kho VA VI TRI
UPDATE #BTImport SET NGUOI_NHAP = MS_NN 
FROM #BTImport T1 INNER JOIN
(
SELECT DISTINCT MAX(MS_KH) MS_NN,  TEN_CONG_TY AS NGUOI_NHAP FROM KHACH_HANG T2 GROUP BY TEN_CONG_TY
UNION
SELECT DISTINCT MAX(MS_KH) A,  TEN_RUT_GON FROM KHACH_HANG T2 GROUP BY TEN_RUT_GON
UNION
SELECT DISTINCT MAX(MS_CONG_NHAN) A,  HO + ' ' + TEN AS HT FROM CONG_NHAN T2 GROUP BY HO + ' ' + TEN ) T2 ON T1.TEN_NN = T2.NGUOI_NHAP

UPDATE #BTImport SET MS_KHO = T2.MS_KHO 
FROM #BTImport T1 INNER JOIN IC_KHO T2 ON T1.TEN_KHO = T2.TEN_KHO

UPDATE #BTImport SET MA_SO_VT = MS_VI_TRI
FROM #BTImport T1 INNER JOIN VI_TRI_KHO T2 ON T1.MS_KHO = T2.MS_KHO AND T1.VI_TRI_KHO = T2.TEN_VI_TRI

--3-- Tao bang tam co phieu nhap va don gia
SELECT 
'PN-' +  CONVERT(NVARCHAR(4) , DATEADD(m, DATEDIFF(m, 0, T1.NGAY_NHAP), 0) , 12)  + '-' +  RIGHT (  '0000' + CONVERT(NVARCHAR(4),ISNULL(
(SELECT ISNULL(MAX(CONVERT(INT,RIGHT (MS_DH_NHAP_PT,4))),0)  
FROM IC_DON_HANG_NHAP
WHERE  LEFT(MS_DH_NHAP_PT,2) = 'PN' AND SUBSTRING(MS_DH_NHAP_PT,4,4) = CONVERT(NVARCHAR(4) , DATEADD(m, DATEDIFF(m, 0, T1.NGAY_NHAP), 0) , 12)) + 
STT_P,0)),4) AS MS_DH_NHAP_PT,

ROW_NUMBER() OVER (PARTITION BY DATEADD(m, DATEDIFF(m, 0, T1.NGAY_NHAP), 0) ORDER BY DATEADD(m, DATEDIFF(m, 0, T1.NGAY_NHAP), 0), T1.NGUOI_NHAP, T1.MS_KHO) AS STT,STT_P,
T1.* ,
CONVERT(FLOAT,ISNULL(DON_GIA_GOC,0) * ISNULL(TI_GIA,0)) AS DON_GIA ,
CONVERT(FLOAT,(ISNULL(DON_GIA_GOC,0) * ISNULL(TI_GIA,0)) * ISNULL(SO_LUONG,0)) +
CONVERT(FLOAT,((ISNULL(DON_GIA_GOC,0) * ISNULL(TI_GIA,0) * ISNULL(TAX,0) )/100) * ISNULL(SO_LUONG,0))
 AS THANH_TIEN,
CONVERT(FLOAT,((ISNULL(DON_GIA_GOC,0) * ISNULL(TI_GIA,0) * ISNULL(TAX,0) )/100) * ISNULL(SO_LUONG,0)) TT_TAX
INTO #IMPORT_NHAP
FROM            #BTImport T1 
INNER JOIN (
SELECT ROW_NUMBER() OVER (PARTITION BY DATEADD(m, DATEDIFF(m, 0, NGAY_NHAP), 0) ORDER BY DATEADD(m, DATEDIFF(m, 0, NGAY_NHAP), 0), nguoi_nhap, ms_kho) AS STT_P, NGAY_NHAP, NGUOI_NHAP, MS_KHO
FROM (SELECT DISTINCT NGAY_NHAP, NGUOI_NHAP, MS_KHO FROM #BTImport) T 
) T4  ON T1.NGAY_NHAP = T4.NGAY_NHAP AND T1.NGUOI_NHAP	 = T4.NGUOI_NHAP AND T1.MS_KHO = T4.MS_KHO
ORDER BY  DATEADD(m, DATEDIFF(m, 0, T1.NGAY_NHAP), 0), T1.NGUOI_NHAP, T1.MS_KHO

--4--Tao ID  INTO #ID_TMP
SELECT ROW_NUMBER() OVER(PARTITION BY MS_DH_NHAP_PT ORDER BY MS_DH_NHAP_PT,MS_PT,NGOAI_TE,DON_GIA_GOC) AS ID, *  INTO #ID_TMP
FROM (SELECT DISTINCT MS_DH_NHAP_PT, MS_KHO,MS_PT,NGOAI_TE,DON_GIA_GOC FROM #IMPORT_NHAP) T ORDER BY MS_DH_NHAP_PT, MS_KHO,MS_PT,NGOAI_TE,DON_GIA_GOC

--5--Tao bang tam chua ID INTO #TMPNHAP 
SELECT CONVERT(INT,T2.ID) AS ID,T1.* INTO #TMPNHAP  FROM #IMPORT_NHAP T1 INNER JOIN #ID_TMP T2 ON T1.MS_DH_NHAP_PT = T2.MS_DH_NHAP_PT AND  T1.MS_PT = T2.MS_PT AND T1.NGOAI_TE = T2.NGOAI_TE AND T1.DON_GIA_GOC = T2.DON_GIA_GOC ORDER BY T1.MS_DH_NHAP_PT,T1.MS_PT, T1.NGOAI_TE,DON_GIA_GOC

----6 IMPORT VAO DON HANG NHAP
DECLARE @GIO NVARCHAR(8)
SET @GIO = CONVERT(NVARCHAR(8), CONVERT(TIME,GETDATE()),108)

	insert into IC_DON_HANG_NHAP(MS_DH_NHAP_PT,SO_PHIEU_XN,GIO,NGAY,
		MS_KHO,MS_DANG_NHAP,NGUOI_NHAP, GHI_CHU,
		LOCK,		
		NGUOI_LAP,THU_KHO )
	SELECT DISTINCT MS_DH_NHAP_PT, MS_DH_NHAP_PT AS SO_PHIEU_XN,CONVERT(DATETIME,CONVERT(NVARCHAR(10),CONVERT(DATE,NGAY_NHAP),101) + ' ' + @GIO) AS GIO,NGAY_NHAP,
		MS_KHO, 2 AS MS_DANG_NHAP, NGUOI_NHAP, N'Import ngày : ' + CONVERT(NVARCHAR(10),GETDATE(),103) AS GHI_CHU,
		0 AS LOCK,		@UserName AS NGUOI_LAP,		@UserName AS THU_KHO
	FROM #TMPNHAP

	
	insert into IC_DON_HANG_NHAP_VAT_TU(MS_DH_NHAP_PT,MS_PT,SO_LUONG_CTU,SL_THUC_NHAP,
			DON_GIA,NGOAI_TE,TY_GIA,TY_GIA_USD,
			THANH_TIEN,GHI_CHU,Tax,ID,MS_DH_NHAP_PT_GOC,ID_GOC,TT_TAX ,DON_GIA_GOC )			

	SELECT  MS_DH_NHAP_PT, MS_PT, SUM(SO_LUONG) AS SO_LUONG_CTU, SUM(SO_LUONG) AS SL_THUC_NHAP, AVG(DON_GIA) AS DON_GIA, NGOAI_TE, AVG(TI_GIA) AS TY_GIA, AVG(TI_GIA_USD) 
							 AS TY_GIA_USD, SUM(THANH_TIEN) AS THANH_TIEN, GHI_CHU, AVG(TAX) AS TAX, ID, MS_DH_NHAP_PT AS MS_DH_NHAP_PT_GOC, AVG(ID) AS ID_GOC, SUM(TT_TAX) AS TT_TAX, AVG(DON_GIA_GOC) AS DON_GIA_GOC
	FROM            #TMPNHAP
	GROUP BY MS_DH_NHAP_PT, MS_PT, NGOAI_TE, GHI_CHU, ID
	ORDER BY MS_DH_NHAP_PT, MS_PT, ID

INSERT INTO IC_DON_HANG_NHAP_VAT_TU_CHI_TIET(MS_DH_NHAP_PT,MS_PT,MS_VI_TRI,SL_VT,ID)
SELECT MS_DH_NHAP_PT,MS_PT,MA_SO_VT,SO_LUONG AS SL_VT,ID 
FROM #TMPNHAP
