

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetPBTNS')
   exec('CREATE PROCEDURE spGetPBTNS AS BEGIN SET NOCOUNT ON; END')
GO



ALTER PROC spGetPBTNS
	@NgayBD DATETIME  = '01/01/2012',
	@NgayKT DATETIME = '01/01/2016',
	@UserName NVARCHAR(50) = 'ADMIN',
	@MsNXuong nvarchar(50) = 'GF-02',
	@MsHeThong int = -1
as


SELECT * INTO #MAY_TMP FROM dbo.MGetMayUserNgay(@NgayBD, @UserName, @MsNXuong, @MsHeThong, - 1, '-1', '-1', '-1', 1)

SELECT CONVERT(BIT,0) AS CHON,MS_PHIEU_BAO_TRI,T3.TEN_LOAI_BT,T1.NGAY_BD_KH, T1.MS_MAY,TEN_MAY, TEN_LOAI_MAY,
Ten_N_XUONG,TEN_HE_THONG,TEN_BP_CHIU_PHI , MS_LOAI_MAY,T1.MS_LOAI_BT
FROM PHIEU_BAO_TRI T1 INNER JOIN #MAY_TMP T2 ON T1.MS_MAY = T2.MS_MAY 
INNER JOIN LOAI_BAO_TRI T3 ON T1.MS_LOAI_BT = T3.MS_LOAI_BT
WHERE NGAY_BD_KH BETWEEN @NgayBD AND @NgayKT
ORDER BY MS_PHIEU_BAO_TRI