IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spKiemNgiemThu')
   exec('CREATE PROCEDURE spKiemNgiemThu AS BEGIN SET NOCOUNT ON; END')
GO


ALTER PROC [dbo].[spKiemNgiemThu]
	@PBT NVARCHAR(100) = 'WO-201802000910'
AS
DECLARE @LOAI INT = 0
DECLARE @PBT_THEO_GIO NVARCHAR(100) = 1
	-- 0 Khong co
	-- 1 PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET
	-- 2 PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO
	-- 3 PHIEU_BAO_TRI_NHAN_SU

SELECT TOP 1 @PBT_THEO_GIO = PBT_THEO_GIO FROM THONG_TIN_CHUNG

IF @PBT_THEO_GIO = 1 
BEGIN
SELECT TOP 1 @LOAI = LOAI FROM
(
	SELECT ISNULL(COUNT(*),0) AS SL,1 AS LOAI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET 
	WHERE (MS_PHIEU_BAO_TRI = @PBT OR @PBT = '-1') AND (ISNULL(CONVERT(NVARCHAR,NGAY),'') = '' OR ISNULL(CONVERT(NVARCHAR,DEN_NGAY),'') = '' 
		OR ISNULL(CONVERT(NVARCHAR,TU_GIO),'') = '' OR ISNULL(CONVERT(NVARCHAR,DEN_GIO),'') = '' )
	UNION
	SELECT ISNULL(COUNT(*),0) AS SL,2 AS LOAI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO 
	WHERE (MS_PHIEU_BAO_TRI = @PBT OR @PBT = '-1') AND (ISNULL( CONVERT(NVARCHAR,NGAY),'') = '' OR ISNULL(CONVERT(NVARCHAR,DEN_NGAY),'') = '' 
		OR ISNULL(CONVERT(NVARCHAR,TU_GIO),'') = '' OR ISNULL(CONVERT(NVARCHAR,DEN_GIO),'') = '')  
	UNION
	SELECT ISNULL(COUNT(*),0) AS SL,3 AS LOAI FROM PHIEU_BAO_TRI_NHAN_SU
	WHERE (MS_PHIEU_BAO_TRI = @PBT OR @PBT = '-1') AND (ISNULL(CONVERT(NVARCHAR,NGAY),'') = '' OR ISNULL(CONVERT(NVARCHAR,DEN_NGAY),'') = '' 
		OR ISNULL(CONVERT(NVARCHAR,TU_GIO),'') = '' OR ISNULL(CONVERT(NVARCHAR,DEN_GIO),'') = '' )
) A WHERE SL > 0 ORDER BY LOAI
END
ELSE
BEGIN
 SELECT TOP 1 @LOAI = LOAI FROM
(
	SELECT ISNULL(COUNT(*),0) AS SL,1 AS LOAI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET 
	WHERE (MS_PHIEU_BAO_TRI = @PBT OR @PBT = '-1') AND (ISNULL(SO_GIO,0) = 0) 
	UNION
	SELECT ISNULL(COUNT(*),0) AS SL,2 AS LOAI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO
	WHERE (MS_PHIEU_BAO_TRI = @PBT OR @PBT = '-1') AND (ISNULL(SO_GIO,0) = 0) 
	UNION         
	SELECT ISNULL(COUNT(*),0) AS SL,3 AS LOAI FROM PHIEU_BAO_TRI_NHAN_SU
	WHERE (MS_PHIEU_BAO_TRI = @PBT OR @PBT = '-1') AND (ISNULL(SO_GIO,0) = 0) 
) A WHERE SL > 0 ORDER BY LOAI
END

SELECT @LOAI
