

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spDeleteChuaNhapNhanSu')
   exec('CREATE PROCEDURE spDeleteChuaNhapNhanSu AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROC spDeleteChuaNhapNhanSu
	@MsPBT NVARCHAR(100)
AS
BEGIN
	DELETE FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET WHERE ISNULL(SO_GIO,0) = 0 AND MS_PHIEU_BAO_TRI = @MsPBT 
	DELETE FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO WHERE ISNULL(SO_GIO,0) = 0 AND MS_PHIEU_BAO_TRI = @MsPBT 
	DELETE FROM PHIEU_BAO_TRI_NHAN_SU WHERE ISNULL(SO_GIO,0) = 0 AND MS_PHIEU_BAO_TRI = @MsPBT

END
