IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spBangKeTGNM')
   exec('CREATE PROCEDURE spBangKeTGNM AS BEGIN SET NOCOUNT ON; END')
GO
--SELECT MS_MAY,TEN_MAY,	MS_N_XUONG,Ten_N_XUONG,MS_HE_THONG,TEN_HE_THONG,MS_BP_CHIU_PHI,TEN_BP_CHIU_PHI,MS_LOAI_MAY,TEN_LOAI_MAY, CONVERT(BIT,1) AS CHON INTO BTMAY FROM          dbo.MGetMayUserNgay('12/01/2019', 'ADMIN', '-1', - 1, - 1, '-1', '-1', '-1', 2)

--EXEC spBangKeTGNM 'BTMAY',-1,'07/01/2018','09/30/2018',0

ALTER PROC [dbo].[spBangKeTGNM]
	@MayTmp NVARCHAR(50) = 'BTMAY',
	@MsLBTri INT = -1,
	@TNgay DATETIME = '01/01/2018',
	@DNgay DATETIME = '01/01/2018',
	@NNgu INT = 0
AS

DECLARE @sSql NVARCHAR(4000)
DECLARE @CVC NVARCHAR(500)
DECLARE @CVP NVARCHAR(500)

SELECT TOP 1 @CVC = CASE @NNgu WHEN 0 THEN VIETNAM WHEN 1 THEN ISNULL(NULLIF(ENGLISH,''),VIETNAM)  ELSE ISNULL(NULLIF(CHINESE,''),VIETNAM) END FROM LANGUAGES WHERE FORM = 'frmPhieuBaoTri_New' AND KEYWORD = 'tabCongViecChinh'
SELECT TOP 1 @CVP = CASE @NNgu WHEN 0 THEN VIETNAM WHEN 1 THEN ISNULL(NULLIF(ENGLISH,''),VIETNAM)  ELSE ISNULL(NULLIF(CHINESE,''),VIETNAM) END FROM LANGUAGES WHERE FORM = 'frmPhieuBaoTri_New' AND KEYWORD = 'tabCongViecPhu'


CREATE TABLE #MAY_TMP (MS_MAY NVARCHAR(250) NULL, TEN_MAY NVARCHAR(500) NULL, MS_N_XUONG NVARCHAR(250) NULL, Ten_N_XUONG NVARCHAR(500) NULL, MS_HE_THONG INT NULL, TEN_HE_THONG NVARCHAR(500) NULL, MS_BP_CHIU_PHI INT, TEN_BP_CHIU_PHI NVARCHAR(500) NULL, MS_LOAI_MAY NVARCHAR(250) NULL, TEN_LOAI_MAY NVARCHAR(500) NULL)  

SET @sSql = ' INSERT INTO #MAY_TMP(MS_MAY,TEN_MAY, MS_N_XUONG,Ten_N_XUONG,MS_HE_THONG,TEN_HE_THONG,MS_BP_CHIU_PHI,TEN_BP_CHIU_PHI,MS_LOAI_MAY,TEN_LOAI_MAY) SELECT MS_MAY,TEN_MAY,	MS_N_XUONG,Ten_N_XUONG,MS_HE_THONG,TEN_HE_THONG,MS_BP_CHIU_PHI,TEN_BP_CHIU_PHI,MS_LOAI_MAY,TEN_LOAI_MAY FROM ' + @MayTmp + ' WHERE ISNULL(CHON,0) = 1'
EXEC (@sSql)

SET @sSql = ' DROP TABLE ' + @MayTmp
EXEC (@sSql)
									
SELECT ROW_NUMBER() OVER (ORDER BY  NGAY_LAP_PHIEU, MS_MAY,HIEN_TUONG,TEN_NGUYEN_NHAN, MS_LOAI_MAY, TEN_LOAI_MAY, Ten_N_XUONG,  TEN_HE_THONG, TEN_BP_CHIU_PHI) AS STT,
 MS_MAY, TEN_MAY,CONVERT(NVARCHAR(10), NGAY_LAP_PHIEU,103) AS NGAY_LAP, TU_NGAY, DEN_NGAY, CA, TRUONG_CA, TG_NM, TG_SUA, HIEN_TUONG, TEN_NGUYEN_NHAN, NGUYEN_NHAN_CU_THE, NGUOI_GIAI_QUYET, MS_PHIEU_BAO_TRI, GHI_CHU, MS_LOAI_MAY, TEN_LOAI_MAY, MS_N_XUONG, Ten_N_XUONG, MS_HE_THONG, TEN_HE_THONG, MS_BP_CHIU_PHI, TEN_BP_CHIU_PHI



FROM(
SELECT        T1.MS_MAY,T5.TEN_MAY,  T2.NGAY AS NGAY_LAP_PHIEU, CONVERT(DATETIME,T1.NGAY + CONVERT(TIME, T1.TU_GIO)) AS TU_NGAY, CONVERT(DATETIME,T1.DEN_NGAY + CONVERT(TIME, T1.DEN_GIO)) AS  DEN_NGAY, T4.CA, T1.TRUONG_CA, SUM(T1.THOI_GIAN_SUA_CHUA) AS TG_NM, SUM(T1.THOI_GIAN_SUA) AS TG_SUA, T1.HIEN_TUONG, T3.TEN_NGUYEN_NHAN, T1.NGUYEN_NHAN_CU_THE, 
                         T1.NGUOI_GIAI_QUYET, T2.MS_PHIEU_BAO_TRI, T1.GHI_CHU,T5.MS_LOAI_MAY, T5.TEN_LOAI_MAY,T5.MS_N_XUONG, T5.Ten_N_XUONG, T5.MS_HE_THONG, T5.TEN_HE_THONG, T5.MS_BP_CHIU_PHI, T5.TEN_BP_CHIU_PHI
FROM            dbo.THOI_GIAN_NGUNG_MAY AS T1 INNER JOIN
                         dbo.THOI_GIAN_NGUNG_MAY_SO_LAN AS T2 ON T1.MS_LAN = T2.MS_LAN INNER JOIN
                         dbo.NGUYEN_NHAN_DUNG_MAY AS T3 ON T1.MS_NGUYEN_NHAN = T3.MS_NGUYEN_NHAN INNER JOIN
                         dbo.CA AS T4 ON T1.CaID = T4.STT INNER JOIN #MAY_TMP T5 ON T1.MS_MAY = T5.MS_MAY
WHERE (T2.NGAY BETWEEN @TNgay AND @DNgay)
GROUP BY T1.MS_MAY,T5.TEN_MAY,T2.NGAY, T1.NGAY, T1.TU_GIO, T1.DEN_NGAY, T1.DEN_GIO, T1.HIEN_TUONG, T3.TEN_NGUYEN_NHAN, T1.NGUYEN_NHAN_CU_THE, T1.NGUOI_GIAI_QUYET, T2.MS_PHIEU_BAO_TRI, T1.GHI_CHU, T4.CA, T1.TRUONG_CA,T5.MS_LOAI_MAY, T5.TEN_LOAI_MAY,T5.MS_N_XUONG, T5.Ten_N_XUONG, T5.MS_HE_THONG, T5.TEN_HE_THONG, T5.MS_BP_CHIU_PHI, T5.TEN_BP_CHIU_PHI
) T1
 ORDER BY  NGAY_LAP_PHIEU, MS_MAY,HIEN_TUONG,TEN_NGUYEN_NHAN, MS_LOAI_MAY, TEN_LOAI_MAY, Ten_N_XUONG,  TEN_HE_THONG, TEN_BP_CHIU_PHI