

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spKiemNTChuaNhapSoLuong')
   exec('CREATE PROCEDURE spKiemNTChuaNhapSoLuong AS BEGIN SET NOCOUNT ON; END')
GO


ALTER PROC spKiemNTChuaNhapSoLuong
	@MsPBT NVARCHAR(100) = 'WO-201810001119'
AS

SELECT        TOP (1) T1.MS_PHIEU_BAO_TRI
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET AS T1 INNER JOIN
                         dbo.IC_PHU_TUNG AS T2 ON T1.MS_PT = T2.MS_PT INNER JOIN
                         dbo.LOAI_VT AS T3 ON T2.MS_LOAI_VT = T3.MS_LOAI_VT
WHERE        (ISNULL(T1.SL_TT, 0) = 0) AND (ISNULL(T1.GHI_CHU, N'') = N'') AND (T1.MS_PHIEU_BAO_TRI = @MsPBT) AND (T3.VAT_TU = 0)
UNION  
SELECT TOP 1 MS_PHIEU_BAO_TRI
FROM            dbo.PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG INNER JOIN
                         dbo.IC_PHU_TUNG ON dbo.PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG.MS_PT = dbo.IC_PHU_TUNG.MS_PT INNER JOIN
                         dbo.LOAI_VT ON dbo.IC_PHU_TUNG.MS_LOAI_VT = dbo.LOAI_VT.MS_LOAI_VT
WHERE (ISNULL(SL_TT, 0) = 0) AND (ISNULL(GHI_CHU, N'') = N'') AND MS_PHIEU_BAO_TRI= @MsPBT AND VAT_TU = 0