alter proc [dbo].[GetMAY_LOAI_BTPN_CHU_KY]
	@MS_MAY NVARCHAR(30),
	@MS_LOAI_BT INT
AS

SELECT M.MS_MAY,M.MS_LOAI_BT,M.NGAY_AD,M.CHU_KY,M.MS_DV_TG,M.RUN_TIME,M.MS_DVT_RT,D.TEN_DVT_RT,MOVEMENT ,M.NGAY_AD AS NGAY_CU, CONVERT (BIT,1) AS [UPDATE]
FROM MAY_LOAI_BTPN_CHU_KY M left JOIN DON_VI_TINH_RUN_TIME D ON M.MS_DVT_RT =D.MS_DVT_RT
WHERE MS_MAY=@MS_MAY AND MS_LOAI_BT=@MS_LOAI_BT ORDER BY M.NGAY_AD desc