IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sp_GetDSCapNhatChoPhieuBT')
   exec('CREATE PROCEDURE sp_GetDSCapNhatChoPhieuBT AS BEGIN SET NOCOUNT ON; END')
GO


ALTER PROCEDURE [dbo].[sp_GetDSCapNhatChoPhieuBT]
	@UserName NVARCHAR(50) = 'admin',
	@MS_PHIEU_BAO_TRI nvarchar(20) ='WO-201404000004',
	@MS_CV INT=58,
	@MS_BO_PHAN NVARCHAR(50)='01.04',
	@NNgu int = 0
AS
BEGIN
SELECT 
--CONVERT(BIT,0) AS CHONN,
T1.MS_PHIEU_BAO_TRI,
T1.MS_BO_PHAN,
CASE @NNgu WHEN 0 THEN T3.TEN_BO_PHAN WHEN 1 THEN ISNULL(NULLIF(T3.TEN_BO_PHAN_ANH,''),T3.TEN_BO_PHAN) ELSE ISNULL(NULLIF(T3.TEN_BO_PHAN_HOA,''),T3.TEN_BO_PHAN) END  AS TEN_BO_PHAN , 
CASE @NNgu WHEN 0 THEN T2.MO_TA_CV WHEN 1 THEN ISNULL(NULLIF(T2.MO_TA_CV_ANH,''),T2.MO_TA_CV) ELSE ISNULL(NULLIF(T2.MO_TA_CV_HOA,''),T2.MO_TA_CV) END  AS MO_TA_CV , T1.MS_CV
FROM            dbo.PHIEU_BAO_TRI_CONG_VIEC AS T1 INNER JOIN
                         dbo.CONG_VIEC AS T2 ON T1.MS_CV = T2.MS_CV INNER JOIN
                         dbo.CAU_TRUC_THIET_BI AS T3 ON T1.MS_BO_PHAN = T3.MS_BO_PHAN INNER JOIN
                         dbo.PHIEU_BAO_TRI AS T4 ON T1.MS_PHIEU_BAO_TRI = T4.MS_PHIEU_BAO_TRI AND T3.MS_MAY = T4.MS_MAY
WHERE (T1.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI)
AND NOT EXISTS ( SELECT * FROM dbo.PHIEU_BAO_TRI_CONG_VIEC T5
 WHERE T1.MS_PHIEU_BAO_TRI = T5.MS_PHIEU_BAO_TRI 
 AND T1.MS_BO_PHAN = T5.MS_BO_PHAN 
 AND T1.MS_CV = T5.MS_CV 
 AND MS_BO_PHAN = @MS_BO_PHAN
 AND MS_CV = @MS_CV)
ORDER BY ISNULL(T3.STT,9999), T1.MS_BO_PHAN, T3.TEN_BO_PHAN, T3.TEN_BO_PHAN_ANH, T3.TEN_BO_PHAN_HOA, T2.MO_TA_CV, T2.MO_TA_CV_ANH, T2.MO_TA_CV_HOA, T1.MS_CV
END

