
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sp_CapNhatNhanVienChoPhieuBT')
   exec('CREATE PROCEDURE sp_CapNhatNhanVienChoPhieuBT AS BEGIN SET NOCOUNT ON; END')
GO
--EXEC [sp_CapNhatNhanVienChoPhieuBT] 
ALTER PROCEDURE [dbo].[sp_CapNhatNhanVienChoPhieuBT]
	@MS_PhieuBaoTri nvarchar(20)='WO-201404000004',
	@MS_CV INT = 58,
	@MS_BO_PHAN nvarchar(40)='01.04',
	@sBT NVARCHAR(100) = 'CNNS_TMPadmin',
	@UName  NVARCHAR(100) = 'ADMIN',
	@NNgu int = 0
AS
BEGIN
CREATE TABLE #AAA(
	MS_BP NVARCHAR(50),MS_CV INT
) 
DECLARE @sSql NVARCHAR(500)
SET @sSql = 'INSERT INTO #AAA SELECT MS_BO_PHAN,MS_CV FROM '+ @sBT
EXEC( @sSql)

SET @sSql = 'DROP TABLE '+ @sBT
EXEC( @sSql)


SELECT DISTINCT T2.MS_PHIEU_BAO_TRI, T1.MS_CV,T1.MS_BP,T2.MS_CONG_NHAN
INTO #TEM5
FROM #AAA T1 ,(
SELECT * FROM dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU WHERE MS_PHIEU_BAO_TRI = @MS_PhieuBaoTri AND MS_BO_PHAN = @MS_BO_PHAN AND MS_CV = @MS_CV) T2 
WHERE NOT EXISTS (
	SELECT MS_PHIEU_BAO_TRI,MS_BO_PHAN,MS_CV,MS_CONG_NHAN FROM	dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU T3 WHERE T3.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI 
	AND T1.MS_BP = T3.MS_BO_PHAN AND T1.MS_CV = T3.MS_CV AND T2.MS_CONG_NHAN = T3.MS_CONG_NHAN
)
ORDER BY T2.MS_PHIEU_BAO_TRI, T1.MS_BP,T1.MS_CV,T2.MS_CONG_NHAN

SELECT DISTINCT T2.MS_PHIEU_BAO_TRI,
 T1.MS_CV,
 T1.MS_BP,
 T2.MS_CONG_NHAN,
 T2.NGAY,
 T2.TU_GIO,
 T2.DEN_NGAY,
 T2.DEN_GIO,
 T2.HOAN_THANH,
 T2.STT,
 T2.SO_GIO,
 T2.NGAY_KH,
 T2.TU_GIO_KH,
 T2.DEN_NGAY_KH,
 T2.DEN_GIO_KH,
 T2.TONG_GIO_KH
INTO #TEM4
FROM #AAA T1 ,(
SELECT * FROM dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET WHERE MS_PHIEU_BAO_TRI = @MS_PhieuBaoTri AND MS_BO_PHAN = @MS_BO_PHAN AND MS_CV = @MS_CV) T2 
WHERE NOT EXISTS (
	SELECT MS_PHIEU_BAO_TRI,MS_BO_PHAN,MS_CV,MS_CONG_NHAN FROM	dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET T3 WHERE T3.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI 
	AND T1.MS_BP = T3.MS_BO_PHAN AND T1.MS_CV = T3.MS_CV AND T2.MS_CONG_NHAN = T3.MS_CONG_NHAN
)
ORDER BY T2.MS_PHIEU_BAO_TRI, T1.MS_BP,T1.MS_CV,T2.MS_CONG_NHAN

INSERT INTO dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU
        ( MS_PHIEU_BAO_TRI ,
          MS_CV ,
          MS_BO_PHAN ,
          MS_CONG_NHAN
        )
		(SELECT T4.MS_PHIEU_BAO_TRI,T4.MS_CV,T4.MS_BP,T4.MS_CONG_NHAN FROM #TEM5 T4)

INSERT INTO dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET
        ( MS_PHIEU_BAO_TRI ,
          MS_CV ,
          MS_BO_PHAN ,
          MS_CONG_NHAN ,
          NGAY ,
          TU_GIO ,
          DEN_NGAY ,
          DEN_GIO ,
          HOAN_THANH ,
          STT ,
          SO_GIO ,
          NGAY_KH ,
          TU_GIO_KH ,
          DEN_NGAY_KH ,
          DEN_GIO_KH ,
          TONG_GIO_KH
        )
		(SELECT 
		T4.MS_PHIEU_BAO_TRI,
		T4.MS_CV,
		T4.MS_BP,
		T4.MS_CONG_NHAN,
		T4.NGAY,
		T4.TU_GIO,
		T4.DEN_NGAY,
		T4.DEN_GIO,
		T4.HOAN_THANH,
		T4.STT,
		T4.SO_GIO,
		T4.NGAY_KH,
		T4.TU_GIO_KH,
		T4.DEN_NGAY_KH,
		T4.DEN_GIO_KH,
		T4.TONG_GIO_KH 
		FROM #TEM4 T4)
END
