IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spInKeHoachTongThe')
   exec('CREATE PROCEDURE spInKeHoachTongThe AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROC [dbo].[spInKeHoachTongThe]
	@TNgay DATETIME ='11/01/2018',
	@DNgay DATETIME='11/05/2018',
	@MsNXuong nvarchar(50) ='-1',
	@MsHeThong INT =-1,
	@MsLoaiMay NVARCHAR (20) ='-1',
	@NhomMay NVARCHAR (20) ='-1',
	@MSMay NVARCHAR (100) ='-1',
	@sUser nvarchar(50) ='ADMIN',
	@LoaiIn INT =0, -- 0 CHUA : 1 BO QUA : -- 2 DA GQ
	@NNgu INT =0
AS

BEGIN
SELECT A.MS_MAY,A.TEN_LOAI_MAY INTO #MAY_USER FROM dbo.MGetMayUserNgay(@DNgay,@sUser,@MsNXuong,@MsHeThong,-1,@MsLoaiMay,@NhomMay,@MSMay, @NNgu) A  
--Chưa giải quyết
IF(@LoaiIn =0)
BEGIN
SELECT    DISTINCT    T1.MS_MAY, T3.TEN_LOAI_MAY,  T2.TEN_HANG_MUC, T2.MS_LOAI_BT,T4.MS_BO_PHAN,T4.TEN_BO_PHAN, T6.MO_TA_CV, 
CASE ISNULL(T1.THUE_NGOAI, 0) WHEN 0 THEN N'Nội bộ' ELSE 'Vendor' END AS THUE_NGOAI, T2.NGAY, T2.GHI_CHU 
FROM            dbo.KE_HOACH_TONG_CONG_VIEC AS T1 INNER JOIN
                         dbo.KE_HOACH_TONG_THE AS T2 ON T1.MS_MAY = T2.MS_MAY AND T1.HANG_MUC_ID = T2.HANG_MUC_ID INNER JOIN
                         #MAY_USER AS T3 ON T2.MS_MAY = T3.MS_MAY INNER JOIN
                         dbo.CONG_VIEC AS T6 ON T1.MS_CV = T6.MS_CV INNER JOIN 
						 dbo.CAU_TRUC_THIET_BI T4 ON T4.MS_MAY = T1.MS_MAY AND T4.MS_BO_PHAN = T1.MS_BO_PHAN
WHERE        (ISNULL( T1.KHONG_GQ,0) = 0) AND (ISNULL( T1.EOR_ID,'')='') AND (ISNULL(T1.MS_PHIEU_BAO_TRI,'')='') AND (ISNULL(T1.THUE_NGOAI,0)=0) AND (T2.NGAY BETWEEN @TNgay AND @DNgay) 
ORDER BY T1.MS_MAY,T4.MS_BO_PHAN
END
--bỏ qua
IF(@LoaiIn =1)
BEGIN
SELECT    DISTINCT    T1.MS_MAY, T3.TEN_LOAI_MAY, T2.TEN_HANG_MUC,T4.MS_BO_PHAN,T4.TEN_BO_PHAN, T6.MO_TA_CV, 
CASE ISNULL(T1.THUE_NGOAI, 0) WHEN 0 THEN N'Nội bộ' ELSE 'Vendor' END AS THUE_NGOAI, T2.NGAY, T2.GHI_CHU
FROM            dbo.KE_HOACH_TONG_CONG_VIEC AS T1 INNER JOIN
                         dbo.KE_HOACH_TONG_THE AS T2 ON T1.MS_MAY = T2.MS_MAY AND T1.HANG_MUC_ID = T2.HANG_MUC_ID INNER JOIN
                         #MAY_USER AS T3 ON T2.MS_MAY = T3.MS_MAY INNER JOIN
                         dbo.CONG_VIEC AS T6 ON T1.MS_CV = T6.MS_CV INNER JOIN 
						 dbo.CAU_TRUC_THIET_BI T4 ON T4.MS_MAY = T1.MS_MAY AND T4.MS_BO_PHAN = T1.MS_BO_PHAN
WHERE        (T1.KHONG_GQ = 1) AND (T1.EOR_ID IS NULL) AND (T1.MS_PHIEU_BAO_TRI IS NULL)
AND (T2.NGAY BETWEEN @TNgay AND @DNgay) AND  (T1.THUE_NGOAI = 1) 
ORDER BY T1.MS_MAY,T4.MS_BO_PHAN
END

--đã giải quyết
IF(@LoaiIn =2)
BEGIN
SELECT   DISTINCT     T1.MS_MAY, T3.TEN_LOAI_MAY, T2.TEN_HANG_MUC,T4.MS_BO_PHAN,T4.TEN_BO_PHAN, T6.MO_TA_CV, 
CASE ISNULL(T1.THUE_NGOAI, 0) WHEN 0 THEN N'Nội bộ' ELSE 'Vendor' END AS THUE_NGOAI, T2.NGAY, T2.GHI_CHU
FROM            dbo.KE_HOACH_TONG_CONG_VIEC AS T1 INNER JOIN
                         dbo.KE_HOACH_TONG_THE AS T2 ON T1.MS_MAY = T2.MS_MAY AND T1.HANG_MUC_ID = T2.HANG_MUC_ID INNER JOIN
                         #MAY_USER AS T3 ON T2.MS_MAY = T3.MS_MAY INNER JOIN
                         dbo.CONG_VIEC AS T6 ON T1.MS_CV = T6.MS_CV INNER JOIN 
						 dbo.CAU_TRUC_THIET_BI T4 ON T4.MS_MAY = T1.MS_MAY AND T4.MS_BO_PHAN = T1.MS_BO_PHAN
WHERE      ((ISNULL(T1.MS_PHIEU_BAO_TRI,'') <> '' OR ISNULL(T1.EOR_ID,'') <> ''))
AND (T2.NGAY BETWEEN @TNgay AND @DNgay)
ORDER BY T1.MS_MAY,T4.MS_BO_PHAN
END
END
