
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetLoaiBaoTri')
   exec('CREATE PROCEDURE spGetLoaiBaoTri AS BEGIN SET NOCOUNT ON; END')
GO


ALTER PROC [dbo].[spGetLoaiBaoTri]
AS
SELECT * FROM (
SELECT MS_LOAI_BT,TEN_LOAI_BT,1 AS LOAI FROM dbo.LOAI_BAO_TRI
UNION
SELECT MS_HT_BT,TEN_HT_BT,0 AS LOAI FROM dbo.HINH_THUC_BAO_TRI
UNION	SELECT -1,'< ALL >',-1
) T1 ORDER BY LOAI,T1.TEN_LOAI_BT