IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_Y_GET_TSGSTTDHKT_BAOCAO')  
exec('CREATE PROCEDURE SP_Y_GET_TSGSTTDHKT_BAOCAO AS BEGIN SET NOCOUNT ON; END')
GO

--exec [SP_Y_GET_TSGSTTDHKT_BAOCAO] 'administrator',0,'01/01/2018','01/30/2018',-1, -1,-1,-1,-1,-1,-1,-1 ,0
--exec [SP_Y_GET_TSGSTTDHKT_BAOCAO] 'administrator',0,'01/01/2018','01/30/2019',-1, -1,-1,-1,-1,-1,-1,-1 ,2
ALTER procedure [dbo].[SP_Y_GET_TSGSTTDHKT_BAOCAO]
	@USERNAME VARCHAR (64), 
	@LANGUAGE INT,
	@TU_NGAY DATETIME,
	@DEN_NGAY DATETIME,
	@MS_NHA_XUONG VARCHAR (50), 
	@MS_HE_THONG INT ,
	@MS_LOAI_MAY VARCHAR(30),
	@MS_MAY VARCHAR (30),
	@MS_TINH VARCHAR(50),
	@MS_QUAN VARCHAR(50),
	@MS_DUONG VARCHAR(50),
	@MS_LOAI_CV INT,
	@LOAIIN INT = 1
AS
BEGIN 
set fmtonly off 

SELECT * INTO #MAY_USER	FROM [dbo].[MGetMayUserNgay](@DEN_NGAY,@USERNAME,@MS_NHA_XUONG,@MS_HE_THONG,-1,@MS_LOAI_MAY,'-1',@MS_MAY,@LANGUAGE)


SELECT        T4.MS_TS_GSTT, 
CASE @LANGUAGE WHEN 0 THEN T4.TEN_TS_GSTT WHEN 1 THEN ISNULL(NULLIF(T4.TEN_TS_GSTT_ANH,''),T4.TEN_TS_GSTT) ELSE ISNULL(NULLIF(T4.TEN_TS_GSTT_HOA,''),T4.TEN_TS_GSTT) END AS	TEN_TS_GSTT
, T4.MS_DV_DO, T4.LOAI_TS, T4.GHI_CHU, T4.MS_BP_GSTT, T4.DUONG_DAN, T4.MS_LOAI_CV
INTO #THONG_SO_GSTT
FROM            dbo.NHOM_LOAI_CONG_VIEC AS T2 INNER JOIN
                         dbo.USERS AS T3 ON T2.GROUP_ID = T3.GROUP_ID INNER JOIN
                         dbo.THONG_SO_GSTT AS T4 ON T2.MS_LOAI_CV = T4.MS_LOAI_CV
WHERE (USERNAME = @USERNAME) AND (T4.MS_LOAI_CV = @MS_LOAI_CV OR @MS_LOAI_CV = -1) AND (ISNULL(T4.MS_LOAI_CV,'') <> '')

UNION

SELECT * FROM
(
SELECT T4.MS_TS_GSTT,
CASE @LANGUAGE WHEN 0 THEN T4.TEN_TS_GSTT WHEN 1 THEN ISNULL(NULLIF(T4.TEN_TS_GSTT_ANH,''),T4.TEN_TS_GSTT) ELSE ISNULL(NULLIF(T4.TEN_TS_GSTT_HOA,''),T4.TEN_TS_GSTT) END AS	TEN_TS_GSTT, 
T4.MS_DV_DO, T4.LOAI_TS, T4.GHI_CHU, T4.MS_BP_GSTT, T4.DUONG_DAN, ISNULL(T4.MS_LOAI_CV,-99) AS MS_LOAI_CV
FROM            dbo.THONG_SO_GSTT AS T4 
WHERE  (ISNULL(MS_LOAI_CV,'') = '')
) A WHERE (MS_LOAI_CV = @MS_LOAI_CV OR @MS_LOAI_CV = -1)

SELECT T2.STT , T1.MS_MAY , T1.MS_TS_GSTT , T1.MS_BO_PHAN,T1.MS_TT , T1.NGAY_KT_CUOI 
INTO #GIAM_SAT_TINH_TRANG_TS_TMP
FROM (
	SELECT     X.MS_MAY, X.MS_TS_GSTT,X.MS_TT, X.MS_BO_PHAN, 
	MAX(Y.NGAY_KT) AS NGAY_KT_CUOI
	FROM         dbo.GIAM_SAT_TINH_TRANG_TS X INNER JOIN
	(
		SELECT     STT, CONVERT(DATETIME, CONVERT(NVARCHAR(10), NGAY_KT, 101) + ' '+ CONVERT(NVARCHAR(8), GIO_KT, 108)) AS NGAY_KT
		FROM          dbo.GIAM_SAT_TINH_TRANG AS T
	) AS Y ON 
		X.STT = Y.STT
		GROUP BY X.MS_MAY, X.MS_TS_GSTT, X.MS_BO_PHAN,X.MS_TT 
) T1 INNER JOIN 
	(
SELECT     X.MS_MAY, X.MS_TS_GSTT, X.MS_BO_PHAN, X.MS_TT, 
	MAX(Y.NGAY_KT) AS NGAY_KT_CUOI, X.STT
	FROM         dbo.GIAM_SAT_TINH_TRANG_TS X INNER JOIN
	(SELECT     STT, CONVERT(DATETIME, CONVERT(NVARCHAR(10), NGAY_KT, 101) + ' '+ CONVERT(NVARCHAR(8), GIO_KT, 108)) AS NGAY_KT
	FROM          dbo.GIAM_SAT_TINH_TRANG AS T) AS Y ON 
	X.STT = Y.STT
	GROUP BY X.MS_MAY, X.MS_TS_GSTT, X.MS_BO_PHAN, 
	X.STT,X.MS_TT
) T2 ON T1.MS_MAY  = T2.MS_MAY AND T1.MS_TS_GSTT = T2.MS_TS_GSTT AND 
T1.MS_BO_PHAN = T2.MS_BO_PHAN AND T1.NGAY_KT_CUOI = T2.NGAY_KT_CUOI and T1.MS_TT = T2.MS_TT

--DINH TINH
SELECT DISTINCT CTTB.MS_MAY, T1.TEN_MAY, CTTB.MS_BO_PHAN + ' - ' + 
CASE @LANGUAGE WHEN 0 THEN CTTB.TEN_BO_PHAN WHEN 1 THEN CTTB.TEN_BO_PHAN_ANH ELSE CTTB.TEN_BO_PHAN_HOA END 
AS TEN_BO_PHAN ,GSTT.TEN_TS_GSTT, 
T2.MS_DV_TG , T3.NGAY_KT_CUOI, 
CASE T2.MS_DV_TG WHEN 1 THEN DATEADD(DAY, T2.CHU_KY_DO, 
T3.NGAY_KT_CUOI) WHEN 2 THEN DATEADD(DAY, 
T2.CHU_KY_DO * 7.25, T3.NGAY_KT_CUOI) 
WHEN 3 THEN DATEADD(MONTH, T2.CHU_KY_DO, 
T3.NGAY_KT_CUOI) WHEN 4 THEN DATEADD(YEAR, T2.CHU_KY_DO, 
T3.NGAY_KT_CUOI) END AS NGAY_KT_KE,T1.MS_N_XUONG ,
T3.MS_TS_GSTT,CTTB.MS_BO_PHAN
INTO #TEMP_DINH_TINH
FROM         dbo.CAU_TRUC_THIET_BI_TS_GSTT AS T2 INNER JOIN
                      #GIAM_SAT_TINH_TRANG_TS_TMP AS T3 ON T2.MS_MAY = T3.MS_MAY AND T2.MS_BO_PHAN = T3.MS_BO_PHAN AND 
                      T2.MS_TS_GSTT = T3.MS_TS_GSTT INNER JOIN
                      #THONG_SO_GSTT GSTT ON T2.MS_TS_GSTT = GSTT.MS_TS_GSTT INNER JOIN
                      dbo.CAU_TRUC_THIET_BI AS CTTB ON T2.MS_MAY = CTTB.MS_MAY AND T2.MS_BO_PHAN = CTTB.MS_BO_PHAN INNER JOIN
                      dbo.DON_VI_THOI_GIAN ON T2.MS_DV_TG = dbo.DON_VI_THOI_GIAN.MS_DV_TG INNER JOIN
                      #MAY_USER AS T1 ON CTTB.MS_MAY = T1.MS_MAY                      
WHERE GSTT.LOAI_TS = 1 AND T2.ACTIVE = 1
AND 
CONVERT(DATE,
CASE T2.MS_DV_TG 
	WHEN 1 THEN  DATEADD(DAY,T2.CHU_KY_DO,T3.NGAY_KT_CUOI)
	WHEN 2 THEN  DATEADD(WEEK,T2.CHU_KY_DO ,T3.NGAY_KT_CUOI)
	WHEN 3 THEN  DATEADD(MONTH,T2.CHU_KY_DO,T3.NGAY_KT_CUOI)
	WHEN 4 THEN  DATEADD(YEAR,T2.CHU_KY_DO,T3.NGAY_KT_CUOI) END) >=  DATEADD(DAY,-1,  @TU_NGAY )
AND 
CONVERT(DATE,
CASE T2.MS_DV_TG 
	WHEN 1 THEN  DATEADD(DAY,T2.CHU_KY_DO,T3.NGAY_KT_CUOI)
	WHEN 2 THEN  DATEADD(WEEK,T2.CHU_KY_DO ,T3.NGAY_KT_CUOI)
	WHEN 3 THEN  DATEADD(MONTH,T2.CHU_KY_DO,T3.NGAY_KT_CUOI)
	WHEN 4 THEN  DATEADD(YEAR,T2.CHU_KY_DO,T3.NGAY_KT_CUOI) END) <= @DEN_NGAY 



--DINH LUONG
SELECT DISTINCT
TEMP.MS_N_XUONG,TEMP.MS_MAY,TEMP.TEN_MAY, 
(SELECT TOP 1 ISNULL(TEN_BO_PHAN,'') FROM CAU_TRUC_THIET_BI WHERE MS_BO_PHAN = (
SELECT TOP 1 CASE  WHEN ISNULL(MS_BO_PHAN_CHA,'') = MS_MAY THEN MS_BO_PHAN ELSE MS_BO_PHAN_CHA END
  FROM CAU_TRUC_THIET_BI where MS_BO_PHAN = TEMP.MS_BO_PHAN AND MS_MAY = TEMP.MS_MAY)
AND MS_MAY = TEMP.MS_MAY) + ' - ' + 
TEMP.TEN_BO_PHAN AS TEN_BO_PHAN ,TEMP.TEN_TS_GSTT,TEMP.MS_DV_TG,TEMP.NGAY_KT_CUOI,
	   TEMP.NGAY_KT_KE,


CASE @LANGUAGE WHEN 0 THEN Ten_N_XUONG WHEN 1 THEN ISNULL(NULLIF(TEN_N_XUONG_A,''),Ten_N_XUONG) ELSE ISNULL(NULLIF(TEN_N_XUONG_H,''),Ten_N_XUONG) END AS	Ten_N_XUONG

INTO	#temptt
FROM
(
SELECT *  FROM #TEMP_DINH_TINH
UNION ALL
SELECT  DISTINCT
          CTTB.MS_MAY, 
          T1.TEN_MAY,
            CTTB.MS_BO_PHAN + ' - ' +
             CASE @LANGUAGE WHEN 0 THEN CTTB.TEN_BO_PHAN WHEN 1 THEN CTTB.TEN_BO_PHAN_ANH ELSE CTTB.TEN_BO_PHAN_HOA END 
AS TEN_BO_PHAN ,
           GSTT.TEN_TS_GSTT, CTTB_GSTT.MS_DV_TG , GSTT_TMP.NGAY_KT_CUOI, 
          CASE CTTB_GSTT.MS_DV_TG WHEN 1 THEN DATEADD(DAY, CTTB_GSTT.CHU_KY_DO, 
          GSTT_TMP.NGAY_KT_CUOI) WHEN 2 THEN DATEADD(DAY, 
          CTTB_GSTT.CHU_KY_DO * 7.25, GSTT_TMP.NGAY_KT_CUOI) 
          WHEN 3 THEN DATEADD(MONTH, CTTB_GSTT.CHU_KY_DO, 
          GSTT_TMP.NGAY_KT_CUOI) WHEN 4 THEN DATEADD(YEAR, CTTB_GSTT.CHU_KY_DO, 
          GSTT_TMP.NGAY_KT_CUOI) END AS NGAY_KT_KE, T1.MS_N_XUONG ,CTTB_GSTT.MS_TS_GSTT,CTTB.MS_BO_PHAN
FROM         dbo.CAU_TRUC_THIET_BI_TS_GSTT CTTB_GSTT INNER JOIN
      #THONG_SO_GSTT GSTT ON CTTB_GSTT.MS_TS_GSTT = GSTT.MS_TS_GSTT INNER JOIN
      dbo.CAU_TRUC_THIET_BI CTTB ON CTTB_GSTT.MS_MAY = CTTB.MS_MAY AND 
      CTTB_GSTT.MS_BO_PHAN = CTTB.MS_BO_PHAN INNER JOIN
      dbo.DON_VI_THOI_GIAN ON CTTB_GSTT.MS_DV_TG = dbo.DON_VI_THOI_GIAN.MS_DV_TG INNER JOIN
      #MAY_USER T1 ON CTTB.MS_MAY = T1.MS_MAY INNER JOIN
    
      #GIAM_SAT_TINH_TRANG_TS_TMP GSTT_TMP ON CTTB_GSTT.MS_MAY = GSTT_TMP.MS_MAY AND 
      CTTB_GSTT.MS_BO_PHAN = GSTT_TMP.MS_BO_PHAN AND 
      CTTB_GSTT.MS_TS_GSTT = GSTT_TMP.MS_TS_GSTT INNER JOIN
      dbo.GIAM_SAT_TINH_TRANG_TS ON CTTB_GSTT.MS_MAY = dbo.GIAM_SAT_TINH_TRANG_TS.MS_MAY AND 
      CTTB_GSTT.MS_BO_PHAN = dbo.GIAM_SAT_TINH_TRANG_TS.MS_BO_PHAN AND 
      CTTB_GSTT.MS_TS_GSTT = dbo.GIAM_SAT_TINH_TRANG_TS.MS_TS_GSTT AND 
      CTTB_GSTT.MS_TT = dbo.GIAM_SAT_TINH_TRANG_TS.MS_TT
WHERE GSTT.LOAI_TS =0  AND CTTB_GSTT.ACTIVE=1
AND 
CONVERT(DATE,
CASE CTTB_GSTT.MS_DV_TG 
	WHEN 1 THEN  DATEADD(DAY,CTTB_GSTT.CHU_KY_DO,GSTT_TMP.NGAY_KT_CUOI)
	WHEN 2 THEN  DATEADD(DAY,CTTB_GSTT.CHU_KY_DO * 7.25,GSTT_TMP.NGAY_KT_CUOI)
	WHEN 3 THEN  DATEADD(MONTH,CTTB_GSTT.CHU_KY_DO,GSTT_TMP.NGAY_KT_CUOI)
	WHEN 4 THEN  DATEADD(YEAR,CTTB_GSTT.CHU_KY_DO,GSTT_TMP.NGAY_KT_CUOI) END) >= DATEADD(DAY,-1,  @TU_NGAY ) 
AND 
CONVERT(DATE,
CASE CTTB_GSTT.MS_DV_TG 
	WHEN 1 THEN  DATEADD(DAY,CTTB_GSTT.CHU_KY_DO,GSTT_TMP.NGAY_KT_CUOI)
	WHEN 2 THEN  DATEADD(DAY,CTTB_GSTT.CHU_KY_DO * 7.25,GSTT_TMP.NGAY_KT_CUOI)
	WHEN 3 THEN  DATEADD(MONTH,CTTB_GSTT.CHU_KY_DO,GSTT_TMP.NGAY_KT_CUOI)
	WHEN 4 THEN  DATEADD(YEAR,CTTB_GSTT.CHU_KY_DO,GSTT_TMP.NGAY_KT_CUOI) END) <= @DEN_NGAY 

)TEMP INNER JOIN NHA_XUONG ON NHA_XUONG.MS_N_XUONG = TEMP.MS_N_XUONG

-- bao cao theo nam
IF(@LOAIIN = 2)
BEGIN
SELECT 
 pvt.* into #TMP2 FROM 
(SELECT T1.Ten_N_XUONG AS MS_N_XUONG ,T1.MS_MAY,T1.TEN_MAY,T1.TEN_BO_PHAN,T1.TEN_TS_GSTT,T1.NGAY_KT_KE,convert(NVARCHAR(5),month(T1.NGAY_KT_KE)) AS THANG,T1.MS_DV_TG FROM #temptt T1)
 A
		PIVOT
		(
			COUNT(A.NGAY_KT_KE)
			FOR A.THANG IN ([1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12])
		)AS pvt	
		UPDATE #TMP2 SET [1] = NULL WHERE [1] = 0
		UPDATE #TMP2 SET [2] = NULL WHERE [2] = 0
		UPDATE #TMP2 SET [3] = NULL WHERE [3] = 0
		UPDATE #TMP2 SET [4] = NULL WHERE [4] = 0
		UPDATE #TMP2 SET [5] = NULL WHERE [5] = 0
		UPDATE #TMP2 SET [6] = NULL WHERE [6] = 0
		UPDATE #TMP2 SET [7] = NULL WHERE [7] = 0
		UPDATE #TMP2 SET [8] = NULL WHERE [8] = 0
		UPDATE #TMP2 SET [9] = NULL WHERE [9] = 0
		UPDATE #TMP2 SET [10] = NULL WHERE [10] = 0
		UPDATE #TMP2 SET [11] = NULL WHERE [11] = 0
		UPDATE #TMP2 SET [12] = NULL WHERE [12] = 0
		SELECT MS_N_XUONG ,MS_MAY,TEN_MAY,TEN_BO_PHAN,TEN_TS_GSTT, [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], CONVERT(NVARCHAR(10),ISNULL([R],0)) + ',' + CONVERT(NVARCHAR(10),ISNULL([G],0)) + ',' +  CONVERT(NVARCHAR(10),ISNULL([B],0)) AS [CL]  FROM #TMP2 T1 LEFT JOIN dbo.DON_VI_THOI_GIAN_MAU T2 ON T1.MS_DV_TG = T2.MS_DV_TG ORDER BY MS_N_XUONG ,MS_MAY,TEN_MAY,TEN_BO_PHAN

END
-- bao cao theo thang
ELSE
BEGIN
DECLARE @TN DATE;
SET @TN =  @TU_NGAY;
DECLARE @DN DATE;
SET @DN =  @DEN_NGAY; 
DECLARE @sSql NVARCHAR(max)
DECLARE @sSqlL NVARCHAR(max)
DECLARE @sSqlUpdate NVARCHAR(max) =''
SET @sSql =''
WHILE @TN < = @DN
BEGIN
   SET @sSql = @sSql + ' ['+ CAST(CONVERT(varchar, @TN, 103) AS NVARCHAR(20)) +'],';
   SET @sSqlUpdate =@sSqlUpdate + 'UPDATE #TMP1 SET ['+ CAST(CONVERT(varchar, @TN, 103) AS NVARCHAR(20)) +'] = NULL WHERE ['+ CAST(CONVERT(varchar,@TN, 103) AS NVARCHAR(20)) +'] = 0; ';
   SET @TN = DATEADD(day,1,@TN);
END


SET @sSql =  LEFT(@sSql,LEN(@sSql) - 1) 

SET @sSqlL ='SELECT pvt.* into #TMP1 FROM 
(SELECT T1.Ten_N_XUONG AS MS_N_XUONG,T1.MS_MAY,T1.TEN_MAY,T1.TEN_BO_PHAN,T1.TEN_TS_GSTT,T1.NGAY_KT_KE, CONVERT(varchar, T1.NGAY_KT_KE, 103) AS NGAY,MS_DV_TG FROM #temptt T1)
 A
		PIVOT
		(
			COUNT(A.NGAY_KT_KE)
			FOR A.NGAY IN ('+@sSql+')
		)AS pvt
		'+@sSqlUpdate+'
		
		SELECT MS_N_XUONG ,MS_MAY,TEN_MAY,TEN_BO_PHAN,TEN_TS_GSTT, ' + @sSql + ',		
		CONVERT(NVARCHAR(10),ISNULL([R],0)) + '','' + CONVERT(NVARCHAR(10),ISNULL([G],0)) + '','' + CONVERT(NVARCHAR(10),ISNULL([B],0)) AS [CL]   FROM #TMP1 T1 LEFT JOIN dbo.DON_VI_THOI_GIAN_MAU T2 ON T1.MS_DV_TG = T2.MS_DV_TG ORDER BY MS_N_XUONG ,MS_MAY,TEN_MAY,TEN_BO_PHAN'
EXEC(@sSqlL)

END
END