IF NOT EXISTS(SELECT *	FROM	sys.objects WHERE type='P' AND name='spGetBCGSTTDenHanKiemTraVF')
EXEC('CREATE PROCEDURE spGetBCGSTTDenHanKiemTraVF AS BEGIN SET NOCOUNT ON; END');
GO


IF  EXISTS(SELECT *	FROM	sys.objects WHERE type='P' AND name='SP_Y_GET_TSGSTTDHKT_BAOCAO_VIFON')
EXEC('DROP PROCEDURE  SP_Y_GET_TSGSTTDHKT_BAOCAO_VIFON ');
GO
--	exec [spGetBCGSTTDenHanKiemTraVF] 'admin',1,'03/17/2019','03/23/2019','-1', -1,-1,'-1','-1',-1,-1,1

ALTER PROCEDURE [dbo].[spGetBCGSTTDenHanKiemTraVF] 
	@UserName NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@TuNgay DATETIME =  '03/01/2019',
	@DenNgay DATETIME = '03/31/2019',
	@MsNhaXuong NVARCHAR(50) ='-1',
	@MsHeThong INT =-1,
	@MsBPCP INT =-1,
	@MsLoaiMay NVARCHAR(30) ='-1',
	@MsNhomMay NVARCHAR(30) ='-1',
	@MsMay NVARCHAR(30) ='-1',
	@MsLoaiCV INT =-1,
	@LoaiIn INT = 1
AS
-- LoaiIn = 1 bao cao theo ngày tháng
-- LoaiIn = 2 bao cao theo nam
BEGIN
	SET FMTONLY OFF;

	SELECT	MS_MAY, T1.Ten_N_XUONG, T1.MS_N_XUONG
	INTO	#MAY_USER
	FROM	[dbo].[MGetMayUserNgay](@DenNgay, @UserName, @MsNhaXuong, @MsHeThong, @MsBPCP, @MsLoaiMay, @MsNhomMay, @MsMay, @NNgu) T1;
	

	SELECT	DISTINCT T2.MS_N_XUONG,T1.TEN_MAY,T1.MS_MAY,T1.MS_DV_TG,T1.CHU_KY_DO, T1.TEN_DV_TG ,T1.NGAY_CUOI AS NGAY_KT_CUOI, T1.NGAY_KE AS NGAY_KT_KE,T2.Ten_N_XUONG
	INTO	#GSTT_DH
	FROM	dbo.MGetHieuChuanKeGSTT(@TuNgay, @DenNgay, @UserName, @MsNhaXuong, @MsHeThong, @MsBPCP, @MsLoaiMay, @MsNhomMay, @MsLoaiCV, 1, @NNgu) T1
				INNER JOIN #MAY_USER T2 ON T1.MS_MAY=T2.MS_MAY
	WHERE CONVERT(DATE, T1.NGAY_KE) BETWEEN CONVERT(DATE, @TuNgay)AND CONVERT(DATE, @DenNgay);

	SELECT	DISTINCT T1.MS_N_XUONG,T1.TEN_MAY,T1.MS_MAY,T1.MS_DV_TG,RTRIM(CONVERT(CHAR(10), T1.CHU_KY_DO))+' '+ T1.TEN_DV_TG AS CHU_KY_DO, NGAY_KT_CUOI, NGAY_KT_KE,Ten_N_XUONG,CONVERT(NVARCHAR(5), MONTH(NGAY_KT_KE)) AS THANG
	INTO	#GSTT
	FROM	#GSTT_DH T1 INNER JOIN 
				(SELECT DISTINCT T1.MS_MAY FROM dbo.CAU_TRUC_THIET_BI_TS_GSTT  T1  WHERE T1.ACTIVE=1)  T2 ON T2.MS_MAY=T1.MS_MAY 
	


	--bao cao theo nam
	IF(@LoaiIn=2)BEGIN
		SELECT	PVT.*
		INTO	#TMP2
		FROM
		(
		SELECT		T1.Ten_N_XUONG AS MS_N_XUONG, T1.MS_MAY, T1.TEN_MAY, T1.MS_DV_TG, T1.CHU_KY_DO, T1.NGAY_KT_CUOI, T1.NGAY_KT_KE, THANG AS THANG
			FROM	#GSTT T1
		) A
		PIVOT
		(
		COUNT(A.NGAY_KT_KE)
			FOR A.THANG IN([1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12])
		) AS PVT;


				UPDATE  #TMP2 SET [1] = NULL WHERE   [1] = 0
				UPDATE  #TMP2 SET [2] = NULL WHERE   [2] = 0
				UPDATE  #TMP2 SET [3] = NULL WHERE   [3] = 0
				UPDATE  #TMP2 SET [4] = NULL WHERE   [4] = 0
				UPDATE  #TMP2 SET [5] = NULL WHERE   [5] = 0
				UPDATE  #TMP2 SET [6] = NULL WHERE   [6] = 0
				UPDATE  #TMP2 SET [7] = NULL WHERE   [7] = 0
				UPDATE  #TMP2 SET [8] = NULL WHERE   [8] = 0
				UPDATE  #TMP2 SET [9] = NULL WHERE   [9] = 0
				UPDATE  #TMP2 SET [10] = NULL WHERE   [10] = 0
				UPDATE  #TMP2 SET [11] = NULL WHERE   [11] = 0
				UPDATE  #TMP2 SET [12] = NULL WHERE   [12] = 0
				              
		SELECT	MS_N_XUONG, MS_MAY, TEN_MAY, CHU_KY_DO, NGAY_KT_CUOI, [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], CONVERT(NVARCHAR(10), ISNULL([R], 0))+','+CONVERT(NVARCHAR(10), ISNULL([G], 0))+','+CONVERT(NVARCHAR(10), ISNULL([B], 0)) AS [CL]
		FROM	#TMP2 T1 LEFT JOIN dbo.DON_VI_THOI_GIAN_MAU T2 ON T1.MS_DV_TG=T2.MS_DV_TG;
	END;
	ELSE 
	BEGIN
		
		DECLARE @sSql NVARCHAR(MAX);
		DECLARE @sSqlL NVARCHAR(MAX);		
		DECLARE @sSqlSelect NVARCHAR(MAX) = ''

		SELECT @sSql = COALESCE(ISNULL(@sSql,'') + CASE LEN(@sSql) WHEN 0 THEN '' ELSE ',' END , '') + ISNULL(NGAY,'')  ,
				@sSqlSelect = COALESCE(ISNULL(@sSqlSelect,'') + CASE LEN(@sSqlSelect) WHEN 0 THEN '' ELSE ',' END , '') + 
					' CASE ' + NGAY + ' WHEN 0 THEN NULL ELSE ' + NGAY + ' END AS '  + NGAY
		 FROM 
		(
		SELECT DISTINCT number,
		N' [' +CONVERT(NVARCHAR(10), DATEADD(day,number,@TuNgay),103)+N']'  AS NGAY
		 from master..spt_values where number between 0 and 1000 AND DATEADD(day,number,@TuNgay) <= @DenNgay
		 ) T1
		 SET @sSql= SUBSTRING(@sSql,2,LEN(@sSql)-1 );
	

		SET @sSqlL=N'SELECT pvt.* into #TMP1 FROM 
(SELECT T1.Ten_N_XUONG AS MS_N_XUONG,T1.MS_MAY,T1.TEN_MAY,T1.NGAY_KT_KE, ISNULL(CONVERT(NVARCHAR, T1.NGAY_KT_KE, 103),0) AS NGAY,T1.CHU_KY_DO,T1.NGAY_KT_CUOI,T1.MS_DV_TG FROM #GSTT T1)
 A
		PIVOT
		(
			COUNT(A.NGAY_KT_KE)
			FOR A.NGAY IN ('+@sSql+N')
		)AS pvt
		
		SELECT MS_N_XUONG ,MS_MAY,TEN_MAY,CHU_KY_DO,NGAY_KT_CUOI, '+@sSqlSelect+N',		
		CONVERT(NVARCHAR(10),ISNULL([R],0)) + '','' + CONVERT(NVARCHAR(10),ISNULL([G],0)) + '','' + CONVERT(NVARCHAR(10),ISNULL([B],0)) AS [CL]   FROM #TMP1 T1 LEFT JOIN dbo.DON_VI_THOI_GIAN_MAU T2 ON T1.MS_DV_TG = T2.MS_DV_TG ORDER BY MS_N_XUONG ,MS_MAY,TEN_MAY';

		EXEC(@sSqlL);
	END;
END;