IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCheckMayExist')
   exec('CREATE PROCEDURE spCheckMayExist AS BEGIN SET NOCOUNT ON; END')
GO


ALTER PROC [dbo].spCheckMayExist
	@MsMay NVARCHAR(50) = N'AIC-00011'
AS 


SELECT TOP 1 COUNT(MS_MAY) AS SL FROM dbo.MAY	WHERE MS_MAY = @MsMay
UNION
SELECT TOP 1 COUNT(MS_MAY) AS SL FROM dbo.MAY_NHA_XUONG	WHERE MS_MAY = @MsMay
UNION
SELECT TOP 1 COUNT(MS_MAY) AS SL FROM dbo.MAY_HE_THONG	WHERE MS_MAY = @MsMay
UNION
SELECT TOP 1 COUNT(MS_MAY) AS SL FROM dbo.MAY_BO_PHAN_CHIU_PHI	WHERE MS_MAY = @MsMay