IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ReportTGNM')
exec('CREATE PROCEDURE ReportTGNM AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE ReportTGNM
	@Tu_Ngay DATE = '01/01/2019',
	@Den_Ngay DATE = '11/30/2018',
	@HeThong INT = 22,
	@sbTGNN NVARCHAR(100) ='TGNMAdmin'
AS
BEGIN
CREATE TABLE #BTGT 
(
	[MS_NGUYEN_NHAN] [int] NULL,
	[TEN_NGUYEN_NHAN] [nvarchar] (500),
)
DECLARE @sSql	NVARCHAR(MAX)
SET @sSql	= 'INSERT INTO #BTGT( MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN ) SELECT MS_NGUYEN_NHAN,TEN_NGUYEN_NHAN FROM '+@sbTGNN
EXEC (@sSql)

DECLARE @Weekcount INT 
SET @Weekcount = (SELECT COUNT(*) from MGetWeeksOfMonth(@Tu_Ngay,0))

--Tạo table chứa từ ngày đến ngày
SELECT convert(DATETIME,CONVERT(NVARCHAR(2), x.number) + '/' + CONVERT(NVARCHAR(2),MONTH(@Tu_Ngay))+ '/' + CONVERT(NVARCHAR(4),YEAR(@Tu_Ngay)) + ' 00:00:00',104) AS NGAY_THANG INTO #NGAY FROM master.dbo.spt_values x WHERE   x.type = 'P' AND  x.number BETWEEN DAY(@Tu_Ngay) AND	DAY(@Den_Ngay)

--tạo table chứa hết nguyên nhân dưng máy theo all ngày
  SELECT NGAY_THANG,T1.MS_NGUYEN_NHAN,TEN_NGUYEN_NHAN, CONVERT(FLOAT,0) AS TGNM INTO #TGNM 
  FROM #NGAY, #BTGT T1 
  ORDER BY NGAY_THANG,TEN_NGUYEN_NHAN

--tao table NNNM theo điều kiện chọn
SELECT T1.NGAY,T1.THOI_GIAN_SUA,T1.MS_NGUYEN_NHAN INTO #TGNGUNG FROM dbo.THOI_GIAN_NGUNG_MAY T1 INNER JOIN dbo.THOI_GIAN_NGUNG_MAY_SO_LAN T2 ON T2.MS_LAN = T1.MS_LAN
 WHERE CONVERT(DATE,T1.NGAY) BETWEEN @Tu_Ngay AND @Den_Ngay AND MS_HE_THONG = @HeThong AND  ISNULL(T2.KHONG_DC,0) = 0

--table chứa all du liệu TGNM
SELECT ISNULL(CONVERT(NVARCHAR(2), DAY(T1.NGAY_THANG)),0) AS NGAY,T1.MS_NGUYEN_NHAN,T1.TEN_NGUYEN_NHAN, NULLIF(SUM(T2.THOI_GIAN_SUA),0) AS TGNM 
INTO #TMP	
FROM #TGNM T1 LEFT JOIN #TGNGUNG T2 ON T1.NGAY_THANG = T2.NGAY AND T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN

GROUP BY NGAY_THANG,T1.MS_NGUYEN_NHAN,T1.TEN_NGUYEN_NHAN

UNION
SELECT ISNULL(CONVERT(NVARCHAR(2), DAY(T1.NGAY_THANG)),0) AS NGAY,9998 AS MS_NGUYEN_NHAN,N'Shutdown total (minutes)' AS TEN_NGUYEN_NHAN, NULLIF(SUM(T2.THOI_GIAN_SUA),0) AS TGNM FROM #TGNM T1 LEFT JOIN #TGNGUNG T2 ON T1.NGAY_THANG = T2.NGAY AND T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN
GROUP BY NGAY_THANG

UNION
--nếu sum thời gian sửa chữa lớn hơn 0 thì(lấy giờ kế hoạch nếu tồn tại không thì lấy 24) ngược lại là null
SELECT ISNULL(CONVERT(NVARCHAR(2), DAY(T1.NGAY_THANG)),0) AS NGAY,9999 AS MS_NGUYEN_NHAN,N'Schedule Run (Hours)' AS TEN_NGUYEN_NHAN, 
CASE  WHEN NULLIF(SUM(T2.THOI_GIAN_SUA),0)  > 0 THEN 
CASE WHEN ISNULL(GIO_KH,0) = 0 THEN 24 ELSE GIO_KH END
ELSE NULL END AS TGNM 
FROM #TGNM T1 LEFT JOIN #TGNGUNG T2 ON T1.NGAY_THANG = T2.NGAY AND T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN LEFT JOIN (SELECT * FROM dbo.KHSX_NGAY WHERE NGAY BETWEEN @Tu_Ngay AND @Den_Ngay AND MS_HE_THONG = @HeThong) T3 ON T1.NGAY_THANG = T3.NGAY AND ISNULL(T3.LOAI,0) = 0
GROUP BY NGAY_THANG,GIO_KH


		DECLARE @TGIOCHAY DECIMAL(10,2) = 0
		DECLARE @TGIONGUNG DECIMAL(10,2) = 0
		SELECT @TGIOCHAY  = SUM(TGNM) FROM #TMP WHERE MS_NGUYEN_NHAN = 9999
		SELECT @TGIONGUNG = NULLIF(  CONVERT(DECIMAL(10,2), SUM(TGNM)/60 ) ,0 )   FROM #TMP	 WHERE MS_NGUYEN_NHAN = 9998
		 
		SELECT CASE WHEN MS_NGUYEN_NHAN IN (9999,9998) THEN MS_NGUYEN_NHAN ELSE	ROW_NUMBER() OVER(ORDER BY TEN_NGUYEN_NHAN) END AS STT,
		pvt.* FROM (
			SELECT t1.MS_NGUYEN_NHAN,T1.TEN_NGUYEN_NHAN,T1.TGNM,T1.NGAY FROM #TMP T1
			UNION
			SELECT MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN, CASE WHEN MS_NGUYEN_NHAN = 9999 THEN NULL ELSE NULLIF(SUM(TGNM),0) END AS TGNM, 35 AS NGA FROM #TMP	GROUP BY MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN
			UNION
			SELECT MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN,  
			CASE WHEN MS_NGUYEN_NHAN = 9999 THEN  NULLIF(@TGIOCHAY,0) ELSE NULLIF(CONVERT(DECIMAL(10,2), SUM(TGNM)/60 ),0)  END	AS TGNM, 36 AS NGA FROM #TMP GROUP BY MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN 

			UNION
			SELECT MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN,  
			CASE WHEN MS_NGUYEN_NHAN = 9999 THEN NULLIF(CONVERT(DECIMAL(10,5), @TGIONGUNG/@TGIOCHAY),0) ELSE NULLIF( CONVERT(DECIMAL(10,5), SUM(TGNM)/60 / @TGIOCHAY),0)  END	
			AS TGNM, 37 AS NGA  FROM #TMP	 GROUP BY MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN 
			
		)
		 A PIVOT
		(
			SUM(A.TGNM) FOR A.NGAY IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20],[21],[22],[23],[24],[25],[26],[27],[28],[29],[30],[31], [35], [36], [37])
		) AS pvt
			ORDER BY STT	

-- SUM THEO TONG TGNM
SELECT TT,Week ,WeekStart ,WeekEnd,CONVERT(DECIMAL(10,2),NULL) AS TGNM INTO	#TMP1 FROM  MGetWeeksOfMonth(@Tu_Ngay,1)
UNION
SELECT 0,Week ,WeekStart ,WeekEnd ,NULL   FROM (
SELECT  TOP 1 TT ,Week ,WeekStart ,WeekEnd   FROM  MGetWeeksOfMonth(DATEADD(MONTH,-1,@Tu_Ngay),1)  ORDER BY  tt DESC) A


DECLARE @TNgay DATE,@DNgay Date
DECLARE @TT INT
DECLARE TNNM CURSOR
FOR
	SELECT WeekStart , WeekEnd ,TT  FROM #TMP1 ORDER BY TT
OPEN  TNNM
FETCH NEXT FROM TNNM INTO @TNgay, @DNgay,@TT
WHILE @@FETCH_STATUS = 0
    BEGIN
		UPDATE #TMP1 SET TGNM = (SELECT SUM(THOI_GIAN_SUA) AS TGS FROM dbo.THOI_GIAN_NGUNG_MAY T1
		INNER JOIN #BTGT T2 ON T2.MS_NGUYEN_NHAN = T1.MS_NGUYEN_NHAN
		WHERE CONVERT(DATE,NGAY) BETWEEN @TNgay AND @DNgay AND MS_HE_THONG = @HeThong) WHERE TT = @TT
        FETCH NEXT FROM TNNM INTO  @TNgay, @DNgay ,@TT
    END

CLOSE  TNNM
DEALLOCATE TNNM

IF(@Weekcount > 5)
	SELECT 
		pvt.* FROM (
		SELECT TT,TGNM FROM #TMP1
		) A PIVOT
		(
			SUM(A.TGNM) FOR A.TT IN ([0],[1],[2],[3],[4],[5],[6])
		) AS pvt

ELSE	

		SELECT 
		pvt.* FROM (
		SELECT TT,TGNM FROM #TMP1
		) A PIVOT
		(
			SUM(A.TGNM) FOR A.TT IN ([0],[1],[2],[3],[4],[5])
		) AS pvt		

 --SUM THEO NGUYEN NHAN
SELECT TT,MS_NGUYEN_NHAN,TEN_NGUYEN_NHAN,CONVERT(DECIMAL(10,2),NULL) AS TGNM INTO #NNNM  FROM #BTGT ,#TMP1 ORDER BY TT
DECLARE TNNM1 CURSOR
FOR
	SELECT WeekStart , WeekEnd ,TT  FROM #TMP1 ORDER BY TT
OPEN  TNNM1
FETCH NEXT FROM TNNM1 INTO @TNgay, @DNgay,@TT
WHILE @@FETCH_STATUS = 0
    BEGIN
		
		UPDATE #NNNM  SET TGNM = TGS FROM #NNNM  T1 INNER JOIN 
		(SELECT SUM(THOI_GIAN_SUA) AS TGS,MS_NGUYEN_NHAN FROM dbo.THOI_GIAN_NGUNG_MAY WHERE	CONVERT(DATE,NGAY) BETWEEN @TNgay AND @DNgay AND MS_HE_THONG = @HeThong GROUP BY MS_NGUYEN_NHAN) T2 ON T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN WHERE TT = @TT
        FETCH NEXT FROM TNNM1 INTO  @TNgay, @DNgay ,@TT
    END

CLOSE  TNNM1
DEALLOCATE TNNM1
IF(@Weekcount > 5)
	SELECT 
		pvt.* FROM (
		SELECT TT,TGNM,TEN_NGUYEN_NHAN FROM #NNNM
		) A PIVOT
		(
			SUM(A.TGNM) FOR A.TT IN ([0],[1],[2],[3],[4],[5],[6])
		) AS pvt
		ORDER BY TEN_NGUYEN_NHAN	

ELSE
SELECT 
		pvt.* FROM (
		SELECT TT,TGNM,TEN_NGUYEN_NHAN FROM #NNNM
		) A PIVOT
		(
			SUM(A.TGNM) FOR A.TT IN ([0],[1],[2],[3],[4],[5])
		) AS pvt
		ORDER BY TEN_NGUYEN_NHAN	
END

--ReportTGNM