IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ReportTGNM')
exec('CREATE PROCEDURE ReportTGNM AS BEGIN SET NOCOUNT ON; END')
GO
--SELECT TOP 1 * FROM dbo.PHIEU_BAO_TRI ORDER BY NGAY_BD_KH DESC	
ALTER PROCEDURE ReportTGNM
	@Tu_Ngay DATE = '11/01/2018',
	@Den_Ngay DATE = '11/30/2018',
	@HeThong INT = 13
AS 
BEGIN
	

--Tạo table chứa từ ngày đến ngày
SELECT convert(DATETIME,CONVERT(NVARCHAR(2), x.number) + '/' + CONVERT(NVARCHAR(2),MONTH(@Tu_Ngay))+ '/' + CONVERT(NVARCHAR(4),YEAR(@Tu_Ngay)) + ' 00:00:00',104) AS NGAY_THANG INTO #NGAY
 FROM master.dbo.spt_values x WHERE   x.type = 'P' AND  x.number BETWEEN DAY(@Tu_Ngay) AND	DAY(@Den_Ngay)

--tạo table chứa hết nguyên nhân dưng máy theo all ngày
  SELECT NGAY_THANG,MS_NGUYEN_NHAN,TEN_NGUYEN_NHAN, CONVERT(FLOAT,0) AS TGNM INTO #TGNM FROM #NGAY, dbo.NGUYEN_NHAN_DUNG_MAY ORDER BY NGAY_THANG,TEN_NGUYEN_NHAN

--tao table NNNM theo điều kiện chọn
SELECT * INTO #TGNGUNG FROM dbo.THOI_GIAN_NGUNG_MAY WHERE CONVERT(DATE,NGAY) BETWEEN @Tu_Ngay AND @Den_Ngay AND MS_HE_THONG = @HeThong

--table chứa all du liệu TGNM
SELECT ISNULL(CONVERT(NVARCHAR(2), DAY(T1.NGAY_THANG)),0) AS NGAY,T1.MS_NGUYEN_NHAN,T1.TEN_NGUYEN_NHAN, NULLIF(SUM(T2.THOI_GIAN_SUA),0) AS TGNM 
INTO #TMP	
FROM #TGNM T1 LEFT JOIN #TGNGUNG T2 ON T1.NGAY_THANG = T2.NGAY AND T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN
GROUP BY NGAY_THANG,T1.MS_NGUYEN_NHAN,T1.TEN_NGUYEN_NHAN

UNION
SELECT ISNULL(CONVERT(NVARCHAR(2), DAY(T1.NGAY_THANG)),0) AS NGAY,9998 AS MS_NGUYEN_NHAN,N'Shutdown total (minutes)' AS TEN_NGUYEN_NHAN, NULLIF(ISNULL(SUM(T2.THOI_GIAN_SUA),0),0) AS TGNM FROM #TGNM T1 LEFT JOIN #TGNGUNG T2 ON T1.NGAY_THANG = T2.NGAY AND T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN
GROUP BY NGAY_THANG

UNION
SELECT ISNULL(CONVERT(NVARCHAR(2), DAY(T1.NGAY_THANG)),0) AS NGAY,9999 AS MS_NGUYEN_NHAN,N'Schedule Run (Hours)' AS TEN_NGUYEN_NHAN, NULLIF(
CASE  WHEN ISNULL(SUM(T2.THOI_GIAN_SUA),0)  > 0 THEN 
CASE WHEN ISNULL(GIO_KH,0) = 0 THEN 24 ELSE GIO_KH END
ELSE 0 END,0) AS TGNM 
FROM #TGNM T1 LEFT JOIN #TGNGUNG T2 ON T1.NGAY_THANG = T2.NGAY AND T1.MS_NGUYEN_NHAN = T2.MS_NGUYEN_NHAN LEFT JOIN dbo.KHSX_NGAY T3 ON T1.NGAY_THANG = T3.NGAY
GROUP BY NGAY_THANG,GIO_KH





	DECLARE @sSql NVARCHAR(MAX)
	DECLARE @sSqlL NVARCHAR(MAX)
	SET @sSql = ''
	SELECT @sSql = COALESCE(ISNULL(@sSql,'') + CASE LEN(@sSql) WHEN 0 THEN '' ELSE ',' END , '') + ISNULL(NGAY,'')
	 FROM 
	(
		SELECT DISTINCT number,
		N' [' +CONVERT(NVARCHAR(2),DAY(DATEADD(day,number,@Tu_Ngay)))+N']'  AS NGAY
		 from master.dbo.spt_values WHERE number between 0 and 1000 AND DATEADD(day,number,@Tu_Ngay) <= @Den_Ngay
	 ) T1

	  
         SET @sSqlL = '
		 
		DECLARE @TGIOCHAY DECIMAL(10,2) = 0
		DECLARE @TGIONGUNG DECIMAL(10,2) = 0
		SELECT @TGIOCHAY  = SUM(TGNM) FROM #TMP WHERE MS_NGUYEN_NHAN = 9999
		SELECT @TGIONGUNG = ISNULL(  CONVERT(DECIMAL(10,2), SUM(TGNM)/60 ) ,0 )   FROM #TMP	 WHERE MS_NGUYEN_NHAN = 9998
		 
		SELECT CASE WHEN MS_NGUYEN_NHAN IN (9999,9998) THEN MS_NGUYEN_NHAN ELSE	ROW_NUMBER() OVER(ORDER BY TEN_NGUYEN_NHAN) END AS STT,
		pvt.* FROM (
			SELECT t1.MS_NGUYEN_NHAN,T1.TEN_NGUYEN_NHAN,T1.TGNM,T1.NGAY FROM #TMP T1
			UNION
			SELECT MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN, NULLIF(CASE WHEN MS_NGUYEN_NHAN = 9999 THEN 0 ELSE ISNULL(SUM(TGNM),0) END,0) AS TGNM, 35 AS NGA FROM #TMP	GROUP BY MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN
			UNION
			SELECT MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN,  NULLIF(
			CASE WHEN MS_NGUYEN_NHAN = 9999 THEN @TGIOCHAY ELSE ISNULL(  CONVERT(DECIMAL(10,2), SUM(TGNM)/60 ) ,0 )  END	,0)
			AS TGNM, 36 AS NGA FROM #TMP	 GROUP BY MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN 

			UNION
			SELECT MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN,  NULLIF(
			CASE WHEN MS_NGUYEN_NHAN = 9999 THEN CONVERT(DECIMAL(10,5), @TGIONGUNG/@TGIOCHAY) ELSE  CONVERT(DECIMAL(10,5),ISNULL( SUM(TGNM)/60,0 ) / @TGIOCHAY)  END	,0)
			AS TGNM, 37 AS NGA FROM #TMP	 GROUP BY MS_NGUYEN_NHAN, TEN_NGUYEN_NHAN 		
		)
		 A PIVOT
		(
			SUM(A.TGNM) FOR A.NGAY IN (' + @sSql + ', [35], [36], [37])
		) AS pvt
			ORDER BY STT

			
			'
			--ReportTGNM
       EXEC(@sSqlL)
END




	
