IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'KiemTraKeHoachSanXuat')   
exec('CREATE PROCEDURE KiemTraKeHoachSanXuat AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE KiemTraKeHoachSanXuat
	@Loai INT =1,
	@TuNgay DATE = '12/31/2018',
	@DenNgay DATE  ='02/28/2019',
	@MsHeThong INT =1
AS
BEGIN
--DECLARE @resulst INT;
	IF(@Loai = 0 OR @Loai = 2)
		BEGIN 
		SELECT COUNT(*) FROM KHSX_NGAY WHERE MS_HE_THONG =@MsHeThong AND NGAY BETWEEN CONVERT(DATE,@TuNgay) AND CONVERT(DATE,@DenNgay) AND ISNULL(LOAI,0) = @Loai
		END
	ELSE
		BEGIN
				SELECT COUNT(*) FROM KHSX_NGAY WHERE MS_N_XUONG =@MsHeThong AND NGAY BETWEEN CONVERT(DATE,@TuNgay) AND CONVERT(DATE,@DenNgay)  AND ISNULL(LOAI,0) = @Loai
		END
END

-----0 MS_HE_THONG,NGAY
--SELECT * FROM dbo.KHSX_NGAY WHERE ISNULL(LOAI,0) =0
-----3 MS_HE_THONG,NGAY ---tảrget
--SELECT * FROM dbo.KHSX_NGAY WHERE ISNULL(LOAI,0) =3


-----1 MS_N_XUONG,NGAY ---tảrget
--SELECT * FROM dbo.KHSX_NGAY WHERE ISNULL(LOAI,0) =1


-----2 MS_N_XUONG,NGAY ---tảrget
--SELECT * FROM dbo.KHSX_NGAY WHERE ISNULL(LOAI,0) =2

