IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetListHeThong')
   
exec('CREATE PROCEDURE GetListHeThong AS BEGIN SET NOCOUNT ON; END')
GO
ALTER proc [dbo].[GetListHeThong]
	@UserName nvarchar(50)='admin',
	@NNgu INT =0
AS
BEGIN
	SELECT DISTINCT H.MS_HE_THONG, 
	CASE @NNgu WHEN 0 THEN H.TEN_HE_THONG WHEN 1 THEN ISNULL(NULLIF (H.TEN_HE_THONG_ANH, ''), H.TEN_HE_THONG) 
							 ELSE ISNULL(NULLIF (H.TEN_HE_THONG_HOA, ''), H.TEN_HE_THONG) END AS TEN_HE_THONG,
	H.GHI_CHU,NHOM_IN,H.NHOM_LINE
	FROM	dbo.HE_THONG AS H INNER JOIN
			dbo.NHOM_HE_THONG AS NT ON H.MS_HE_THONG = NT.MS_HE_THONG INNER JOIN
			dbo.USERS ON NT.GROUP_ID = dbo.USERS.GROUP_ID 
	WHERE     (dbo.USERS.USERNAME = @UserName OR @UserName = '-1')
	ORDER BY TEN_HE_THONG
END

