IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetKeHoachSanXuat')
exec('CREATE PROCEDURE GetKeHoachSanXuat AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE GetKeHoachSanXuat
	@USERNAME VARCHAR(64) ='admin', 
	@LANGUAGE INT =1, 
	@iLoai INT = 1
AS
BEGIN
SELECT T1.ID,CASE @LANGUAGE WHEN 0 THEN T2.TEN_HE_THONG WHEN 1 THEN ISNULL(NULLIF(T2.TEN_HE_THONG_ANH, ''),T2.TEN_HE_THONG)ELSE ISNULL(NULLIF(T2.TEN_HE_THONG_HOA, ''), T2.TEN_HE_THONG)END AS TEN_HE_THONG,
CASE @iLoai WHEN 1 THEN CASE @LANGUAGE WHEN 0 THEN	'Nhóm ' ELSE 'Group ' END + CONVERT(NVARCHAR(10),T1.MS_N_XUONG) ELSE NULL END NHOM, T1.MS_HE_THONG,T1.MS_N_XUONG,T1.NGAY,T1.GIO_KH,T1.GHI_CHU
FROM dbo.KHSX_NGAY T1
LEFT JOIN dbo.HE_THONG T2 ON T2.MS_HE_THONG = T1.MS_HE_THONG
WHERE ISNULL(LOAI,0)= @iLoai
ORDER BY T1.NGAY DESC,TEN_HE_THONG,T1.MS_N_XUONG
END	