IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'Add_PhieuBaoTri_CongViec')
exec('CREATE PROCEDURE Add_PhieuBaoTri_CongViec AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[Add_PhieuBaoTri_CongViec]
@MS_PHIEU_BAO_TRI NVARCHAR(20) ='WO-201906000365',
@SBT NVARCHAR(100) ='TEMPTALLadmin',
@Loai INT = 1
AS
BEGIN
CREATE TABLE #TEMPT_CV (
[MS_TS_GSTT] [nvarchar] (10),
[MS_BO_PHAN] [nvarchar](50),
[MS_CV] [nvarchar](10)
) ON [PRIMARY]
DECLARE @sSql nvarchar(4000)
BEGIN
IF @Loai = 0
BEGIN
set @sSql = 'INSERT INTO #TEMPT_CV SELECT [MS_TS_GSTT],[MS_BO_PHAN], NULL FROM ' + @SBT + ' WHERE CHON = 1'
EXEC (@sSql)
set @sSql = 'DROP TABLE ' + @SBT
EXEC (@sSql)
INSERT INTO dbo.PHIEU_BAO_TRI_CONG_VIEC(MS_PHIEU_BAO_TRI,MS_CV,MS_BO_PHAN,SO_GIO_KH,SO_NGUOI,YEU_CAU_NS,YEU_CAU_DUNG_CU)
SELECT DISTINCT @MS_PHIEU_BAO_TRI,T2.MS_CV,T1.MS_BO_PHAN,T3.THOI_GIAN_DU_KIEN,T3.SO_NGUOI,T3.YEU_CAU_NS,T3.YEU_CAU_DUNG_CU FROM #TEMPT_CV T1
INNER JOIN dbo.GSTT_CV T2 ON T2.MS_TS_GSTT = T1.MS_TS_GSTT
INNER JOIN dbo.CONG_VIEC T3 ON T3.MS_CV = T2.MS_CV
END
ELSE
BEGIN
set @sSql = 'INSERT INTO #TEMPT_CV SELECT [MS_TS_GSTT],[MS_BO_PHAN],[MS_CV] FROM ' + @SBT + ' WHERE CHON = 1'
EXEC (@sSql)
set @sSql = 'DROP TABLE ' + @SBT
EXEC (@sSql)
INSERT INTO dbo.PHIEU_BAO_TRI_CONG_VIEC(MS_PHIEU_BAO_TRI,MS_CV,MS_BO_PHAN,SO_GIO_KH,SO_NGUOI,YEU_CAU_NS,YEU_CAU_DUNG_CU)
SELECT DISTINCT @MS_PHIEU_BAO_TRI,T2.MS_CV,T1.MS_BO_PHAN,T2.THOI_GIAN_DU_KIEN,T2.SO_NGUOI,T2.YEU_CAU_NS,T2.YEU_CAU_DUNG_CU 
FROM #TEMPT_CV T1
INNER JOIN dbo.CONG_VIEC T2 ON T2.MS_CV = T1.MS_CV
END	
END
END
