IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetGiamSatTinhTrangCongViec')
   
exec('CREATE PROCEDURE GetGiamSatTinhTrangCongViec AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE GetGiamSatTinhTrangCongViec
	@LoaiTS INT = -1, 
	@NNgu INT =0,
	@Kieu INT =0

--loaiTS = -1 load all
--loaiTS = 0 dinh luong
--loaiTS = 1 dinh tinh

--kieu = 0 load form
--kieu =1 chinh sua

AS
BEGIN
IF(@Kieu = 0)
	BEGIN
	SELECT DISTINCT T1.MS_TS_GSTT,
CASE @NNgu WHEN 0 THEN T2.TEN_TS_GSTT WHEN 1 THEN ISNULL(NULLIF(T2.TEN_TS_GSTT_ANH,''),T2.TEN_TS_GSTT) ELSE ISNULL(NULLIF(T2.TEN_TS_GSTT_HOA,''),T2.TEN_TS_GSTT) END AS TEN_TS_GSTT
FROM GSTT_CV T1 
INNER JOIN dbo.THONG_SO_GSTT T2 ON T2.MS_TS_GSTT = T1.MS_TS_GSTT
WHERE	T2.LOAI_TS = @LoaiTS OR -1 = @LoaiTS
	END
ELSE
	BEGIN
	SELECT DISTINCT T2.MS_TS_GSTT,
	CASE @NNgu WHEN 0 THEN T2.TEN_TS_GSTT WHEN 1 THEN ISNULL(NULLIF(T2.TEN_TS_GSTT_ANH,''),T2.TEN_TS_GSTT) ELSE ISNULL(NULLIF(T2.TEN_TS_GSTT_HOA,''),T2.TEN_TS_GSTT) END AS TEN_TS_GSTT
	FROM GSTT_CV T1 
	RIGHT JOIN dbo.THONG_SO_GSTT T2 ON T2.MS_TS_GSTT = T1.MS_TS_GSTT
	WHERE	T2.LOAI_TS = @LoaiTS OR -1 = @LoaiTS
	END
END	
