IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sp_GetDanhSachThietBiByLoaiTS')
   exec('CREATE PROCEDURE sp_GetDanhSachThietBiByLoaiTS AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC	sp_GetDanhSachThietBiByLoaiTS
@STT	int =6166,
@LoaiTS INT =0
AS
BEGIN
SELECT DISTINCT GIAM_SAT_TINH_TRANG_TS.MS_MAY,  TEN_MAY
FROM         GIAM_SAT_TINH_TRANG_TS 
INNER JOIN dbo.MAY ON MAY.MS_MAY = GIAM_SAT_TINH_TRANG_TS.MS_MAY
JOIN dbo.THONG_SO_GSTT T3 ON T3.MS_TS_GSTT = GIAM_SAT_TINH_TRANG_TS.MS_TS_GSTT
WHERE STT=@STT AND T3.LOAI_TS = @LoaiTS
ORDER BY GIAM_SAT_TINH_TRANG_TS.MS_MAY
END
