
ALTER procedure [dbo].[H_INSERT_MAY_NHA_XUONG] 
	@MS_MAY NVARCHAR(30),
	@MS_N_XUONG NVARCHAR(50),
	@NGAY_NHAP DATETIME,
	@GHI_CHU NVARCHAR(max)
 AS
INSERT INTO dbo.MAY_NHA_XUONG 
(MS_MAY, NGAY_NHAP,MS_N_XUONG,GC_NX)
VALUES
(@MS_MAY, @NGAY_NHAP,@MS_N_XUONG,@GHI_CHU)

