IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGet_LICH_SU_MUA_HANG')
exec('CREATE PROCEDURE spGet_LICH_SU_MUA_HANG AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGet_LICH_SU_MUA_HANG
	@MS_PT NVARCHAR(25) ='COS-AC-470'
AS
BEGIN
SELECT T1.MS_DH_NHAP_PT,T1.NGAY,T3.TEN_CONG_TY,T2.SL_THUC_NHAP,T2.DON_GIA,T2.NGOAI_TE ,T2.TY_GIA,(T2.DON_GIA * T2.TY_GIA) * T2.SL_THUC_NHAP AS 'THANH_TIENVND' FROM dbo.IC_DON_HANG_NHAP T1 INNER JOIN dbo.IC_DON_HANG_NHAP_VAT_TU T2 ON T2.MS_DH_NHAP_PT = T1.MS_DH_NHAP_PT 
LEFT JOIN (SELECT MS_KH,TEN_CONG_TY FROM dbo.KHACH_HANG
union
SELECT MS_CONG_NHAN,HO +' '+TEN FROM dbo.CONG_NHAN) T3 ON T1.NGUOI_NHAP = T3.MS_KH
WHERE T2.MS_PT = @MS_PT
ORDER BY T1.NGAY DESC,T1.MS_DH_NHAP_PT DESC
END


