IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spImportCTTBCV')
   
exec('CREATE PROCEDURE spImportCTTBCV AS BEGIN SET NOCOUNT ON; END')

GO


--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO

--SELECT * INTO CTTBDCM630 FROM  CTTBAdmin
--SELECT DISTINCT	* FROM CTTBAdmin
ALTER PROCEDURE spImportCTTBCV
	@BTam NVARCHAR(250) = 'CTTBAdmin',
    @MsMay NVARCHAR(100) =   'DCM-630' ,
	@MsBP NVARCHAR(100) =   '-1' 
AS
BEGIN
CREATE TABLE  #CTTBCV (
	[STT] [FLOAT] NULL,
	[MSM] [NVARCHAR](500) NULL,
	[TENBP] [NVARCHAR](500) NULL,
	[TENBP2] [NVARCHAR](500) NULL,
	[TENBP3] [NVARCHAR](500) NULL,
	[TENBP4] [NVARCHAR](500) NULL,
	[TENBP5] [NVARCHAR](500) NULL,
	[TENBP6] [NVARCHAR](500) NULL,
	[TenCongViec] [NVARCHAR](500) NULL,
	[DinhLuong] [NVARCHAR](500) NULL,
	[DungHayKhong] [NVARCHAR](500) NULL,
	[CanDuoi] [NVARCHAR](500) NULL,
	[CanTren] [NVARCHAR](500) NULL,
	[DVT] [NVARCHAR](500) NULL,
	[ChuKy] [FLOAT] NULL,
	[DVTThoiGian] [NVARCHAR](500) NULL,
	[GiaTriTS] [NVARCHAR](500) NULL,
	[TGian] [FLOAT] NULL,
	[NgayBTGanNhat] [NVARCHAR](500) NULL
)   

--SELECT  FROM #CTTBCV
DECLARE @Sql NVARCHAR(MAX)
SET @Sql = 'INSERT INTO #CTTBCV (STT, MSM, TENBP, TENBP2, TENBP3, TENBP4, TENBP5, TENBP6, TenCongViec, DinhLuong, DungHayKhong, CanDuoi, CanTren, DVT, ChuKy, DVTThoiGian, GiaTriTS, TGian, NgayBTGanNhat)	 
SELECT STT, MSM, TENBP, TENBP2, TENBP3, TENBP4, TENBP5, TENBP6, TenCongViec, DinhLuong, DungHayKhong, CanDuoi, CanTren, DVT, ChuKy, DVTThoiGian, GiaTriTS, TGian, NgayBTGanNhat FROM ' + @BTam ;
EXEC (@Sql);

SET @Sql = 'DROP TABLE ' + @BTam;
--EXEC (@Sql);

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'DATACVBT') AND type in (N'U'))
	DROP TABLE  DATACVBT

SELECT T1.MSCHA, A.TEN_MAY,B.Ten_N_XUONG,MS_N_XUONG,C.TEN_HE_THONG,C.MS_HE_THONG,T1.MS_BO_PHAN,T1.TEN_BO_PHAN AS TENBP1,T2.MSBP2,T2.TEN_BO_PHAN AS TENBP2,T3.MSBP3,
T3.TEN_BO_PHAN AS TENBP3,T4.MSBP4,T4.TENBP4,T5.MSBP5,T5.TENBP5,T6.MSBP6,T6.TENBP6 
	   INTO DATACVBT 
	   FROM 
(
SELECT DISTINCT	MS_MAY AS MSCHA , MS_BO_PHAN,TEN_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI  WHERE  (MS_BO_PHAN_CHA = MS_MAY) AND (MS_MAY = @MsMay) AND (MS_BO_PHAN = @MsBP OR @MsBP = '-1')
) T1 
LEFT JOIN 
(
	SELECT DISTINCT	 MS_BO_PHAN_CHA AS MSCHA2 ,  MS_BO_PHAN AS MSBP2,TEN_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI  WHERE (MS_BO_PHAN_CHA = MS_MAY) AND (MS_MAY = @MsMay) AND (MS_BO_PHAN = @MsBP OR @MsBP = '-1') ) 
				) T2 ON T1.MS_BO_PHAN = T2.MSCHA2	

LEFT JOIN 
(
		SELECT DISTINCT	T1.MS_BO_PHAN_CHA MSCHA3,  MS_BO_PHAN AS MSBP3,TEN_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
				(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI WHERE  MS_BO_PHAN_CHA = MS_MAY AND MS_MAY = @MsMay ) 

		)
)	T3 ON T2.MSBP2 = T3.MSCHA3	

LEFT JOIN 
(
		SELECT DISTINCT	T1.MS_BO_PHAN_CHA MSCHA4 , MS_BO_PHAN AS MSBP4,TEN_BO_PHAN AS TENBP4 FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
			(
				SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI  WHERE MS_BO_PHAN_CHA = MS_MAY AND MS_MAY = @MsMay) 

			)
		)
) T4 ON T3.MSBP3 = T4.MSCHA4
LEFT JOIN 
(
	SELECT DISTINCT		T1.MS_BO_PHAN_CHA MSCHA5 , MS_BO_PHAN AS MSBP5,TEN_BO_PHAN AS TENBP5 FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
	(

		SELECT DISTINCT	MS_MAY + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
			(
				SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI WHERE  MS_BO_PHAN_CHA = MS_MAY  AND MS_MAY = @MsMay) 
			)
		)
	)
) T5 ON T4.MSBP4 = T5.MSCHA5

LEFT JOIN 
(
SELECT DISTINCT	T1.MS_BO_PHAN_CHA MSCHA6 , MS_BO_PHAN AS MSBP6,TEN_BO_PHAN AS TENBP6  FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
(
	SELECT DISTINCT	MS_MAY + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
	(

		SELECT DISTINCT	MS_MAY + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
			(
				SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI WHERE  MS_BO_PHAN_CHA = MS_MAY  AND MS_MAY = @MsMay )  

			)
		)
	)
)
) T6 ON T5.MSBP5 = T6.MSCHA6 INNER JOIN dbo.MAY A ON T1.MSCHA = A.MS_MAY LEFT JOIN 
(SELECT T1.MS_MAY,T2.Ten_N_XUONG,T1.MS_N_XUONG FROM dbo.MAY_NHA_XUONG T1 INNER JOIN dbo.NHA_XUONG T2 ON T2.MS_N_XUONG = T1.MS_N_XUONG) B ON T1.MSCHA = B.MS_MAY LEFT JOIN 
(SELECT T2.MS_MAY,T1.TEN_HE_THONG,T1.MS_HE_THONG FROM dbo.HE_THONG T1 INNER JOIN dbo.MAY_HE_THONG T2 ON T2.MS_HE_THONG = T1.MS_HE_THONG) C ON T1.MSCHA = C.MS_MAY

ORDER BY C.MS_HE_THONG,MS_N_XUONG,T1.MSCHA, T1.MS_BO_PHAN,T2.MSBP2,T3.MSBP3,T4.MSBP4,T5.MSBP5



IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CVBTCongViec') AND type in (N'U'))
	DROP TABLE  CVBTCongViec

	SELECT * INTO CVBTCongViec FROM #CTTBCV T1 WHERE (ISNULL(T1.TenCongViec,'') <> '') AND (ISNULL(T1.DINHLUONG,'') = 0) AND ( ISNULL(T1.DUNGHAYKHONG,'') = 1) 


-----INSERT VAO CAU TRUC THIET BI CONG VIEC
INSERT INTO dbo.CAU_TRUC_THIET_BI_CONG_VIEC(MS_MAY,MS_BO_PHAN,MS_CV,ACTIVE,TG_KH)
SELECT  A.MSM,MS_BO_PHAN,(SELECT TOP 1 A.MS_CV FROM dbo.CONG_VIEC A WHERE A.MO_TA_CV = TENCONGVIEC) MsCV,1 AS ACTIVE ,TGIAN
FROM 
(
--cong viec cap 1
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MS_BO_PHAN, t2.TENBP1,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU , 1 AS CAP , '' AS CACHTHUCHIEN
FROM dbo.CVBTCongViec T1 INNER JOIN dbo.DATACVBT T2 ON mscha = t1.msm  AND T2.TENBP1 = T1.TENBP  WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') = '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  
UNION

--cong viec cap 2
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MSBP2, t2.TENBP2,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU ,2 AS CAP , '' AS CACHTHUCHIEN 
FROM dbo.CVBTCongViec T1 INNER JOIN dbo.DATACVBT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  
UNION
--cong viec cap 3
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP3, t2.TENBP3,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU  , 3 AS CAP, '' AS CACHTHUCHIEN 
FROM dbo.CVBTCongViec T1 INNER JOIN dbo.DATACVBT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  
UNION
--cong viec cap 4
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP4, t2.TENBP4,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU   , 4 AS CAP, '' AS CACHTHUCHIEN
FROM dbo.CVBTCongViec T1 INNER JOIN dbo.DATACVBT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''   
UNION
--cong viec cap 5
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP5, t2.TENBP5,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU  , 5 AS CAP , '' AS CACHTHUCHIEN 
FROM dbo.CVBTCongViec T1 INNER JOIN dbo.DATACVBT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP  AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''
UNION
--cong viec cap 6
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP6, t2.TENBP6,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU  , 6 AS CAP , '' AS CACHTHUCHIEN 
FROM dbo.CVBTCongViec T1 INNER JOIN dbo.DATACVBT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP   AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  AND T2.TENBP6 = T1.TENBP6  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') <> ''  AND	 ISNULL(T1.TenCongViec,'') <> '' 
) A

ORDER BY A.CAP

--cONG VIEC

-- MAY LOAI BAO TRI
INSERT INTO dbo.MAY_LOAI_BTPN(MS_MAY,MS_LOAI_BT,NGAY_CUOI)
SELECT DISTINCT A.[MSM ],MSLoaiBT,MAX(CONVERT(DATETIME,NgayBTGanNhat,103)) AS NgayBTGanNhat FROM (
SELECT T1.[MSM ],
(SELECT TOP 1 A.MS_LOAI_BT FROM dbo.LOAI_BAO_TRI A INNER JOIN dbo.HINH_THUC_BAO_TRI B ON B.MS_HT_BT = A.MS_HT_BT WHERE B.PHONG_NGUA = 1 AND	A.TEN_LOAI_BT = 
CONVERT(NVARCHAR(10),T1.ChuKy) + ' ' + T1.DVTThoiGian ) AS MSLoaiBT,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM CVBTCongViec T1 WHERE (ISNULL(T1.TenCongViec,'') <> '') AND (ISNULL(T1.DINHLUONG,'') = 0) AND ( ISNULL(T1.DUNGHAYKHONG,'') = 1) )A
GROUP BY A.[MSM ],MSLoaiBT
ORDER BY A.MSLoaiBT



--MAY LOAI BAO TRI CHU_KY
INSERT INTO	dbo.MAY_LOAI_BTPN_CHU_KY(MS_MAY,MS_LOAI_BT,NGAY_AD,CHU_KY,MS_DV_TG,RUN_TIME,MS_DVT_RT,MOVEMENT)
SELECT DISTINCT T1.[MSM ],
(SELECT TOP 1 A.MS_LOAI_BT FROM dbo.LOAI_BAO_TRI A INNER JOIN dbo.HINH_THUC_BAO_TRI B ON B.MS_HT_BT = A.MS_HT_BT WHERE B.PHONG_NGUA = 1 AND	A.TEN_LOAI_BT = 
CONVERT(NVARCHAR(10),T1.ChuKy) + ' ' + T1.DVTThoiGian ) AS MSLoaiBT, '01/01/2019' AS NgayAD,T1.ChuKy,
(SELECT A.MS_DV_TG FROM dbo.DON_VI_THOI_GIAN A WHERE A.TEN_DV_TG = T1.DVTThoiGian) AS MsDVTTinhTG, 0 AS RunTime,
(SELECT MS_DVT_RT FROM dbo.MAY a WHERE T1.[MSM ] = A.MS_MAY) AS MsDVTRunTime,0 AS Movement 
FROM CVBTCongViec T1 WHERE (ISNULL(T1.TenCongViec,'') <> '') AND (ISNULL(T1.DINHLUONG,'') = 0) AND ( ISNULL(T1.DUNGHAYKHONG,'') = 1) 

-- MAY CONG VIEC BNAO TRI
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CVMLBTri') AND type in (N'U'))
	DROP TABLE  CVMLBTri

SELECT T1.[MSM ],(SELECT TOP 1 A.MS_LOAI_BT FROM dbo.LOAI_BAO_TRI A INNER JOIN dbo.HINH_THUC_BAO_TRI B ON B.MS_HT_BT = A.MS_HT_BT WHERE B.PHONG_NGUA = 1 AND	A.TEN_LOAI_BT = 
CONVERT(NVARCHAR(10),T1.ChuKy) + ' ' + T1.DVTThoiGian ) AS MSLoaiBT ,T1.TenCongViec,T1.TENBP,T1.TENBP2,T1.TENBP3,T1.TENBP4,T1.TENBP5,T1.TENBP6 
INTO CVMLBTri
FROM CVBTCongViec T1 WHERE (ISNULL(T1.TenCongViec,'') <> '') AND (ISNULL(T1.DINHLUONG,'') = 0) AND ( ISNULL(T1.DUNGHAYKHONG,'') = 1) 


--
INSERT INTO dbo.MAY_LOAI_BTPN_CONG_VIEC(MS_MAY,MS_LOAI_BT,MS_CV,MS_BO_PHAN)
SELECT A.MSM,MSLoaiBT,(SELECT TOP 1 A.MS_CV FROM dbo.CONG_VIEC A WHERE TENCONGVIEC = A.MO_TA_CV) MSCV,MS_BO_PHAN 
FROM 
(
--cong viec cap 1
SELECT DISTINCT  T1.MSM,T2.MS_BO_PHAN, t2.TENBP1,T1.TENCONGVIEC,MSLoaiBT ,1 AS CAP
FROM dbo.CVMLBTri T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP  WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') = '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  
UNION

--cong viec cap 2
SELECT DISTINCT  T1.MSM,T2.MSBP2, t2.TENBP2,T1.TENCONGVIEC,MSLoaiBT ,2 AS CAP
FROM dbo.CVMLBTri T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  
UNION
--cong viec cap 3
SELECT DISTINCT   T1.MSM,T2.MSBP3, t2.TENBP3,T1.TENCONGVIEC,MSLoaiBT ,3 AS CAP
FROM dbo.CVMLBTri T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  
UNION
--cong viec cap 4
SELECT DISTINCT   T1.MSM,T2.MSBP4, t2.TENBP4,T1.TENCONGVIEC,MSLoaiBT ,4 AS CAP
FROM dbo.CVMLBTri T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''   
UNION
--cong viec cap 5
SELECT DISTINCT   T1.MSM,T2.MSBP5, t2.TENBP5,T1.TENCONGVIEC,MSLoaiBT ,5 AS CAP
FROM dbo.CVMLBTri T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP  AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5   WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''
UNION
--cong viec cap 6
SELECT DISTINCT   T1.MSM,T2.MSBP6, t2.TENBP6,T1.TENCONGVIEC,MSLoaiBT ,6 AS CAP
FROM dbo.CVMLBTri T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP   AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  AND T2.TENBP6 = T1.TENBP6  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') <> ''  AND	 ISNULL(T1.TenCongViec,'') <> '' 
) A

ORDER BY A.CAP 






---- DINH TINH
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'BTDT') AND type in (N'U'))
	DROP TABLE BTDT



SELECT * INTO BTDT FROM #CTTBCV T1 WHERE (ISNULL(T1.TenCongViec,'') <> '') AND (ISNULL(T1.DINHLUONG,'') = ''  OR ISNULL(T1.DINHLUONG,'') = 0) AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0) 


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CVBTDT') AND type in (N'U'))
	DROP TABLE CVBTDT
SELECT A.MSM,TENMAY,MS_BO_PHAN,A.TENBP1,TENCONGVIEC,CHUKY,DVTTHOIGIAN, HIEULUC,TGIAN,THAOTAC,CACHTHUCHIEN,A.TIEUCHUANKYTHUAT,A.YCNS,A.YCDC,GIATRITS,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat INTO	 CVBTDT
FROM 
(
--cong viec cap 1
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MS_BO_PHAN, t2.TENBP1,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,CANDUOI,CANTREN,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU , 1 AS CAP , '' AS CACHTHUCHIEN,GIATRITS,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM dbo.BTDT T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP  WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') = '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0)
UNION

--cong viec cap 2
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MSBP2, t2.TENBP2,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,CANDUOI,CANTREN,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU ,2 AS CAP , '' AS CACHTHUCHIEN ,GIATRITS ,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM dbo.BTDT T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0)
UNION
--cong viec cap 3
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP3, t2.TENBP3,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,CANDUOI,CANTREN,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU  , 3 AS CAP, '' AS CACHTHUCHIEN ,GIATRITS,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM dbo.BTDT T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0)
UNION
--cong viec cap 4
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP4, t2.TENBP4,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,CANDUOI,CANTREN,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU   , 4 AS CAP, '' AS CACHTHUCHIEN,GIATRITS,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM dbo.BTDT T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''   AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0)
UNION
--cong viec cap 5
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP5, t2.TENBP5,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,CANDUOI,CANTREN,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU  , 5 AS CAP , '' AS CACHTHUCHIEN ,GIATRITS,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM dbo.BTDT T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP  AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0)
UNION
--cong viec cap 6
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP6, t2.TENBP6,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,CANDUOI,CANTREN,CHUKY,DVTTHOIGIAN, 1 AS HIEULUC,'' AS GHICHU  , 6 AS CAP , '' AS CACHTHUCHIEN ,GIATRITS,CONVERT(DATETIME,NgayBTGanNhat,103) AS NgayBTGanNhat
FROM dbo.BTDT T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP   AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  AND T2.TENBP6 = T1.TENBP6  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') <> ''  AND	 ISNULL(T1.TenCongViec,'') <> '' AND (ISNULL(T1.DUNGHAYKHONG,'') = ''  OR ISNULL(T1.DUNGHAYKHONG,0) = 0)
) A

ORDER BY A.CAP 

--DT
INSERT INTO [CAU_TRUC_THIET_BI_TS_GSTT]([MS_MAY],[MS_BO_PHAN],[MS_TS_GSTT],[CHU_KY_DO],[MS_DV_TG],[ACTIVE],[MS_TT]  , THOI_GIAN, CACH_THUC_HIEN, TIEU_CHUAN_KT, YEU_CAU_NS, YEU_CAU_DUNG_CU,NGAY_GS_CUOI )

SELECT MSM,MS_BO_PHAN,
(SELECT TOP 1 MS_TS_GSTT FROM dbo.THONG_SO_GSTT T2 WHERE T2.TEN_TS_GSTT = T1.TENCONGVIEC AND T2.YEU_CAU_DUNG_CU = T1.GIATRITS AND ISNULL(T2.LOAI_TS,0) = 1 ) AS [MS_TS_GSTT],CHUKY,(SELECT TOP 1 MS_DV_TG FROM dbo.DON_VI_THOI_GIAN T3 WHERE T3.TEN_DV_TG = T1.DVTTHOIGIAN) AS [MS_DV_TG],1 AS [ACTIVE],1 AS [MS_TT],TGIAN,CACHTHUCHIEN,TIEUCHUANKYTHUAT,YCNS,YCDC,T1.NgayBTGanNhat 
FROM CVBTDT T1










-- DINH LUONG



CREATE TABLE  #TS (POS INT,TENTHONGSO NVARCHAR(MAX), GiaTriTS NVARCHAR(MAX))

DECLARE @sGTri NVARCHAR(MAX),@sSql NVARCHAR(MAX)
Declare  Cap1 CURSOR FOR
	SELECT DISTINCT	GiaTriTS FROM #CTTBCV  WHERE (ISNULL(TenCongViec,'') <> '') AND (DINHLUONG = '1')
OPEN Cap1

FETCH NEXT FROM Cap1
INTO @sGTri
WHILE @@Fetch_Status = 0
BEGIN
	INSERT INTO	#TS(POS, TENTHONGSO,GiaTriTS)	
	SELECT *,@sGTri AS GiaTriTS FROM [dbo].[MGetSplit](@sGTri,N'!')  A 
	
    FETCH NEXT FROM Cap1
    INTO @sGTri
End

Close Cap1
Deallocate Cap1


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CVBTDinhLuong') AND type in (N'U'))
	DROP TABLE CVBTDinhLuong

SELECT * INTO CVBTDinhLuong FROM #CTTBCV T1 WHERE (ISNULL(T1.TenCongViec,'') <> '') AND (DINHLUONG = '1')


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'DDinhLuong') AND type in (N'U'))
	DROP TABLE DDinhLuong


SELECT *   INTO DDinhLuong
FROM 
(
--cong viec cap 1
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MS_BO_PHAN, t2.TENBP1,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,T9.TENTHONGSO AS GIATRITHONGSO,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANDUOI) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN) END) AS CANDUOI ,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANTREN) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN,0) + 10 END) AS CANTREN ,
CHUKY,DVTTHOIGIAN, CASE WHEN POS = 1 THEN POS ELSE 0 END AS DAT,1 AS HIEULUC,'' AS GHICHU ,POS, 1 AS CAP,'' CachThucHien
FROM dbo.CVBTDinhLuong T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP INNER JOIN #TS T9 ON  T1.GIATRITS = T9.GiaTriTS  WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') = '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''   AND (T1.DinhLuong = '1')
UNION

--cong viec cap 2
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MSBP2, t2.TENBP2,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,T9.TENTHONGSO AS GIATRITHONGSO,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANDUOI) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN) END) AS CANDUOI ,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANTREN) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN,0) + 10 END) AS CANTREN ,
CHUKY,DVTTHOIGIAN, CASE WHEN POS = 1 THEN POS ELSE 0 END AS DAT,1 AS HIEULUC,'' AS GHICHU ,POS,2 AS CAP ,'' CachThucHien
FROM dbo.CVBTDinhLuong T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  INNER JOIN #TS T9 ON T1.GIATRITS = T9.GiaTriTS  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''    AND (T1.DinhLuong = '1')
UNION
--cong viec cap 3
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP3, t2.TENBP3,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,T9.TENTHONGSO AS GIATRITHONGSO,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANDUOI) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN) END) AS CANDUOI ,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANTREN) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN,0) + 10 END) AS CANTREN ,
CHUKY,DVTTHOIGIAN, CASE WHEN POS = 1 THEN POS ELSE 0 END AS DAT,1 AS HIEULUC,'' AS GHICHU ,POS , 3 AS CAP ,'' CachThucHien
FROM dbo.CVBTDinhLuong T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 INNER JOIN #TS T9 ON T1.GIATRITS = T9.GiaTriTS  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''    AND (T1.DinhLuong = '1')
UNION
--cong viec cap 4
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP4, t2.TENBP4,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,T9.TENTHONGSO AS GIATRITHONGSO,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANDUOI) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN) END) AS CANDUOI ,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANTREN) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN,0) + 10 END) AS CANTREN ,
CHUKY,DVTTHOIGIAN, CASE WHEN POS = 1 THEN POS ELSE 0 END AS DAT,1 AS HIEULUC,'' AS GHICHU ,POS  , 4 AS CAP,'' CachThucHien
FROM dbo.CVBTDinhLuong T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4 INNER JOIN #TS T9 ON T1.GIATRITS = T9.GiaTriTS  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''     AND (T1.DinhLuong = '1')
UNION
--cong viec cap 5
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP5, t2.TENBP5,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,T9.TENTHONGSO AS GIATRITHONGSO, 
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANDUOI) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN) END) AS CANDUOI ,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANTREN) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN,0) + 10 END) AS CANTREN ,
CHUKY,DVTTHOIGIAN, CASE WHEN POS = 1 THEN POS ELSE 0 END AS DAT,1 AS HIEULUC,'' AS GHICHU ,POS , 5 AS CAP ,'' CachThucHien
FROM dbo.CVBTDinhLuong T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP  AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  INNER JOIN #TS T9 ON T1.GIATRITS = T9.GiaTriTS  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.TenCongViec,'') <> ''  AND (T1.DinhLuong = '1')
UNION
--cong viec cap 6
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP6, t2.TENBP6,T1.TENCONGVIEC,TGIAN,'' AS THAOTAC,'' TIEUCHUANKYTHUAT,'' YCNS,'' YCDC,T9.TENTHONGSO AS GIATRITHONGSO,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANDUOI) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN) END) AS CANDUOI ,
CONVERT(FLOAT,CASE WHEN POS = 1 THEN CONVERT(FLOAT,CANTREN) WHEN POS= 2 THEN CONVERT(FLOAT,CANTREN,0) + 10 END) AS CANTREN ,
CHUKY,DVTTHOIGIAN, CASE WHEN POS = 1 THEN POS ELSE 0 END AS DAT,1 AS HIEULUC,'' AS GHICHU ,POS , 6 AS CAP ,'' CachThucHien
FROM dbo.CVBTDinhLuong T1 INNER JOIN dbo.DATACVBT T2 ON T2.TENBP1 = T1.TENBP   AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  AND T2.TENBP6 = T1.TENBP6 INNER JOIN #TS T9 ON T1.GIATRITS = T9.GiaTriTS  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') <> ''  AND	 ISNULL(T1.TenCongViec,'') <> ''   AND (T1.DinhLuong = '1')
) A

ORDER BY A.CAP,POS 


INSERT INTO [CAU_TRUC_THIET_BI_TS_GSTT](MS_TT, [MS_MAY],[MS_BO_PHAN],[MS_TS_GSTT], [TEN_GT],   [GIA_TRI_TREN] , [GIA_TRI_DUOI], [CHU_KY_DO],[MS_DV_TG] ,[DAT],[ACTIVE],[GHI_CHU],THOI_GIAN, CACH_THUC_HIEN, TIEU_CHUAN_KT, YEU_CAU_NS, YEU_CAU_DUNG_CU)

SELECT 

ROW_NUMBER() OVER(PARTITION BY MSM, MS_BO_PHAN,  TENCONGVIEC  ORDER BY MSM, MS_BO_PHAN, TENCONGVIEC) +  (SELECT ISNULL(MAX(MS_TT),0) FROM CAU_TRUC_THIET_BI_TS_GSTT B  WHERE  T1.MSM = B.[MS_MAY]  AND  T1.MS_BO_PHAN = B.[MS_BO_PHAN]  AND T1.TENCONGVIEC = B.MS_TS_GSTT) AS MS_TT 


,MSM,MS_BO_PHAN,(SELECT TOP 1 MS_TS_GSTT FROM dbo.THONG_SO_GSTT T2 WHERE T2.TEN_TS_GSTT = T1.TENCONGVIEC AND ISNULL(T2.LOAI_TS,0) = 0 ) AS [MS_TS_GSTT],giatrithongso,cantren,canduoi, CHUKY,
(SELECT TOP 1 T3.MS_DV_TG FROM dbo.DON_VI_THOI_GIAN T3 WHERE T3.TEN_DV_TG = T1.DVTTHOIGIAN) AS [MS_DV_TG],dat,1 AS [ACTIVE],'' AS ghichu, TGIAN,CACHTHUCHIEN,TIEUCHUANKYTHUAT,YCNS,YCDC 
 FROM DDinhLuong T1


 --SELECT * INTO DATACVBTADMIN FROM DATACVBT




END