IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spImportCTTBPT')
   
exec('CREATE PROCEDURE spImportCTTBPT AS BEGIN SET NOCOUNT ON; END')

GO


--SELECT * INTO CTTBDCM630 FROM  CTTBAdmin
--SELECT DISTINCT	* FROM CTTBAdmin
alter PROCEDURE spImportCTTBPT
	@BTam NVARCHAR(250) = 'CTTBPTecomaint1',
    @MsMay NVARCHAR(100) =   'MCLT3G' ,
	@MsBP NVARCHAR(100) =   '-1' 
AS
BEGIN
CREATE TABLE  #CTTBPT (
	[STT] [FLOAT] NULL,
	[MSM] [NVARCHAR](500) NULL,
	[TENBP] [NVARCHAR](500) NULL,
	[TENBP2] [NVARCHAR](500) NULL,
	[TENBP3] [NVARCHAR](500) NULL,
	[TENBP4] [NVARCHAR](500) NULL,
	[TENBP5] [NVARCHAR](500) NULL,
	[TENBP6] [NVARCHAR](500) NULL,
	[Phụ tùng ] [NVARCHAR](255) NULL,
	[Thông số] [NVARCHAR](255) NULL,
	[Part Number] [NVARCHAR](255) NULL,
	[PT cha] [NVARCHAR](255) NULL,
	[Thông tin khác ] [NVARCHAR](255) NULL,
	[Vị trí PT ] [NVARCHAR](255) NULL,
	[Số lượng ] [FLOAT] NULL,
	MSPT NVARCHAR(50)
)   

--SELECT  FROM #CTTBPT
DECLARE @Sql NVARCHAR(MAX)
--SET @Sql = 'INSERT INTO #CTTBPT (STT, MSM, TENBP, TENBP2, TENBP3, TENBP4, TENBP5, TENBP6, [Phụ tùng ], [Thông số], [Part Number], [PT cha], [Thông tin khác ], [Vị trí PT ], [Số lượng ],MSPT)	 
--SELECT STT, MSM, TENBP, TENBP2, TENBP3, TENBP4, TENBP5, TENBP6, [Phụ tùng ], [Thông số], [Part Number], [PT cha], [Thông tin khác ], [Vị trí PT ], [Số lượng ], ISNULL([Phụ tùng ],'') + '''' + ISNULL([Thông số],'')  AS MSPT FROM ' + @BTam ;
SET @Sql = N'INSERT INTO #CTTBPT (STT, MSM, TENBP, TENBP2, TENBP3, TENBP4, TENBP5, TENBP6, [Phụ tùng ], [Thông số], [Part Number], [PT cha], [Thông tin khác ], [Vị trí PT ], [Số lượng ],MSPT)	 
SELECT STT, MSM, TENBP, TENBP2, TENBP3, TENBP4, TENBP5, TENBP6, [Phụ tùng ], [Thông số], [Part Number], [PT cha], [Thông tin khác ], [Vị trí PT ], [Số lượng ],  MSPT FROM ' + @BTam  ;
EXEC (@Sql);

SET @Sql = 'DROP TABLE ' + @BTam;
--EXEC (@Sql);

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'DATACVPT') AND type in (N'U'))
	DROP TABLE  DATACVPT

SELECT T1.MSCHA, A.TEN_MAY,B.Ten_N_XUONG,MS_N_XUONG,C.TEN_HE_THONG,C.MS_HE_THONG,T1.MS_BO_PHAN,T1.TEN_BO_PHAN AS TENBP1,T2.MSBP2,T2.TEN_BO_PHAN AS TENBP2,T3.MSBP3,
T3.TEN_BO_PHAN AS TENBP3,T4.MSBP4,T4.TENBP4,T5.MSBP5,T5.TENBP5,T6.MSBP6,T6.TENBP6 
	   INTO DATACVPT 
	   FROM 
(
SELECT DISTINCT	MS_MAY AS MSCHA , MS_BO_PHAN,TEN_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI  WHERE  (MS_BO_PHAN_CHA = MS_MAY) AND (MS_MAY = @MsMay) AND (MS_BO_PHAN = @MsBP OR @MsBP = '-1')
) T1 
LEFT JOIN 
(
	SELECT DISTINCT	 MS_BO_PHAN_CHA AS MSCHA2 ,  MS_BO_PHAN AS MSBP2,TEN_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI  WHERE (MS_BO_PHAN_CHA = MS_MAY) AND (MS_MAY = @MsMay) AND (MS_BO_PHAN = @MsBP OR @MsBP = '-1') ) 
				) T2 ON T1.MS_BO_PHAN = T2.MSCHA2	

LEFT JOIN 
(
		SELECT DISTINCT	T1.MS_BO_PHAN_CHA MSCHA3,  MS_BO_PHAN AS MSBP3,TEN_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
				(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI WHERE  MS_BO_PHAN_CHA = MS_MAY AND MS_MAY = @MsMay ) 

		)
)	T3 ON T2.MSBP2 = T3.MSCHA3	

LEFT JOIN 
(
		SELECT DISTINCT	T1.MS_BO_PHAN_CHA MSCHA4 , MS_BO_PHAN AS MSBP4,TEN_BO_PHAN AS TENBP4 FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
			(
				SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI  WHERE MS_BO_PHAN_CHA = MS_MAY AND MS_MAY = @MsMay) 

			)
		)
) T4 ON T3.MSBP3 = T4.MSCHA4
LEFT JOIN 
(
	SELECT DISTINCT		T1.MS_BO_PHAN_CHA MSCHA5 , MS_BO_PHAN AS MSBP5,TEN_BO_PHAN AS TENBP5 FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
	(

		SELECT DISTINCT	MS_MAY + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
			(
				SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI WHERE  MS_BO_PHAN_CHA = MS_MAY  AND MS_MAY = @MsMay) 
			)
		)
	)
) T5 ON T4.MSBP4 = T5.MSCHA5

LEFT JOIN 
(
SELECT DISTINCT	T1.MS_BO_PHAN_CHA MSCHA6 , MS_BO_PHAN AS MSBP6,TEN_BO_PHAN AS TENBP6  FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
(
	SELECT DISTINCT	MS_MAY + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
	(

		SELECT DISTINCT	MS_MAY + MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
		(
			SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	 MS_MAY + MS_BO_PHAN_CHA  IN 
			(
				SELECT DISTINCT	MS_MAY +  MS_BO_PHAN FROM dbo.CAU_TRUC_THIET_BI T1 WHERE	MS_MAY + MS_BO_PHAN_CHA  IN 
					(SELECT DISTINCT	MS_MAY + MS_BO_PHAN   FROM dbo.CAU_TRUC_THIET_BI WHERE  MS_BO_PHAN_CHA = MS_MAY  AND MS_MAY = @MsMay )  

			)
		)
	)
)
) T6 ON T5.MSBP5 = T6.MSCHA6 INNER JOIN dbo.MAY A ON T1.MSCHA = A.MS_MAY LEFT JOIN 
(SELECT T1.MS_MAY,T2.Ten_N_XUONG,T1.MS_N_XUONG FROM dbo.MAY_NHA_XUONG T1 INNER JOIN dbo.NHA_XUONG T2 ON T2.MS_N_XUONG = T1.MS_N_XUONG) B ON T1.MSCHA = B.MS_MAY LEFT JOIN 
(SELECT T2.MS_MAY,T1.TEN_HE_THONG,T1.MS_HE_THONG FROM dbo.HE_THONG T1 INNER JOIN dbo.MAY_HE_THONG T2 ON T2.MS_HE_THONG = T1.MS_HE_THONG) C ON T1.MSCHA = C.MS_MAY

ORDER BY C.MS_HE_THONG,MS_N_XUONG,T1.MSCHA, T1.MS_BO_PHAN,T2.MSBP2,T3.MSBP3,T4.MSBP4,T5.MSBP5





IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CTTBPTung') AND type in (N'U'))
	DROP TABLE  CTTBPTung
	
	SELECT * INTO CTTBPTung FROM #CTTBPT T1 WHERE ISNULL(T1.MSPT,'') <> '' AND ISNULL(T1.[PT cha],'')  = ''

-----INSERT VAO CAU_TRUC_THIET_BI_PHU_TUNG
--INSERT	INTO dbo.CAU_TRUC_THIET_BI_PHU_TUNG(MS_MAY, MS_BO_PHAN, MS_PT, MS_VI_TRI_PT, SO_LUONG, ACTIVE)

SELECT  A.MSM AS MS_MAY ,MS_BO_PHAN,MSPT AS MS_PT, CASE ISNULL([Vị trí PT ],'') WHEN '' THEN 'N/A' ELSE [Vị trí PT ] END  AS MS_VI_TRI_PT ,A.SL AS SO_LUONG,1 AS ACTIVE INTO #CTTBPTIS
FROM 
(
--cong viec cap 1
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MS_BO_PHAN, t2.TENBP1,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ], 1 AS CAP ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND T2.TENBP1 = T1.TENBP  WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') = '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''  
UNION

--cong viec cap 2
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MSBP2, t2.TENBP2,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ], 2 AS CAP ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
UNION
--cong viec cap 3
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP3, t2.TENBP3,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ], 3 AS CAP,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
UNION
--cong viec cap 4
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP4, t2.TENBP4,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ],  4 AS CAP,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> '' 
UNION
--cong viec cap 5
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP5, t2.TENBP5,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ],  5 AS CAP ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP  AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
UNION
--cong viec cap 6
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP6, t2.TENBP6,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ],  6 AS CAP  ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP   AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  AND T2.TENBP6 = T1.TENBP6  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') <> ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
) A


-----INSERT VAO CAU_TRUC_THIET_BI_PHU_TUNG
INSERT	INTO dbo.CAU_TRUC_THIET_BI_PHU_TUNG(MS_MAY, MS_BO_PHAN, MS_PT, MS_VI_TRI_PT, SO_LUONG, ACTIVE)
SELECT MS_MAY, MS_BO_PHAN, MS_PT, MS_VI_TRI_PT, MAX(SO_LUONG), ACTIVE FROM #CTTBPTIS GROUP BY 
MS_MAY, MS_BO_PHAN, MS_PT, MS_VI_TRI_PT, ACTIVE







--- CAP NHAP PHU TUNG CHA

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CTTBPTung') AND type in (N'U'))
	DROP TABLE  CTTBPTung

	SELECT * INTO CTTBPTung FROM #CTTBPT T1 WHERE ISNULL(T1.MSPT,'') <> '' AND ([PT cha] = 'X' OR [PT cha] = '1')
	
SELECT  A.MSM AS MS_MAY ,MS_BO_PHAN,MSPT AS MS_PT, CASE ISNULL([Vị trí PT ],'') WHEN '' THEN 'N/A' ELSE [Vị trí PT ] END  AS MS_VI_TRI_PT ,A.SL AS SO_LUONG,1 AS ACTIVE INTO #CTTBPCHA
FROM 
(
--cong viec cap 1
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MS_BO_PHAN, t2.TENBP1,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ], 1 AS CAP ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND T2.TENBP1 = T1.TENBP  WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') = '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''  
UNION

--cong viec cap 2
SELECT DISTINCT  T1.MSM,'' AS TENMAY ,T2.MSBP2, t2.TENBP2,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ], 2 AS CAP ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') = '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
UNION
--cong viec cap 3
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP3, t2.TENBP3,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ], 3 AS CAP,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') = '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
UNION
--cong viec cap 4
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP4, t2.TENBP4,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ],  4 AS CAP,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') = '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> '' 
UNION
--cong viec cap 5
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP5, t2.TENBP5,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ],  5 AS CAP ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP  AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5   
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') = ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
UNION
--cong viec cap 6
SELECT DISTINCT   T1.MSM,'' AS TENMAY ,T2.MSBP6, t2.TENBP6,T1.MSPT,T1.[Thông số], T1.[Vị trí PT ],  6 AS CAP  ,T1.[Số lượng ] AS SL
FROM dbo.CTTBPTung T1 INNER JOIN dbo.DATACVPT T2 ON mscha = t1.msm  AND  T2.TENBP1 = T1.TENBP   AND T2.TENBP2 = T1.TENBP2  AND T2.TENBP3 = T1.TENBP3 AND T2.TENBP4 = T1.TENBP4  AND T2.TENBP5 = T1.TENBP5  AND T2.TENBP6 = T1.TENBP6  
WHERE ISNULL(T1.TENBP,'') <> '' AND ISNULL(T1.TENBP2,'') <> '' AND ISNULL(T1.TENBP3,'') <> '' AND  ISNULL(T1.TENBP4,'') <> '' AND ISNULL(T1.TENBP5,'') <> '' AND ISNULL(T1.TENBP6,'') <> ''  AND	 ISNULL(T1.[Phụ tùng ],'') <> ''
) A


-----CAP NHAP VAO CAU TRUC THIET BI VOI CAC PHU TUNG CHA

	UPDATE dbo.CAU_TRUC_THIET_BI SET MS_PT = T1.MS_PT FROM 
(SELECT DISTINCT MS_MAY, MS_BO_PHAN, MS_PT  FROM #CTTBPCHA ) AS  T1 INNER JOIN CAU_TRUC_THIET_BI T2 ON T1.MS_MAY = T2.MS_MAY AND T1.MS_BO_PHAN = T2.MS_BO_PHAN  WHERE T2.MS_MAY = @MsMay


END