IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spImportPXK_TN')
exec('CREATE PROCEDURE spImportPXK_TN AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spImportPXK_TN
	@UserName NVARCHAR(50),
	@sBT NVARCHAR(100),
	@sSql NVARCHAR(max)
AS 
BEGIN
CREATE TABLE #APXVT(
	[ID] [BIGINT] NULL,
	[SO_PHIEU_XN] [NVARCHAR](20) NULL,
	[NGAY] [DATETIME] NULL,
	[MS_PBT] [NVARCHAR](20) NULL,
	[MS_KHO] [INT] NULL,
	[MS_VI_TRI] [INT] NULL,
	[MS_PT] [NVARCHAR](25) NULL,
	[SL] [FLOAT] NULL,
	[TT] [INT] NULL,
	[DG] [FLOAT] NULL,
	[PN] [BIT] NULL,
	[PX] [BIT] NULL
) ON [PRIMARY]

EXEC ( @sSql)
DECLARE @SPN NVARCHAR(50) 
DECLARE @sNguoiNhap NVARCHAR(50)
SET @sNguoiNhap = (SELECT TOP 1 MS_CONG_NHAN FROM dbo.CONG_NHAN_VAI_TRO WHERE MS_VAI_TRO = 4  )

DECLARE @sNguoiXuat NVARCHAR(50)
SET @sNguoiXuat = (SELECT TOP 1 MS_CONG_NHAN FROM dbo.CONG_NHAN_VAI_TRO WHERE MS_VAI_TRO = 5  )

DECLARE @UName NVARCHAR(50) = @UserName
DECLARE	 @SPInt NVARCHAR(50),@MsKho NVARCHAR(50),@NgayInt DATETIME
Declare  TaoPN CURSOR FOR
	SELECT DISTINCT MS_KHO,MIN(NGAY) FROM #APXVT GROUP BY MS_KHO
Open TaoPN
FETCH NEXT FROM TaoPN
INTO @MsKho ,@NgayInt
While @@Fetch_Status = 0
Begin
	SELECT @SPN = [dbo].[AUTO_CREATE_SO_PHIEU_NHAP](@NgayInt) 
	INSERT INTO IC_DON_HANG_NHAP(MS_DH_NHAP_PT,SO_PHIEU_XN,GIO,NGAY,MS_KHO,MS_DANG_NHAP,NGUOI_NHAP,NGAY_CHUNG_TU,SO_CHUNG_TU,GHI_CHU,LOCK,THU_KHO,LY_DO )	
	SELECT	@SPN AS MS_DH_NHAP_PT,@SPN AS SO_PHIEU_XN, CONVERT(DATETIME, CONVERT(NVARCHAR(10),@NgayInt,101) + ' ' + CONVERT(NVARCHAR(8),GETDATE(),108)) AS GIO, CONVERT(DATE, @NgayInt)  NGAY, @MsKho AS MS_KHO,2 AS MS_DANG_NHAP,@sNguoiNhap AS NGUOI_NHAP,CONVERT(DATE, @NgayInt)  AS NGAY_CHUNG_TU, @SPN AS SO_CHUNG_TU, N'Nhập INT' AS GHI_CHU, 1 AS LOCK,@UName AS THU_KHO,N'Nhập INT' AS LY_DO 

	INSERT INTO IC_DON_HANG_NHAP_VAT_TU(MS_DH_NHAP_PT,MS_PT,SO_LUONG_CTU,SL_THUC_NHAP,DON_GIA,NGOAI_TE,TY_GIA,TY_GIA_USD,			THANH_TIEN,ID,MS_DH_NHAP_PT_GOC,ID_GOC,DON_GIA_GOC	)
	SELECT @SPN AS MS_DH_NHAP_PT,MS_PT,T1.SL AS SO_LUONG_CTU,T1.SL AS SL_THUC_NHAP,DG AS DON_GIA,'VND' AS NGOAI_TE,1  AS TY_GIA,5.72E-05 AS TY_GIA_USD, T1.TT, T1.ID AS ID, @SPN AS MS_DH_NHAP_PT_GOC,T1.ID AS ID_GOC,T1.DG AS DON_GIA_GOC
	FROM #APXVT T1 WHERE T1.MS_KHO = @MsKho --AND ISNULL(PN,0) = 0

	
	INSERT INTO IC_DON_HANG_NHAP_VAT_TU_CHI_TIET(MS_DH_NHAP_PT,MS_PT,MS_VI_TRI,SL_VT,ID)	
	SELECT @SPN AS MS_DH_NHAP_PT ,MS_PT,MS_VI_TRI ,SL, ID
	FROM #APXVT  WHERE MS_KHO = @MsKho --AND ISNULL(PN,0) = 0


	UPDATE #APXVT SET PN = 1 WHERE MS_KHO = @MsKho
------Tao phieu xuat theo PBT
DECLARE @sPXuat NVARCHAR(50), @NgayXuat DATETIME, @PBT AS NVARCHAR(50)
Declare  TaoPXuat CURSOR FOR
	SELECT DISTINCT SO_PHIEU_XN,NGAY,MS_PBT FROM #APXVT WHERE MS_KHO = @MsKho
Open TaoPXuat
FETCH NEXT FROM TaoPXuat
INTO @sPXuat , @NgayXuat , @PBT 
While @@Fetch_Status = 0
BEGIN
	DECLARE @sMsDHXuat NVARCHAR(50) = 'MS_DH_XUAT_PT'
	SELECT @sMsDHXuat = [dbo].[AUTO_CREATE_SO_PHIEU_XUAT](@NgayXuat) 
	INSERT INTO [dbo].[IC_DON_HANG_XUAT] ([MS_DH_XUAT_PT],[SO_PHIEU_XN]
	,[GIO],[NGAY],[MS_KHO],[MS_DANG_XUAT],[NGUOI_NHAN],[NGAY_CHUNG_TU],[SO_CHUNG_TU],[MS_PHIEU_BAO_TRI],[GHI_CHU]
	,[LOCK],[THU_KHO],[MS_BP_CHIU_PHI],NGUOI_LAP,CAN_CU,THU_KHO_KY,LY_DO_XUAT )
	SELECT @sMsDHXuat  AS [MS_DH_XUAT_PT], @sPXuat AS [SO_PHIEU_XN], CONVERT(DATETIME, CONVERT(NVARCHAR(10),@NgayXuat,101) + ' ' + CONVERT(NVARCHAR(8),GETDATE(),108))  AS [GIO],CONVERT(DATE, @NgayXuat) AS [NGAY],@MsKho AS MS_KHO,1 AS [MS_DANG_XUAT], @sNguoiXuat AS [NGUOI_NHAN],CONVERT(DATE, @NgayXuat) AS [NGAY_CHUNG_TU], @sPXuat AS [SO_CHUNG_TU],@PBT AS [MS_PHIEU_BAO_TRI], N'Xuất INT' AS [GHI_CHU], 1 AS [LOCK], @UName AS [THU_KHO],
	(SELECT TOP 1 T2.MS_BP_CHIU_PHI FROM dbo.PHIEU_BAO_TRI T1 INNER JOIN dbo.V_MAY_BO_PHAN_CHIU_PHI_MAX T2 ON T1.MS_MAY = T2.MS_MAY WHERE T1.MS_PHIEU_BAO_TRI = @PBT) AS [MS_BP_CHIU_PHI] ,@sNguoiNhap AS NGUOI_LAP,'','',''


	INSERT INTO [dbo].[IC_DON_HANG_XUAT_VAT_TU]([MS_DH_XUAT_PT],[MS_PT],[SO_LUONG_CTU],[SO_LUONG_THUC_XUAT])
	SELECT @sMsDHXuat  AS [MS_DH_XUAT_PT],MS_PT ,SUM(T1.SL) AS [SO_LUONG_CTU] ,SUM(T1.SL) AS [SO_LUONG_THUC_XUAT]
	FROM #APXVT T1 WHERE MS_KHO = @MsKho AND SO_PHIEU_XN = @sPXuat AND NGAY = @NgayXuat AND T1.MS_PBT = @PBT -- AND ISNULL(PX,0) = 0
	GROUP BY MS_PT



	INSERT INTO [dbo].[IC_DON_HANG_XUAT_VAT_TU_CHI_TIET]([MS_DH_XUAT_PT],[MS_PT],[STT],[MS_DH_NHAP_PT],[MS_VI_TRI],[SL_VT],ID_XUAT)
	SELECT T2.MS_DH_XUAT_PT,T2.MS_PT,T2.ID AS STT,T2.MS_DH_NHAP_PT,T2.MS_VI_TRI,T2.SL_VT,T2.ID FROM (
	SELECT @sMsDHXuat  AS [MS_DH_XUAT_PT],MS_PT,@SPN AS [MS_DH_NHAP_PT], [T1].[MS_VI_TRI], SUM(T1.SL) AS [SL_VT] ,T1.ID
	FROM #APXVT T1 WHERE MS_KHO = @MsKho AND SO_PHIEU_XN = @sPXuat AND NGAY = @NgayXuat AND T1.MS_PBT = @PBT  -- AND ISNULL(PX,0) = 0
	GROUP BY T1.MS_PT,[T1].TT, [T1].[MS_VI_TRI] ,T1.ID
	)T2


FETCH NEXT FROM TaoPXuat
INTO  @sPXuat , @NgayXuat , @PBT 
End

Close TaoPXuat
Deallocate TaoPXuat



----- hit tao phieu xuat 



    FETCH NEXT FROM TaoPN
    INTO  @MsKho ,@NgayInt


End

Close TaoPN
Deallocate TaoPN
END
