IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetLoaiBTTreeListAll')
exec('CREATE PROCEDURE GetLoaiBTTreeListAll AS BEGIN SET NOCOUNT ON; END')
GO
ALTER proc [dbo].[GetLoaiBTTreeListAll]
	@UserName nvarchar(50) ='admin',
	@NNgu INT = 0
AS
BEGIN
SELECT  RTRIM(CAST(MS_LOAI_BT AS CHAR(10))) AS MS_LOAI_BT,TEN_LOAI_BT, RTRIM('@'+ CAST(MS_HT_BT AS CHAR(10))) AS MS_CHA,MS_HT_BT AS STT FROM dbo.LOAI_BAO_TRI
union
SELECT RTRIM('@'+ CAST(MS_HT_BT AS CHAR(10))) AS MS_LOAI_BT,TEN_HT_BT,'-1',-99 AS STT FROM dbo.HINH_THUC_BAO_TRI
UNION 
SELECT '-1' AS MS_LOAI_BT, '< All >' TEN_HT_BT,NULL,-1 AS STT 
ORDER BY STT,MS_CHA,TEN_LOAI_BT
END

