IF EXISTS (SELECT * FROM sys.objects WHERE [name] = 'NgayXLYCBT' AND [type] = 'TR')
    DROP TRIGGER NgayXLYCBT

GO

CREATE TRIGGER NgayXLYCBT ON [dbo].[YEU_CAU_NSD_CHI_TIET] FOR UPDATE
AS
	IF NOT UPDATE(NGAY_DBT) 
	BEGIN 
		RETURN 
	END

	UPDATE dbo.YEU_CAU_NSD_CHI_TIET SET NGAY_XU_LY = T2.NGAY_DBT FROM dbo.YEU_CAU_NSD_CHI_TIET T1 INNER JOIN INSERTED T2 ON T1.STT = T2.STT AND T1.MS_MAY = T2.MS_MAY AND T1.STT_VAN_DE = T2.STT_VAN_DE 
