
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sprptPhieuXuatKho')
   
exec('CREATE PROCEDURE sprptPhieuXuatKho AS BEGIN SET NOCOUNT ON; END')

GO

ALTER PROCEDURE sprptPhieuXuatKho
	@PXN NVARCHAR(50) = 'PX-2010-0001',
	@NNgu INT = 0,
	@PRIVATE NVARCHAR(50) = 'NUTI' 
AS
BEGIN


SELECT MS_KH AS MS, TEN_CONG_TY AS TEN_NGUOI_NHAN INTO #NGUOI_NHAN FROM dbo.KHACH_HANG
UNION
SELECT  MS_CONG_NHAN,     HO + ' ' + TEN AS HO_TEN
FROM dbo.CONG_NHAN

SELECT DISTINCT T7.SO_PHIEU_XN, T15.TEN_NGUOI_NHAN AS TEN_CONG_TY,T7.SO_CHUNG_TU,(CASE @NNgu WHEN 0 THEN T11.DANG_XUAT_VIET WHEN 1 THEN T11.DANG_XUAT_ANH END) AS TEN_DANG_XUAT, T7.NGAY, T7.GHI_CHU, T8.TEN_KHO, T8.DIA_CHI, T6.SO_LUONG_CTU, T9.QUY_CACH,(CASE @NNgu WHEN 0 THEN TEN_1 WHEN 1 THEN TEN_2 END) AS TEN,T16.TEN_VI_TRI AS VI_TRI,T5.SL_VT, T3.DON_GIA, T3.NGOAI_TE,CASE @PRIVATE WHEN N'GREENFEED' THEN ISNULL(TG_PB, 0) ELSE T5.SL_VT * ISNULL(DON_GIA, 0) * TY_GIA END AS THANH_TIEN, T5.SL_VT * ISNULL(T3.DON_GIA, 0) * T3.TY_GIA_USD AS THANH_TIEN_USD, T5.MS_DH_NHAP_PT, T7.LY_DO_XUAT, (SELECT FULL_NAME FROM dbo.USERS WHERE (USERNAME = T7.THU_KHO)) AS THU_KHO, ISNULL(T7.MS_PHIEU_BAO_TRI, '') AS MS_PHIEU_BAO_TRI, T6.GHI_CHU AS GHI_CHU_CT, ISNULL(T9.TEN_PT,'') + ' ' + ISNULL(T9.QUY_CACH,'') AS TEN_PT, T9.MS_PT, T14.TEN_BP_CHIU_PHI, T7.NGUOI_LAP, T7.CAN_CU, T7.THU_KHO_KY, T9.MS_PT_NCC,T9.MS_PT_CTY FROM dbo.TO_PHONG_BAN AS T1 RIGHT OUTER JOIN dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET AS T2 INNER JOIN dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 INNER JOIN dbo.IC_DON_HANG_NHAP AS T4 ON T3.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT ON T2.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT AND T2.MS_PT = T3.MS_PT AND T2.ID = T3.ID INNER JOIN dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS T5 INNER JOIN dbo.IC_DON_HANG_XUAT_VAT_TU AS T6 ON T5.MS_DH_XUAT_PT = T6.MS_DH_XUAT_PT AND T5.MS_PT = T6.MS_PT INNER JOIN dbo.IC_DON_HANG_XUAT AS T7 ON T6.MS_DH_XUAT_PT = T7.MS_DH_XUAT_PT INNER JOIN dbo.IC_KHO AS T8 ON T7.MS_KHO = T8.MS_KHO INNER JOIN dbo.IC_PHU_TUNG AS T9 ON T6.MS_PT = T9.MS_PT INNER JOIN dbo.DON_VI_TINH AS T10 ON T9.DVT = T10.DVT INNER JOIN dbo.DANG_XUAT AS T11 ON T7.MS_DANG_XUAT = T11.MS_DANG_XUAT ON T2.MS_DH_NHAP_PT = T5.MS_DH_NHAP_PT AND T2.MS_PT = T5.MS_PT AND T2.MS_VI_TRI = T5.MS_VI_TRI AND T2.ID = T5.ID_XUAT LEFT OUTER JOIN dbo.CONG_NHAN AS T12 ON T7.NGUOI_NHAN = T12.MS_CONG_NHAN LEFT OUTER JOIN dbo.[TO] AS T13 ON T13.MS_TO1 = T12.MS_TO ON T1.MS_TO = T13.MS_TO LEFT OUTER JOIN dbo.BO_PHAN_CHIU_PHI AS T14 ON T7.MS_BP_CHIU_PHI = T14.MS_BP_CHIU_PHI LEFT JOIN #NGUOI_NHAN T15 ON T7.NGUOI_NHAN = T15.MS INNER JOIN dbo.VI_TRI_KHO T16 ON T5.MS_VI_TRI = T16.MS_VI_TRI AND T7.MS_KHO = T16.MS_KHO WHERE (T7.MS_DH_XUAT_PT = @PXN)






END