
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spViewLogCmb')
   
exec('CREATE PROCEDURE spViewLogCmb AS BEGIN SET NOCOUNT ON; END')

GO
--SELECT * FROM dbo.USERS
ALTER PROCEDURE spViewLogCmb
	@CoAll INT = 1,
    @NNgu INT = 0,
	@UName NVARCHAR(50) = 'CNO22'
AS
BEGIN

SELECT DISTINCT T1.MENU_ID INTO #MENUTMP FROM dbo.NHOM_MENU   T1 INNER JOIN dbo.USERS T2 ON T2.GROUP_ID = T1.GROUP_ID WHERE T2.USERNAME = @UName



--exec GetNhaXuongTreeList 0,'administrator',1
SELECT * INTO #TMP FROM (
SELECT T2.MENU_ID,
CASE @NNgu WHEN 0 THEN T2.MENU_TEXT WHEN 1 THEN	 T2.MENU_ENGLISH ELSE T2.MENU_CHINESE END AS MENU_TEXT, 
CASE @NNgu WHEN 0 THEN T3.VIETNAM WHEN 1 THEN	 T3.ENGLISH ELSE T3.CHINESE END AS TEN_FORMS,
T2.MENU_PARENT
FROM dbo.CHI_TIET_FORMS T1 INNER JOIN dbo.MENU T2 ON T1.MENU_ID = T2.MENU_ID INNER JOIN (SELECT * FROM dbo.LANGUAGES WHERE FORM = KEYWORD) T3 ON T1.FORM_NAME = T3.FORM INNER JOIN #MENUTMP T4 ON T2.MENU_ID = T4.MENU_ID
WHERE LOG_VIEW = 1
UNION	
SELECT MENU_ID ,
CASE @NNgu WHEN 0 THEN T2.MENU_TEXT WHEN 1 THEN	 T2.MENU_ENGLISH ELSE T2.MENU_CHINESE END AS MENU_TEXT, 
NULL AS TEN_FORMS_VIET,NULL AS MENU_PARENT
FROM dbo.MENU T2 WHERE MENU_ID IN (
SELECT T2.MENU_PARENT
FROM dbo.CHI_TIET_FORMS T1 INNER JOIN dbo.MENU T2 ON T1.MENU_ID = T2.MENU_ID INNER JOIN #MENUTMP T3 ON T2.MENU_ID = T3.MENU_ID
WHERE LOG_VIEW = 1
))T1

IF @CoAll = 0 
BEGIN
    SELECT * FROM #TMP ORDER BY MENU_TEXT
END
ELSE	
BEGIN
    SELECT MENU_ID, MENU_TEXT, TEN_FORMS, ISNULL(MENU_PARENT,-1) AS MENU_PARENT FROM #TMP 
	UNION	SELECT	'-1',' < ALL > ',NULL,NULL
	ORDER BY MENU_TEXT
END
	


END