

----exec MTimVatTuDX '01/01/2020','09/01/2020'

ALTER procedure [dbo].[MTimVatTuDX]	
	@TNgay DATETIME,
	@DNgay DATETIME
AS
BEGIN

SELECT     A.MS_DDH AS DX, B.MS_PT, ISNULL(SUM(B.SL_THUC_NHAP),0) AS SL_THUC_NHAP,MAX(NGAY) AS NGAY_NHAP, A.MS_DH_NHAP_PT,T1.TEN_CONG_TY INTO #NHAP_TMP
FROM         dbo.IC_DON_HANG_NHAP AS A INNER JOIN
                      dbo.IC_DON_HANG_NHAP_VAT_TU AS B ON A.MS_DH_NHAP_PT = B.MS_DH_NHAP_PT LEFT JOIN 
					  dbo.KHACH_HANG T1 ON A.NGUOI_NHAP = T1.MS_KH
GROUP BY A.MS_DDH, B.MS_PT, A.MS_DANG_NHAP, A.MS_DH_NHAP_PT,T1.TEN_CONG_TY
HAVING      (A.MS_DANG_NHAP = 3)



--SELECT T1.DX, T1.MS_PT, T2.SL_THUC_NHAP, T1.NGAY_NHAP, T1.MS_DH_NHAP_PT,T1.TEN_CONG_TY  INTO #NHAP_TMP FROM 
--(
--SELECT     A.MS_DDH AS DX, B.MS_PT, ISNULL(SUM(B.SL_THUC_NHAP),0) AS SL_THUC_NHAP,NGAY AS NGAY_NHAP ,A.MS_DH_NHAP_PT,T1.TEN_CONG_TY
--FROM         dbo.IC_DON_HANG_NHAP AS A INNER JOIN
--                      dbo.IC_DON_HANG_NHAP_VAT_TU AS B ON A.MS_DH_NHAP_PT = B.MS_DH_NHAP_PT LEFT JOIN 
--					  dbo.KHACH_HANG T1 ON A.NGUOI_NHAP = T1.MS_KH
--GROUP BY A.MS_DDH, B.MS_PT, A.MS_DANG_NHAP,NGAY,A.MS_DH_NHAP_PT,T1.TEN_CONG_TY
--HAVING      (A.MS_DANG_NHAP = 3)
--) T1 INNER JOIN (
--SELECT     A.MS_DDH AS DX, B.MS_PT, ISNULL(SUM(B.SL_THUC_NHAP),0) AS SL_THUC_NHAP,MAX(NGAY) AS NGAY_NHAP 
--FROM         dbo.IC_DON_HANG_NHAP AS A INNER JOIN
--                      dbo.IC_DON_HANG_NHAP_VAT_TU AS B ON A.MS_DH_NHAP_PT = B.MS_DH_NHAP_PT
--GROUP BY A.MS_DDH, B.MS_PT, A.MS_DANG_NHAP
--HAVING      (A.MS_DANG_NHAP = 3)) T2 ON T2.DX = T1.DX AND T2.MS_PT = T1.MS_PT AND T2.NGAY_NHAP = T1.NGAY_NHAP


SELECT    T2.MS_PT,T2.TEN_PT, T2.QUY_CACH, T2.DVT AS TEN_1, T2.MS_DE_XUAT, T5.PHONG_BAN TEN_TO, 
	CASE ISNULL(T1.TEN_KHO, '') WHEN '' THEN '' ELSE T1.TEN_KHO END AS TEN_KHO, T2.SL_DE_XUAT, T8.MS_DH_NHAP_PT,T8.NGAY_NHAP,T8.TEN_CONG_TY,	T8.SL_THUC_NHAP,
	 T2.GHI_CHU, CASE ISNULL(T1.MS_KHO, '') WHEN '' THEN 0 ELSE T1.MS_KHO END AS MS_KHO 
FROM        
                      dbo.DE_XUAT_MUA_HANG_CHI_TIET AS T2 INNER JOIN
                      dbo.DE_XUAT_MUA_HANG AS T5 ON T2.MS_DE_XUAT = T5.MS_DE_XUAT LEFT JOIN
                      #NHAP_TMP T8 ON T2.MS_DE_XUAT = T8.DX AND T2.MS_PT = T8.MS_PT LEFT JOIN   
					  dbo.IC_KHO AS T1 ON T1.MS_KHO = T5.MS_KHO
WHERE     (T5.NGAY_LAP BETWEEN @TNGAY AND @DNGAY )
ORDER BY TEN_KHO,T2.MS_PT,T2.TEN_PT, T2.MS_DE_XUAT, T8.MS_DH_NHAP_PT DESC,T8.NGAY_NHAP DESC	,T8.TEN_CONG_TY
END



