

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spViewLogData')
   
exec('CREATE PROCEDURE spViewLogData AS BEGIN SET NOCOUNT ON; END')
--SELECT * FROM dbo.W_HE_THONG ORDER BY CREATEDATE DESC	
GO
--SELECT * FROM dbo.USERS
ALTER PROCEDURE spViewLogData
	@MenuView NVARCHAR(50) = 'mnuHeThong',
	@TNgay DATETIME = '12/15/2001',
	@DNgay DATETIME = '12/30/2020',
	@NNgu INT = 0
AS
BEGIN
/*
@MenuView NVARCHAR(50) = '-1' coi all thao tac log -- lấy du liệu trong table W_LOG      
mnuWork	2. 2. Danh mục công việc -- from  frmDanhmuccongviec
mnuMaintenanceForm	2. 6. Hình thức / Loai bảo trì -- from  frmBaoTri
mnuArea		2.19. Địa điểm hoạt động   --  frmBranch
mnuHeThong	2. 8. Dây chuyền	-- frmDanhmuchethong
mnuHieuchuan	5.6. Kiểm định và hiệu chuẩn	--frmHieuchuan
*/

--SELECT * FROM dbo.MENU ORDER BY MENU_TEXT
--Lấy nn form
SELECT FORM, T2.MENU_ID,
CASE @NNgu WHEN 0 THEN VIETNAM WHEN 1 THEN ENGLISH ELSE CHINESE END AS TEN_FORMS
, MENU_TEXT
INTO #L_TMP FROM dbo.LANGUAGES  T1 
LEFT JOIN 	(SELECT FORM_NAME,CASE 0 WHEN 0 THEN T2.MENU_TEXT WHEN 1 THEN	 T2.MENU_ENGLISH ELSE T2.MENU_CHINESE END AS MENU_TEXT,T1.MENU_ID FROM dbo.CHI_TIET_FORMS T1 INNER JOIN dbo.MENU T2 ON T1.MENU_ID = T2.MENU_ID WHERE LOG_VIEW = 1) T2 ON T1.FORM = T2.FORM_NAME 
WHERE FORM = KEYWORD


DECLARE @Them NVARCHAR(10) ,@Sua NVARCHAR(10),@Xoa  NVARCHAR(10)

IF @NNgu = 0 
BEGIN
	SET @Them = N'Thêm'
	SET	@Sua = N'Sửa'
	SET @Xoa = N'Xoá'
END
ELSE
BEGIN
	SET @Them = N'Add'
	SET	@Sua = N'Edit'
	SET @Xoa = N'Delete'    
END

IF @MenuView = '-1' 
BEGIN
	SELECT DISTINCT 
	ROW_NUMBER() OVER (	ORDER BY CONVERT(DATETIME, CONVERT(VARCHAR,T1.NGAY,120))  DESC,
	ISNULL(T2.MENU_TEXT,ISNULL(T2.TEN_FORMS,T1.FORM_NAME)),
	TEN_FORMS) AS STT,
	ISNULL(T2.MENU_TEXT,ISNULL(T2.TEN_FORMS,T1.FORM_NAME)) AS MENU_TEXT,
	ISNULL(T2.TEN_FORMS,T1.FORM_NAME) AS TEN_FORMS,T1.USER_SIGN,CONVERT(DATETIME, CONVERT(VARCHAR,T1.NGAY,120))   AS CREATEDATE, CASE T1.THAOTAC WHEN 1 THEN @Them WHEN 2 THEN @Sua WHEN 3 THEN @Xoa END AS THAOTAC , CONVERT(INT,ISNULL(T1.THAOTAC,0)) AS TT,T2.MENU_ID
	FROM dbo.W_LOG T1 LEFT JOIN #L_TMP T2 ON T1.FORM_NAME = T2.FORM 
	WHERE CONVERT(DATE,T1.NGAY) BETWEEN @TNgay AND @DNgay
	ORDER BY CONVERT(DATETIME, CONVERT(VARCHAR,T1.NGAY,120))  DESC,
	ISNULL(T2.MENU_TEXT,ISNULL(T2.TEN_FORMS,T1.FORM_NAME)),
	TEN_FORMS
	

END

--mnuWork	2. 2. Danh mục công việc
BEGIN
IF @MenuView = 'mnuWork' 
BEGIN
SELECT DISTINCT T1.MS_CV,T1.MO_TA_CV, T1.MO_TA_CV_ANH, T1.KY_HIEU_CV, T1.AN_TOAN, T1.TEN_LOAI_MAY, T1.TEN_LOAI_CV, T1.TEN_CHUYEN_MON, T1.TEN_BAC_THO, T1.SO_NGUOI, T1.THOI_GIAN_DU_KIEN, T1.THAO_TAC, T1.TIEU_CHUAN_KT, T1.YEU_CAU_NS, T1.YEU_CAU_DUNG_CU, T1.GHI_CHU, T1.PATH_HD, T1.USER_SIGN, T1.CREATEDATE, T1.THAOTAC,TT  INTO	  #TmpWork
FROM (
	SELECT T1.MS_CV,MO_TA_CV, MO_TA_CV_ANH, KY_HIEU_CV, AN_TOAN,T2.TEN_LOAI_MAY,T4.TEN_LOAI_CV,T5.TEN_CHUYEN_MON, T3.TEN_BAC_THO, SO_NGUOI,THOI_GIAN_DU_KIEN,THAO_TAC,  TIEU_CHUAN_KT,YEU_CAU_NS, YEU_CAU_DUNG_CU,  T1.GHI_CHU, PATH_HD,T1.USER_SIGN, T1.CREATEDATE,
	CASE T1.THAOTAC WHEN 1 THEN @Them WHEN 2 THEN @Sua WHEN 3 THEN @Xoa END AS THAOTAC , T1.THAOTAC AS TT
	FROM dbo.W_CONG_VIEC T1 LEFT JOIN dbo.LOAI_MAY T2 ON T2.MS_LOAI_MAY = T1.MS_LOAI_MAY LEFT JOIN dbo.BAC_THO T3 ON T3.MS_BAC_THO = T1.MS_BAC_THO LEFT JOIN dbo.LOAI_CONG_VIEC T4 ON T4.MS_LOAI_CV = T1.MS_LOAI_CV LEFT JOIN dbo.CHUYEN_MON T5 ON T5.MS_CHUYEN_MON = T1.MS_CHUYEN_MON
	WHERE CONVERT(DATE,T1.CREATEDATE) BETWEEN @TNgay AND @DNgay
	UNION	
	SELECT T1.MS_CV,MO_TA_CV, MO_TA_CV_ANH, KY_HIEU_CV, AN_TOAN,T2.TEN_LOAI_MAY,T4.TEN_LOAI_CV,T5.TEN_CHUYEN_MON, T3.TEN_BAC_THO, SO_NGUOI,THOI_GIAN_DU_KIEN,THAO_TAC,  TIEU_CHUAN_KT,YEU_CAU_NS, YEU_CAU_DUNG_CU,  T1.GHI_CHU, PATH_HD, NULL AS USER_SIGN,NULL AS CREATEDATE, NULL THAOTAC , CONVERT(INT,0) AS TT
	FROM dbo.CONG_VIEC T1 LEFT JOIN dbo.LOAI_MAY T2 ON T2.MS_LOAI_MAY = T1.MS_LOAI_MAY LEFT JOIN dbo.BAC_THO T3 ON T3.MS_BAC_THO = T1.MS_BAC_THO LEFT JOIN dbo.LOAI_CONG_VIEC T4 ON T4.MS_LOAI_CV = T1.MS_LOAI_CV LEFT JOIN dbo.CHUYEN_MON T5 ON T5.MS_CHUYEN_MON = T1.MS_CHUYEN_MON
	WHERE T1.MS_CV IN(SELECT MS_CV FROM dbo.W_CONG_VIEC WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay )
	) T1

	SELECT T1.MS_CV, T1.MO_TA_CV, T1.MO_TA_CV_ANH, T1.KY_HIEU_CV, T1.AN_TOAN, T1.TEN_LOAI_MAY, T1.TEN_LOAI_CV, T1.TEN_CHUYEN_MON, T1.TEN_BAC_THO, T1.SO_NGUOI, T1.THOI_GIAN_DU_KIEN, T1.THAO_TAC, T1.TIEU_CHUAN_KT, T1.YEU_CAU_NS, T1.YEU_CAU_DUNG_CU, T1.GHI_CHU, T1.PATH_HD, T1.USER_SIGN, T1.CREATEDATE, T1.THAOTAC, T1.TT FROM #TmpWork T1 ORDER BY  (SELECT MAX(T2.CREATEDATE) FROM #TmpWork T2 WHERE T1.MS_CV = T2.MS_CV) DESC, ISNULL(CREATEDATE,GETDATE()) DESC	
END
END

--mnuMaintenanceForm	2. 6. Hình thức / Loai bảo trì
BEGIN
IF @MenuView = 'mnuMaintenanceForm' 
BEGIN
SELECT DISTINCT T1.TEN_HT_BT, T1.TEN_LOAI_BT, T1.THU_TU, T1.GHI_CHU, T1.HU_HONG, T1.USER_SIGN, T1.CREATEDATE, T1.THAOTAC, TT, T1.MS_HT_BT,T1.MS_LOAI_BT  INTO	  #TmpMaintenanceForm 
FROM 
(
	SELECT DISTINCT	T2.TEN_HT_BT, T1.TEN_LOAI_BT, T1.THU_TU, T1.GHI_CHU, T1.HU_HONG,T1.MS_HT_BT, MS_LOAI_BT, T1.FORM_NAME, T1.USER_SIGN, T1.CREATEDATE, CASE T1.THAO_TAC WHEN 1 THEN @Them WHEN 2 THEN @Sua WHEN 3 THEN @Xoa END AS THAOTAC  , T1.THAO_TAC AS TT  
	FROM W_LOAI_BAO_TRI T1 INNER JOIN dbo.HINH_THUC_BAO_TRI T2 ON T1.MS_HT_BT = T2.MS_HT_BT 
	WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay
	UNION
	SELECT DISTINCT	T2.TEN_HT_BT, T1.TEN_LOAI_BT, T1.THU_TU, T1.GHI_CHU, T1.HU_HONG,T1.MS_HT_BT, MS_LOAI_BT, NULL  FORM_NAME, NULL USER_SIGN, NULL AS CREATEDATE, NULL THAOTAC , CONVERT(INT,0) AS TT  
	FROM LOAI_BAO_TRI T1 INNER JOIN dbo.HINH_THUC_BAO_TRI T2 ON T1.MS_HT_BT = T2.MS_HT_BT  
	WHERE T1.MS_LOAI_BT IN(SELECT MS_LOAI_BT FROM dbo.W_LOAI_BAO_TRI WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay)
) T1
	ORDER BY  MS_HT_BT, MS_LOAI_BT,TT DESC, CREATEDATE DESC	

	SELECT T1.MS_HT_BT,TEN_HT_BT,T1.MS_LOAI_BT, TEN_LOAI_BT, THU_TU, GHI_CHU, HU_HONG, USER_SIGN, CREATEDATE, THAOTAC,TT FROM #TmpMaintenanceForm T1
	ORDER BY  (SELECT MAX(T2.CREATEDATE) FROM #TmpMaintenanceForm T2 WHERE T1.MS_HT_BT = T2.MS_HT_BT AND  T1.MS_LOAI_BT = T2.MS_LOAI_BT ) DESC, ISNULL(CREATEDATE,GETDATE()) DESC	
END
END

--mnuArea		2.19. Địa điểm hoạt động
BEGIN
IF @MenuView = 'mnuArea' 
BEGIN

SELECT T1.MS_CHA, T1.TEN_NX_CHA, T1.MS_N_XUONG, T1.Ten_N_XUONG, T1.TEN_N_XUONG_A, T1.TEN_N_XUONG_H, T1.TRU_SO, T1.NGUOI_DAI_DIEN, T1.DIEN_THOAI, T1.DIA_CHI, T1.DIEN_TICH, T1.KHOANG_CACH, T1.GHI_CHU, T1.TEN_DON_VI, T1.USER_SIGN, T1.CREATEDATE, T1.THAOTAC,  T1.TT  INTO #TmpArea	 FROM 
(
	SELECT ISNULL(MS_CHA,T1.MS_N_XUONG) AS MS_CHA,(SELECT T2.Ten_N_XUONG FROM dbo.NHA_XUONG T2 WHERE T2.MS_N_XUONG = ISNULL(T1.MS_CHA,T1.MS_N_XUONG)) AS TEN_NX_CHA, MS_N_XUONG,  Ten_N_XUONG, TEN_N_XUONG_A, TEN_N_XUONG_H, TRU_SO, NGUOI_DAI_DIEN, DIEN_THOAI, DIA_CHI, DIEN_TICH, KHOANG_CACH, GHI_CHU, (SELECT T2.TEN_DON_VI FROM dbo.DON_VI T2 WHERE T2.MS_DON_VI =  T1.MS_DON_VI) AS TEN_DON_VI, USER_SIGN,  CREATEDATE, CASE T1.THAO_TAC WHEN 1 THEN @Them WHEN 2 THEN @Sua WHEN 3 THEN @Xoa END AS THAOTAC , T1.THAO_TAC AS TT 
	FROM W_NHA_XUONG T1
	WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay
	UNION	

	SELECT ISNULL(MS_CHA,T1.MS_N_XUONG) AS MS_CHA,(SELECT T2.Ten_N_XUONG FROM dbo.NHA_XUONG T2 WHERE T2.MS_N_XUONG = ISNULL(T1.MS_CHA,T1.MS_N_XUONG)) AS TEN_NX_CHA,  MS_N_XUONG, Ten_N_XUONG, TEN_N_XUONG_A, TEN_N_XUONG_H, TRU_SO, NGUOI_DAI_DIEN, DIEN_THOAI, DIA_CHI, DIEN_TICH, KHOANG_CACH, GHI_CHU, (SELECT T2.TEN_DON_VI FROM dbo.DON_VI T2 WHERE T2.MS_DON_VI =  T1.MS_DON_VI) AS TEN_DON_VI, NULL USER_SIGN, NULL AS CREATEDATE, NULL THAOTAC , CONVERT(INT,0) AS TT FROM dbo.NHA_XUONG T1
	WHERE T1.MS_N_XUONG IN(SELECT MS_N_XUONG FROM dbo.W_NHA_XUONG WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay)
	
) T1

	SELECT *		 FROM #TmpArea T1 ORDER BY  (SELECT MAX(T2.CREATEDATE) FROM #TmpArea T2 WHERE T1.MS_N_XUONG = T2.MS_N_XUONG ) DESC, ISNULL(CREATEDATE,GETDATE()) DESC	

END
END

--mnuHeThong	2. 8. Dây chuyền
BEGIN
IF @MenuView = 'mnuHeThong' 
BEGIN
SELECT T1.MS_HE_THONG, T1.TEN_HE_THONG, T1.GHI_CHU, T1.NO_LINE, 
T1.USER_SIGN, T1.CREATEDATE, THAOTAC, T1.TT   INTO	  #TmpHeThong 
FROM 
(
	SELECT	T1.MS_HE_THONG, T1.TEN_HE_THONG, T1.GHI_CHU, T1.NO_LINE, T1.MA_HE_THONG,
		USER_SIGN,  CREATEDATE,  
		CASE T1.THAO_TAC WHEN 1 THEN @Them WHEN 2 THEN @Sua WHEN 3 THEN @Xoa END AS THAOTAC  , T1.THAO_TAC AS TT  
		
	FROM dbo.W_HE_THONG T1
	WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay
	UNION	
	
	SELECT T1.MS_HE_THONG, T1.TEN_HE_THONG, T1.GHI_CHU, T1.NO_LINE, T1.MA_HE_THONG,
	NULL USER_SIGN, NULL AS CREATEDATE, NULL THAOTAC , CONVERT(INT,0) AS TT 
	FROM dbo.HE_THONG T1
	WHERE T1.MS_HE_THONG IN(SELECT MS_HE_THONG FROM dbo.W_HE_THONG WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay)
	
) T1
	ORDER BY  MS_HE_THONG,TT DESC, CREATEDATE DESC	

	SELECT * FROM #TmpHeThong T1
	ORDER BY  (SELECT MAX(T2.CREATEDATE) FROM #TmpHeThong T2 WHERE T1.MS_HE_THONG = T2.MS_HE_THONG) DESC, ISNULL(CREATEDATE,GETDATE()) DESC	
END
END

--mnuHieuchuan	5.6. Kiểm định và hiệu chuẩn	--frmHieuchuan
BEGIN
IF @MenuView = 'mnuHieuchuan' 
BEGIN
SELECT T1.MS_HE_THONG, T1.TEN_HE_THONG, T1.GHI_CHU, T1.NO_LINE, 
T1.USER_SIGN, T1.CREATEDATE, THAOTAC, T1.TT   INTO	  #TmpHieuchuan 
FROM 
(
	SELECT	T1.MS_HE_THONG, T1.TEN_HE_THONG, T1.GHI_CHU, T1.NO_LINE, T1.MA_HE_THONG,
		USER_SIGN,  CREATEDATE,  
		CASE T1.THAO_TAC WHEN 1 THEN @Them WHEN 2 THEN @Sua WHEN 3 THEN @Xoa END AS THAOTAC  , T1.THAO_TAC AS TT  
		
	FROM dbo.W_HE_THONG T1
	WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay
	UNION	
	
	SELECT T1.MS_HE_THONG, T1.TEN_HE_THONG, T1.GHI_CHU, T1.NO_LINE, T1.MA_HE_THONG,
	NULL USER_SIGN, NULL AS CREATEDATE, NULL THAOTAC , CONVERT(INT,0) AS TT 
	FROM dbo.HE_THONG T1
	WHERE T1.MS_HE_THONG IN(SELECT MS_HE_THONG FROM dbo.W_HE_THONG WHERE CONVERT(DATE,CREATEDATE) BETWEEN @TNgay AND @DNgay)
	
) T1
	ORDER BY  MS_HE_THONG,TT DESC, CREATEDATE DESC	

	SELECT * FROM #TmpHieuchuan T1
	ORDER BY  (SELECT MAX(T2.CREATEDATE) FROM #TmpHieuchuan T2 WHERE T1.MS_HE_THONG = T2.MS_HE_THONG) DESC, ISNULL(CREATEDATE,GETDATE()) DESC	
END
END





END