


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spDDNhomCNhan')
   
exec('CREATE PROCEDURE spDDNhomCNhan AS BEGIN SET NOCOUNT ON; END')

GO

ALTER PROCEDURE spDDNhomCNhan
	@Action INT = 4, --1 Cmb
	@UName NVARCHAR(50) = 'admin',
	@NNgu INT = 0

AS
BEGIN

SELECT MS_CONG_NHAN,HO,TEN, HOTEN,TEN_DON_VI,TEN_PHONG_BAN, TEN_TO ,MS_DON_VI, MS_PHONG_BAN,MS_TO,BO_VIEC  INTO #PBUser FROM dbo.MGetCongNhanToPhongBan(@UName,'-1','-1',-1,-1,@NNgu)


		 
--LOAD CMB DD NHOM
IF @Action = 1 
BEGIN
	SELECT ID_NHOM_DD, CASE @NNgu WHEN 0 THEN TEN_NHOM WHEN 1 THEN ISNULL(NULLIF(TEN_NHOM_ANH,''),TEN_NHOM) ELSE ISNULL(NULLIF(TEN_NHOM_HOA,''),TEN_NHOM)  END AS TEN_NHOM ,  GHI_CHU FROM dbo.DIEU_DO_NHOM 
	UNION	SELECT -1, ' < ALL > ', NULL
	ORDER BY TEN_NHOM
END


--LOAD LUOI DD NHOM cong nhan view luoi
IF @Action = 2 
BEGIN
	SELECT T1.MS_CONG_NHAN,T2.HOTEN,T2.TEN_DON_VI,T2.TEN_PHONG_BAN,T2.TEN_TO,T1.ID_NHOM_DD,T1.GHI_CHU, T2.MS_DON_VI,T2.MS_TO,T2.MS_PHONG_BAN  FROM dbo.DIEU_DO_NHOM_CN T1 INNER JOIN #PBUser T2 ON T2.MS_CONG_NHAN = T1.MS_CONG_NHAN ORDER BY  T2.TEN,T1.MS_CONG_NHAN

END

--LOAD CMB DD NHOM  LUOI
IF @Action = 3 
BEGIN
	SELECT ID_NHOM_DD, CASE @NNgu WHEN 0 THEN TEN_NHOM WHEN 1 THEN ISNULL(NULLIF(TEN_NHOM_ANH,''),TEN_NHOM) ELSE ISNULL(NULLIF(TEN_NHOM_HOA,''),TEN_NHOM)  END AS TEN_NHOM ,  GHI_CHU FROM dbo.DIEU_DO_NHOM 
	UNION	SELECT -99, NULL, NULL
	ORDER BY TEN_NHOM

END

--LOAD LUOI DD NHOM CN THEM SUA
IF @Action = 4 
BEGIN
	SELECT T2.MS_CONG_NHAN,T2.HOTEN,TEN_DON_VI,T2.TEN_PHONG_BAN,T2.TEN_TO,T1.ID_NHOM_DD,T1.GHI_CHU,T2.MS_DON_VI,T2.MS_TO,T2.MS_PHONG_BAN FROM dbo.DIEU_DO_NHOM_CN T1 RIGHT JOIN #PBUser T2 ON T2.MS_CONG_NHAN = T1.MS_CONG_NHAN WHERE  (ISNULL(T2.BO_VIEC,0) <> 1) 
	ORDER BY  T2.TEN,T1.MS_CONG_NHAN
END

END

