


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spDDNhomMay')
   
exec('CREATE PROCEDURE spDDNhomMay AS BEGIN SET NOCOUNT ON; END')

GO

ALTER PROCEDURE spDDNhomMay
	@Action INT = 4, --1 Cmb
	@UName NVARCHAR(50) = 'admin',
	@NNgu INT = 0

AS
BEGIN

--Nha xuong
;with cte(MS_N_XUONG, MS_CHA,[ALL_CHA])
AS 
(
select MS_N_XUONG, MS_CHA , CAST('' AS NVARCHAR(MAX))  AS ALL_CHA from 
dbo.NHA_XUONG
where MS_CHA is null 
UNION ALL
select A.MS_N_XUONG, A.MS_CHA,
cast ((B.ALL_CHA + cast(A.MS_CHA as nvarchar(50)) +', ') as NVARCHAR(MAX)) 
from 
dbo.NHA_XUONG A 
inner join cte B
ON A.MS_CHA=B.MS_N_XUONG
) 
select MS_N_XUONG, CASE substring(ALL_CHA,0,LEN(ALL_CHA)) WHEN '' THEN MS_N_XUONG ELSE substring(ALL_CHA,0,LEN(ALL_CHA)) END  AS MS_NX_CHA  INTO #NX_CHA from cte 
ORDER BY MS_N_XUONG

--He Thong
;with cte(MS_HE_THONG, MS_CHA,[ALL_CHA])
AS 
(
select MS_HE_THONG, MS_CHA , CAST('' AS NVARCHAR(MAX))  AS ALL_CHA from 
dbo.HE_THONG
where MS_CHA is null 
UNION ALL
select A.MS_HE_THONG, A.MS_CHA,cast ((B.ALL_CHA + cast(A.MS_CHA as nvarchar(50)) +', ') as NVARCHAR(MAX))from 
dbo.HE_THONG A 
inner join cte B
ON A.MS_CHA=B.MS_HE_THONG
) 

select MS_HE_THONG, 
CONVERT(NVARCHAR(MAX),CASE substring(ALL_CHA,0,LEN(ALL_CHA)) WHEN '' THEN MS_HE_THONG ELSE substring(ALL_CHA,0,LEN(ALL_CHA)) END)  AS MS_HT_CHA  INTO #HT_CHA from cte 
ORDER BY MS_HE_THONG






SELECT A.MS_MAY,A.TEN_MAY,A.MS_N_XUONG,A.MS_HE_THONG,A.MS_LOAI_MAY,A.Ten_N_XUONG,A.TEN_HE_THONG,A.TEN_LOAI_MAY,ISNULL(T3.MS_NX_CHA,A.MS_N_XUONG) AS MS_NX_CHA ,ISNULL(T4.MS_HT_CHA,A.MS_HE_THONG) AS MS_HT_CHA INTO #MAY FROM dbo.MGetMayUserNgay(GETDATE(),@UName,'-1',-1,-1,-1,'-1','-1', @NNgu) A  LEFT JOIN #NX_CHA T3 ON A.MS_N_XUONG = T3.MS_N_XUONG LEFT JOIN #HT_CHA T4 ON A.MS_HE_THONG = T4.MS_HE_THONG  	  
--LOAD CMB DD NHOM
IF @Action = 1 
BEGIN
	SELECT ID_NHOM_DD, CASE @NNgu WHEN 0 THEN TEN_NHOM WHEN 1 THEN ISNULL(NULLIF(TEN_NHOM_ANH,''),TEN_NHOM) ELSE ISNULL(NULLIF(TEN_NHOM_HOA,''),TEN_NHOM)  END AS TEN_NHOM ,  GHI_CHU FROM dbo.DIEU_DO_NHOM 
	UNION	SELECT -1, ' < ALL > ', NULL
	ORDER BY TEN_NHOM
END


--LOAD LUOI DD NHOM MAY view luoi
IF @Action = 2 
BEGIN
 

	SELECT  T1.MS_MAY,T2.TEN_MAY,T2.Ten_N_XUONG,T2.TEN_HE_THONG,T2.TEN_LOAI_MAY,ID_NHOM_DD, T1.GHI_CHU,T2.MS_N_XUONG,T2.MS_HE_THONG,T2.MS_LOAI_MAY,T2.MS_NX_CHA,T2.MS_HT_CHA FROM dbo.DIEU_DO_NHOM_MAY T1 INNER JOIN #MAY T2 ON T1.MS_MAY = T2.MS_MAY  ORDER BY  T1.MS_MAY

END

--LOAD CMB DD NHOM  LUOI
IF @Action = 3 
BEGIN
	SELECT ID_NHOM_DD, CASE @NNgu WHEN 0 THEN TEN_NHOM WHEN 1 THEN ISNULL(NULLIF(TEN_NHOM_ANH,''),TEN_NHOM) ELSE ISNULL(NULLIF(TEN_NHOM_HOA,''),TEN_NHOM)  END AS TEN_NHOM ,  GHI_CHU FROM dbo.DIEU_DO_NHOM 
	UNION	SELECT -99, NULL, NULL
	ORDER BY TEN_NHOM
END

--LOAD LUOI DD NHOM MAY THEM SUA
IF @Action = 4 
BEGIN
--ISNULL(ID_NHOM_DD,-99) AS
	SELECT  T2.MS_MAY,T2.TEN_MAY, T2.Ten_N_XUONG,T2.TEN_HE_THONG,T2.TEN_LOAI_MAY, ID_NHOM_DD, T1.GHI_CHU,T2.MS_N_XUONG,T2.MS_HE_THONG,T2.MS_LOAI_MAY,T2.MS_NX_CHA,T2.MS_HT_CHA FROM dbo.DIEU_DO_NHOM_MAY T1 RIGHT JOIN #MAY T2 ON T1.MS_MAY = T2.MS_MAY ORDER BY  T2.MS_MAY,T2.TEN_MAY

END


END

