

-- EXEC spGetPTHTDX -1,'04/01/2020','04/17/2021',-1,'ADMINISTRATOR',0
ALTER procedure [dbo].[spGetPTHTDX]
	@PhongBan INT,
	@TuNgay datetime,
	@DenNgay datetime,
	@IsLock INT,
	@UserName nvarchar(50),
	@NNgu INT
AS
BEGIN
declare @GroupID INT
SELECT @GroupID = GROUP_ID FROM USERS WHERE USERNAME = @UserName

CREATE TABLE #TMP(
	MS_DE_XUAT [nvarchar](250) NULL,
	MS_PT [nvarchar](250) NULL,
	SL_DX FLOAT NOT NULL,
	SL_NH FLOAT NOT NULL
 ) 

DECLARE @DDH_XMH BIT
SELECT TOP 1 @DDH_XMH = DDH_DXMH FROM THONG_TIN_CHUNG


CREATE TABLE #DXMH(
	MS_DE_XUAT [nvarchar](250) NULL, TRANG_THAI INT 
 ) 


INSERT INTO #DXMH(MS_DE_XUAT,T1.TRANG_THAI)
SELECT DISTINCT T1.MS_DE_XUAT,T1.TRANG_THAI FROM dbo.DE_XUAT_MUA_HANG T1 INNER JOIN dbo.NHOM_TO_PHONG_BAN AS T2 ON T2.MS_TO = T1.MS_TO
WHERE (T1.NGAY_LAP BETWEEN @TuNgay AND @DenNgay)
			AND (T1.MS_TO = @PhongBan OR  @PhongBan = -1 )
			AND (T2.GROUP_ID = @GroupID)



IF @DDH_XMH = 0 
BEGIN
	INSERT INTO #TMP (MS_DE_XUAT, MS_PT, SL_DX, SL_NH )
	SELECT  T.MS_DE_XUAT, T1.MS_PT, ISNULL(ROUND(T1.SL_DX,2),0) AS SL_DX, ISNULL(ROUND(T2.SL_NH,2),0) AS SL_NH
	FROM #DXMH T LEFT JOIN 
	(
			SELECT T1.MS_DE_XUAT, A.MS_PT, SUM(SL_DA_DUYET) AS SL_DX FROM #DXMH T1 INNER JOIN dbo.DE_XUAT_MUA_HANG_CHI_TIET A ON A.MS_DE_XUAT = T1.MS_DE_XUAT
			GROUP BY T1.MS_DE_XUAT, A.MS_PT
			UNION
			SELECT DISTINCT T1.MS_DE_XUAT,'DXDV', 1 AS SL_DX FROM #DXMH T1 INNER JOIN dbo.DE_XUAT_MUA_HANG_DICH_VU T2 ON T2.MS_DE_XUAT = T1.MS_DE_XUAT

	) T1 ON T1.MS_DE_XUAT = T.MS_DE_XUAT LEFT JOIN 
	(
			SELECT   A.MS_DDH AS MSDX, B.MS_PT,  SUM(B.SL_THUC_NHAP) AS SL_NH
			FROM         dbo.IC_DON_HANG_NHAP AS A INNER JOIN
								  dbo.IC_DON_HANG_NHAP_VAT_TU AS B ON A.MS_DH_NHAP_PT = B.MS_DH_NHAP_PT
			WHERE     (A.MS_DANG_NHAP = 3) 
			GROUP BY A.MS_DDH, B.MS_PT
			UNION
			SELECT DISTINCT T1.MS_DE_XUAT,'DXDV', 1 AS SL_NH FROM #DXMH T1 INNER JOIN dbo.DE_XUAT_MUA_HANG_DICH_VU T2 ON T2.MS_DE_XUAT = T1.MS_DE_XUAT WHERE T1.TRANG_THAI = 4
	) T2 ON T1.MS_DE_XUAT = T2.MSDX AND T1.MS_PT = T2.MS_PT
END
ELSE
BEGIN
	INSERT INTO #TMP (MS_DE_XUAT, MS_PT, SL_DX, SL_NH )
	SELECT  T1.MS_DE_XUAT, T1.MS_PT, T1.SL_DX, T2.SL_NH 
	FROM
	(
			SELECT T1.MS_DE_XUAT, A.MS_PT, SUM(A.SL_DA_DUYET) AS SL_DX FROM  #DXMH T1 INNER JOIN dbo.DE_XUAT_MUA_HANG_CHI_TIET A ON A.MS_DE_XUAT = T1.MS_DE_XUAT 
			GROUP BY T1.MS_DE_XUAT, A.MS_PT
	) T1 INNER JOIN 
	(
	SELECT   MS_DE_XUAT AS MSDX, MS_PT,  SUM(SL_DAT_HANG) AS SL_NH
	FROM  dbo.DON_DAT_HANG_CHI_TIET 
	GROUP BY MS_DE_XUAT , MS_PT
	) T2 ON T1.MS_DE_XUAT = T2.MSDX AND T1.MS_PT = T2.MS_PT
END


DECLARE @TDX NVARCHAR(250)
DECLARE @THT NVARCHAR(250)
DECLARE @PT NVARCHAR(250)
SELECT @TDX = NULLIF(CASE @NNgu WHEN 0 THEN VIETNAM WHEN 1 THEN ENGLISH ELSE CHINESE END,'') FROM dbo.LANGUAGES WHERE FORM = 'frmDeXuatMuaHang_New' AND KEYWORD =  'lblTongDeXuat'
SELECT @THT = NULLIF(CASE @NNgu WHEN 0 THEN VIETNAM WHEN 1 THEN ENGLISH ELSE CHINESE END,'') FROM dbo.LANGUAGES WHERE FORM = 'frmDeXuatMuaHang_New' AND KEYWORD =  'lblTongHoanThanh'
SELECT @PT = NULLIF(CASE @NNgu WHEN 0 THEN VIETNAM WHEN 1 THEN ENGLISH ELSE CHINESE END,'') FROM dbo.LANGUAGES WHERE FORM = 'frmDeXuatMuaHang_New' AND KEYWORD =  'lblPhanTramHT'

DECLARE @NewLineChar AS CHAR(2) = CHAR(13) + CHAR(10)


SELECT 
ISNULL(CONVERT(NVARCHAR(250),@TDX + CONVERT(NVARCHAR(20),ROUND(T2.TDX,2))),N'Tổng vật tư đề xuất : ') + @NewLineChar +
ISNULL(CONVERT(NVARCHAR(250),@THT + CONVERT(NVARCHAR(20),ROUND(T2.HT,2))),N'Tổng vật tư hoàn thành : ') + @NewLineChar +
ISNULL(CONVERT(NVARCHAR(250),@PT + CONVERT(NVARCHAR(20),T2.PT) + '%' ),N'Phần trăm hoàn thành : ') AS PTHT
FROM (
SELECT CONVERT(FLOAT,ISNULL(SUM(TDX),0)) AS TDX, CONVERT(FLOAT,(ISNULL(SUM(HT),0))) AS HT,CONVERT(FLOAT,ISNULL(SUM(CHT),0)) AS CHT, 


CASE WHEN SUM(TDX) > 0 THEN (100 * CONVERT(FLOAT,(ISNULL(SUM(HT),0)))) / SUM(TDX) ELSE 0 END AS PT 

FROM (

SELECT 
COUNT(TDX) AS TDX,
CASE WHEN  A.TTHAI = 2 THEN COUNT(A.TTHAI) ELSE 0 END AS HT,
CASE WHEN A.TTHAI <> 2 THEN COUNT(A.TTHAI) ELSE 0 END AS CHT

FROM (
SELECT MS_DE_XUAT,TDX, CASE ISNULL(SL_DX,0) WHEN 0 THEN 0 
			ELSE
				CASE ISNULL(SL_DX,0) - ISNULL(SL_NH,0) WHEN 0 THEN 2 
				ELSE 1 END 
			END AS TTHAI FROM 
(SELECT MS_DE_XUAT,MS_PT ,COUNT(MS_PT) AS TDX, SUM(SL_DX) AS SL_DX, SUM(SL_NH) AS SL_NH FROM #TMP GROUP BY MS_DE_XUAT,MS_PT) T1

) A  GROUP BY A.TTHAI


) T1) 
T2



END

