
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spThongtinthietbi')
   
exec('CREATE PROCEDURE spThongtinthietbi AS BEGIN SET NOCOUNT ON; END')

GO


ALTER PROCEDURE [dbo].[spThongtinthietbi]
	@MSMay NVARCHAR(100) = '-1',
	@sDMuc NVARCHAR(50) = NULL,
	@iLoai INT = 1,
	@UserName NVARCHAR(50) ='admin',
	@NNgu INT = NULL,
	@MS_MAY nvarchar(30)= NULL,
	@TEN_MAY NVARCHAR(255)= NULL,
	@MS_NHOM_MAY nvarchar(20)= NULL,
	@MS_HSX nvarchar(10)= NULL,
	@MS_HIEN_TRANG nvarchar(2)= NULL,
	@MS_KH VARCHAR(20)= NULL,
	@SO_NAM_KHAU_HAO INT= NULL,
	@MO_TA nvarchar(255)= NULL,
	@NHIEM_VU_THIET_BI NVARCHAR(150)= NULL,
	@MODEL NVARCHAR(50)= NULL,
	@SERIAL_NUMBER NVARCHAR(50)= NULL,
	@NGAY_SX DATETIME= NULL,
	@NUOC_SX NVARCHAR(30)= NULL,
	@NGAY_MUA DATETIME= NULL,
	@NGAY_BD_BAO_HANH DATETIME= NULL,
	@NGAY_DUA_VAO_SD DATETIME= NULL,
	@SO_THE NVARCHAR(50)= NULL,
	@SO_NGAY_LV_TRONG_TUAN SMALLINT= NULL,
	@SO_GIO_LV_TRONG_NGAY SMALLINT= NULL,
	@MS_DVT_RT int= NULL,
	@TY_LE_CON_LAI NVARCHAR(4)= NULL,
	@MUC_UU_TIEN SMALLINT= NULL,
	@SO_THANG_BH SMALLINT= NULL,
	@GIA_MUA FLOAT= NULL,
	@NGOAI_TE NVARCHAR(6)= NULL,
	@CHU_KY_HC_TB INT= NULL,
	@SO_CT NVARCHAR (30)= NULL,
	@TI_GIA_VND FLOAT= NULL,
	@TI_GIA_USD FLOAT= NULL,
	@CHU_KY_HC_TB_NGOAI INT= NULL,
	@CHU_KY_KD_TB INT= NULL,
	@DON_VI_TG INT =NULL,
	@HINH_ANH IMAGE = NULL
	--SELECT* FROM HANG_HOA WHERE MS_HH='005'
AS
BEGIN       
	--@iLoai = 1 -- VIEW
	--@iLoai = 2 -- DELETE
	--@iLoai = 3 -- INSERT
	--@iLoai = 4 -- Kiem Trung
	IF @iLoai = 1
	BEGIN
	IF @MSMay = '-1'
	SELECT MS_MAY,MS_MAY,TEN_MAY,TEN_LOAI_MAY,TEN_NHOM_MAY,Ten_N_XUONG,TEN_HE_THONG FROM dbo.MGetMayUserNgay(GETDATE(),@UserName,'-1',-1,-1,'-1','-1','-1',@NNgu);
	ELSE
	BEGIN
		SELECT * into #MAY FROM dbo.MGetMayUserNgay(GETDATE(),@UserName,'-1',-1,-1,'-1','-1',@MSMay,@NNgu);

		SELECT MS_HE_THONG AS MS_HT, MS_MAY, TEN_MAY, A.MS_HIEN_TRANG, TEN_HIEN_TRANG,TEN_HSX,TEN_CONG_TY, TEN_NHOM_MAY,
	TEN_LOAI_MAY, SO_NAM_KHAU_HAO,MO_TA, NHIEM_VU_THIET_BI, MODEL, SERIAL_NUMBER, NGAY_SX, NUOC_SX, NGAY_MUA, NGAY_BD_BAO_HANH, 
	NGAY_DUA_VAO_SD, SO_THE, SO_NGAY_LV_TRONG_TUAN, SO_GIO_LV_TRONG_NGAY, T6.TEN_DVT_RT, TY_LE_CON_LAI, MUC_UU_TIEN, SO_THANG_BH, GIA_MUA, 
	A.NGOAI_TE, T4.TEN_NGOAI_TE, Anh_TB, T5.TEN_UU_TIEN, CHU_KY_HC_TB, LUU_Y_SU_DUNG, SO_CT, TI_GIA_VND, TI_GIA_USD, DON_VI_THOI_GIAN, 
	CHU_KY_HIEU_CHUAN_TB_NGOAI, CHU_KY_KD_TB, USER_INSERT, USER_UPDATE, NGAY_INSERT, NGAY_UPDATE, DINH_MUC_SL, DVT_SL,A.MS_NHOM_MAY,A.MS_LOAI_MAY,A.MS_DVT_RT,A.Ten_N_XUONG,A.TEN_HE_THONG,A.TEN_BP_CHIU_PHI,(SELECT HINH_ANH FROM dbo.MAY WHERE MS_MAY = @MSMay) AS HINH_ANH
FROM #MAY A LEFT OUTER JOIN
	dbo.HIEN_TRANG_SU_DUNG_MAY AS B ON A.MS_HIEN_TRANG = B.MS_HIEN_TRANG  LEFT OUTER JOIN
	dbo.HANG_SAN_XUAT AS C ON A.MS_HSX = C.MS_HSX  LEFT OUTER JOIN
	dbo.KHACH_HANG AS D ON A.MS_KH = D.MS_KH LEFT OUTER JOIN
	dbo.NGOAI_TE AS T4 ON A.NGOAI_TE = T4.NGOAI_TE INNER JOIN
	dbo.MUC_UU_TIEN AS T5 ON A.MUC_UU_TIEN = T5.MS_UU_TIEN LEFT OUTER JOIN
	dbo.DON_VI_TINH_RUN_TIME AS T6 ON A.MS_DVT_RT = T6.MS_DVT_RT 
	END
	END

	--@iLoai = 3 -- INSERT
	IF @iLoai = 3
	BEGIN

	DECLARE @NgayHT DATETIME
SET @NgayHT = GETDATE()
IF @MS_KH = '-1' 
	SET @MS_KH = NULL	
IF @MS_DVT_RT = -1 
	SET @MS_DVT_RT = NULL	
	
if @MS_HSX = '-99' 
	set @MS_HSX = NULL
	
if @MS_KH = '-99' 
	set @MS_KH = NULL

	IF	@MSMay = '-1'
	BEGIN
	----insert
	INSERT INTO MAY 
(
	MS_MAY ,TEN_MAY,MS_NHOM_MAY ,MS_HSX ,MS_HIEN_TRANG ,MS_KH ,SO_NAM_KHAU_HAO ,MO_TA ,NHIEM_VU_THIET_BI ,
	MODEL ,SERIAL_NUMBER ,NGAY_SX ,NUOC_SX ,NGAY_MUA ,NGAY_BD_BAO_HANH ,NGAY_DUA_VAO_SD ,SO_THE ,SO_NGAY_LV_TRONG_TUAN ,
	SO_GIO_LV_TRONG_NGAY ,MS_DVT_RT ,TY_LE_CON_LAI ,MUC_UU_TIEN ,SO_THANG_BH ,GIA_MUA ,NGOAI_TE ,CHU_KY_HC_TB,
	SO_CT,TI_GIA_VND,TI_GIA_USD,CHU_KY_HIEU_CHUAN_TB_NGOAI,CHU_KY_KD_TB,DON_VI_THOI_GIAN, NGAY_INSERT,TEN_MAY_ANH,HINH_ANH
)
VALUES
(
	@MS_MAY ,@TEN_MAY,@MS_NHOM_MAY ,@MS_HSX ,@MS_HIEN_TRANG  ,@MS_KH ,@SO_NAM_KHAU_HAO ,@MO_TA ,@NHIEM_VU_THIET_BI ,
	@MODEL ,@SERIAL_NUMBER ,@NGAY_SX ,@NUOC_SX ,@NGAY_MUA ,@NGAY_BD_BAO_HANH ,@NGAY_DUA_VAO_SD ,@SO_THE ,@SO_NGAY_LV_TRONG_TUAN ,
	@SO_GIO_LV_TRONG_NGAY ,@MS_DVT_RT ,@TY_LE_CON_LAI ,@MUC_UU_TIEN ,@SO_THANG_BH ,@GIA_MUA ,@NGOAI_TE ,@CHU_KY_HC_TB,
	@SO_CT,@TI_GIA_VND,@TI_GIA_USD,@CHU_KY_HC_TB_NGOAI,@CHU_KY_KD_TB,@DON_VI_TG,@NgayHT,@TEN_MAY,@HINH_ANH
)

	END
	ELSE
    BEGIN
	---update
	UPDATE MAY SET	
	MS_MAY = @MS_MAY,
	TEN_MAY=@TEN_MAY,
	MS_NHOM_MAY=@MS_NHOM_MAY ,
	MS_HSX=@MS_HSX ,
	MS_HIEN_TRANG=@MS_HIEN_TRANG ,
	MS_KH=@MS_KH ,
	SO_NAM_KHAU_HAO=@SO_NAM_KHAU_HAO ,
	MO_TA=@MO_TA ,
	NHIEM_VU_THIET_BI=@NHIEM_VU_THIET_BI ,
	MODEL=@MODEL ,
	SERIAL_NUMBER=@SERIAL_NUMBER ,
	NGAY_SX=@NGAY_SX ,
	NUOC_SX=@NUOC_SX ,
	NGAY_MUA=@NGAY_MUA ,
	NGAY_BD_BAO_HANH=@NGAY_BD_BAO_HANH ,
	NGAY_DUA_VAO_SD=@NGAY_DUA_VAO_SD ,
	SO_THE=@SO_THE ,
	SO_NGAY_LV_TRONG_TUAN=@SO_NGAY_LV_TRONG_TUAN ,
	SO_GIO_LV_TRONG_NGAY=@SO_GIO_LV_TRONG_NGAY ,
	MS_DVT_RT=@MS_DVT_RT ,
	TY_LE_CON_LAI=@TY_LE_CON_LAI ,
	MUC_UU_TIEN=@MUC_UU_TIEN ,
	SO_THANG_BH=@SO_THANG_BH ,
	GIA_MUA=@GIA_MUA ,
	NGOAI_TE=@NGOAI_TE ,
	CHU_KY_HC_TB=@CHU_KY_HC_TB,
	SO_CT = @SO_CT,
	TI_GIA_VND = @TI_GIA_VND,
	TI_GIA_USD = @TI_GIA_USD,
	CHU_KY_HIEU_CHUAN_TB_NGOAI=@CHU_KY_HC_TB_NGOAI,
	CHU_KY_KD_TB=@CHU_KY_KD_TB,
	DON_VI_THOI_GIAN=@DON_VI_TG,
	NGAY_UPDATE = @NgayHT,
	HINH_ANH =@HINH_ANH
WHERE
	MS_MAY= @MSMay
	END
		SELECT @MS_MAY
	END

END



