DECLARE @menu nvarchar(500)
DECLARE @menu1 nvarchar(500)

SET @menu1 = 'mnuWeb'
set @menu =  N'ΞΠήͲΎΈ'


IF NOT EXISTS (SELECT * FROM dbo.LIC_MENU WHERE MENU_ID = @menu)
	INSERT INTO LIC_MENU (MENU_ID,TYPE_LIC) VALUES ( @menu,N'̦')

IF NOT EXISTS (SELECT * FROM dbo.MENU WHERE MENU_ID = @menu1)
	INSERT	dbo.MENU(MENU_ID,MENU_TEXT,MENU_ENGLISH,MENU_PARENT,MENU_LINE,MENU_INDEX,CLASS_NAME,AN_HIEN)
		VALUES(@menu1, N'nhap giam sat tt',  N'con', NULL,0,11,NULL,1 )
	
IF NOT EXISTS (SELECT * FROM NHOM_MENU WHERE MENU_ID = @menu1)
	INSERT INTO NHOM_MENU(MENU_ID,GROUP_ID)
	VALUES(@menu1, 1)


