IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PSDV_PHIEU_BT]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[PSDV_PHIEU_BT](
		[ID_PSDV_PBT] [bigint] IDENTITY(1,1) NOT NULL,
		[MS_YEU_CAU] [nvarchar](20) NOT NULL,
		[SER_GROUP_CODE] [nvarchar](10) NOT NULL,
		[MS_PHIEU_BAO_TRI] [nvarchar](20) NOT NULL,
		[NOI_DUNG] [nvarchar](250) NULL,
		[CHI_PHI_PB] [float] NULL,
	 CONSTRAINT [PK_PSDV_PHIEU_BT] PRIMARY KEY CLUSTERED 
	(
		[ID_PSDV_PBT] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END

