IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHAT_SINH_DICH_VU]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[PHAT_SINH_DICH_VU](
		[ID_PSDV] [bigint] IDENTITY(1,1) NOT NULL,
		[MS_YEU_CAU] [nvarchar](20) NOT NULL,
		[SO_YEU_CAU] [nvarchar](250) NULL,
		[NGAY_YEU_CAU] [datetime] NULL,
		[MS_CONG_NHAN] [nvarchar](9) NULL,
		[MS_TRANG_THAI] [int] NULL,
		[MAIL_YC] [nvarchar](250) NOT NULL,
		[NOI_DUNG_YC] [nvarchar](255) NULL,
	 CONSTRAINT [PK_PHAT_SINH_DICH_VU] PRIMARY KEY CLUSTERED 
	(
		[ID_PSDV] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

