
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapPSDVNhom')
   exec('CREATE PROCEDURE [dbo].[spCapNhapPSDVNhom] AS BEGIN SET NOCOUNT ON; END')
GO

--	EXEC spCapNhapPSDVNhom 'PSDV_TMPAdministrator'
ALTER PROC spCapNhapPSDVNhom
	@BTam NVARCHAR(250), 
	@MsYC NVARCHAR(25)
AS	


CREATE TABLE #PSDVNhom(
	[SER_GROUP_CODE] [nvarchar](10) NULL,
	[SER_GROUP_NAME] [nvarchar](10) NULL,
	[MO_TA] [nvarchar](255) NULL,
	[MS_GL] [nvarchar](50) NULL,
	[TEN_CONG_TY] [nvarchar](255) NULL,
	[TEN_BP_CHIU_PHI] [nvarchar](100) NULL,
	[CHI_PHI] [float] NULL,
	[ID_PSDV_NHOM] [bigint] NULL,
	[MS_YEU_CAU] [nvarchar](20) NULL,
	[MS_KH] [nvarchar](20) NULL,
	[MS_BP_CHIU_PHI] [int] NULL,
	[CU_MOI] [bit]
)

DECLARE @sSql NVARCHAR(4000)
SET @sSql = 'INSERT INTO #PSDVNhom ([SER_GROUP_CODE],[SER_GROUP_NAME],[MO_TA],[MS_GL],[TEN_CONG_TY],[TEN_BP_CHIU_PHI],[CHI_PHI],[ID_PSDV_NHOM],
[MS_YEU_CAU],[MS_KH],[MS_BP_CHIU_PHI],[CU_MOI]) SELECT [SER_GROUP_CODE],[SER_GROUP_NAME],[MO_TA],[MS_GL],[TEN_CONG_TY],[TEN_BP_CHIU_PHI],[CHI_PHI],[ID_PSDV_NHOM],
[MS_YEU_CAU],[MS_KH],[MS_BP_CHIU_PHI],[CU_MOI] FROM ' + @BTam

EXEC (@sSql)

DELETE  A FROM PSDV_NHOM_DV A WHERE NOT EXISTS (SELECT * FROM #PSDVNhom B WHERE A.ID_PSDV_NHOM = B.ID_PSDV_NHOM)  
	AND MS_YEU_CAU = @MsYC
	
INSERT INTO PSDV_NHOM_DV(MS_YEU_CAU,SER_GROUP_CODE,MO_TA,MS_GL,MS_KH,MS_BP_CHIU_PHI,CHI_PHI)
SELECT MS_YEU_CAU,SER_GROUP_CODE,MO_TA,MS_GL,MS_KH,MS_BP_CHIU_PHI,CHI_PHI FROM #PSDVNhom A
WHERE [CU_MOI] IS NULL
AND NOT EXISTS ( SELECT * FROM PSDV_NHOM_DV B WHERE A.MS_YEU_CAU = B.MS_YEU_CAU AND A.SER_GROUP_CODE = B.SER_GROUP_CODE)


UPDATE PSDV_NHOM_DV SET 
	MS_YEU_CAU = B.MS_YEU_CAU,
	SER_GROUP_CODE = B.SER_GROUP_CODE,
	MO_TA = B.MO_TA,
	MS_GL = B.MS_GL,
	MS_KH = B.MS_KH,
	MS_BP_CHIU_PHI = B.MS_BP_CHIU_PHI,
	CHI_PHI = B.CHI_PHI
FROM PSDV_NHOM_DV A INNER JOIN #PSDVNhom B ON A.ID_PSDV_NHOM = B.ID_PSDV_NHOM 
