
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapPSDV')
   exec('CREATE PROCEDURE [dbo].[spCapNhapPSDV] AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC spCapNhapPSDV
	@ID_PSDV bigint,
	@MS_YEU_CAU nvarchar(20),
	@SO_YEU_CAU nvarchar(250),
	@NGAY_YEU_CAU datetime,
	@MS_CONG_NHAN nvarchar(9),
	@MS_TRANG_THAI int,
	@MAIL_YC nvarchar(250),
	@NOI_DUNG_YC nvarchar(255)
AS	
IF (@ID_PSDV = -1)
BEGIN	
	INSERT INTO PHAT_SINH_DICH_VU(MS_YEU_CAU,SO_YEU_CAU,NGAY_YEU_CAU,MS_CONG_NHAN,MS_TRANG_THAI,MAIL_YC,NOI_DUNG_YC)
		VALUES (@MS_YEU_CAU,@SO_YEU_CAU,@NGAY_YEU_CAU,@MS_CONG_NHAN,@MS_TRANG_THAI,@MAIL_YC,@NOI_DUNG_YC)
END
ELSE
BEGIN	
	UPDATE PHAT_SINH_DICH_VU SET 
			MS_YEU_CAU = @MS_YEU_CAU,
			SO_YEU_CAU = @SO_YEU_CAU,
			NGAY_YEU_CAU = @NGAY_YEU_CAU,
			MS_CONG_NHAN = @MS_CONG_NHAN,
			MS_TRANG_THAI = @MS_TRANG_THAI,
			MAIL_YC = @MAIL_YC,
			NOI_DUNG_YC = @NOI_DUNG_YC
	WHERE 	ID_PSDV = @ID_PSDV 
END

