IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetPSDVNhom')
   exec('CREATE PROCEDURE [dbo].[spGetPSDVNhom] AS BEGIN SET NOCOUNT ON; END')
GO

--EXEC spGetPSDVNhom 

ALTER PROC spGetPSDVNhom
	@MsYeuCau NVARCHAR(20)
AS
	
SELECT     T1.SER_GROUP_CODE, T1.SER_GROUP_CODE AS SER_GROUP_NAME, T1.MO_TA, T1.MS_GL, T4.TEN_CONG_TY, T3.TEN_BP_CHIU_PHI, T1.CHI_PHI, 
		T1.ID_PSDV_NHOM , T1.MS_YEU_CAU, T1.MS_KH, T1.MS_BP_CHIU_PHI, CONVERT(BIT,1) AS CU_MOI 
FROM         dbo.PSDV_NHOM_DV AS T1 INNER JOIN
                      dbo.LOAI_DICH_VU AS T2 ON T1.SER_GROUP_CODE = T2.SER_GROUP_CODE LEFT OUTER JOIN
                      dbo.BO_PHAN_CHIU_PHI AS T3 ON T1.MS_BP_CHIU_PHI = T3.MS_BP_CHIU_PHI LEFT OUTER JOIN
                      dbo.KHACH_HANG AS T4 ON T1.MS_KH = T4.MS_KH
WHERE     (T1.MS_YEU_CAU = @MsYeuCau)
ORDER BY T1.SER_GROUP_CODE