

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapPSDVPBTri')
   exec('CREATE PROCEDURE [dbo].[spCapNhapPSDVPBTri] AS BEGIN SET NOCOUNT ON; END')
GO

--	EXEC spCapNhapPSDVPBTri 'PSDV_PBT_TMPAdministrator'
ALTER PROC spCapNhapPSDVPBTri
	@BTam NVARCHAR(250), 
	@MsYC NVARCHAR(25),
	@MsSER NVARCHAR(25)
AS	



CREATE TABLE #PSDV_PBT_TMP(
	[MS_PHIEU_BAO_TRI] [nvarchar](20) NULL,
	[TEN_MAY] [nvarchar](255) NULL,
	[NOI_DUNG] [nvarchar](250) NULL,
	[TEN_BP_CHIU_PHI] [nvarchar](250) NULL,
	[CHI_PHI_PB] [float] NULL,
	[ID_PSDV_PBT] [bigint] NULL,
	[MS_YEU_CAU] [nvarchar](20) NULL,
	[SER_GROUP_CODE] [nvarchar](10) NULL,
	[CU_MOI] [bit] NULL
) 

DECLARE @sSql NVARCHAR(4000)
SET @sSql = 'INSERT INTO #PSDV_PBT_TMP ([MS_PHIEU_BAO_TRI],[TEN_MAY],[NOI_DUNG],[TEN_BP_CHIU_PHI],[CHI_PHI_PB],[ID_PSDV_PBT],[MS_YEU_CAU],[SER_GROUP_CODE],[CU_MOI]) 
	SELECT [MS_PHIEU_BAO_TRI],[TEN_MAY],[NOI_DUNG],[TEN_BP_CHIU_PHI],[CHI_PHI_PB],[ID_PSDV_PBT],[MS_YEU_CAU],[SER_GROUP_CODE],[CU_MOI] FROM ' + @BTam
EXEC (@sSql)

DELETE  A FROM PSDV_PHIEU_BT A WHERE NOT EXISTS (SELECT * FROM #PSDV_PBT_TMP B WHERE A.ID_PSDV_PBT = B.ID_PSDV_PBT)  
	AND MS_YEU_CAU = @MsYC AND A.SER_GROUP_CODE = @MsSER


INSERT INTO [PSDV_PHIEU_BT]([MS_YEU_CAU],[SER_GROUP_CODE],[MS_PHIEU_BAO_TRI],[NOI_DUNG],[CHI_PHI_PB])
SELECT [MS_YEU_CAU],[SER_GROUP_CODE],[MS_PHIEU_BAO_TRI],[NOI_DUNG],[CHI_PHI_PB] FROM #PSDV_PBT_TMP
WHERE CU_MOI IS NULL


UPDATE PSDV_PHIEU_BT SET 
			[MS_YEU_CAU] = B.[MS_YEU_CAU],
			[SER_GROUP_CODE] = B.[SER_GROUP_CODE],
			[MS_PHIEU_BAO_TRI] = B.[MS_PHIEU_BAO_TRI],
			[NOI_DUNG] = B.[NOI_DUNG],
			[CHI_PHI_PB] = B.[CHI_PHI_PB]
FROM PSDV_PHIEU_BT A INNER JOIN #PSDV_PBT_TMP B ON A.ID_PSDV_PBT = B.ID_PSDV_PBT
WHERE CU_MOI IS NOT NULL
