
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapPSDVTLieu')
   exec('CREATE PROCEDURE [dbo].[spCapNhapPSDVTLieu] AS BEGIN SET NOCOUNT ON; END')
GO

--	EXEC spCapNhapPSDVTLieu 'PSDV_TLIEUAdministrator','PR-201508000013'
ALTER PROC spCapNhapPSDVTLieu
	@BTam NVARCHAR(250), 
	@MsYC NVARCHAR(25)
AS	


CREATE TABLE #PSDVTLieu(
	[TAI_LIEU_THAU] [nvarchar](250) NULL,
	[TL_SO] [nvarchar](250) NULL,
	[NOI_DUNG] [nvarchar](250) NULL,
	[GHI_CHU] [nvarchar](250) NULL,
	[DUONG_DAN] [nvarchar](250) NULL,
	[ID_PSDV_TL] [bigint] NULL,
	[MS_YEU_CAU] [nvarchar](20) NULL,
	[CU_MOI] [bit] NULL
)

DECLARE @sSql NVARCHAR(4000)
SET @sSql = 'INSERT INTO #PSDVTLieu ([TAI_LIEU_THAU],[TL_SO],[NOI_DUNG],[GHI_CHU],[DUONG_DAN],[ID_PSDV_TL],[MS_YEU_CAU],[CU_MOI]) 
SELECT [TAI_LIEU_THAU],[TL_SO],[NOI_DUNG],[GHI_CHU],[DUONG_DAN],[ID_PSDV_TL],[MS_YEU_CAU],[CU_MOI] FROM ' + @BTam

EXEC (@sSql)


DELETE  A FROM [PSDV_TAI_LIEU] A WHERE MS_YEU_CAU = @MsYC AND
	NOT EXISTS (SELECT * FROM #PSDVTLieu B WHERE A.ID_PSDV_TL = B.ID_PSDV_TL)  
	


INSERT INTO [PSDV_TAI_LIEU]([MS_YEU_CAU],[TAI_LIEU_THAU],[TL_SO],[NOI_DUNG],[GHI_CHU],[DUONG_DAN])
	SELECT [MS_YEU_CAU],[TAI_LIEU_THAU],[TL_SO],[NOI_DUNG],[GHI_CHU],[DUONG_DAN] FROM #PSDVTLieu A
WHERE [CU_MOI] IS NULL 

UPDATE [PSDV_TAI_LIEU] SET 
	[MS_YEU_CAU] = B.[MS_YEU_CAU],
	[TAI_LIEU_THAU] = B.[TAI_LIEU_THAU],
	[TL_SO] = B.[TL_SO],
	[NOI_DUNG] = B.[NOI_DUNG],
	[GHI_CHU] = B.[GHI_CHU],
	[DUONG_DAN] = B.[DUONG_DAN]
FROM [PSDV_TAI_LIEU] A INNER JOIN #PSDVTLieu B ON A.ID_PSDV_TL = B.ID_PSDV_TL 
WHERE A.MS_YEU_CAU = @MsYC

	



