
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapMaBPCPhi')
   exec('CREATE PROCEDURE [dbo].[spCapNhapMaBPCPhi] AS BEGIN SET NOCOUNT ON; END')
GO

-- EXEC spCapNhapMaBPCPhi  '251', '112'
ALTER PROC spCapNhapMaBPCPhi
	@MaCu int, 
	@MaMoi int 
AS

Declare @TABLE nvarchar (100),@COT nvarchar (100), @sql nvarchar (1000)
--Declare @MaCu nvarchar (100), @MaMoi nvarchar (100) 

--set @MaCu = 'BUE-BO-002TEST'
--set @MaMoi = 'BUE-BO-002'

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__BUDGET__MS_BP_CH__5721B060]') AND parent_object_id = OBJECT_ID(N'[dbo].[BUDGET]'))
ALTER TABLE [dbo].[BUDGET] DROP CONSTRAINT [FK__BUDGET__MS_BP_CH__5721B060]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BO_PHAN_CHIU_PHI_RULE_BO_PHAN_CHIU_PHI]') AND parent_object_id = OBJECT_ID(N'[dbo].[BO_PHAN_CHIU_PHI_RULE]'))
ALTER TABLE [dbo].[BO_PHAN_CHIU_PHI_RULE] DROP CONSTRAINT [FK_BO_PHAN_CHIU_PHI_RULE_BO_PHAN_CHIU_PHI]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHI_PHI_THEO_THANG_BO_PHAN_CHIU_PHI]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHI_PHI_THEO_THANG]'))
ALTER TABLE [dbo].[CHI_PHI_THEO_THANG] DROP CONSTRAINT [FK_CHI_PHI_THEO_THANG_BO_PHAN_CHIU_PHI]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DISTRIBUTION_RULE_BO_PHAN_CHIU_PHI]') AND parent_object_id = OBJECT_ID(N'[dbo].[DISTRIBUTION_RULE]'))
ALTER TABLE [dbo].[DISTRIBUTION_RULE] DROP CONSTRAINT [FK_DISTRIBUTION_RULE_BO_PHAN_CHIU_PHI]


IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_KINH_PHI_NAM_BO_PHAN_CHIU_PHI]') AND parent_object_id = OBJECT_ID(N'[dbo].[KINH_PHI_NAM]'))
ALTER TABLE [dbo].[KINH_PHI_NAM] DROP CONSTRAINT [FK_KINH_PHI_NAM_BO_PHAN_CHIU_PHI]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MAY_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI]') AND parent_object_id = OBJECT_ID(N'[dbo].[MAY_BO_PHAN_CHIU_PHI]'))
ALTER TABLE [dbo].[MAY_BO_PHAN_CHIU_PHI] DROP CONSTRAINT [FK_MAY_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NHOM_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI]') AND parent_object_id = OBJECT_ID(N'[dbo].[NHOM_BO_PHAN_CHIU_PHI]'))
ALTER TABLE [dbo].[NHOM_BO_PHAN_CHIU_PHI] DROP CONSTRAINT [FK_NHOM_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI]



Set IDENTITY_INSERT BO_PHAN_CHIU_PHI ON
	INSERT INTO [BO_PHAN_CHIU_PHI](MS_BP_CHIU_PHI,[TEN_BP_CHIU_PHI],[LOAI_CHI_PHI],[MSDV],[GHI_CHU],[ISIT],[ACCOUNT],[SUB],[MA_BP_CHIU_PHI])
	SELECT @MaMoi,[TEN_BP_CHIU_PHI],[LOAI_CHI_PHI],[MSDV],[GHI_CHU],[ISIT],[ACCOUNT],[SUB],[MA_BP_CHIU_PHI] FROM BO_PHAN_CHIU_PHI WHERE MS_BP_CHIU_PHI = @MaCu
	
	DELETE BO_PHAN_CHIU_PHI WHERE MS_BP_CHIU_PHI = @MaCu
Set IDENTITY_INSERT BO_PHAN_CHIU_PHI OFF
	
	
--Tao bang tam chua du lieu
	SELECT DISTINCT sysobjects.NAME AS NAME_TB, syscolumns.NAME AS NAME_COT, CONVERT(BIT,0) CAP_NHAP  INTO  #BTam 
	FROM sysobjects INNER JOIN syscolumns ON sysobjects.ID = syscolumns.ID 
	WHERE syscolumns.NAME LIKE 'MS_BP_CHIU_PHI%'  and OBJECTPROPERTY(sysobjects.id, N'IsUserTable') = 1 
	and ((sysobjects.NAME   ) NOT IN ('BO_PHAN_CHIU_PHI' ) )  
--Chay vong lap

Declare @iTT int
set @iTT = 1
Declare  MS_BP_CHIU_PHIinh CURSOR FOR
	SELECT NAME_TB,NAME_COT FROM #BTam ORDER BY NAME_TB
Open MS_BP_CHIU_PHIinh
FETCH NEXT FROM MS_BP_CHIU_PHIinh
INTO @TABLE,@COT
While @@Fetch_Status = 0
Begin

BEGIN TRY
	set @sql = CONVERT(nvarchar(10),@iTT) +  '. UPDATE [' +  @TABLE  + '] SET [' + @COT + '] = ' +  CONVERT(NVARCHAR,@MaMoi) + ' WHERE [' + @COT + '] =	' +  CONVERT(NVARCHAR,@MaCu) 
	PRINT (@sql)
	set @sql = 'UPDATE [' +  @TABLE  + '] SET [' + @COT + '] = ' +  CONVERT(NVARCHAR,@MaMoi) + ' WHERE [' + @COT + '] =	' +  CONVERT(NVARCHAR,@MaCu)
	EXEC (@sql)
	UPDATE #BTam SET CAP_NHAP = 1 WHERE NAME_TB = @TABLE AND NAME_COT = @COT
END TRY
BEGIN CATCH
	PRINT (@sql)     
	UPDATE #BTam SET CAP_NHAP = 0 WHERE NAME_TB = @TABLE AND NAME_COT = @COT
END CATCH

	
    FETCH NEXT FROM MS_BP_CHIU_PHIinh
    INTO  @TABLE,@COT
	set @iTT = @iTT +1
End

Close MS_BP_CHIU_PHIinh
Deallocate MS_BP_CHIU_PHIinh



ALTER TABLE [dbo].[BUDGET]  WITH NOCHECK ADD  CONSTRAINT [FK__BUDGET__MS_BP_CH__5721B060] FOREIGN KEY([MS_BP_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])

ALTER TABLE [dbo].[BUDGET] CHECK CONSTRAINT [FK__BUDGET__MS_BP_CH__5721B060]


ALTER TABLE [dbo].[BO_PHAN_CHIU_PHI_RULE]  WITH CHECK ADD  CONSTRAINT [FK_BO_PHAN_CHIU_PHI_RULE_BO_PHAN_CHIU_PHI] FOREIGN KEY([MS_BP_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])
ON UPDATE CASCADE

ALTER TABLE [dbo].[BO_PHAN_CHIU_PHI_RULE] CHECK CONSTRAINT [FK_BO_PHAN_CHIU_PHI_RULE_BO_PHAN_CHIU_PHI]


ALTER TABLE [dbo].[CHI_PHI_THEO_THANG]  WITH CHECK ADD  CONSTRAINT [FK_CHI_PHI_THEO_THANG_BO_PHAN_CHIU_PHI] FOREIGN KEY([MS_BO_PHAN_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])
ON UPDATE CASCADE

ALTER TABLE [dbo].[CHI_PHI_THEO_THANG] CHECK CONSTRAINT [FK_CHI_PHI_THEO_THANG_BO_PHAN_CHIU_PHI]


ALTER TABLE [dbo].[DISTRIBUTION_RULE]  WITH CHECK ADD  CONSTRAINT [FK_DISTRIBUTION_RULE_BO_PHAN_CHIU_PHI] FOREIGN KEY([MS_BP_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])

ALTER TABLE [dbo].[DISTRIBUTION_RULE] CHECK CONSTRAINT [FK_DISTRIBUTION_RULE_BO_PHAN_CHIU_PHI]


ALTER TABLE [dbo].[KINH_PHI_NAM]  WITH NOCHECK ADD  CONSTRAINT [FK_KINH_PHI_NAM_BO_PHAN_CHIU_PHI] FOREIGN KEY([MS_BP_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])
ON UPDATE CASCADE

ALTER TABLE [dbo].[KINH_PHI_NAM] CHECK CONSTRAINT [FK_KINH_PHI_NAM_BO_PHAN_CHIU_PHI]


ALTER TABLE [dbo].[MAY_BO_PHAN_CHIU_PHI]  WITH CHECK ADD  CONSTRAINT [FK_MAY_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI] FOREIGN KEY([MS_BP_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])
ON UPDATE CASCADE

ALTER TABLE [dbo].[MAY_BO_PHAN_CHIU_PHI] CHECK CONSTRAINT [FK_MAY_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI]


ALTER TABLE [dbo].[NHOM_BO_PHAN_CHIU_PHI]  WITH CHECK ADD  CONSTRAINT [FK_NHOM_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI] FOREIGN KEY([MS_BP_CHIU_PHI])
REFERENCES [dbo].[BO_PHAN_CHIU_PHI] ([MS_BP_CHIU_PHI])
ON UPDATE CASCADE

ALTER TABLE [dbo].[NHOM_BO_PHAN_CHIU_PHI] CHECK CONSTRAINT [FK_NHOM_BO_PHAN_CHIU_PHI_BO_PHAN_CHIU_PHI]
