//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biz.Lib.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelperSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelperSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biz.Lib.Helpers.HelperSetting", typeof(HelperSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @2015.Biz.Security.
        /// </summary>
        public static string CRYPTO_KEY {
            get {
                return ResourceManager.GetString("CRYPTO_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract_Number.
        /// </summary>
        public static string EXPORT_CONTRACT_STATUS_SHEET_NAME {
            get {
                return ResourceManager.GetString("EXPORT_CONTRACT_STATUS_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC_Target.
        /// </summary>
        public static string EXPORT_FC_TARGET_SHEET_NAME {
            get {
                return ResourceManager.GetString("EXPORT_FC_TARGET_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC_Target.
        /// </summary>
        public static string IMPORT_FC_TARGET_SHEET_NAME {
            get {
                return ResourceManager.GetString("IMPORT_FC_TARGET_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input_Data.
        /// </summary>
        public static string IMPORT_SHEET_NAME {
            get {
                return ResourceManager.GetString("IMPORT_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MAIL_BCC {
            get {
                return ResourceManager.GetString("MAIL_BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3 - Notification.
        /// </summary>
        public static string MAIL_BODY {
            get {
                return ResourceManager.GetString("MAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MAIL_CC {
            get {
                return ResourceManager.GetString("MAIL_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE.
        /// </summary>
        public static string MAIL_ENABLE_SSL {
            get {
                return ResourceManager.GetString("MAIL_ENABLE_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bizcell.info@gmail.com.
        /// </summary>
        public static string MAIL_FROM {
            get {
                return ResourceManager.GetString("MAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE.
        /// </summary>
        public static string MAIL_GMAIL_SMTP {
            get {
                return ResourceManager.GetString("MAIL_GMAIL_SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        public static string MAIL_IS_HTML_BODY {
            get {
                return ResourceManager.GetString("MAIL_IS_HTML_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width: 700px; padding: 20px 20px 20px 20px&quot;&gt;
        ///	&lt;table style=&quot;width: 100%; border: solid 1px #176081&quot; cellpadding=&quot;4&quot; cellspacing=&quot;4&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;color: #FFFFFF; background-color: #0070B9; padding: 10px; font-size: 12px;
        ///				font-weight: bold; font-family: Arial&quot;&gt;
        ///				{_title_}
        ///			&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;color: #000000; padding: 10px; font-size: 12px; font-family: Arial&quot;&gt;
        ///				{_body_}
        ///			&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;color: #FFFFFF; background-color: #9D9FA2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MAIL_MASTER_TEMPLATE {
            get {
                return ResourceManager.GetString("MAIL_MASTER_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3.
        /// </summary>
        public static string MAIL_SENDER {
            get {
                return ResourceManager.GetString("MAIL_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3 - Notification.
        /// </summary>
        public static string MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nguyentrongtrung.aft@gmail.com.
        /// </summary>
        public static string MAIL_TO {
            get {
                return ResourceManager.GetString("MAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract_Number.
        /// </summary>
        public static string UPDATE_CONTRACT_STATUS_SHEET_NAME {
            get {
                return ResourceManager.GetString("UPDATE_CONTRACT_STATUS_SHEET_NAME", resourceCulture);
            }
        }
    }
}
