IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sp_GetAutocompleteMail')
exec('CREATE PROCEDURE sp_GetAutocompleteMail AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE sp_GetAutocompleteMail
AS
BEGIN
SELECT DISTINCT ROW_NUMBER() OVER(ORDER BY MAIL_TO) AS IDMAIL,A.MAIL_TO AS MAILNAME
FROM(SELECT DISTINCT MAIL_TO FROM  dbo.DS_MAIL) AS A
END
