IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetNhomMenu_Web')
exec('CREATE PROCEDURE GetNhomMenu_Web AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE GetNhomMenu_Web
	@UserName NVARCHAR(50) = 'admin'
	AS
    BEGIN
DECLARE @GROUP_ID INT = (SELECT TOP 1 GROUP_ID FROM dbo.USERS WHERE USERNAME =@UserName)
SELECT T1.* INTO #TEMPT FROM dbo.WebMenu T1
INNER JOIN  dbo.MenuWebWin T2 ON T1.MenuID = T2.MenuWEB_ID
INNER JOIN  dbo.NHOM_MENU T3 ON T3.MENU_ID = T2.MENU_ID
WHERE T3.GROUP_ID = @GROUP_ID
UNION
SELECT * FROM dbo.WebMenu A WHERE NOT EXISTS(SELECT MenuWEB_ID  FROM dbo.MenuWebWin B WHERE	A.MenuID = B.MenuWEB_ID)

SELECT * FROM #TEMPT WHERE Hide = 0 ORDER BY [Index]
END



