ALTER TABLE Operator
ALTER COLUMN CardID NVARCHAR(50)

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DON_VI_TINH_TOC_DO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DON_VI_TINH_TOC_DO]
(
[MS_DVT_TD] [int] NOT NULL IDENTITY(1, 1),
[TEN_DVT_TD] [nvarchar] (50)  NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[DON_VI_TINH_TOC_DO] ADD CONSTRAINT [PK_DON_VI_TINH_TOC_DO] PRIMARY KEY CLUSTERED  ([MS_DVT_TD]) ON [PRIMARY]
END	