IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetDON_VI_TINH_TOC_DO')
exec('CREATE PROCEDURE GetDON_VI_TINH_TOC_DO AS BEGIN SET NOCOUNT ON; END')
GO
ALTER proc [dbo].[GetDON_VI_TINH_TOC_DO]
@TYPE INT
AS
SELECT MS_DVT_TD,TEN_DVT_TD
 FROM dbo.DON_VI_TINH_TOC_DO
