IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'OEE_spGetListMacHang')
exec('CREATE PROCEDURE OEE_spGetListMacHang AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE OEE_spGetListMacHang
    @TNgay DATETIME = '1/1/2020',
	@DNgay DATETIME = '1/1/2021'
AS
BEGIN
SELECT ID_MACHANG, MA_MACHANG, TEN_MACHANG, GHI_CHU, NGAY_NHAP, NGUOI_NHAP	 FROM dbo.MAC_HANG WHERE NGAY_NHAP BETWEEN @TNgay AND @DNgay

END