CREATE PROCEDURE spGetProDuctionOEE
	@DetailID BIGINT = 0 
AS 
BEGIN
SELECT T.TH,T.NPH,T.GPH,T.DT,(T.TH/T.NPH)*100 AS PE,(T.TH/T.GPH)*100 AS OEE,(T.DT/T.GPH)*100 AS DTP,T.EL,T.EL -(NPH-T.TH) AS ELV FROM (
SELECT [dbo].[fnGetQuantityCapacity](ItemID,ActualQuantity) AS TH, ((DATEDIFF(MINUTE,StartTime,EndTime) -ISNULL((SELECT SUM(B.THOI_GIAN_SUA_CHUA) FROM dbo.THOI_GIAN_NGUNG_MAY B WHERE B.ProductionRunID = A.ProductionRunID AND B.ProductionRunDetailsID = A.DetailID),0))/60) AS NPH, DATEDIFF(HOUR,StartTime,EndTime) AS GPH,ISNULL((SELECT SUM(B.THOI_GIAN_SUA_CHUA) FROM dbo.THOI_GIAN_NGUNG_MAY B INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY C ON C.MS_NGUYEN_NHAN = B.MS_NGUYEN_NHAN WHERE B.ProductionRunID = A.ProductionRunID AND B.ProductionRunDetailsID = A.DetailID AND C.BTDK = 1),0) /60 AS DT,ISNULL((SELECT SUM(B.THOI_GIAN_SUA_CHUA) FROM dbo.THOI_GIAN_NGUNG_MAY B INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY C ON C.MS_NGUYEN_NHAN = B.MS_NGUYEN_NHAN WHERE B.ProductionRunID = A.ProductionRunID AND B.ProductionRunDetailsID = A.DetailID AND C.BTDK = 0),0) /60 AS EL  FROM dbo.ProductionRunDetails A WHERE A.DetailID = @DetailID) AS T
END



