
--GetParameterInfo 4589

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetParameterInfo')
   exec('CREATE PROCEDURE GetParameterInfo AS BEGIN SET NOCOUNT ON; END')
GO

alter proc GetParameterInfo
	@ID INT
as
begin

	SELECT DISTINCT   T5.TEN_TS_GSTT, T1.MS_TS_GSTT, T1.MS_BO_PHAN,T2.TEN_BO_PHAN, T5.LOAI_TS, ISNULL(T4.TEN_DV_DO, '') TEN_DV_DO, 0 GIA_TRI_DO, T6.TEN_GIA_TRI
	FROM GIAM_SAT_TINH_TRANG T 
	INNER JOIN dbo.GIAM_SAT_TINH_TRANG_TS T1 ON T.STT = T1.STT  
	
	INNER JOIN THONG_SO_GSTT T5 ON T1.MS_TS_GSTT = T5.MS_TS_GSTT 
	INNER JOIN GIA_TRI_TS_GSTT T6 ON T5.MS_TS_GSTT = T6.MS_TS_GSTT 
	INNER JOIN CAU_TRUC_THIET_BI T2 ON T1.MS_BO_PHAN = T2.MS_BO_PHAN AND T1.MS_MAY = T2.MS_MAY 
	LEFT JOIN DON_VI_DO T4 ON T5.MS_DV_DO = T4.MS_DV_DO
	WHERE T.STT = @ID and T5.LOAI_TS = 1

	UNION

	SELECT DISTINCT  T5.TEN_TS_GSTT, T1.MS_TS_GSTT, T1.MS_BO_PHAN, T2.TEN_BO_PHAN, T5.LOAI_TS, ISNULL(T4.TEN_DV_DO, '') TEN_DV_DO, T1.GIA_TRI_DO,  dbo.GetGiaTriThongSo(T1.MS_MAY,T1.MS_BO_PHAN, T1.MS_TS_GSTT) TEN_GIA_TRI
	FROM GIAM_SAT_TINH_TRANG T 
	INNER JOIN dbo.GIAM_SAT_TINH_TRANG_TS T1 ON T.STT = T1.STT  
	INNER JOIN THONG_SO_GSTT T5 ON T1.MS_TS_GSTT = T5.MS_TS_GSTT 
	INNER JOIN CAU_TRUC_THIET_BI T2 ON T1.MS_BO_PHAN = T2.MS_BO_PHAN AND T1.MS_MAY = T2.MS_MAY 
	LEFT JOIN DON_VI_DO T4 ON T5.MS_DV_DO = T4.MS_DV_DO
	WHERE T.STT = @ID and T5.LOAI_TS = 0
	GROUP BY T5.TEN_TS_GSTT, T1.MS_TS_GSTT, T1.MS_BO_PHAN, T2.TEN_BO_PHAN
	, T5.LOAI_TS, TEN_DV_DO ,T1.MS_MAY, T1.GIA_TRI_DO





end
