

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type in (N'FN', N'IF', N'TF', N'FS', N'FT') AND name = 'GetVTuTheoPBTBPCVVF')
   exec('CREATE FUNCTION  dbo.GetVTuTheoPBTBPCVVF () RETURNS  nvarchar(4000) as Begin return null end')
GO

--SELECT DBO.GetVTuTheoPBTBPCVVF ('WO-201901000011' ,33,	'04', 0) 
ALTER function [dbo].[GetVTuTheoPBTBPCVVF]
(
	@MS_PHIEU_BAO_TRI nvarchar(20),
	@MS_CV INT,
	@MS_BO_PHAN nvarchar(50),
	@NNgu int
)
returns nvarchar(4000)
as
begin
declare @sName nvarchar(4000)


SELECT 
 @sName =COALESCE(ISNULL(@sName,'') + CASE LEN(ISNULL(@sName,'')) WHEN 0 THEN '' ELSE '; ' END  ,'' )  + ISNULL(A.MS_PT ,'') + ' - '+ CASE @NNgu  WHEN 0 THEN B.TEN_PT WHEN 1 THEN B.TEN_PT_ANH ELSE B.TEN_PT_HOA END  + ' (' + CONVERT(NVARCHAR,CASE SL_KH WHEN 0 THEN SL_TT ELSE SL_KH END) + ' ' + 
CASE @NNgu  WHEN 0 THEN TEN_1 WHEN 1 THEN TEN_2 ELSE TEN_3 END + ')'

FROM 
(
	SELECT Y.MS_PT, ISNULL(SUM(SL_KH) ,0) AS SL_KH , ISNULL(SUM(Y.SL_TT),0) AS SL_TT
	FROM         dbo.PHIEU_BAO_TRI AS X INNER JOIN
						  dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG AS Y ON X.MS_PHIEU_BAO_TRI = Y.MS_PHIEU_BAO_TRI
	WHERE     (X.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI) AND (Y.MS_CV = @MS_CV) AND (Y.MS_BO_PHAN = @MS_BO_PHAN) 
	GROUP BY 	Y.MS_PT
UNION
	SELECT Y.MS_PT, ISNULL(SUM(SL_KH) ,0) AS SL_KH , ISNULL(SUM(Y.SL_TT),0) AS SL_TT
	FROM         dbo.PHIEU_BAO_TRI AS X INNER JOIN
						  dbo.PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG AS Y ON X.MS_PHIEU_BAO_TRI = Y.MS_PHIEU_BAO_TRI
	WHERE     (X.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI) AND (Y.STT = @MS_CV) 
	GROUP BY 	Y.MS_PT

) A INNER JOIN IC_PHU_TUNG B ON A.MS_PT = B.MS_PT  INNER JOIN DON_VI_TINH C ON B.DVT = C.DVT 

ORDER BY ISNULL(A.MS_PT ,'')

return @sName
end

