IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetBCPBTVF')
   exec('CREATE PROCEDURE GetBCPBTVF AS BEGIN SET NOCOUNT ON; END')
GO


--	select top 50 *, convert(bit,1) as CHON, NULL AS TEN_N_XUONG into PBT_IN from PHIEU_BAO_TRI WHERE MS_PHIEU_BAO_TRI = 'WO-201901000012' ORDER BY NGAY_LAP DESC ; EXEC GetBCPBTVF 0
--GetBCPBTVF 0
ALTER PROC [dbo].[GetBCPBTVF]
(
	@NNgu INT = 0
)
as

SELECT * INTO #BT_PBT FROM PBT_IN WHERE CHON = 1

DROP TABLE PBT_IN


SELECT DISTINCT  D.HO + ' ' + D.TEN AS HO_TEN, dbo.Gettenchuyenmon(D.MS_CONG_NHAN) AS CHUYEN_MON, ISNULL(B.TEN_GOI, '') AS TRINH_DO_VH, 
                      dbo.Getnhantenbactho(D.MS_CONG_NHAN) AS BAC_THO
FROM         dbo.PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU AS A INNER JOIN
                      dbo.CONG_NHAN AS D ON A.MS_CONG_NHAN = D.MS_CONG_NHAN LEFT OUTER JOIN
                      dbo.TRINH_DO_VAN_HOA AS B ON D.MS_TRINH_DO = B.MS_TRINH_DO INNER JOIN 
                      #BT_PBT C ON A.MS_PHIEU_BAO_TRI = C.MS_PHIEU_BAO_TRI



--tao bang chua CV
SELECT        T1.*, T2.MS_CV, T2.MS_BO_PHAN, T4.TEN_LOAI_BT,T3.MO_TA_CV,T5.TEN_MAY,T2.DANH_GIA,Ten_N_XUONG INTO #TMP_cv
FROM            dbo.CONG_VIEC AS T3 INNER JOIN
                         dbo.PHIEU_BAO_TRI_CONG_VIEC AS T2 ON T3.MS_CV = T2.MS_CV RIGHT OUTER JOIN
                         dbo.PHIEU_BAO_TRI AS T1 INNER JOIN
                         dbo.LOAI_BAO_TRI AS T4 ON T1.MS_LOAI_BT = T4.MS_LOAI_BT ON T2.MS_PHIEU_BAO_TRI = T1.MS_PHIEU_BAO_TRI INNER JOIN dbo.MAY T5 ON T1.MS_MAY = T5.MS_MAY INNER JOIN 
						 #BT_PBT T6 ON T1.MS_MAY = T6.MS_MAY AND T6.MS_PHIEU_BAO_TRI = T1.MS_PHIEU_BAO_TRI
--						 	

SELECT  T1.MS_PHIEU_BAO_TRI , T1.MS_BO_PHAN , T2.TEN_BO_PHAN , T1.MO_TA_CV,
dbo.MGetCongNhanPBTCV(T1.MS_PHIEU_BAO_TRI,T1.MS_CV , T1.MS_BO_PHAN , '' ) AS CONG_NHAN,
dbo.GetVTuTheoPBTBPCVVF(T1.MS_PHIEU_BAO_TRI,T1.MS_CV , T1.MS_BO_PHAN , @NNgu ) AS VAT_TU, 
 T1.DANH_GIA, T1.MS_MAY , T1.TEN_MAY , 
 DBO.GetCongNhanYCSDCT(T1.MS_PHIEU_BAO_TRI) AS CN_YCSDCT,T1.LY_DO_BT,
  T1.Ten_N_XUONG,
 dbo.Get_MsYeuCau (T1.MS_PHIEU_BAO_TRI) AS PHIEU_YC, dbo.Get_NoiDungYeuCau(T1.MS_PHIEU_BAO_TRI) AS NOI_DUNG_YC,T1.TEN_LOAI_BT
FROM            #TMP_cv AS T1 LEFT JOIN
dbo.CAU_TRUC_THIET_BI AS T2 ON T1.MS_MAY = T2.MS_MAY AND T1.MS_BO_PHAN = T2.MS_BO_PHAN


	
--SELECT  E.MS_PHIEU_BAO_TRI , A.MS_BO_PHAN , B.TEN_BO_PHAN , D.MO_TA_CV,
--dbo.MGetCongNhanPBTCV(E.MS_PHIEU_BAO_TRI,A.MS_CV , A.MS_BO_PHAN , '' ) AS CONG_NHAN,
--dbo.GetVTuTheoPBTBPCVVF(E.MS_PHIEU_BAO_TRI,A.MS_CV , A.MS_BO_PHAN , @NNgu ) AS VAT_TU, 
-- A.DANH_GIA,E.MS_MAY , F.TEN_MAY , 
-- DBO.GetCongNhanYCSDCT(E.MS_PHIEU_BAO_TRI) AS CN_YCSDCT,E.LY_DO_BT, E.Ten_N_XUONG,
-- dbo.Get_MsYeuCau (E.MS_PHIEU_BAO_TRI) AS PHIEU_YC, dbo.Get_NoiDungYeuCau(E.MS_PHIEU_BAO_TRI) AS NOI_DUNG_YC,T1.TEN_LOAI_BT,A.MS_BO_PHAN,D.MS_CV 
--FROM         dbo.PHIEU_BAO_TRI_CONG_VIEC AS A INNER JOIN
--                      dbo.CAU_TRUC_THIET_BI AS B ON A.MS_BO_PHAN = B.MS_BO_PHAN INNER JOIN
--                      dbo.PHIEU_BAO_TRI AS C ON A.MS_PHIEU_BAO_TRI = C.MS_PHIEU_BAO_TRI AND B.MS_MAY = C.MS_MAY INNER JOIN
--                      dbo.CONG_VIEC AS D ON A.MS_CV = D.MS_CV INNER JOIN 
--                      #BT_PBT E ON A.MS_PHIEU_BAO_TRI = E.MS_PHIEU_BAO_TRI INNER JOIN
--                      MAY AS F ON C.MS_MAY = F.MS_MAY INNER JOIN dbo.LOAI_BAO_TRI T1 ON C.MS_LOAI_BT = T1.MS_LOAI_BT
--ORDER BY E.MS_PHIEU_BAO_TRI, A.MS_BO_PHAN ,  B.TEN_BO_PHAN                 
                      

SELECT  A.MS_PHIEU_BAO_TRI,     B.MS_MAY, E.TEN_BO_PHAN, C.MS_PT, D.TEN_PT, 
CASE ISNULL( SUM(C.SL_KH),0) WHEN 0 THEN  SUM(C.SL_TT) ELSE SUM(C.SL_KH) END AS SO_LUONG
,  CASE @NNgu  WHEN 0 THEN TEN_1 WHEN 1 THEN TEN_2 ELSE TEN_3 END AS TEN_DVT

FROM         dbo.PHIEU_BAO_TRI AS A INNER JOIN
                      MAY AS B ON A.MS_MAY = B.MS_MAY INNER JOIN
                      dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG AS C INNER JOIN
                      dbo.IC_PHU_TUNG AS D ON C.MS_PT = D.MS_PT ON A.MS_PHIEU_BAO_TRI = C.MS_PHIEU_BAO_TRI INNER JOIN
                      dbo.CAU_TRUC_THIET_BI AS E ON C.MS_BO_PHAN = E.MS_BO_PHAN AND A.MS_MAY = E.MS_MAY INNER JOIN
                      dbo.DON_VI_TINH AS F ON D.DVT = F.DVT INNER JOIN 
                      #BT_PBT G ON G.MS_PHIEU_BAO_TRI = A.MS_PHIEU_BAO_TRI
--WHERE 1 <> 1             
GROUP BY A.MS_PHIEU_BAO_TRI,     B.MS_MAY, E.TEN_BO_PHAN, C.MS_PT, D.TEN_PT,   
CASE @NNgu  WHEN 0 THEN TEN_1 WHEN 1 THEN TEN_2 ELSE TEN_3 END       

ORDER BY A.MS_PHIEU_BAO_TRI, B.MS_MAY, E.TEN_BO_PHAN, C.MS_PT, D.TEN_PT

