IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo'  AND Table_Name ='LOAI_GIAY_PHEP')
BEGIN
/****** Object:  Table [dbo].[GIAY_PHEP]    Script Date: 26/11/2020 09:00:18 ******/
CREATE TABLE [dbo].[LOAI_GIAY_PHEP](
	[MS_LOAI_GP] [bigint] IDENTITY(1,1) NOT NULL,
	[TEN_LOAI_GP] [nvarchar](250) NULL,
	[TEN_LOAI_GP_A] [nvarchar](250) NULL,
	[TEN_LOAI_GP_H] [nvarchar](250) NULL,
 CONSTRAINT [PK_LOAI_GIAY_PHEP] PRIMARY KEY CLUSTERED 
(
	[MS_LOAI_GP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
SET IDENTITY_INSERT [dbo].[LOAI_GIAY_PHEP] ON 

INSERT [dbo].[LOAI_GIAY_PHEP] ([MS_LOAI_GP], [TEN_LOAI_GP], [TEN_LOAI_GP_A], [TEN_LOAI_GP_H]) VALUES (1, N'GP LV Trên Cao', N'GP LV Trên Cao', N'GP LV Trên Cao')
INSERT [dbo].[LOAI_GIAY_PHEP] ([MS_LOAI_GP], [TEN_LOAI_GP], [TEN_LOAI_GP_A], [TEN_LOAI_GP_H]) VALUES (2, N'GP cắt hàn', N'GP cắt hàn', N'GP cắt hàn')
INSERT [dbo].[LOAI_GIAY_PHEP] ([MS_LOAI_GP], [TEN_LOAI_GP], [TEN_LOAI_GP_A], [TEN_LOAI_GP_H]) VALUES (3, N'GP KVGH', N'GP KVGH', N'GP KVGH')
SET IDENTITY_INSERT [dbo].[LOAI_GIAY_PHEP] OFF
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo'  AND Table_Name ='GIAY_PHEP')
BEGIN
/****** Object:  Table [dbo].[GIAY_PHEP]    Script Date: 26/11/2020 09:00:18 ******/
CREATE TABLE [dbo].[GIAY_PHEP](
	[MS_GP] [nvarchar](12) NOT NULL,
	[MS_LOAI_GP] [bigint] NULL,
	[MS_N_XUONG] [nvarchar](50) NULL,
	[DS_PHIEU_BAO_TRI] [nvarchar](500) NULL,
	[DUYET] [bit] NULL,
	[NGUOI_LAP] [nvarchar](9) NULL,
	[NGAY_LAP] [datetime] NULL,
	[NGUOI_DUYET] [nvarchar](9) NULL,
	[NGAY_DUYET] [datetime] NULL,
	[GHI_CHU] [nvarchar](500) NULL,
 CONSTRAINT [PK_GIAY_PHEP] PRIMARY KEY CLUSTERED 
(
	[MS_GP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[GIAY_PHEP]  WITH CHECK ADD  CONSTRAINT [FK_GIAY_PHEP_LOAI_GIAY_PHEP] FOREIGN KEY([MS_LOAI_GP])
REFERENCES [dbo].[LOAI_GIAY_PHEP] ([MS_LOAI_GP])
ALTER TABLE [dbo].[GIAY_PHEP] CHECK CONSTRAINT [FK_GIAY_PHEP_LOAI_GIAY_PHEP]
ALTER TABLE [dbo].[GIAY_PHEP]  WITH CHECK ADD  CONSTRAINT [FK_GIAY_PHEP_NHA_XUONG] FOREIGN KEY([MS_N_XUONG])
REFERENCES [dbo].[NHA_XUONG] ([MS_N_XUONG])
ALTER TABLE [dbo].[GIAY_PHEP] CHECK CONSTRAINT [FK_GIAY_PHEP_NHA_XUONG]
END
if not exists(select * from sys.columns 
            where Name = N'BAN_GIAO' and Object_ID = Object_ID(N'PHIEU_BAO_TRI'))
begin
    ALTER TABLE dbo.PHIEU_BAO_TRI ADD BAN_GIAO BIT  DEFAULT (0)
END    
GO	
