
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo'  AND Table_Name ='PHIEU_TAM_XUAT_TAI_NHAP')
BEGIN
CREATE TABLE [dbo].[PHIEU_TAM_XUAT_TAI_NHAP](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[MS_TX_TN] [NVARCHAR](12) NULL,
	[NGUOI_DE_NGHI] [NVARCHAR](50) NULL,
	[MS_NHAN_VIEN] [NVARCHAR](50) NULL,
	[TEN_BO_PHAN] [NCHAR](50) NULL,
	[CNMD] [NVARCHAR](50) NULL,
	[NGUOI_MANG_RA] [NVARCHAR](50) NULL,
	[NOI_NHAN] [NVARCHAR](50) NULL,
	[PHUONG_TIEN_VC] [NVARCHAR](50) NULL,
	[TG_MANG_VE] [DATETIME] NULL,
	[NGUOI_LAP] [NVARCHAR](50) NULL,
	[NGAY_LAP] [DATETIME] NULL,
	[NGUOI_DUYET] [NVARCHAR](50) NULL,
	[NGAY_DUYET] [DATETIME] NULL,
	[GHI_CHU] [NVARCHAR](250) NULL,
 CONSTRAINT [PK_PHIEU_TAM_XUAT_TAI_NHAP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo'  AND Table_Name ='PHIEU_TAM_XUAT_TAI_NHAP_CHI_TIET')
BEGIN
CREATE TABLE [dbo].[PHIEU_TAM_XUAT_TAI_NHAP_CHI_TIET](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[ID_TNX] [BIGINT] NULL,
	[MS_TAI_SAN] [NVARCHAR](50) NULL,
	[TEN_TAI_SAN] [NVARCHAR](50) NULL,
	[DVT] [NVARCHAR](10) NULL,
	[SL_XUAT] [DECIMAL](18, 2) NULL,
	[LY_DO_XUAT] [NVARCHAR](150) NULL,
	[NGAY_XUAT] [DATETIME] NULL,
	[SL_NHAP] [DECIMAL](18, 2) NULL,
	[LY_DO_NHAP] [NVARCHAR](150) NULL,
	[NGAY_NHAP] [DATETIME] NULL,
 CONSTRAINT [PK_PHIEU_TAM_XUAT_TAI_NHAP_CHI_TIET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

if not exists(select * from sys.columns 
            where Name = N'Col1' and Object_ID = Object_ID(N'GIAY_PHEP'))
begin
    ALTER TABLE dbo.GIAY_PHEP ADD Col1 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col2 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col3 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col4 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col5 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col6 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col7 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col8 NVARCHAR(250) NULL
	ALTER TABLE dbo.GIAY_PHEP ADD Col9 NVARCHAR(250) NULL
END    
GO	
