

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AUTO_CREATE_SO_TAM_XUAT]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[AUTO_CREATE_SO_TAM_XUAT]
GO
CREATE FUNCTION [dbo].[AUTO_CREATE_SO_TAM_XUAT] (
	@DATE DATETIME = '01/01/2020' )
	RETURNS NVARCHAR(12)
AS 
BEGIN
DECLARE @STTMAX INT 
SELECT @STTMAX = MAX(CONVERT(INT,RIGHT (MS_TX_TN,4)))  
FROM dbo.PHIEU_TAM_XUAT_TAI_NHAP
WHERE  LEFT(MS_TX_TN,2) = 'TX' AND SUBSTRING(MS_TX_TN,4,4) = CONVERT(NVARCHAR(4) , @DATE , 12)

DECLARE @STT_NEXT NVARCHAR(10)
SET @STT_NEXT =  '0000' + CONVERT(NVARCHAR(4),ISNULL(@STTMAX,0) +1)
--SELECT @STT_NEXT 
DECLARE @ID NVARCHAR(12)
SET @ID = 'TX-' +  CONVERT(NVARCHAR(4) , @DATE , 12)  + '-' +  RIGHT (@STT_NEXT,4)
RETURN @ID
END

