

--INSERT INTO CMMS_PILMICO.DBO.DON_VI_TINH(DVT,TEN_1,TEN_2,TEN_3)
--SELECT T1.UOMID ,UOMName TEN_1,UOMName TEN_2,UOMName TEN_3  FROM PilmicoIntegration.DBO.UnitOfMeasurement T1 INNER JOIN (
--SELECT MAX(ID) AS ID,UOMID FROM PilmicoIntegration.DBO.UnitOfMeasurement GROUP BY UOMID) T2 
--ON T1.ID = T2.ID

--SELECT * FROM PilmicoIntegration.DBO.WarehouseList
--SELECT * FROM CMMS_PILMICO.DBO.IC_KHO



--SELECT T1.WarehouseID AS MS_KHO_INT ,WarehouseName AS TEN_KHO INTO #KHOTAM  FROM PilmicoIntegration.DBO.WarehouseList T1 INNER JOIN (
--SELECT MAX(ID) AS ID,WarehouseID FROM PilmicoIntegration.DBO.WarehouseList GROUP BY WarehouseID) T2 
--ON T1.ID = T2.ID 
--WHERE T1.WarehouseID NOT IN(SELECT MS_KHO_INT FROM CMMS_PILMICO.DBO.IC_KHO)

----SELECT * FROM #KHOTAM

--INSERT INTO CMMS_PILMICO.DBO.IC_KHO(TEN_KHO,MS_KHO_INT)
--SELECT TEN_KHO,MS_KHO_INT FROM #KHOTAM


--INSERT INTO CMMS_PILMICO.DBO.VI_TRI_KHO(MS_KHO,TEN_VI_TRI,GHI_CHU)
--SELECT T2.MS_KHO, 'N/A' AS TEN_VI_TRI, 'Integration' AS GHI_CHU FROM #KHOTAM T1 INNER JOIN CMMS_PILMICO.DBO.IC_KHO T2 ON CONVERT(NVARCHAR(50),T1.MS_KHO_INT) = CONVERT(NVARCHAR(50),T2.MS_KHO_INT)




--SELECT T1.ItemID,ItemName,Active,UOMID INTO #ITEM FROM PilmicoIntegration.DBO.ItemList T1 INNER JOIN (
--SELECT MAX(ID) AS ID,ItemID FROM PilmicoIntegration.DBO.ItemList GROUP BY ItemID) T2 
--ON T1.ID = T2.ID

--INSERT into CMMS_PILMICO.dbo.IC_PHU_TUNG(MS_PT,TEN_PT,ACTIVE_PT,DVT,MS_LOAI_VT, MS_CACH_DAT_HANG,SO_NGAY_DAT_MUA_HANG,HANG_NGOAI,THEO_KHO,USER_INSERT_PT,NGAY_INSERT_PT,MS_KHO) 
--SELECT ItemID,ItemName,Active,UOMID,'0000',11,0,0,1,'Admin',GETDATE(),34 FROM #ITEM WHERE 
--CONVERT(NVARCHAR(50),ItemID) NOT IN(SELECT DISTINCT MS_PT FROM CMMS_PILMICO.dbo.IC_PHU_TUNG)

--UPDATE CMMS_PILMICO.dbo.IC_PHU_TUNG SET TEN_PT = T2.ItemName, ACTIVE_PT = T2.Active, DVT = T2.UOMID,USER_UPDATE_PT = 'Admin',NGAY_UPDATE_PT =GETDATE() FROM CMMS_PILMICO.dbo.IC_PHU_TUNG T1 INNER JOIN #ITEM T2 ON T1.MS_PT = CONVERT(NVARCHAR,T2.ItemID)

				INSERT INTO CMMS_PILMICO.dbo.IC_PHU_TUNG_KHO(MS_PT,MS_KHO,MS_VI_TRI)
				SELECT distinct CONVERT(NVARCHAR(50),ItemID),MS_KHO,MS_VI_TRI FROM
				(SELECT DISTINCT MS_KHO,MIN(MS_VI_TRI) AS MS_VI_TRI FROM CMMS_PILMICO.dbo.VI_TRI_KHO GROUP BY MS_KHO) T1,#ITEM T2

				INSERT INTO CMMS_PILMICO.dbo.IC_PHU_TUNG_LOAI_MAY(MS_PT,MS_LOAI_MAY)
				SELECT DISTINCT CONVERT(NVARCHAR(50),ItemID) AS MS_PT,MS_LOAI_MAY FROM CMMS_PILMICO.dbo.IC_PHU_TUNG_LOAI_MAY T1,#ITEM T2 

				
				INSERT INTO CMMS_PILMICO.dbo.IC_PHU_TUNG_LOAI_PHU_TUNG(MS_PT,MS_LOAI_PT)
				SELECT DISTINCT CONVERT(NVARCHAR(50),ItemID) AS MS_PT, MS_LOAI_PT FROM CMMS_PILMICO.dbo.IC_PHU_TUNG_LOAI_PHU_TUNG T1,#ITEM T2 