

--INSERT INTO CMMS_PILMICO.DBO.DON_VI_TINH(DVT,TEN_1,TEN_2,TEN_3)
--SELECT T1.UOMID ,UOMName TEN_1,UOMName TEN_2,UOMName TEN_3  FROM PilmicoIntegration.DBO.UnitOfMeasurement T1 INNER JOIN (
--SELECT MAX(ID) AS ID,UOMID FROM PilmicoIntegration.DBO.UnitOfMeasurement GROUP BY UOMID) T2 
--ON T1.ID = T2.ID

SELECT * FROM PilmicoIntegration.DBO.WarehouseList
SELECT * FROM CMMS_PILMICO.DBO.IC_KHO



SELECT T1.WarehouseID AS MS_KHO_INT ,WarehouseName AS TEN_KHO INTO #KHOTAM  FROM PilmicoIntegration.DBO.WarehouseList T1 INNER JOIN (
SELECT MAX(ID) AS ID,WarehouseID FROM PilmicoIntegration.DBO.WarehouseList GROUP BY WarehouseID) T2 
ON T1.ID = T2.ID 
WHERE T1.WarehouseID NOT IN(SELECT MS_KHO_INT FROM CMMS_PILMICO.DBO.IC_KHO)

--SELECT * FROM #KHOTAM

INSERT INTO CMMS_PILMICO.DBO.IC_KHO(TEN_KHO,MS_KHO_INT)
SELECT TEN_KHO,MS_KHO_INT FROM #KHOTAM


INSERT INTO CMMS_PILMICO.DBO.VI_TRI_KHO(MS_KHO,TEN_VI_TRI,GHI_CHU)
SELECT T2.MS_KHO, 'N/A' AS TEN_VI_TRI, 'Integration' AS GHI_CHU FROM #KHOTAM T1 INNER JOIN CMMS_PILMICO.DBO.IC_KHO T2 ON CONVERT(NVARCHAR(50),T1.MS_KHO_INT) = CONVERT(NVARCHAR(50),T2.MS_KHO_INT)