
IF NOT EXISTS (SELECT * FROM   sys.columns WHERE  object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG]') AND name = 'MS_PT_TT')
begin
    ALTER TABLE PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG ADD MS_PT_TT NVARCHAR(25)
end 
