	
UPDATE LANGUAGES SET VIETNAM = N'BM.QT.01.CĐ.08', VIETNAM_OR = N'BM.QT.01.CĐ.08', ENGLISH = N'BM.QT.01.CĐ.08', ENGLISH_OR = N'BM.QT.01.CĐ.08'
WHERE  KEYWORD = N'TM1' AND FORM = N'rptTHONG_TIN_CHUNG_VA_THONG_SO_TB' UPDATE LANGUAGES
SET VIETNAM = N'Lần ban hành: 02', VIETNAM_OR = N'Lần ban hành: 02', ENGLISH = N'Effective times: 02', ENGLISH_OR = N'Effective times: 02'
WHERE  KEYWORD = N'TM2' AND FORM = N'rptTHONG_TIN_CHUNG_VA_THONG_SO_TB'
UPDATE LANGUAGES SET VIETNAM = N'Ngày ban hành: 01/08/2015', VIETNAM_OR = N'Ngày ban hành: 01/08/2015', ENGLISH = N'Effective date: 01/08/2015', ENGLISH_OR = N'Effective date: 01/08/2015'
WHERE  KEYWORD = N'TM3' AND FORM = N'rptTHONG_TIN_CHUNG_VA_THONG_SO_TB'
