UPDATE LANGUAGES SET VIETNAM = N'BM.QT.01.CĐ.06', VIETNAM_OR = N'BM.QT.01.CĐ.06', ENGLISH = N'BM.QT.01.CĐ.06', ENGLISH_OR= N'BM.QT.01.CĐ.06'  
WHERE FORM = N'rptLICH_SU_THIET_BI' AND KEYWORD = 'TM1'
UPDATE LANGUAGES SET VIETNAM = N'Lần ban hành: 02', VIETNAM_OR = N'Lần ban hành: 02', ENGLISH = N'Effective times: 02', ENGLISH_OR= N'Effective times: 02'  
WHERE FORM = N'rptLICH_SU_THIET_BI' AND KEYWORD = 'TM2'
UPDATE LANGUAGES SET VIETNAM = N'Ngày ban hành: 01/08/2015', VIETNAM_OR = N'Ngày ban hành: 01/08/2015', ENGLISH = N'Effective date: 01/08/2015', ENGLISH_OR= N'Effective date: 01/08/2015'  
WHERE FORM = N'rptLICH_SU_THIET_BI' AND KEYWORD = 'TM3'

