IF EXISTS (SELECT * FROM ds_report WHERE report_name = N'ucMailVatTuDeXuatChuaNhapKho'  AND ten_report_viet = N'Vật tư đề xuất chưa nhập kho') 
UPDATE ds_report SET ten_report_viet = N'Vật tư đề xuất chưa nhập kho', ten_report_anh =N'Spare part and materials requested but not received' where 
report_name = N'ucMailVatTuDeXuatChuaNhapKho'  AND ten_report_viet = N'Vật tư đề xuất chưa nhập khon' ELSE INSERT INTO ds_report(report_name, ten_report_viet ,ten_report_anh) 
 VALUES(N'ucMailVatTuDeXuatChuaNhapKho',N'Vật tư đề xuất chưa nhập kho',N'Spare part and materials requested but not received')

 IF EXISTS (SELECT * FROM ds_report WHERE report_name = N'frmBCLSTB_Antoan' ) 
UPDATE ds_report SET ten_report_viet = N'Báo cáo lịch sử thiết bị cần đảm bảo an toàn', ten_report_anh =N'Maintenance history for safety-related equipment' where 
report_name = N'frmBCLSTB_Antoan'  AND ten_report_viet = N'Báo cáo lịch sử thiết bị an toàn' ELSE 
INSERT INTO ds_report(report_name, ten_report_viet ,ten_report_anh) 
 VALUES(N'frmBCLSTB_Antoan',N'Báo cáo lịch sử thiết bị an toàn',N'Maintenance history for safe equipment')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThongTinThietBi' AND KEYWORD =N'chxAnToan') UPDATE LANGUAGES SET VIETNAM=N'Cần đảm bảo an toàn', ENGLISH=N'Safety-related equipment', VIETNAM_OR=N'Cần đảm bảo an toàn', ENGLISH_OR=N'Safety-related equipment' WHERE FORM=N'frmThongTinThietBi' AND KEYWORD=N'chxAnToan' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmThongTinThietBi',N'chxAnToan',N'Cần đảm bảo an toàn',N'Safety-related equipment',N'Cần đảm bảo an toàn',N'Safety-related equipment')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDanhmuccongviec' AND KEYWORD =N'AN_TOAN') UPDATE LANGUAGES SET VIETNAM=N'CV đảm bảo an toàn', ENGLISH=N'Safety-related work', VIETNAM_OR=N'CV đảm bảo an toàn', ENGLISH_OR=N'Safety-related work' WHERE FORM=N'frmDanhmuccongviec' AND KEYWORD=N'AN_TOAN' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmDanhmuccongviec',N'AN_TOAN',N'CV đảm bảo an toàn',N'Safety-related work',N'CV đảm bảo an toàn',N'Safety-related work')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDanhmuccongviec' AND KEYWORD =N'chxAnToan') UPDATE LANGUAGES SET VIETNAM=N'CV đảm bảo an toàn', ENGLISH=N'Safety-related work', VIETNAM_OR=N'CV đảm bảo an toàn', ENGLISH_OR=N'Safety-related work' WHERE FORM=N'frmDanhmuccongviec' AND KEYWORD=N'chxAnToan' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmDanhmuccongviec',N'chxAnToan',N'CV đảm bảo an toàn',N'Safety-related work',N'CV đảm bảo an toàn',N'Safety-related work')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmBCLSTB_Antoan' AND KEYWORD =N'TIEU_DE') UPDATE LANGUAGES SET VIETNAM=N'LỊCH SỬ BẢO TRÌ CHO CÁC THIẾT BỊ CẦN ĐẢM BẢO AN TOÀN ', ENGLISH=N'MAINTENANCE HISTORY FOR SAFETY-RELATED EQUIPMENT', VIETNAM_OR=N'LỊCH SỬ BẢO TRÌ CHO CÁC THIẾT BỊ CẦN ĐẢM BẢO AN TOÀN ', ENGLISH_OR=N'MAINTENANCE HISTORY FOR SAFETY-RELATED EQUIPMENT' WHERE FORM=N'frmBCLSTB_Antoan' AND KEYWORD=N'TIEU_DE' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmBCLSTB_Antoan',N'TIEU_DE',N'LỊCH SỬ BẢO TRÌ CHO CÁC THIẾT BỊ CẦN ĐẢM BẢO AN TOÀN ',N'MAINTENANCE HISTORY FOR SAFETY-RELATED EQUIPMENT',N'LỊCH SỬ BẢO TRÌ CHO CÁC THIẾT BỊ CẦN ĐẢM BẢO AN TOÀN ',N'MAINTENANCE HISTORY FOR SAFETY-RELATED EQUIPMENT')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThietBi' AND KEYWORD =N'Lbltennhomthietbi') UPDATE LANGUAGES SET VIETNAM=N'Tên nhóm TB', ENGLISH=N'Eq. group name', VIETNAM_OR=N'Tên nhóm TB', ENGLISH_OR=N'Eq. group name' WHERE FORM=N'frmThietBi' AND KEYWORD=N'Lbltennhomthietbi' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmThietBi',N'Lbltennhomthietbi',N'Tên nhóm TB',N'Eq. group name',N'Tên nhóm TB',N'Eq. group name')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmThietBi' AND KEYWORD =N'TEN_NHOM_MAY') UPDATE LANGUAGES SET VIETNAM=N'Tên nhóm TB', ENGLISH=N'Eq. group name', VIETNAM_OR=N'Tên nhóm TB', ENGLISH_OR=N'Eq. group name' WHERE FORM=N'frmThietBi' AND KEYWORD=N'TEN_NHOM_MAY' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmThietBi',N'TEN_NHOM_MAY',N'Tên nhóm TB',N'Eq. group name',N'Tên nhóm TB',N'Eq. group name')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD =N'msgPhaiNhapHangMucSuaChua') UPDATE LANGUAGES SET VIETNAM=N'Vui lòng nhập hạng mục sửa chữa', ENGLISH=N'Please enter repair article', VIETNAM_OR=N'Vui lòng nhập hạng mục sửa chữa', ENGLISH_OR=N'Please enter repair article' WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD=N'msgPhaiNhapHangMucSuaChua' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmKehoachtongthe_odd',N'msgPhaiNhapHangMucSuaChua',N'Vui lòng nhập hạng mục sửa chữa',N'Please enter repair article',N'Vui lòng nhập hạng mục sửa chữa',N'Please enter repair article')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD =N'MS_LOAI_YEU_CAU_BT') UPDATE LANGUAGES SET VIETNAM=N'Loại yêu cầu bảo trì', ENGLISH=N'Request type', VIETNAM_OR=N'Loại yêu cầu bảo trì', ENGLISH_OR=N'Request type' WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD=N'MS_LOAI_YEU_CAU_BT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmYeuCauCuaNSD',N'MS_LOAI_YEU_CAU_BT',N'Loại yêu cầu bảo trì',N'Request type',N'Loại yêu cầu bảo trì',N'Request type')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD =N'msgPhaiNhapLyDoSuaChua') UPDATE LANGUAGES SET VIETNAM=N'Vui lòng nhập lý do sửa chữa', ENGLISH=N'Please enter repair cause', VIETNAM_OR=N'Vui lòng nhập lý do sửa chữa', ENGLISH_OR=N'Please enter repair cause' WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD=N'msgPhaiNhapLyDoSuaChua' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmKehoachtongthe_odd',N'msgPhaiNhapLyDoSuaChua',N'Vui lòng nhập lý do sửa chữa',N'Please enter repair cause',N'Vui lòng nhập lý do sửa chữa',N'Please enter repair cause')
