IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'SERVICE_LEVEL') UPDATE LANGUAGES SET VIETNAM=N'Mức đảm bảo', ENGLISH=N'Service level',CHINESE=N'Service level', VIETNAM_OR=N'Mức đảm bảo', ENGLISH_OR=N'Service level' , CHINESE_OR=N'Service level' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'SERVICE_LEVEL' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'SERVICE_LEVEL',N'Mức đảm bảo',N'Service level',N'Service level',N'Mức đảm bảo',N'Service level',N'Service level','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'TEN_PT') UPDATE LANGUAGES SET VIETNAM=N'Tên VT PT', ENGLISH=N'Item name',CHINESE=N'Item name', VIETNAM_OR=N'Tên VT PT', ENGLISH_OR=N'Item name' , CHINESE_OR=N'Item name' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'TEN_PT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'TEN_PT',N'Tên VT PT',N'Item name',N'Item name',N'Tên VT PT',N'Item name',N'Item name','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'HANG_NGOAI') UPDATE LANGUAGES SET VIETNAM=N'Hàng ngoại', ENGLISH=N'Import',CHINESE=N'Import', VIETNAM_OR=N'Hàng ngoại', ENGLISH_OR=N'Import' , CHINESE_OR=N'Import' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'HANG_NGOAI' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'HANG_NGOAI',N'Hàng ngoại',N'Import',N'Import',N'Hàng ngoại',N'Import',N'Import','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'VAT_TU_PT') UPDATE LANGUAGES SET VIETNAM=N'Vật tư', ENGLISH=N'Material',CHINESE=N'Material', VIETNAM_OR=N'Vật tư', ENGLISH_OR=N'Material' , CHINESE_OR=N'Material' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'VAT_TU_PT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'VAT_TU_PT',N'Vật tư',N'Material',N'Material',N'Vật tư',N'Material',N'Material','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'ACTIVE_PT') UPDATE LANGUAGES SET VIETNAM=N'Hiệu lực', ENGLISH=N'Active',CHINESE=N'Active', VIETNAM_OR=N'Hiệu lực', ENGLISH_OR=N'Active' , CHINESE_OR=N'Active' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'ACTIVE_PT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'ACTIVE_PT',N'Hiệu lực',N'Active',N'Active',N'Hiệu lực',N'Active',N'Active','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'MS_LOAI_VT') UPDATE LANGUAGES SET VIETNAM=N'MS Loại VT PT', ENGLISH=N'Item type ID',CHINESE=N'Item type ID', VIETNAM_OR=N'MS Loại VT PT', ENGLISH_OR=N'Item type ID' , CHINESE_OR=N'Item type ID' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'MS_LOAI_VT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'MS_LOAI_VT',N'MS Loại VT PT',N'Item type ID',N'Item type ID',N'MS Loại VT PT',N'Item type ID',N'Item type ID','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD =N'ANH_PT') UPDATE LANGUAGES SET VIETNAM=N'Đường dẫn hình', ENGLISH=N'Image path',CHINESE=N'Image path', VIETNAM_OR=N'Đường dẫn hình', ENGLISH_OR=N'Image path' , CHINESE_OR=N'Image path' WHERE FORM=N'rptDanhsach_VTPT' AND KEYWORD=N'ANH_PT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptDanhsach_VTPT',N'ANH_PT',N'Đường dẫn hình',N'Image path',N'Image path',N'Đường dẫn hình',N'Image path',N'Image path','ECOMAIN')



IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'SO_GIO_KH') UPDATE LANGUAGES SET VIETNAM=N'Số phút thực hiện (kế hoạch) Phút', ENGLISH=N'Plan minutes',CHINESE=N'Plan minutes', VIETNAM_OR=N'Số phút thực hiện (kế hoạch) Phút', ENGLISH_OR=N'Plan minutes' , CHINESE_OR=N'Plan minutes' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'SO_GIO_KH' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'SO_GIO_KH',N'Số phút thực hiện (kế hoạch) Phút',N'Plan minutes',N'Plan minutes',N'Số phút thực hiện (kế hoạch) Phút',N'Plan minutes',N'Plan minutes','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'TG_KH_CO_KH') UPDATE LANGUAGES SET VIETNAM=N'Tổng công cho CV có KH (kế hoạch) Phút', ENGLISH=N'Time of planned work (Planed)',CHINESE=N'Time of planned work (Planed)', VIETNAM_OR=N'Tổng công cho CV có KH (kế hoạch) Phút', ENGLISH_OR=N'Time of planned work (Planed)' , CHINESE_OR=N'Time of planned work (Planed)' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'TG_KH_CO_KH' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'TG_KH_CO_KH',N'Tổng công cho CV có KH (kế hoạch) Phút',N'Time of planned work (Planed)',N'Time of planned work (Planed)',N'Tổng công cho CV có KH (kế hoạch) Phút',N'Time of planned work (Planed)',N'Time of planned work (Planed)','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'TG_KH_KG_KH') UPDATE LANGUAGES SET VIETNAM=N'Tổng công cho CV không KH (kế hoạch) Phút', ENGLISH=N'Time of un-planned work (Planed)',CHINESE=N'Time of un-planned work (Planed)', VIETNAM_OR=N'Tổng công cho CV không KH (kế hoạch) Phút', ENGLISH_OR=N'Time of un-planned work (Planed)' , CHINESE_OR=N'Time of un-planned work (Planed)' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'TG_KH_KG_KH' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'TG_KH_KG_KH',N'Tổng công cho CV không KH (kế hoạch) Phút',N'Time of un-planned work (Planed)',N'Time of un-planned work (Planed)',N'Tổng công cho CV không KH (kế hoạch) Phút',N'Time of un-planned work (Planed)',N'Time of un-planned work (Planed)','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'TG_NM') UPDATE LANGUAGES SET VIETNAM=N'Số phút dừng máy Phút', ENGLISH=N'Breakdown time (min)',CHINESE=N'Breakdown time (min)', VIETNAM_OR=N'Số phút dừng máy Phút', ENGLISH_OR=N'Breakdown time (min)' , CHINESE_OR=N'Breakdown time (min)' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'TG_NM' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'TG_NM',N'Số phút dừng máy Phút',N'Breakdown time (min)',N'Breakdown time (min)',N'Số phút dừng máy Phút',N'Breakdown time (min)',N'Breakdown time (min)','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'TG_S') UPDATE LANGUAGES SET VIETNAM=N'Số phút thực hiện (thực tế) Phút', ENGLISH=N'Actual minutes',CHINESE=N'Actual minutes', VIETNAM_OR=N'Số phút thực hiện (thực tế) Phút', ENGLISH_OR=N'Actual minutes' , CHINESE_OR=N'Actual minutes' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'TG_S' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'TG_S',N'Số phút thực hiện (thực tế) Phút',N'Actual minutes',N'Actual minutes',N'Số phút thực hiện (thực tế) Phút',N'Actual minutes',N'Actual minutes','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'TG_TT_CO_KH') UPDATE LANGUAGES SET VIETNAM=N'Tổng công cho CV có KH (thực tế) Phút', ENGLISH=N'Time of planned work (Actual)',CHINESE=N'Time of planned work (Actual)', VIETNAM_OR=N'Tổng công cho CV có KH (thực tế) Phút', ENGLISH_OR=N'Time of planned work (Actual)' , CHINESE_OR=N'Time of planned work (Actual)' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'TG_TT_CO_KH' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'TG_TT_CO_KH',N'Tổng công cho CV có KH (thực tế) Phút',N'Time of planned work (Actual)',N'Time of planned work (Actual)',N'Tổng công cho CV có KH (thực tế) Phút',N'Time of planned work (Actual)',N'Time of planned work (Actual)','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'TG_TT_KG_KH') UPDATE LANGUAGES SET VIETNAM=N'Tổng công cho CV không KH (thực tế) Phút', ENGLISH=N'Time of un-planned work (Actual)',CHINESE=N'Time of un-planned work (Actual)', VIETNAM_OR=N'Tổng công cho CV không KH (thực tế) Phút', ENGLISH_OR=N'Time of un-planned work (Actual)' , CHINESE_OR=N'Time of un-planned work (Actual)' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'TG_TT_KG_KH' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'TG_TT_KG_KH',N'Tổng công cho CV không KH (thực tế) Phút',N'Time of un-planned work (Actual)',N'Time of un-planned work (Actual)',N'Tổng công cho CV không KH (thực tế) Phút',N'Time of un-planned work (Actual)',N'Time of un-planned work (Actual)','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'ucBangKePBT' AND KEYWORD =N'S_NGUOI') UPDATE LANGUAGES SET VIETNAM=N'Số nhân sự thực hiện', ENGLISH=N'Number of people',CHINESE=N'Number of people', VIETNAM_OR=N'Số nhân sự thực hiện', ENGLISH_OR=N'Number of people' , CHINESE_OR=N'Number of people' WHERE FORM=N'ucBangKePBT' AND KEYWORD=N'S_NGUOI' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'ucBangKePBT',N'S_NGUOI',N'Số nhân sự thực hiện',N'Number of people',N'Number of people',N'Số nhân sự thực hiện',N'Number of people',N'Number of people','ECOMAIN')


