

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD =N'NGAY_GIO') UPDATE LANGUAGES SET VIETNAM=N'Ngày giám sát', ENGLISH=N'Monitoring date',CHINESE=N'Monitoring date', VIETNAM_OR=N'Ngày giám sát', ENGLISH_OR=N'Monitoring date' , CHINESE_OR=N'Monitoring date' WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD=N'NGAY_GIO' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGiamsattinhtrang',N'NGAY_GIO',N'Ngày giám sát',N'Monitoring date',N'Monitoring date',N'Ngày giám sát',N'Monitoring date',N'Monitoring date','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD =N'chkDat') UPDATE LANGUAGES SET VIETNAM=N'Đạt', ENGLISH=N'OK',CHINESE=N'OK', VIETNAM_OR=N'Đạt', ENGLISH_OR=N'OK' , CHINESE_OR=N'OK' WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD=N'chkDat' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonThongSoGSTTDinhTinh',N'chkDat',N'Đạt',N'OK',N'OK',N'Đạt',N'OK',N'OK','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD =N'btDatall') UPDATE LANGUAGES SET VIETNAM=N'Chọn tất cả đạt', ENGLISH=N'All OK',CHINESE=N'All OK', VIETNAM_OR=N'Chọn tất cả đạt', ENGLISH_OR=N'All OK' , CHINESE_OR=N'All OK' WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD=N'btDatall' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonThongSoGSTTDinhTinh',N'btDatall',N'Chọn tất cả đạt',N'All OK',N'All OK',N'Chọn tất cả đạt',N'All OK',N'All OK','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD =N'msgBanCanPhaiChonMotTrongBaDieuKienDeChonTatCa') UPDATE LANGUAGES SET VIETNAM=N'Để chọn được tất cả bạn cần phải chọn một trong 3 điều kiện lọc', ENGLISH=N'',CHINESE=N'', VIETNAM_OR=N'Để chọn được tất cả bạn cần phải chọn một trong 3 điều kiện lọc', ENGLISH_OR=N'' , CHINESE_OR=N'' WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD=N'msgBanCanPhaiChonMotTrongBaDieuKienDeChonTatCa' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonThongSoGSTTDinhTinh',N'msgBanCanPhaiChonMotTrongBaDieuKienDeChonTatCa',N'Để chọn được tất cả bạn cần phải chọn một trong 3 điều kiện lọc',N'',N'',N'Để chọn được tất cả bạn cần phải chọn một trong 3 điều kiện lọc',N'',N'','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD =N'btnAllOK') UPDATE LANGUAGES SET VIETNAM=N'Đạt theo máy', ENGLISH=N'All devices ok',CHINESE=N'All devices ok', VIETNAM_OR=N'Đạt theo máy', ENGLISH_OR=N'All devices ok' , CHINESE_OR=N'All devices ok' WHERE FORM=N'frmChonThongSoGSTTDinhTinh' AND KEYWORD=N'btnAllOK' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonThongSoGSTTDinhTinh',N'btnAllOK',N'Đạt theo máy',N'All devices ok',N'All devices ok',N'Đạt theo máy',N'All devices ok',N'All devices ok','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD =N'MsgChonGiamSat') UPDATE LANGUAGES SET VIETNAM=N'Vui lòng chọn lần giám sát cần sửa!', ENGLISH=N'Please select monitoring need edit!',CHINESE=N'Please select monitoring need edit!', VIETNAM_OR=N'Vui lòng chọn lần giám sát cần sửa!', ENGLISH_OR=N'Please select monitoring need edit!' , CHINESE_OR=N'Please select monitoring need edit!' WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD=N'MsgChonGiamSat' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGiamsattinhtrang',N'MsgChonGiamSat',N'Vui lòng chọn lần giám sát cần sửa!',N'Please select monitoring need edit!',N'Please select monitoring need edit!',N'Vui lòng chọn lần giám sát cần sửa!',N'Please select monitoring need edit!',N'Please select monitoring need edit!','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD =N'msgConDongCuoiCoMuonXoaLuonLanGiamSat') UPDATE LANGUAGES SET VIETNAM=N'Chỉ còn một thông số giám sát của lần giám sát này, Bạn có muốn xóa luôn lần giám sát không!', ENGLISH=N'',CHINESE=N'', VIETNAM_OR=N'Chỉ còn một thông số giám sát của lần giám sát này, Bạn có muốn xóa luôn lần giám sát không!', ENGLISH_OR=N'' , CHINESE_OR=N'' WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD=N'msgConDongCuoiCoMuonXoaLuonLanGiamSat' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGiamsattinhtrang',N'msgConDongCuoiCoMuonXoaLuonLanGiamSat',N'Chỉ còn một thông số giám sát của lần giám sát này, Bạn có muốn xóa luôn lần giám sát không!',N'',N'',N'Chỉ còn một thông số giám sát của lần giám sát này, Bạn có muốn xóa luôn lần giám sát không!',N'',N'','ECOMAIN')

