IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'grouPhieuNhapXac') UPDATE LANGUAGES SET VIETNAM=N'Phiếu nhập thanh lý', ENGLISH=N'Phiếu nhập thanh lý',CHINESE=N'Phiếu nhập thanh lý', VIETNAM_OR=N'Phiếu nhập thanh lý', ENGLISH_OR=N'Phiếu nhập thanh lý' , CHINESE_OR=N'Phiếu nhập thanh lý' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'grouPhieuNhapXac' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'grouPhieuNhapXac',N'Phiếu nhập thanh lý',N'Phiếu nhập thanh lý',N'Phiếu nhập thanh lý',N'Phiếu nhập thanh lý',N'Phiếu nhập thanh lý',N'Phiếu nhập thanh lý','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'btnLook') UPDATE LANGUAGES SET VIETNAM=N'Khóa phiếu', ENGLISH=N'Khóa phiếu',CHINESE=N'Khóa phiếu', VIETNAM_OR=N'Khóa phiếu', ENGLISH_OR=N'Khóa phiếu' , CHINESE_OR=N'Khóa phiếu' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'btnLook' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'btnLook',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'grouChiTietVatTu') UPDATE LANGUAGES SET VIETNAM=N'Chi tiết vật tư', ENGLISH=N'Chi tiết vật tư',CHINESE=N'Chi tiết vật tư', VIETNAM_OR=N'Chi tiết vật tư', ENGLISH_OR=N'Chi tiết vật tư' , CHINESE_OR=N'Chi tiết vật tư' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'grouChiTietVatTu' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'grouChiTietVatTu',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'grouVitrivattu') UPDATE LANGUAGES SET VIETNAM=N'Vị trí vật tư', ENGLISH=N'Vị trí vật tư',CHINESE=N'Vị trí vật tư', VIETNAM_OR=N'Vị trí vật tư', ENGLISH_OR=N'Vị trí vật tư' , CHINESE_OR=N'Vị trí vật tư' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'grouVitrivattu' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'grouVitrivattu',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'grouThongtin') UPDATE LANGUAGES SET VIETNAM=N'Thông tin phiếu nhập', ENGLISH=N'Thông tin phiếu nhập',CHINESE=N'Thông tin phiếu nhập', VIETNAM_OR=N'Thông tin phiếu nhập', ENGLISH_OR=N'Thông tin phiếu nhập' , CHINESE_OR=N'Thông tin phiếu nhập' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'grouThongtin' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'grouThongtin',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'grouViTriVT') UPDATE LANGUAGES SET VIETNAM=N'Vị trí vật tư', ENGLISH=N'Vị trí vật tư',CHINESE=N'Vị trí vật tư', VIETNAM_OR=N'Vị trí vật tư', ENGLISH_OR=N'Vị trí vật tư' , CHINESE_OR=N'Vị trí vật tư' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'grouViTriVT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'grouViTriVT',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'grouThongTinPhieuNhap') UPDATE LANGUAGES SET VIETNAM=N'Thông tin phiếu nhập', ENGLISH=N'Thông tin phiếu nhập',CHINESE=N'Thông tin phiếu nhập', VIETNAM_OR=N'Thông tin phiếu nhập', ENGLISH_OR=N'Thông tin phiếu nhập' , CHINESE_OR=N'Thông tin phiếu nhập' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'grouThongTinPhieuNhap' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'grouThongTinPhieuNhap',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập',N'Thông tin phiếu nhập','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'grouPhieuXuatXac') UPDATE LANGUAGES SET VIETNAM=N'Phiếu xuất thanh lý', ENGLISH=N'Phiếu xuất thanh lý',CHINESE=N'Phiếu xuất thanh lý', VIETNAM_OR=N'Phiếu xuất thanh lý', ENGLISH_OR=N'Phiếu xuất thanh lý' , CHINESE_OR=N'Phiếu xuất thanh lý' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'grouPhieuXuatXac' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'grouPhieuXuatXac',N'Phiếu xuất thanh lý',N'Phiếu xuất thanh lý',N'Phiếu xuất thanh lý',N'Phiếu xuất thanh lý',N'Phiếu xuất thanh lý',N'Phiếu xuất thanh lý','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'grouChiTietVatTu') UPDATE LANGUAGES SET VIETNAM=N'Chi tiết vật tư', ENGLISH=N'Chi tiết vật tư',CHINESE=N'Chi tiết vật tư', VIETNAM_OR=N'Chi tiết vật tư', ENGLISH_OR=N'Chi tiết vật tư' , CHINESE_OR=N'Chi tiết vật tư' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'grouChiTietVatTu' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'grouChiTietVatTu',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư',N'Chi tiết vật tư','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'grouViTriVT') UPDATE LANGUAGES SET VIETNAM=N'Vị trí vật tư', ENGLISH=N'Vị trí vật tư',CHINESE=N'Vị trí vật tư', VIETNAM_OR=N'Vị trí vật tư', ENGLISH_OR=N'Vị trí vật tư' , CHINESE_OR=N'Vị trí vật tư' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'grouViTriVT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'grouViTriVT',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư',N'Vị trí vật tư','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'grouThongTinPhieuXuat') UPDATE LANGUAGES SET VIETNAM=N'Thông tin phiếu xuất', ENGLISH=N'Thông tin phiếu xuất',CHINESE=N'Thông tin phiếu xuất', VIETNAM_OR=N'Thông tin phiếu xuất', ENGLISH_OR=N'Thông tin phiếu xuất' , CHINESE_OR=N'Thông tin phiếu xuất' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'grouThongTinPhieuXuat' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'grouThongTinPhieuXuat',N'Thông tin phiếu xuất',N'Thông tin phiếu xuất',N'Thông tin phiếu xuất',N'Thông tin phiếu xuất',N'Thông tin phiếu xuất',N'Thông tin phiếu xuất','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'btnLook') UPDATE LANGUAGES SET VIETNAM=N'Khóa phiếu', ENGLISH=N'Khóa phiếu',CHINESE=N'Khóa phiếu', VIETNAM_OR=N'Khóa phiếu', ENGLISH_OR=N'Khóa phiếu' , CHINESE_OR=N'Khóa phiếu' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'btnLook' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'btnLook',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu',N'Khóa phiếu','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'btn_TuDongCN') UPDATE LANGUAGES SET VIETNAM=N'Cập nhật tự động', ENGLISH=N'Cập nhật tự động',CHINESE=N'Cập nhật tự động', VIETNAM_OR=N'Cập nhật tự động', ENGLISH_OR=N'Cập nhật tự động' , CHINESE_OR=N'Cập nhật tự động' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'btn_TuDongCN' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'btn_TuDongCN',N'Cập nhật tự động',N'Cập nhật tự động',N'Cập nhật tự động',N'Cập nhật tự động',N'Cập nhật tự động',N'Cập nhật tự động','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'btnUnLook') UPDATE LANGUAGES SET VIETNAM=N'Unlock', ENGLISH=N'Unlock',CHINESE=N'Unlock', VIETNAM_OR=N'Unlock', ENGLISH_OR=N'Unlock' , CHINESE_OR=N'Unlock' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'btnUnLook' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'btnUnLook',N'Unlock',N'Unlock',N'Unlock',N'Unlock',N'Unlock',N'Unlock','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreceive' AND KEYWORD =N'frmGoodreceive') UPDATE LANGUAGES SET VIETNAM=N'Phiếu nhập thanh lý VTPT', ENGLISH=N'Phiếu nhập thanh lý VTPT',CHINESE=N'Phiếu nhập thanh lý VTPT', VIETNAM_OR=N'Phiếu nhập thanh lý VTPT', ENGLISH_OR=N'Phiếu nhập thanh lý VTPT' , CHINESE_OR=N'Phiếu nhập thanh lý VTPT' WHERE FORM=N'frmGoodreceive' AND KEYWORD=N'frmGoodreceive' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreceive',N'frmGoodreceive',N'Phiếu nhập thanh lý VTPT',N'Phiếu nhập thanh lý VTPT',N'Phiếu nhập thanh lý VTPT',N'Phiếu nhập thanh lý VTPT',N'Phiếu nhập thanh lý VTPT',N'Phiếu nhập thanh lý VTPT','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGoodreturn' AND KEYWORD =N'frmGoodreturn') UPDATE LANGUAGES SET VIETNAM=N'Phiếu xuất thanh lý VTPT', ENGLISH=N'Phiếu xuất thanh lý VTPT',CHINESE=N'Phiếu xuất thanh lý VTPT', VIETNAM_OR=N'Phiếu xuất thanh lý VTPT', ENGLISH_OR=N'Phiếu xuất thanh lý VTPT' , CHINESE_OR=N'Phiếu xuất thanh lý VTPT' WHERE FORM=N'frmGoodreturn' AND KEYWORD=N'frmGoodreturn' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGoodreturn',N'frmGoodreturn',N'Phiếu xuất thanh lý VTPT',N'Phiếu xuất thanh lý VTPT',N'Phiếu xuất thanh lý VTPT',N'Phiếu xuất thanh lý VTPT',N'Phiếu xuất thanh lý VTPT',N'Phiếu xuất thanh lý VTPT','ECOMAIN')

 UPDATE
 dbo.MENU
 SET	MENU_TEXT = N'6.16. Nhập thanh lý VTPT'
 WHERE MENU_ID ='mnuPhieuNhapXac'

UPDATE
 dbo.MENU
 SET	MENU_TEXT = N'6.17. Xuất thanh lý VTPT'
 WHERE MENU_ID ='mnuPhieuXuatXac'







