
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'FrmChonTaiLieuChoEOR' AND KEYWORD =N'grpDanhsachtailieunsd') UPDATE LANGUAGES SET VIETNAM=N'Danh sách tài liệu yêu cầu bảo trì', ENGLISH=N'List of documents of maintenance requests',CHINESE=N'List of documents of maintenance requests', VIETNAM_OR=N'Danh sách tài liệu yêu cầu bảo trì', ENGLISH_OR=N'List of documents of maintenance requests' , CHINESE_OR=N'List of documents of maintenance requests' WHERE FORM=N'FrmChonTaiLieuChoEOR' AND KEYWORD=N'grpDanhsachtailieunsd' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'FrmChonTaiLieuChoEOR',N'grpDanhsachtailieunsd',N'Danh sách tài liệu yêu cầu bảo trì',N'List of documents of maintenance requests',N'List of documents of maintenance requests',N'Danh sách tài liệu yêu cầu bảo trì',N'List of documents of maintenance requests',N'List of documents of maintenance requests','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmKehoachtongthe' AND KEYWORD =N'grpYEU_CAU_NSD') UPDATE LANGUAGES SET VIETNAM=N'Danh sách yêu cầu bảo trì', ENGLISH=N'List of users requests',CHINESE=N'List of users requests', VIETNAM_OR=N'Danh sách yêu cầu bảo trì', ENGLISH_OR=N'List of users requests' , CHINESE_OR=N'List of users requests' WHERE FORM=N'frmKehoachtongthe' AND KEYWORD=N'grpYEU_CAU_NSD' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmKehoachtongthe',N'grpYEU_CAU_NSD',N'Danh sách yêu cầu bảo trì',N'List of users requests',N'List of users requests',N'Danh sách yêu cầu bảo trì',N'List of users requests',N'List of users requests','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmKehoachtongthe' AND KEYWORD =N'TabYeucaunguoisudung') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'Maintenance request',CHINESE=N'Maintenance request', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'Maintenance request' , CHINESE_OR=N'Maintenance request' WHERE FORM=N'frmKehoachtongthe' AND KEYWORD=N'TabYeucaunguoisudung' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmKehoachtongthe',N'TabYeucaunguoisudung',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD =N'grpYEU_CAU_NSD') UPDATE LANGUAGES SET VIETNAM=N'Danh sách yêu cầu bảo trì', ENGLISH=N'List of naintenance requests',CHINESE=N'List of naintenance requests', VIETNAM_OR=N'Danh sách yêu cầu bảo trì', ENGLISH_OR=N'List of naintenance requests' , CHINESE_OR=N'List of naintenance requests' WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD=N'grpYEU_CAU_NSD' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmKehoachtongthe_odd',N'grpYEU_CAU_NSD',N'Danh sách yêu cầu bảo trì',N'List of naintenance requests',N'List of naintenance requests',N'Danh sách yêu cầu bảo trì',N'List of naintenance requests',N'List of naintenance requests','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD =N'TabYeucaunguoisudung') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'Maintenance request',CHINESE=N'Maintenance request', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'Maintenance request' , CHINESE_OR=N'Maintenance request' WHERE FORM=N'frmKehoachtongthe_odd' AND KEYWORD=N'TabYeucaunguoisudung' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmKehoachtongthe_odd',N'TabYeucaunguoisudung',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmMain' AND KEYWORD =N'mnuYeucauNSD') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'Maintenance request',CHINESE=N'Maintenance request', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'Maintenance request' , CHINESE_OR=N'Maintenance request' WHERE FORM=N'frmMain' AND KEYWORD=N'mnuYeucauNSD' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmMain',N'mnuYeucauNSD',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeucaucuaNSD' AND KEYWORD =N'frmYeucaucuaNSD') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'Maintenance request',CHINESE=N'Maintenance request', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'Maintenance request' , CHINESE_OR=N'Maintenance request' WHERE FORM=N'frmYeucaucuaNSD' AND KEYWORD=N'frmYeucaucuaNSD' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeucaucuaNSD',N'frmYeucaucuaNSD',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request',N'Yêu cầu bảo trì',N'Maintenance request',N'Maintenance request','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeucaucuaNSD' AND KEYWORD =N'lblTieude') UPDATE LANGUAGES SET VIETNAM=N'YÊU CẦU BẢO TRÌ', ENGLISH=N'USER REQUEST',CHINESE=N'USER REQUEST', VIETNAM_OR=N'YÊU CẦU BẢO TRÌ', ENGLISH_OR=N'USER REQUEST' , CHINESE_OR=N'USER REQUEST' WHERE FORM=N'frmYeucaucuaNSD' AND KEYWORD=N'lblTieude' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeucaucuaNSD',N'lblTieude',N'YÊU CẦU BẢO TRÌ',N'USER REQUEST',N'USER REQUEST',N'YÊU CẦU BẢO TRÌ',N'USER REQUEST',N'USER REQUEST','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeucaucuaNSD' AND KEYWORD =N'TabYeucaucuaNSD') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'User request',CHINESE=N'User request', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'User request' , CHINESE_OR=N'User request' WHERE FORM=N'frmYeucaucuaNSD' AND KEYWORD=N'TabYeucaucuaNSD' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeucaucuaNSD',N'TabYeucaucuaNSD',N'Yêu cầu bảo trì',N'User request',N'User request',N'Yêu cầu bảo trì',N'User request',N'User request','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeucaucuaNSD_Duyet' AND KEYWORD =N'lblTieude') UPDATE LANGUAGES SET VIETNAM=N'XÁC NHẬN YÊU CẦU BẢO TRÌ', ENGLISH=N'CHECK USER REQUEST',CHINESE=N'CHECK USER REQUEST', VIETNAM_OR=N'XÁC NHẬN YÊU CẦU BẢO TRÌ', ENGLISH_OR=N'CHECK USER REQUEST' , CHINESE_OR=N'CHECK USER REQUEST' WHERE FORM=N'frmYeucaucuaNSD_Duyet' AND KEYWORD=N'lblTieude' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeucaucuaNSD_Duyet',N'lblTieude',N'XÁC NHẬN YÊU CẦU BẢO TRÌ',N'CHECK USER REQUEST',N'CHECK USER REQUEST',N'XÁC NHẬN YÊU CẦU BẢO TRÌ',N'CHECK USER REQUEST',N'CHECK USER REQUEST','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeucaucuaNSD_Duyet' AND KEYWORD =N'TabYeucaucuaNSD') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'Request of Users',CHINESE=N'Request of Users', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'Request of Users' , CHINESE_OR=N'Request of Users' WHERE FORM=N'frmYeucaucuaNSD_Duyet' AND KEYWORD=N'TabYeucaucuaNSD' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeucaucuaNSD_Duyet',N'TabYeucaucuaNSD',N'Yêu cầu bảo trì',N'Request of Users',N'Request of Users',N'Yêu cầu bảo trì',N'Request of Users',N'Request of Users','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD =N'TIEU_DE_YC') UPDATE LANGUAGES SET VIETNAM=N'YÊU CẦU BẢO TRÌ', ENGLISH=N'MAINTENANCE REQUEST',CHINESE=N'MAINTENANCE REQUEST', VIETNAM_OR=N'YÊU CẦU BẢO TRÌ', ENGLISH_OR=N'MAINTENANCE REQUEST' , CHINESE_OR=N'MAINTENANCE REQUEST' WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD=N'TIEU_DE_YC' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeuCauCuaNSD',N'TIEU_DE_YC',N'YÊU CẦU BẢO TRÌ',N'MAINTENANCE REQUEST',N'MAINTENANCE REQUEST',N'YÊU CẦU BẢO TRÌ',N'MAINTENANCE REQUEST',N'MAINTENANCE REQUEST','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'UserRequestWeb' AND KEYWORD =N'tabRequest') UPDATE LANGUAGES SET VIETNAM=N'Yêu cầu bảo trì', ENGLISH=N'Request request',CHINESE=N'Request request', VIETNAM_OR=N'Yêu cầu bảo trì', ENGLISH_OR=N'Request request' , CHINESE_OR=N'Request request' WHERE FORM=N'UserRequestWeb' AND KEYWORD=N'tabRequest' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'UserRequestWeb',N'tabRequest',N'Yêu cầu bảo trì',N'Request request',N'Request request',N'Yêu cầu bảo trì',N'Request request',N'Request request','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'FrmChonTaiLieu' AND KEYWORD =N'grpDanhsachtailieunsd') UPDATE LANGUAGES SET VIETNAM=N'Danh sách tài liệu yêu cầu bảo trì', ENGLISH=N'List of documents of request requests',CHINESE=N'List of documents of request requests', VIETNAM_OR=N'Danh sách tài liệu yêu cầu bảo trì', ENGLISH_OR=N'List of documents of request requests' , CHINESE_OR=N'List of documents of request requests' WHERE FORM=N'FrmChonTaiLieu' AND KEYWORD=N'grpDanhsachtailieunsd' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'FrmChonTaiLieu',N'grpDanhsachtailieunsd',N'Danh sách tài liệu yêu cầu bảo trì',N'List of documents of request requests',N'List of documents of request requests',N'Danh sách tài liệu yêu cầu bảo trì',N'List of documents of request requests',N'List of documents of request requests','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'FrmThongtinthietbi' AND KEYWORD =N'MsgQuyenXoa45') UPDATE LANGUAGES SET VIETNAM=N'Dữ liệu đang được sử dụng trong yêu cầu bảo trì! Bạn không thể xoá!', ENGLISH=N'This data cannot be deleted because it is being used in maintenance Request!',CHINESE=N'This data cannot be deleted because it is being used in maintenance Request!', VIETNAM_OR=N'Dữ liệu đang được sử dụng trong yêu cầu bảo trì! Bạn không thể xoá!', ENGLISH_OR=N'This data cannot be deleted because it is being used in maintenance Request!' , CHINESE_OR=N'This data cannot be deleted because it is being used in maintenance Request!' WHERE FORM=N'FrmThongtinthietbi' AND KEYWORD=N'MsgQuyenXoa45' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'FrmThongtinthietbi',N'MsgQuyenXoa45',N'Dữ liệu đang được sử dụng trong yêu cầu bảo trì! Bạn không thể xoá!',N'This data cannot be deleted because it is being used in maintenance Request!',N'This data cannot be deleted because it is being used in maintenance Request!',N'Dữ liệu đang được sử dụng trong yêu cầu bảo trì! Bạn không thể xoá!',N'This data cannot be deleted because it is being used in maintenance Request!',N'This data cannot be deleted because it is being used in maintenance Request!','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDuyetSanXuat' AND KEYWORD =N'frmDuyetSanXuat') UPDATE LANGUAGES SET VIETNAM=N'Duyệt yêu cầu bảo trì', ENGLISH=N'Work request approval',CHINESE=N'Work request approval', VIETNAM_OR=N'Duyệt yêu cầu bảo trì', ENGLISH_OR=N'Work request approval' , CHINESE_OR=N'Work request approval' WHERE FORM=N'frmDuyetSanXuat' AND KEYWORD=N'frmDuyetSanXuat' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDuyetSanXuat',N'frmDuyetSanXuat',N'Duyệt yêu cầu bảo trì',N'Work request approval',N'Work request approval',N'Duyệt yêu cầu bảo trì',N'Work request approval',N'Work request approval','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauBT' AND KEYWORD =N'frmYeuCauBT') UPDATE LANGUAGES SET VIETNAM=N'Tiếp nhận yêu cầu bảo trì', ENGLISH=N'Work Request Receipt',CHINESE=N'Work Request Receipt', VIETNAM_OR=N'Tiếp nhận yêu cầu bảo trì', ENGLISH_OR=N'Work Request Receipt' , CHINESE_OR=N'Work Request Receipt' WHERE FORM=N'frmYeuCauBT' AND KEYWORD=N'frmYeuCauBT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeuCauBT',N'frmYeuCauBT',N'Tiếp nhận yêu cầu bảo trì',N'Work Request Receipt',N'Work Request Receipt',N'Tiếp nhận yêu cầu bảo trì',N'Work Request Receipt',N'Work Request Receipt','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDuyetSanXuat' AND KEYWORD =N'lblTieude') UPDATE LANGUAGES SET VIETNAM=N'DUYỆT YÊU CẦU BẢO TRÌ', ENGLISH=N'WORK REQUET APPROVAL',CHINESE=N'WORK REQUET APPROVAL', VIETNAM_OR=N'DUYỆT YÊU CẦU BẢO TRÌ', ENGLISH_OR=N'WORK REQUET APPROVAL' , CHINESE_OR=N'WORK REQUET APPROVAL' WHERE FORM=N'frmDuyetSanXuat' AND KEYWORD=N'lblTieude' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDuyetSanXuat',N'lblTieude',N'DUYỆT YÊU CẦU BẢO TRÌ',N'WORK REQUET APPROVAL',N'WORK REQUET APPROVAL',N'DUYỆT YÊU CẦU BẢO TRÌ',N'WORK REQUET APPROVAL',N'WORK REQUET APPROVAL','ECOMAIN')
--sửa trong menu
UPDATE dbo.MENU 
SET MENU_TEXT = REPLACE(MENU_TEXT,N'yêu cầu người sử dụng',N'yêu cầu bảo trì'),
MENU_ENGLISH = REPLACE(MENU_ENGLISH,N'Maintenance',N'User')
WHERE MENU_TEXT LIKE N'%Yêu cầu người sử dụng%'
--UPDATE dbo.WebMenu SET Name = N'Yêu cầu bảo trì' WHERE Name =N'Yêu cầu sử dụng'
--UPDATE dbo.WebMenu SET Name = N'Yêu cầu bảo trì' WHERE Name =N'Yêu cầu của sử dụng'


