IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD =N'NGAY_XAY_RA') UPDATE LANGUAGES SET VIETNAM=N'Ngày hỏng', ENGLISH=N'Failure date',CHINESE=N'Failure date', VIETNAM_OR=N'Ngày hỏng', ENGLISH_OR=N'Failure date' , CHINESE_OR=N'Failure date' WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD=N'NGAY_XAY_RA' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeuCauCuaNSD',N'NGAY_XAY_RA',N'Ngày hỏng',N'Failure date',N'Failure date',N'Ngày hỏng',N'Failure date',N'Failure date','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD =N'GIO_XAY_RA') UPDATE LANGUAGES SET VIETNAM=N'Giờ hỏng', ENGLISH=N'Failure time',CHINESE=N'Failure time', VIETNAM_OR=N'Giờ hỏng', ENGLISH_OR=N'Failure time' , CHINESE_OR=N'Failure time' WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD=N'GIO_XAY_RA' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeuCauCuaNSD',N'GIO_XAY_RA',N'Giờ hỏng',N'Failure time',N'Failure time',N'Giờ hỏng',N'Failure time',N'Failure time','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmTaoKHTT' AND KEYWORD =N'frmTaoKHTT') UPDATE LANGUAGES SET VIETNAM=N'Kế hoạch tổng thể', ENGLISH=N'Master Plan',CHINESE=N'Master Plan', VIETNAM_OR=N'Kế hoạch tổng thể', ENGLISH_OR=N'Master Plan' , CHINESE_OR=N'Master Plan' WHERE FORM=N'frmTaoKHTT' AND KEYWORD=N'frmTaoKHTT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmTaoKHTT',N'frmTaoKHTT',N'Kế hoạch tổng thể',N'Master Plan',N'Master Plan',N'Kế hoạch tổng thể',N'Master Plan',N'Master Plan','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmTaoKHTT' AND KEYWORD =N'lblTHangMuc') UPDATE LANGUAGES SET VIETNAM=N'Hạng mục', ENGLISH=N'Article',CHINESE=N'Article', VIETNAM_OR=N'Hạng mục', ENGLISH_OR=N'Article' , CHINESE_OR=N'Article' WHERE FORM=N'frmTaoKHTT' AND KEYWORD=N'lblTHangMuc' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmTaoKHTT',N'lblTHangMuc',N'Hạng mục',N'Article',N'Article',N'Hạng mục',N'Article',N'Article','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmTaoKHTT' AND KEYWORD =N'lblLDSChua') UPDATE LANGUAGES SET VIETNAM=N'Lý do sữa chữa', ENGLISH=N'Repair reason',CHINESE=N'Repair reason', VIETNAM_OR=N'Lý do sữa chữa', ENGLISH_OR=N'Repair reason' , CHINESE_OR=N'Repair reason' WHERE FORM=N'frmTaoKHTT' AND KEYWORD=N'lblLDSChua' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmTaoKHTT',N'lblLDSChua',N'Lý do sữa chữa',N'Repair reason',N'Repair reason',N'Lý do sữa chữa',N'Repair reason',N'Repair reason','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmTaoKHTT' AND KEYWORD =N'lblMUTien') UPDATE LANGUAGES SET VIETNAM=N'Mức ưu tiên', ENGLISH=N'Priority',CHINESE=N'Priority', VIETNAM_OR=N'Mức ưu tiên', ENGLISH_OR=N'Priority' , CHINESE_OR=N'Priority' WHERE FORM=N'frmTaoKHTT' AND KEYWORD=N'lblMUTien' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmTaoKHTT',N'lblMUTien',N'Mức ưu tiên',N'Priority',N'Priority',N'Mức ưu tiên',N'Priority',N'Priority','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmLapphieubaotri_CS' AND KEYWORD =N'lblGiohong') UPDATE LANGUAGES SET VIETNAM=N'Ngày giờ hỏng', ENGLISH=N'Failure Datetime',CHINESE=N'Failure Datetime', VIETNAM_OR=N'Ngày giờ hỏng', ENGLISH_OR=N'Failure Datetime' , CHINESE_OR=N'Failure Datetime' WHERE FORM=N'frmLapphieubaotri_CS' AND KEYWORD=N'lblGiohong' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmLapphieubaotri_CS',N'lblGiohong',N'Ngày giờ hỏng',N'Failure Datetime',N'Failure Datetime',N'Ngày giờ hỏng',N'Failure Datetime',N'Failure Datetime','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmBCYeuCauNSD' AND KEYWORD =N'GIO_YEU_CAU') UPDATE LANGUAGES SET VIETNAM=N'Giờ yêu cầu', ENGLISH=N'Request time',CHINESE=N'Request time', VIETNAM_OR=N'Giờ yêu cầu', ENGLISH_OR=N'Request time' , CHINESE_OR=N'Request time' WHERE FORM=N'frmBCYeuCauNSD' AND KEYWORD=N'GIO_YEU_CAU' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmBCYeuCauNSD',N'GIO_YEU_CAU',N'Giờ yêu cầu',N'Request time',N'Request time',N'Giờ yêu cầu',N'Request time',N'Request time','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD =N'TMP4') UPDATE LANGUAGES SET VIETNAM=N'Ngày giờ hỏng', ENGLISH=N'Failure Datetime',CHINESE=N'Failure Datetime', VIETNAM_OR=N'Ngày giờ hỏng', ENGLISH_OR=N'Failure Datetime' , CHINESE_OR=N'Failure Datetime' WHERE FORM=N'frmYeuCauCuaNSD' AND KEYWORD=N'TMP4' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmYeuCauCuaNSD',N'TMP4',N'Ngày giờ hỏng',N'Failure Datetime',N'Failure Datetime',N'Ngày giờ hỏng',N'Failure Datetime',N'Failure Datetime','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'rptPHIEU_BAO_TRI_NT' AND KEYWORD =N'TMP6') UPDATE LANGUAGES SET VIETNAM=N'Lý do bảo trì', ENGLISH=N'Maintenance cause',CHINESE=N'Maintenance cause', VIETNAM_OR=N'Lý do bảo trì', ENGLISH_OR=N'Maintenance cause' , CHINESE_OR=N'Maintenance cause' WHERE FORM=N'rptPHIEU_BAO_TRI_NT' AND KEYWORD=N'TMP6' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'rptPHIEU_BAO_TRI_NT',N'TMP6',N'Lý do bảo trì',N'Maintenance cause',N'Maintenance cause',N'Lý do bảo trì',N'Maintenance cause',N'Maintenance cause','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'UserRequestWeb' AND KEYWORD =N'DateCompleted') UPDATE LANGUAGES SET VIETNAM=N'Ngày YC HT', ENGLISH=N'Complete before',CHINESE=N'Complete before', VIETNAM_OR=N'Ngày YC HT', ENGLISH_OR=N'Complete before' , CHINESE_OR=N'Complete before' WHERE FORM=N'UserRequestWeb' AND KEYWORD=N'DateCompleted' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'UserRequestWeb',N'DateCompleted',N'Ngày YC HT',N'Complete before',N'Complete before',N'Ngày YC HT',N'Complete before',N'Complete before','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'UserRequestWeb' AND KEYWORD =N'NGAY_XAY_RA') UPDATE LANGUAGES SET VIETNAM=N'Ngày hỏng', ENGLISH=N'Failure date',CHINESE=N'Failure date', VIETNAM_OR=N'Ngày hỏng', ENGLISH_OR=N'Failure date' , CHINESE_OR=N'Failure date' WHERE FORM=N'UserRequestWeb' AND KEYWORD=N'NGAY_XAY_RA' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'UserRequestWeb',N'NGAY_XAY_RA',N'Ngày hỏng',N'Failure date',N'Failure date',N'Ngày hỏng',N'Failure date',N'Failure date','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'UserRequestWeb' AND KEYWORD =N'HourOccurred') UPDATE LANGUAGES SET VIETNAM=N'Giờ hỏng', ENGLISH=N'Failure time',CHINESE=N'Failure time', VIETNAM_OR=N'Giờ hỏng', ENGLISH_OR=N'Failure time' , CHINESE_OR=N'Failure time' WHERE FORM=N'UserRequestWeb' AND KEYWORD=N'HourOccurred' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'UserRequestWeb',N'HourOccurred',N'Giờ hỏng',N'Failure time',N'Failure time',N'Giờ hỏng',N'Failure time',N'Failure time','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'UserRequestWeb' AND KEYWORD =N'DateOccurred') UPDATE LANGUAGES SET VIETNAM=N'Ngày hỏng', ENGLISH=N'Failure date',CHINESE=N'Failure date', VIETNAM_OR=N'Ngày hỏng', ENGLISH_OR=N'Failure date' , CHINESE_OR=N'Failure date' WHERE FORM=N'UserRequestWeb' AND KEYWORD=N'DateOccurred' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'UserRequestWeb',N'DateOccurred',N'Ngày hỏng',N'Failure date',N'Failure date',N'Ngày hỏng',N'Failure date',N'Failure date','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'UserRequestWeb' AND KEYWORD =N'GIO_XAY_RA') UPDATE LANGUAGES SET VIETNAM=N'Giờ hỏng', ENGLISH=N'Failure time',CHINESE=N'Failure time', VIETNAM_OR=N'Giờ hỏng', ENGLISH_OR=N'Failure time' , CHINESE_OR=N'Failure time' WHERE FORM=N'UserRequestWeb' AND KEYWORD=N'GIO_XAY_RA' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'UserRequestWeb',N'GIO_XAY_RA',N'Giờ hỏng',N'Failure time',N'Failure time',N'Giờ hỏng',N'Failure time',N'Failure time','ECOMAIN')

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmDanhmucphutung_CS' AND KEYWORD =N'btnImportPT') UPDATE LANGUAGES SET VIETNAM=N'Import VTPT', ENGLISH=N'Import Item',CHINESE=N'Import Item', VIETNAM_OR=N'Import VTPT', ENGLISH_OR=N'Import Item' , CHINESE_OR=N'Import Item' WHERE FORM=N'frmDanhmucphutung_CS' AND KEYWORD=N'btnImportPT' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmDanhmucphutung_CS',N'btnImportPT',N'Import VTPT',N'Import Item',N'Import Item',N'Import VTPT',N'Import Item',N'Import Item','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonInPhieuBaoTri' AND KEYWORD =N'btnChonFile') UPDATE LANGUAGES SET VIETNAM=N'Chọn file', ENGLISH=N'Select file',CHINESE=N'Select file', VIETNAM_OR=N'Chọn file', ENGLISH_OR=N'Select file' , CHINESE_OR=N'Select file' WHERE FORM=N'frmChonInPhieuBaoTri' AND KEYWORD=N'btnChonFile' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonInPhieuBaoTri',N'btnChonFile',N'Chọn file',N'Select file',N'Select file',N'Chọn file',N'Select file',N'Select file','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonInPhieuBaoTri' AND KEYWORD =N'frmImportPhuTung') UPDATE LANGUAGES SET VIETNAM=N'Form import vật tư phụ tùng', ENGLISH=N'Form import item',CHINESE=N'Form import item', VIETNAM_OR=N'Form import vật tư phụ tùng', ENGLISH_OR=N'Form import item' , CHINESE_OR=N'Form import item' WHERE FORM=N'frmChonInPhieuBaoTri' AND KEYWORD=N'frmImportPhuTung' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonInPhieuBaoTri',N'frmImportPhuTung',N'Form import vật tư phụ tùng',N'Form import item',N'Form import item',N'Form import vật tư phụ tùng',N'Form import item',N'Form import item','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmChonInPhieuBaoTri' AND KEYWORD =N'frmImportPhieuNhap') UPDATE LANGUAGES SET VIETNAM=N'Form import xuất kho cho phiếu bảo trì', ENGLISH=N'Form item issue work order',CHINESE=N'Form item issue work order', VIETNAM_OR=N'Form import xuất kho cho phiếu bảo trì', ENGLISH_OR=N'Form item issue work order' , CHINESE_OR=N'Form item issue work order' WHERE FORM=N'frmChonInPhieuBaoTri' AND KEYWORD=N'frmImportPhieuNhap' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmChonInPhieuBaoTri',N'frmImportPhieuNhap',N'Form import xuất kho cho phiếu bảo trì',N'Form item issue work order',N'Form item issue work order',N'Form import xuất kho cho phiếu bảo trì',N'Form item issue work order',N'Form item issue work order','ECOMAIN')
IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD =N'TG_XU_LY') UPDATE LANGUAGES SET VIETNAM=N'TG KH', ENGLISH=N'Plan time',CHINESE=N'Plan time', VIETNAM_OR=N'TG KH', ENGLISH_OR=N'Plan time' , CHINESE_OR=N'Plan time' WHERE FORM=N'frmGiamsattinhtrang' AND KEYWORD=N'TG_XU_LY' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,CHINESE,VIETNAM_OR,ENGLISH_OR,CHINESE_OR,MS_MODULE)  VALUES(N'frmGiamsattinhtrang',N'TG_XU_LY',N'TG KH',N'Plan time',N'Plan time',N'TG KH',N'Plan time',N'Plan time','ECOMAIN')
--UPDATE dbo.WebMenu SET Name = N'Tổng quan' WHERE Name =N'Tổng quang'
--UPDATE dbo.WebMenu SET Name = N'Yêu cầu của sử dụng' WHERE Name =N'Yêu cầu sử dụng'
UPDATE dbo.LANGUAGES SET VIETNAM = N'Địa điểm' WHERE VIETNAM ='work site'
