
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIEU_DO_BD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DIEU_DO_BD](
	[ID_DD] [bigint] NOT NULL,
	[MA_SO] [bigint] NOT NULL,
	[NGAY_KH] [datetime] NULL,
	[TG_KH] [float] NULL,
	[NGAY_DD] [datetime] NULL,
 CONSTRAINT [PK_DIEU_DO_BD] PRIMARY KEY CLUSTERED 
(
	[ID_DD] ASC,
	[MA_SO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DIEU_DO_BD_DIEU_DO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DIEU_DO_BD]'))
ALTER TABLE [dbo].[DIEU_DO_BD]  WITH CHECK ADD  CONSTRAINT [FK_DIEU_DO_BD_DIEU_DO] FOREIGN KEY([ID_DD])
REFERENCES [dbo].[DIEU_DO] ([ID_DD])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DIEU_DO_BD_DIEU_DO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DIEU_DO_BD]'))
ALTER TABLE [dbo].[DIEU_DO_BD] CHECK CONSTRAINT [FK_DIEU_DO_BD_DIEU_DO]
GO
