
INSERT INTO IC_DON_HANG_NHAP_VAT_TU_CHI_TIET_GOC
([MS_DH_NHAP_PT]
,[MS_PT]
,[MS_VI_TRI]
,[ID]
,[MS_DH_NHAP_PT_GOC]
,[MS_PT_GOC]
,[MS_VI_TRI_GOC]
,[ID_GOC]
,[SL_VT_GOC]
)

SELECT        T4.MS_DH_NHAP_PT, T4.MS_PT, T4.MS_VI_TRI, T4.ID, 
T6.MS_DH_NHAP_PT AS MS_DH_NHAP_PT_GOC, T4.MS_PT,T6.MS_VI_TRI AS MS_VI_TRI_GOC, T6.ID_XUAT AS ID_GOC, 
                         T6.SL_VT AS SL_VT_GOC
FROM            dbo.IC_DON_HANG_NHAP AS T1 INNER JOIN
                         dbo.IC_DON_HANG_XUAT AS T2 ON T1.MS_DHX = T2.MS_DH_XUAT_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU AS T3 ON T1.MS_DH_NHAP_PT = T3.MS_DH_NHAP_PT INNER JOIN
                         dbo.IC_DON_HANG_NHAP_VAT_TU_CHI_TIET AS T4 ON T3.MS_DH_NHAP_PT = T4.MS_DH_NHAP_PT AND T3.MS_PT = T4.MS_PT AND T3.ID = T4.ID INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU AS T5 ON T2.MS_DH_XUAT_PT = T5.MS_DH_XUAT_PT AND T3.MS_PT = T5.MS_PT INNER JOIN
                         dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS T6 ON T5.MS_DH_XUAT_PT = T6.MS_DH_XUAT_PT AND T5.MS_PT = T6.MS_PT
WHERE T1.MS_DANG_NHAP = 6
AND        (T2.MS_PHIEU_BAO_TRI = N'WO-201702000407') 
AND (T4.MS_PT = N'T3860116024')