UPDATE CMMS_VF.dbo.DS_REPORT SET	STT = T2.STT 
FROM CMMS_VF.dbo.DS_REPORT  T1 INNER JOIN CMMS_TRANG.dbo.DS_REPORT T2 ON T1.REPORT_NAME = T2.REPORT_NAME

UPDATE CMMS_VF.DBO.LANGUAGES SET VIETNAM = T2.VIETNAM
FROM CMMS_VF.dbo.LANGUAGES T1 INNER JOIN CMMS_GREENFEED.dbo.LANGUAGES T2 ON T1.FORM = T2.FORM AND T1.MS_MODULE = T2.MS_MODULE AND T1.KEYWORD = T2.KEYWORD
