


SELECT * FROM NHOM_LOAI_MAY WHERE GROUP_ID  = 1
SELECT * FROM IC_PHU_TUNG_LOAI_MAY WHERE MS_PT = 'ACY-008'

SELECT * FROM NHOM_LOAI_PHU_TUNG WHERE GROUP_ID  = 1
SELECT * FROM IC_PHU_TUNG_LOAI_PHU_TUNG WHERE MS_PT = 'ACY-008'

