--SELECT CONVERT(NVARCHAR(20),MS_KH) AS MS_KH , CONVERT(NVARCHAR(20),MS_KH) AS MS_KH_NEW,CONVERT(NVARCHAR(255),TEN_CONG_TY) AS TEN_CONG_TY,TEN_RUT_GON INTO KH_TAM FROM KHACH_HANG  WHERE 1 = 0
--GO
--IF NOT EXISTS(select * from sys.columns 
--            where Name IN (N'MS_KH_NEWKH') and Object_ID = Object_ID(N'KHACH_HANG'))
--BEGIN
--		ALTER TABLE KHACH_HANG ADD  MS_KH_NEWKH NVARCHAR(20)
--END


--IF NOT EXISTS(select * from sys.columns 
--            where Name IN (N'MS_KH_OLDKH') and Object_ID = Object_ID(N'KHACH_HANG'))
--BEGIN
--		ALTER TABLE KHACH_HANG ADD  MS_KH_OLDKH NVARCHAR(20)
--END
--GO


--UPDATE KHACH_HANG SET MS_KH_NEWKH = T2.MS_KH_NEW , MS_KH_OLDKH = T2.MS_KH, TEN_CONG_TY = T2.TEN_CONG_TY, TEN_RUT_GON = T2.TEN_RUT_GON 
--FROM KHACH_HANG T1 INNER JOIN KH_TAM T2 ON T1.MS_KH = T2.MS_KH









--UPDATE KHACH_HANG SET MS_KH = MS_KH_NEW FROM KHACH_HANG T1 INNER JOIN
--(
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T2.MS_KH_UP=  T1.MS_KH



--GO


--UPDATE EOR_SERVICE_MNR SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE THONG_TIN_SP_CHI_TIET SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE Z_Z_phutung SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE EOR_PHU_TUNG SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE W_NGUOI_DAI_DIEN SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE W_MAY SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE SYN_TB_NHAP_KHO_CMMS SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE SYN_TB_NHAP_KHO_INTEGRATION SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE NGUOI_DAI_DIEN SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE DDH_MUA SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE PHIEU_BAO_TRI_SERVICE SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE W_KHACH_HANG SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE rptDANH_GIA_DICH_VU_KH_TMPadministrator SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE EOR_SERVICE_CHUNG SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE MAY SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH
--UPDATE IC_PHU_TUNG SET MS_KH = T2.MS_KH_NEW 
--FROM  IC_PHU_TUNG T1 INNER JOIN (
--	SELECT MS_KH_UP,MS_KH,T1.MS_KH_NEW FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW
--) T2 ON T1.MS_KH = T2.MS_KH





--DELETE T1
--FROM KHACH_HANG T1 INNER JOIN

--(
--	SELECT MS_KH FROM KH_TAM T1 LEFT JOIN
--		(
--			SELECT DISTINCT MS_KH_NEW, (SELECT TOP 1 MS_KH FROM KH_TAM A WHERE A.MS_KH_NEW = B.MS_KH_NEW) AS MS_KH_UP FROM KH_TAM B
--		) T2 ON T1.MS_KH_NEW = T2.MS_KH_NEW 
--		WHERE MS_KH_UP <> MS_KH
--) T2 ON T2.MS_KH=  T1.MS_KH
--WHERE ISNULL(MS_KH_NEWKH,'') <> ''

