DELETE T2 FROM
(
SELECT MAX(T1.ID) ID,T1.REPORT_NAME,T1.TYPE_LIC FROM LIC_REPORT T1 INNER JOIN(
SELECT TYPE_LIC,REPORT_NAME FROM LIC_REPORT 
GROUP BY TYPE_LIC,REPORT_NAME HAVING COUNT(*) > 1) T2 ON T1.TYPE_LIC = T2.TYPE_LIC AND T1.REPORT_NAME = T2.REPORT_NAME
GROUP BY T1.REPORT_NAME,T1.TYPE_LIC 
) T1 INNER JOIN LIC_REPORT T2 ON T1.ID = T2.ID

