--SELECT *,TYPE_LIC,MENU_ID FROM LIC_MENU
--mnuPhanTichNNNM
--mnuVTPTExcel



DECLARE @t TABLE(TYPE_LIC NVARCHAR(2500) ,MENU_ID  NVARCHAR(2500) , ID INT)

INSERT INTO @t
SELECT TYPE_LIC,MENU_ID,count(ID) AS ID FROM LIC_MENU B group by TYPE_LIC,MENU_ID having count(ID) >1

SELECT MIN(A.ID)  AS ID_MIN,A.TYPE_LIC,A.MENU_ID  INTO #ID_MIN 
FROM LIC_MENU A INNER JOIN @t B ON A.TYPE_LIC = B.TYPE_LIC AND A.MENU_ID = B.MENU_ID
GROUP BY A.TYPE_LIC,A.MENU_ID 



DELETE A FROM LIC_MENU A INNER JOIN @t C ON A.TYPE_LIC = C.TYPE_LIC AND A.MENU_ID = C.MENU_ID 
WHERE A.ID NOT IN(
SELECT DISTINCT ID_MIN FROM #ID_MIN B WHERE  A.TYPE_LIC = B.TYPE_LIC AND A.MENU_ID = B.MENU_ID AND A.ID = B.ID_MIN)



