 

 IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spChonPhuTungXuat')
   exec('CREATE PROCEDURE spChonPhuTungXuat AS BEGIN SET NOCOUNT ON; END')
GO


-- exec spChonPhuTungXuat 'WO-201702000773','CHON_VTXadmin'
ALTER procedure spChonPhuTungXuat
	@PBT NVARCHAR(50),
	@BTAM NVARCHAR(250)
AS

DECLARE @sSql NVARCHAR(4000)
CREATE TABLE #CHON_TMP(
	[VAT_TU] [bit] NOT NULL,
	[MS_PT] [nvarchar](25) NOT NULL,
	[SL_KH] [float] NULL,
	[SL_TT] [float] NULL
) ON [PRIMARY]


SET @sSql = 'INSERT INTO #CHON_TMP SELECT * FROM ' + @BTAM
exec (@sSql)

SET @sSql = 'DROP TABLE ' + @BTAM
exec (@sSql)


 SELECT * FROM 
 (SELECT A.VAT_TU,A.MS_PT, (CASE WHEN ((ISNULL(A.SL_KH,0)) - ISNULL(B.SL_VT, 0)) <= 0 THEN 0 ELSE (ISNULL(A.SL_KH,0)) - ISNULL(B.SL_VT, 0) END)  AS SL_KH ,  ISNULL((A.SL_TT),0) AS SL_TT  
 FROM  ( 
	SELECT T1.VAT_TU,T1.MS_PT, SUM(T1.SL_KH) AS SL_KH, SUM(T1.SL_TT) AS SL_TT FROM 
		(
		SELECT        T2.VAT_TU, T4.MS_PT, SUM(ISNULL(T4.SL_KH, 0)) AS SL_KH, SUM(ISNULL(T4.SL_TT, 0)) AS SL_TT
		FROM            dbo.IC_PHU_TUNG AS T1 INNER JOIN
								dbo.LOAI_VT AS T2 ON T1.MS_LOAI_VT = T2.MS_LOAI_VT INNER JOIN
								dbo.PHIEU_BAO_TRI AS T3 INNER JOIN
								dbo.PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG AS T4 ON T3.MS_PHIEU_BAO_TRI = T4.MS_PHIEU_BAO_TRI ON T1.MS_PT = T4.MS_PT INNER JOIN
								dbo.PHIEU_BAO_TRI_CONG_VIEC AS T5 ON T3.MS_PHIEU_BAO_TRI = T5.MS_PHIEU_BAO_TRI AND T4.MS_PHIEU_BAO_TRI = T5.MS_PHIEU_BAO_TRI AND T4.MS_CV = T5.MS_CV AND 
								T4.MS_BO_PHAN = T5.MS_BO_PHAN
		WHERE        (T3.MS_PHIEU_BAO_TRI = @PBT) AND (T5.STT_SERVICE IS NULL)
		GROUP BY T2.VAT_TU, T4.MS_PT
		UNION  
		SELECT        T2.VAT_TU, T4.MS_PT, ISNULL(SUM(T4.SL_KH), 0) AS SL_KH, ISNULL(SUM(T4.SL_TT), 0) AS SL_TT
		FROM            dbo.IC_PHU_TUNG AS T1 INNER JOIN
								 dbo.LOAI_VT AS T2 ON T1.MS_LOAI_VT = T2.MS_LOAI_VT INNER JOIN
								 dbo.PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG AS T4 ON T1.MS_PT = T4.MS_PT
		WHERE        (T4.MS_PHIEU_BAO_TRI = @PBT)
		GROUP BY T2.VAT_TU, T4.MS_PT
		UNION 
		SELECT        VAT_TU, MS_PT, ISNULL(SUM(SL_KH),0) AS SL_KH, ISNULL(SUM(SL_TT),0) AS SL_TT
		FROM            #CHON_TMP
		GROUP BY VAT_TU, MS_PT
		) T1 GROUP BY T1.VAT_TU,T1.MS_PT
) A  
 LEFT JOIN (
						SELECT     T2.MS_PT, ISNULL(SUM(T2.SL_VT), 0) AS SL_VT
						FROM            dbo.IC_DON_HANG_XUAT AS T1 INNER JOIN
												 dbo.IC_DON_HANG_XUAT_VAT_TU_CHI_TIET AS T2 ON T1.MS_DH_XUAT_PT = T2.MS_DH_XUAT_PT 
						WHERE        (T1.MS_PHIEU_BAO_TRI = @PBT)
						GROUP BY T2.MS_PT
   
   ) B ON B.MS_PT = A.MS_PT  
) C WHERE SL_KH > 0



