IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GetPHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG')
   exec('CREATE PROCEDURE GetPHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG AS BEGIN SET NOCOUNT ON; END')
GO



ALTER procedure [dbo].[GetPHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG]
	@MS_PHIEU_BAO_TRI NVARCHAR(20),
	@NNgu INT
AS

SELECT        T1.MS_PT, CASE @NNgu WHEN 0 THEN T2.TEN_PT WHEN 0 THEN T2.TEN_PT_ANH ELSE T2.TEN_PT_HOA END AS TEN_PT, 
	T2.QUY_CACH, T1.SL_KH, T1.SL_TT, T1.GHI_CHU,STT,
	CONVERT(NVARCHAR(2000),T1.MS_PT + CONVERT(NVARCHAR(20),STT)) AS MS_PT_STT
FROM            dbo.PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG AS T1 INNER JOIN
                         dbo.IC_PHU_TUNG AS T2 ON T1.MS_PT = T2.MS_PT
WHERE T1.MS_PHIEU_BAO_TRI = @MS_PHIEU_BAO_TRI 
ORDER BY MS_PT