IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PSDV_NHOM_DV]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[PSDV_NHOM_DV](
		[ID_PSDV_NHOM] [bigint] IDENTITY(1,1) NOT NULL,
		[MS_YEU_CAU] [nvarchar](20) NOT NULL,
		[SER_GROUP_CODE] [nvarchar](10) NOT NULL,
		[MO_TA] [nvarchar](255) NULL,
		[MS_GL] [nvarchar](50) NULL,
		[MS_KH] [varchar](20) NULL,
		[MS_BP_CHIU_PHI] [int] NULL,
		[CHI_PHI] [float] NULL,
	 CONSTRAINT [PK_PSDV_NHOM_DV] PRIMARY KEY CLUSTERED 
	(
		[ID_PSDV_NHOM] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END

