
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOAI_DICH_VU]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[LOAI_DICH_VU](
		[SER_GROUP_CODE] [nvarchar](10) NOT NULL,
		[SER_GROUP_PARENT] [nvarchar](10) NULL,
		[SER_GROUP_NAME] [nvarchar](255) NULL,
	 CONSTRAINT [PK_LOAI_DICH_VU] PRIMARY KEY CLUSTERED 
	(
		[SER_GROUP_CODE] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

