IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetPSDV')
   exec('CREATE PROCEDURE [dbo].[spGetPSDV] AS BEGIN SET NOCOUNT ON; END')
GO

--EXEC spGetPSDV '01/01/2015','01/01/2016', -1

ALTER PROC spGetPSDV
	@TuNgay DATETIME,
	@DenNgay DATETIME
AS
	
	SELECT     T1.SO_YEU_CAU, T1.NGAY_YEU_CAU, T2.HO + T2.TEN AS HO_TEN, T3.TEN_TRANG_THAI, T1.MAIL_YC, T1.NOI_DUNG_YC, 
	CONVERT(NVARCHAR(4000),dbo.GetPBTPSDV(MS_YEU_CAU)) AS PBT,CONVERT(FLOAT,NULL) AS CHI_PHI,
	T1.ID_PSDV, T1.MS_YEU_CAU, T1.MS_CONG_NHAN, T1.MS_TRANG_THAI
	FROM         dbo.PHAT_SINH_DICH_VU AS T1 INNER JOIN
						  dbo.CONG_NHAN AS T2 ON T1.MS_CONG_NHAN = T2.MS_CONG_NHAN INNER JOIN
						  dbo.TRANG_THAI_PSDV AS T3 ON T1.MS_TRANG_THAI = T3.MS_TRANG_THAI
	WHERE NGAY_YEU_CAU BETWEEN @TuNgay AND @DenNgay
	ORDER BY NGAY_YEU_CAU DESC, T1.MS_YEU_CAU 