IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYN_TB_ALLOCATION_VTPT_FOR_PBT]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[SYN_TB_ALLOCATION_VTPT_FOR_PBT](
		[STT] [bigint] IDENTITY(1,1) NOT NULL,
		[MS_DH_XUAT_PT] [nvarchar](50) NULL,
		[MS_KHO] [int] NULL,
		[MS_PHIEU_BT] [nvarchar](50) NULL,
		[MS_MAY] [nvarchar](30) NULL,
		[MS_BP_CHIU_PHI] [int] NULL,
		[MS_PT] [nvarchar](100) NULL,
		[SO_LUONG_PHAN_BO] [float] NULL,
		[DON_GIA] [float] NULL,
		[DA_TAO_PHIEU] [bit] NULL,
		[STT_SYNC] [bigint] NULL,
	 CONSTRAINT [PK_ALLOCATION_VTPT_FOR_PBT] PRIMARY KEY CLUSTERED 
	(
		[STT] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
