IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spNAV_REQUEST_SERVICE')
   exec('CREATE PROCEDURE [dbo].[spNAV_REQUEST_SERVICE] AS BEGIN SET NOCOUNT ON; END')
GO

--	EXEC spNAV_REQUEST_SERVICE 'N'PR-201508000012''
ALTER PROC spNAV_REQUEST_SERVICE
	@MsYC NVARCHAR(25)
AS	

DECLARE @Ngay DATETIME
SET @Ngay = GETDATE()

INSERT INTO NAV_REQUEST_SERVICE (MS_YEU_CAU, SER_GROUP_CODE, GL_ACC, SO_LUONG, MO_TA_SERVICE, MS_CONG_NHAN, NGAY_YEU_CAU, MS_PHIEU_BAO_TRI,INSERT_DATE,[STATUS])
SELECT     T1.MS_YEU_CAU, T2.SER_GROUP_CODE, T2.MS_GL, 1 AS SO_LUONG, T2.MO_TA, T1.MS_CONG_NHAN, T1.NGAY_YEU_CAU, 
CONVERT(NVARCHAR(255),dbo.GetPBTPSDVGroupCode(T1.MS_YEU_CAU,SER_GROUP_CODE)) AS PBT,@Ngay, 'N'
FROM         dbo.PHAT_SINH_DICH_VU AS T1 INNER JOIN
                      dbo.PSDV_NHOM_DV AS T2 ON T1.MS_YEU_CAU = T2.MS_YEU_CAU
WHERE     (T1.MS_YEU_CAU = @MsYC)