
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapMaKho')
   exec('CREATE PROCEDURE [dbo].[spCapNhapMaKho] AS BEGIN SET NOCOUNT ON; END')
GO

-- EXEC spCapNhapMaKho  '1', '0'
ALTER PROC spCapNhapMaKho
	@MaCu int, 
	@MaMoi int 
AS

Declare @TABLE nvarchar (100),@COT nvarchar (100), @sql nvarchar (1000)

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DE_XUAT_MUA_HANG_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DE_XUAT_MUA_HANG]'))
ALTER TABLE [dbo].[DE_XUAT_MUA_HANG] DROP CONSTRAINT [FK_DE_XUAT_MUA_HANG_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DON_DAT_HANG_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DON_DAT_HANG]'))
ALTER TABLE [dbo].[DON_DAT_HANG] DROP CONSTRAINT [FK_DON_DAT_HANG_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_IC_DON_HANG_NHAP_PT_IC_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[IC_DON_HANG_NHAP]'))
ALTER TABLE [dbo].[IC_DON_HANG_NHAP] DROP CONSTRAINT [FK_IC_DON_HANG_NHAP_PT_IC_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_IC_DON_HANG_NHAP_X_PT_IC_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[IC_DON_HANG_NHAP_X]'))
ALTER TABLE [dbo].[IC_DON_HANG_NHAP_X] DROP CONSTRAINT [FK_IC_DON_HANG_NHAP_X_PT_IC_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_IC_PHU_TUNG_KHO_IC_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[IC_PHU_TUNG_KHO]'))
ALTER TABLE [dbo].[IC_PHU_TUNG_KHO] DROP CONSTRAINT [FK_IC_PHU_TUNG_KHO_IC_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_KIEM_KE_PT_IC_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[KIEM_KE]'))
ALTER TABLE [dbo].[KIEM_KE] DROP CONSTRAINT [FK_KIEM_KE_PT_IC_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NHOM_KHO_IC_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[NHOM_KHO]'))
ALTER TABLE [dbo].[NHOM_KHO] DROP CONSTRAINT [FK_NHOM_KHO_IC_KHO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VI_TRI_KHO_IC_KHO]') AND parent_object_id = OBJECT_ID(N'[dbo].[VI_TRI_KHO]'))
ALTER TABLE [dbo].[VI_TRI_KHO] DROP CONSTRAINT [FK_VI_TRI_KHO_IC_KHO]





Set IDENTITY_INSERT IC_KHO ON
	INSERT INTO IC_KHO([MS_KHO],[TEN_KHO],[DIA_CHI],[SO_DO],[ISIT],[MS_CONG_NHAN],[NGAY_LOCK],[GIO_LOCK],[UNAME],
			[SN_CANH_BAO],[KHO_DD],[MS_KHO_CHINH],[MS_DON_VI],[MS_KHO_INT])
	SELECT @MaMoi,[TEN_KHO],[DIA_CHI],[SO_DO],[ISIT],[MS_CONG_NHAN],[NGAY_LOCK],[GIO_LOCK],[UNAME],
			[SN_CANH_BAO],[KHO_DD],[MS_KHO_CHINH],[MS_DON_VI],[MS_KHO_INT]
	FROM IC_KHO WHERE MS_KHO = @MaCu
	
	DELETE IC_KHO WHERE MS_KHO = @MaCu
Set IDENTITY_INSERT IC_KHO OFF
	
	
--Tao bang tam chua du lieu
	SELECT DISTINCT sysobjects.NAME AS NAME_TB, syscolumns.NAME AS NAME_COT, CONVERT(BIT,0) CAP_NHAP  INTO  #BTam 
	FROM sysobjects INNER JOIN syscolumns ON sysobjects.ID = syscolumns.ID 
	WHERE syscolumns.NAME LIKE 'MS_KHO%'  and OBJECTPROPERTY(sysobjects.id, N'IsUserTable') = 1 
	and ((sysobjects.NAME   ) NOT IN ('IC_KHO' ) )  
--Chay vong lap

Declare @iTT int
set @iTT = 1
Declare  CurFor CURSOR FOR
	SELECT NAME_TB,NAME_COT FROM #BTam ORDER BY NAME_TB
Open CurFor
FETCH NEXT FROM CurFor
INTO @TABLE,@COT
While @@Fetch_Status = 0
Begin

BEGIN TRY
	set @sql = CONVERT(nvarchar(10),@iTT) +  '. UPDATE [' +  @TABLE  + '] SET [' + @COT + '] = ' +  CONVERT(NVARCHAR,@MaMoi) + ' WHERE [' + @COT + '] =	' +  CONVERT(NVARCHAR,@MaCu) 
	PRINT (@sql)
	set @sql = 'UPDATE [' +  @TABLE  + '] SET [' + @COT + '] = ' +  CONVERT(NVARCHAR,@MaMoi) + ' WHERE [' + @COT + '] =	' +  CONVERT(NVARCHAR,@MaCu)
	EXEC (@sql)
	UPDATE #BTam SET CAP_NHAP = 1 WHERE NAME_TB = @TABLE AND NAME_COT = @COT
END TRY
BEGIN CATCH
	PRINT (@sql)     
	UPDATE #BTam SET CAP_NHAP = 0 WHERE NAME_TB = @TABLE AND NAME_COT = @COT
END CATCH

	
    FETCH NEXT FROM CurFor
    INTO  @TABLE,@COT
	set @iTT = @iTT +1
End

Close CurFor
Deallocate CurFor




ALTER TABLE [dbo].[DE_XUAT_MUA_HANG]  WITH CHECK ADD  CONSTRAINT [FK_DE_XUAT_MUA_HANG_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])

ALTER TABLE [dbo].[DE_XUAT_MUA_HANG] CHECK CONSTRAINT [FK_DE_XUAT_MUA_HANG_KHO]


ALTER TABLE [dbo].[DON_DAT_HANG]  WITH CHECK ADD  CONSTRAINT [FK_DON_DAT_HANG_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])

ALTER TABLE [dbo].[DON_DAT_HANG] CHECK CONSTRAINT [FK_DON_DAT_HANG_KHO]


ALTER TABLE [dbo].[IC_DON_HANG_NHAP]  WITH NOCHECK ADD  CONSTRAINT [FK_IC_DON_HANG_NHAP_PT_IC_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[IC_DON_HANG_NHAP] CHECK CONSTRAINT [FK_IC_DON_HANG_NHAP_PT_IC_KHO]


ALTER TABLE [dbo].[IC_DON_HANG_NHAP_X]  WITH NOCHECK ADD  CONSTRAINT [FK_IC_DON_HANG_NHAP_X_PT_IC_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[IC_DON_HANG_NHAP_X] CHECK CONSTRAINT [FK_IC_DON_HANG_NHAP_X_PT_IC_KHO]


ALTER TABLE [dbo].[IC_PHU_TUNG_KHO]  WITH CHECK ADD  CONSTRAINT [FK_IC_PHU_TUNG_KHO_IC_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[IC_PHU_TUNG_KHO] CHECK CONSTRAINT [FK_IC_PHU_TUNG_KHO_IC_KHO]


ALTER TABLE [dbo].[KIEM_KE]  WITH NOCHECK ADD  CONSTRAINT [FK_KIEM_KE_PT_IC_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[KIEM_KE] CHECK CONSTRAINT [FK_KIEM_KE_PT_IC_KHO]


ALTER TABLE [dbo].[NHOM_KHO]  WITH NOCHECK ADD  CONSTRAINT [FK_NHOM_KHO_IC_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[NHOM_KHO] CHECK CONSTRAINT [FK_NHOM_KHO_IC_KHO]


ALTER TABLE [dbo].[VI_TRI_KHO]  WITH NOCHECK ADD  CONSTRAINT [FK_VI_TRI_KHO_IC_KHO] FOREIGN KEY([MS_KHO])
REFERENCES [dbo].[IC_KHO] ([MS_KHO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[VI_TRI_KHO] CHECK CONSTRAINT [FK_VI_TRI_KHO_IC_KHO]
