IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCapNhapMsTo')
   exec('CREATE PROCEDURE [dbo].[spCapNhapMsTo] AS BEGIN SET NOCOUNT ON; END')
GO

-- EXEC spCapNhapMsTo  '25', '11'
ALTER PROC spCapNhapMsTo
	@MaCu int, 
	@MaMoi int 
AS

Declare @TABLE nvarchar (100),@COT nvarchar (100), @sql nvarchar (1000)
--Declare @MaCu nvarchar (100), @MaMoi nvarchar (100) 

--set @MaCu = 'BUE-BO-002TEST'
--set @MaMoi = 'BUE-BO-002'
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NHOM_TO_PHONG_BAN_TO_PHONG_BAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[NHOM_TO_PHONG_BAN]'))
ALTER TABLE [dbo].[NHOM_TO_PHONG_BAN] DROP CONSTRAINT [FK_NHOM_TO_PHONG_BAN_TO_PHONG_BAN]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TO_TO_PHONG_BAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[TO]'))
ALTER TABLE [dbo].[TO] DROP CONSTRAINT [FK_TO_TO_PHONG_BAN]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USERS_TO_PHONG_BAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[USERS]'))
ALTER TABLE [dbo].[USERS] DROP CONSTRAINT [FK_USERS_TO_PHONG_BAN]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CONG_NHAN_TO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CONG_NHAN]'))
ALTER TABLE [dbo].[CONG_NHAN] DROP CONSTRAINT [FK_CONG_NHAN_TO]

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_EOR_TO]') AND parent_object_id = OBJECT_ID(N'[dbo].[EOR]'))
ALTER TABLE [dbo].[EOR] DROP CONSTRAINT [FK_EOR_TO]


Set IDENTITY_INSERT TO_PHONG_BAN ON
	INSERT INTO [TO_PHONG_BAN]([MS_TO],[TEN_TO],[MS_DON_VI],[STT_TO],[TO_TRUONG],[MS_TO_INT])
	SELECT @MaMoi,[TEN_TO],[MS_DON_VI],[STT_TO],[TO_TRUONG],[MS_TO_INT] FROM TO_PHONG_BAN WHERE MS_TO = @MaCu
	
	DELETE TO_PHONG_BAN WHERE MS_TO = @MaCu
Set IDENTITY_INSERT TO_PHONG_BAN OFF
	
Set IDENTITY_INSERT [TO] ON
	INSERT INTO [TO]([MS_TO1],[TEN_TO],[MS_TO])
	SELECT @MaMoi,[TEN_TO],[MS_TO] FROM TO_PHONG_BAN WHERE MS_TO = @MaCu

	DELETE [TO] WHERE MS_TO1 = @MaCu
Set IDENTITY_INSERT [TO] OFF
	
		
--Tao bang tam chua du lieu
	SELECT DISTINCT sysobjects.NAME AS NAME_TB, syscolumns.NAME AS NAME_COT, CONVERT(BIT,0) CAP_NHAP  INTO  #BTam 
	FROM sysobjects INNER JOIN syscolumns ON sysobjects.ID = syscolumns.ID 
	WHERE syscolumns.NAME LIKE 'MS_TO%'  and OBJECTPROPERTY(sysobjects.id, N'IsUserTable') = 1 
	and ((sysobjects.NAME   ) NOT IN ('TO_PHONG_BAN','TO' ) )  
--Chay vong lap

Declare @iTT int
set @iTT = 1
Declare  CurFor CURSOR FOR
	SELECT NAME_TB,NAME_COT FROM #BTam ORDER BY NAME_TB
Open CurFor
FETCH NEXT FROM CurFor
INTO @TABLE,@COT
While @@Fetch_Status = 0
Begin

BEGIN TRY
	set @sql = CONVERT(nvarchar(10),@iTT) +  '. UPDATE [' +  @TABLE  + '] SET [' + @COT + '] = ' +  CONVERT(NVARCHAR,@MaMoi) + ' WHERE [' + @COT + '] =	' +  CONVERT(NVARCHAR,@MaCu) 
	PRINT (@sql)
	set @sql = 'UPDATE [' +  @TABLE  + '] SET [' + @COT + '] = ' +  CONVERT(NVARCHAR,@MaMoi) + ' WHERE [' + @COT + '] =	' +  CONVERT(NVARCHAR,@MaCu)
	EXEC (@sql)
	UPDATE #BTam SET CAP_NHAP = 1 WHERE NAME_TB = @TABLE AND NAME_COT = @COT
END TRY
BEGIN CATCH
	PRINT (@sql)     
	UPDATE #BTam SET CAP_NHAP = 0 WHERE NAME_TB = @TABLE AND NAME_COT = @COT
END CATCH

	
    FETCH NEXT FROM CurFor
    INTO  @TABLE,@COT
	set @iTT = @iTT +1
End

Close CurFor
Deallocate CurFor



UPDATE [TO] SET MS_TO = @MaMoi WHERE MS_TO = @MaCu
UPDATE [TO_PHONG_BAN] SET MS_TO_INT = @MaMoi WHERE MS_TO_INT = @MaCu

UPDATE [EOR] SET BAN_TO_LAP = @MaMoi WHERE BAN_TO_LAP = @MaCu


ALTER TABLE [dbo].[NHOM_TO_PHONG_BAN]  WITH NOCHECK ADD  CONSTRAINT [FK_NHOM_TO_PHONG_BAN_TO_PHONG_BAN] FOREIGN KEY([MS_TO])
REFERENCES [dbo].[TO_PHONG_BAN] ([MS_TO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[NHOM_TO_PHONG_BAN] CHECK CONSTRAINT [FK_NHOM_TO_PHONG_BAN_TO_PHONG_BAN]


ALTER TABLE [dbo].[TO]  WITH NOCHECK ADD  CONSTRAINT [FK_TO_TO_PHONG_BAN] FOREIGN KEY([MS_TO])
REFERENCES [dbo].[TO_PHONG_BAN] ([MS_TO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[TO] CHECK CONSTRAINT [FK_TO_TO_PHONG_BAN]


ALTER TABLE [dbo].[USERS]  WITH NOCHECK ADD  CONSTRAINT [FK_USERS_TO_PHONG_BAN] FOREIGN KEY([MS_TO])
REFERENCES [dbo].[TO_PHONG_BAN] ([MS_TO])
ON UPDATE CASCADE

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_TO_PHONG_BAN]


ALTER TABLE [dbo].[CONG_NHAN]  WITH NOCHECK ADD  CONSTRAINT [FK_CONG_NHAN_TO] FOREIGN KEY([MS_TO])
REFERENCES [dbo].[TO] ([MS_TO1])
ON UPDATE CASCADE

ALTER TABLE [dbo].[CONG_NHAN] CHECK CONSTRAINT [FK_CONG_NHAN_TO]


ALTER TABLE [dbo].[EOR]  WITH NOCHECK ADD  CONSTRAINT [FK_EOR_TO] FOREIGN KEY([BAN_TO_LAP])
REFERENCES [dbo].[TO] ([MS_TO1])
ON UPDATE CASCADE

ALTER TABLE [dbo].[EOR] CHECK CONSTRAINT [FK_EOR_TO]

