IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spBCPhanTramTuanThuGSTT')
   exec('CREATE PROCEDURE spBCPhanTramTuanThuGSTT AS BEGIN SET NOCOUNT ON; END')
GO




--exec spBCPhanTramTuanThuGSTT '02/01/2016','02/28/2016','admin','-1'
--SELECT * FROM TEMP_DINH_TINHadministrator

ALTER procedure spBCPhanTramTuanThuGSTT
	@TU_NGAY DATETIME,
	@DEN_NGAY DATETIME,
	@USERNAME VARCHAR (64) = 'ADMIN', 
	@LANGUAGE INT = 0,
	@MS_NHA_XUONG VARCHAR (50) = '-1', 
	@MS_HE_THONG INT = -1,
	@MS_LOAI_MAY VARCHAR(100) = '-1',
	@MS_NHOM_MAY VARCHAR(100)= '-1'

AS
BEGIN
-- delete bang tam

	IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL DROP TABLE #TEMP
	IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL DROP TABLE #NGAYKEGSTT_TEMP
	IF OBJECT_ID('tempdb..#TEMP_FINAL') IS NOT NULL DROP TABLE #TEMP_FINAL
	IF OBJECT_ID('tempdb..#TONGTG_TEMP') IS NOT NULL DROP TABLE #TONGTG_TEMP
	IF OBJECT_ID('tempdb..#Thang_Temp') IS NOT NULL DROP TABLE #Thang_Temp

	
SELECT DISTINCT MS_MAY, MS_LOAI_MAY INTO #MAY_USER
	FROM [dbo].[MGetMayUserNgay](@DEN_NGAY,@USERNAME,@MS_NHA_XUONG,@MS_HE_THONG,-1,@MS_LOAI_MAY,@MS_NHOM_MAY,'-1',@LANGUAGE)

	 
	SELECT  DATEPART(MONTH, DATEADD(MONTH, x.number, @Tu_Ngay))AS THANG,YEAR(DATEADD(MONTH, x.number, @Tu_Ngay)) AS NAM,MS_LOAI_MAY,TEN_LOAI_MAY INTO #Thang_Temp
			FROM    master.dbo.spt_values x,LOAI_MAY
			WHERE   x.type = 'P'  AND x.number <= DATEDIFF(MONTH, @Tu_Ngay, @Den_Ngay)
			AND (MS_LOAI_MAY = @MS_LOAI_MAY OR @MS_LOAI_MAY = '-1') 
	
		SELECT DISTINCT MS_MAY,MS_BO_PHAN,MS_TS_GSTT , NGAY_KE INTO #NGAYKEGSTT_TEMP FROM [dbo].GetNgayKeGiamSatTinhTrang(@Tu_Ngay,@Den_Ngay,@USERNAME,@MS_NHA_XUONG,@MS_HE_THONG,@MS_LOAI_MAY,@MS_NHOM_MAY,'-1',@LANGUAGE,1) A
		
		
	SELECT DISTINCT F.MS_MAY,F.MS_TS_GSTT,F.MS_BO_PHAN,F.NGAY_KT INTO #TEMP FROM 			
	(
		(SELECT T2.MS_MAY,MS_TS_GSTT,MS_BO_PHAN,NGAY_KT FROM GIAM_SAT_TINH_TRANG_TS T2 INNER JOIN 
			GIAM_SAT_TINH_TRANG T1 ON T1.STT  = T2.STT INNER JOIN #MAY_USER T3 ON T2.MS_MAY = T3.MS_MAY
			WHERE NGAY_KT BETWEEN DATEADD(DAY,-3,@TU_NGAY) AND DATEADD(DAY,3,@DEN_NGAY))
		UNION ALL
		(SELECT T2.MS_MAY ,MS_TS_GSTT,MS_BO_PHAN,NGAY_KT FROM GIAM_SAT_TINH_TRANG_TS_DT T2 INNER JOIN 
			GIAM_SAT_TINH_TRANG T1 ON T1.STT  = T2.STT INNER JOIN #MAY_USER T3 ON T2.MS_MAY = T3.MS_MAY
			WHERE NGAY_KT BETWEEN DATEADD(DAY,-3,@TU_NGAY) AND DATEADD(DAY,3,@DEN_NGAY))
	) AS F 
						
	SELECT MONTH(T1.NGAY_KE) AS M,COUNT(T1.MS_MAY) AS TONG_DAT INTO #TONGTG_TEMP from #NGAYKEGSTT_TEMP  T1		
	GROUP BY MONTH(T1.NGAY_KE)
	
	
SELECT M.MS_LOAI_MAY,YEAR(T.NGAY_KT) AS Y,MONTH(T.NGAY_KT) AS M,COUNT(T.MS_MAY) AS COUNT_DAT INTO #TEMP_FINAL from #TEMP t
	INNER JOIN #NGAYKEGSTT_TEMP AS T1 ON T.MS_MAY=T1.MS_MAY AND T.MS_BO_PHAN=T1.MS_BO_PHAN AND T.MS_TS_GSTT=T1.MS_TS_GSTT
	INNER JOIN #MAY_USER M ON T1.MS_MAY=M.MS_MAY
	WHERE (T.MS_MAY IS NOT NULL AND T1.NGAY_KE BETWEEN DATEADD(DAY,-2,T.NGAY_KT) AND DATEADD(DAY,2,T.NGAY_KT)) 
	GROUP BY M.MS_LOAI_MAY,YEAR(T.NGAY_KT),MONTH(T.NGAY_KT)

	DECLARE @Columns NVARCHAR(MAX),@query NVARCHAR(MAX)
	SELECT @Columns = STUFF(
	 (SELECT  ', ' +QUOTENAME(CONVERT(VARCHAR,(convert(nvarchar,T.THANG)+'-'+convert(nvarchar,T.NAM)))) FROM
	 (SELECT DISTINCT v.THANG,v.NAM FROM ( SELECT T.thang,T.NAM,(T1.COUNT_DAT/tm.TONG_DAT)AS PHAN_TRAM FROM #Thang_Temp T
								LEFT JOIN (SELECT * FROM #TEMP_FINAL) T1 ON T.THANG=T1.M AND T.NAM=t1.y
								LEFT JOIN #TONGTG_TEMP tm ON T.thang=TM.M)as v) AS T
								ORDER BY T.NAM,T.THANG FOR XML PATH('')),1,2,'') 						
	SET @query = N'
	select ROW_NUMBER() OVER (ORDER BY TEN_LOAI_MAY ASC) AS STT,*
	from
	(
	 SELECT (convert(nvarchar,T.thang)+''-''+convert(nvarchar,T.NAM))as ThoiGian,T.TEN_LOAI_MAY, ( CONVERT(FLOAT,T1.COUNT_DAT)/CONVERT(FLOAT,tm.TONG_DAT)) AS PHAN_TRAM FROM #Thang_Temp T
	LEFT JOIN (SELECT * FROM #TEMP_FINAL) T1 ON T.THANG=T1.M AND T.NAM=t1.y AND T.MS_LOAI_MAY=T1.MS_LOAI_MAY
	LEFT JOIN #TONGTG_TEMP tm ON T.thang=TM.M
	) d
	pivot
	(
	  max(PHAN_TRAM)
	  for d.ThoiGian in ('+@Columns+')
	) piv ORDER BY TEN_LOAI_MAY;';
	EXEC (@query)
	
END
GO

