IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spBCPhanTramTuanThuBTDK')
   exec('CREATE PROCEDURE spBCPhanTramTuanThuBTDK AS BEGIN SET NOCOUNT ON; END')
GO



--spBCPhanTramTuanThuBTDK '01/01/2015','01/01/2016'
ALTER PROCEDURE spBCPhanTramTuanThuBTDK
	@TU_NGAY DATETIME,
	@DEN_NGAY DATETIME,
	@USERNAME VARCHAR (64) = 'ADMIN', 
	@LANGUAGE INT = 0,
	@MS_NHA_XUONG VARCHAR (50) = '-1', 
	@MS_HE_THONG INT = -1,
	@MS_LOAI_MAY VARCHAR(100) = '-1',
	@MS_NHOM_MAY VARCHAR(100)= '-1'
AS
BEGIN 


SELECT DISTINCT MS_MAY INTO #MAY_USER
	FROM [dbo].[MGetMayUserNgay](@DEN_NGAY,@USERNAME,@MS_NHA_XUONG,@MS_HE_THONG,-1,@MS_LOAI_MAY,@MS_NHOM_MAY,'-1',@LANGUAGE)


-- delete bang tam

	IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL DROP TABLE #TEMP
	IF OBJECT_ID('tempdb..#TONGTG_TEMP') IS NOT NULL DROP TABLE #TONGTG_TEMP
	IF OBJECT_ID('tempdb..#Thang_Temp') IS NOT NULL DROP TABLE #Thang_Temp

	SELECT  DATEPART(MONTH, DATEADD(MONTH, x.number, @Tu_Ngay))AS THANG,YEAR(DATEADD(MONTH, x.number, @Tu_Ngay)) AS NAM,MS_HT_BT,TEN_HT_BT INTO #Thang_Temp
			FROM    master.dbo.spt_values x,HINH_THUC_BAO_TRI
			WHERE   x.type = 'P'        
			AND     x.number <= DATEDIFF(MONTH, @Tu_Ngay, @Den_Ngay)

	--select MONTH(pbt.NGAY_NGHIEM_THU) AS M,SUM(SO_GIO) AS TONG_GIO INTO #TONGTG_TEMP from PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET pbt_ct
	--INNER JOIN (SELECT PBT.MS_PHIEU_BAO_TRI,HTBT.MS_HT_BT,PBT.NGAY_NGHIEM_THU FROM PHIEU_BAO_TRI PBT
	--			INNER JOIN LOAI_BAO_TRI LBT ON PBT.MS_LOAI_BT=LBT.MS_LOAI_BT
	--			INNER JOIN HINH_THUC_BAO_TRI HTBT ON LBT.MS_HT_BT=HTBT.MS_HT_BT ) AS PBT ON pbt_ct.MS_PHIEU_BAO_TRI=PBT.MS_PHIEU_BAO_TRI
	--where NGAY_NGHIEM_THU>=@Tu_Ngay AND NGAY_NGHIEM_THU<=@Den_Ngay
	--GROUP BY MONTH(pbt.NGAY_NGHIEM_THU) 

	SELECT MONTH(T1.NGAY_NGHIEM_THU) AS M,SUM(T2.SO_GIO) AS TONG_GIO INTO #TONGTG_TEMP
	FROM PHIEU_BAO_TRI T1 INNER JOIN PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI INNER JOIN 
		LOAI_BAO_TRI T3 ON T1.MS_LOAI_BT = T3.MS_LOAI_BT INNER JOIN HINH_THUC_BAO_TRI T4 ON T3.MS_HT_BT = T4.MS_HT_BT INNER JOIN 
		#MAY_USER T5 ON T1.MS_MAY = T5.MS_MAY
	WHERE NGAY_NGHIEM_THU>=@Tu_Ngay AND NGAY_NGHIEM_THU<=@Den_Ngay AND TINH_TRANG_PBT > = 3
	GROUP BY MONTH(T1.NGAY_NGHIEM_THU) 

	--select PBT.MS_HT_BT,YEAR(pbt.NGAY_NGHIEM_THU) AS y,MONTH(pbt.NGAY_NGHIEM_THU) AS M,SUM(SO_GIO) AS GIO INTO #TEMP from PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET pbt_ct
	--INNER JOIN (SELECT PBT.MS_PHIEU_BAO_TRI,HTBT.MS_HT_BT,HTBT.TEN_HT_BT,PBT.NGAY_NGHIEM_THU FROM PHIEU_BAO_TRI PBT
	--			INNER JOIN LOAI_BAO_TRI LBT ON PBT.MS_LOAI_BT=LBT.MS_LOAI_BT
	--			INNER JOIN HINH_THUC_BAO_TRI HTBT ON LBT.MS_HT_BT=HTBT.MS_HT_BT) AS PBT ON pbt_ct.MS_PHIEU_BAO_TRI=PBT.MS_PHIEU_BAO_TRI
	--where PBT.NGAY_NGHIEM_THU>=@Tu_Ngay AND PBT.NGAY_NGHIEM_THU<=@Den_Ngay
	--GROUP BY PBT.MS_HT_BT,YEAR(pbt.NGAY_NGHIEM_THU),MONTH(pbt.NGAY_NGHIEM_THU)


	SELECT T3.MS_HT_BT,YEAR(T1.NGAY_NGHIEM_THU) AS y,MONTH(T1.NGAY_NGHIEM_THU) AS M,SUM(SO_GIO) AS GIO INTO #TEMP
	FROM PHIEU_BAO_TRI T1 INNER JOIN PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI INNER JOIN 
		LOAI_BAO_TRI T3 ON T1.MS_LOAI_BT = T3.MS_LOAI_BT INNER JOIN HINH_THUC_BAO_TRI T4 ON T3.MS_HT_BT = T4.MS_HT_BT INNER JOIN 
		#MAY_USER T5 ON T1.MS_MAY = T5.MS_MAY
	WHERE NGAY_NGHIEM_THU>=@Tu_Ngay AND NGAY_NGHIEM_THU<=@Den_Ngay AND TINH_TRANG_PBT > = 3
	GROUP BY T3.MS_HT_BT,YEAR(T1.NGAY_NGHIEM_THU),MONTH(T1.NGAY_NGHIEM_THU)

	DECLARE @Columns NVARCHAR(4000),@query NVARCHAR(4000)
	SELECT @Columns = STUFF(
	 (SELECT  ', ' +QUOTENAME(CONVERT(VARCHAR,(convert(nvarchar,T.THANG)+'-'+convert(nvarchar,T.NAM)))) FROM
	 (SELECT DISTINCT v.THANG,v.NAM FROM ( SELECT T.thang,T.NAM,(T1.GIO/tm.TONG_GIO)AS PHAN_TRAM FROM #Thang_Temp T
								LEFT JOIN (SELECT * FROM #TEMP) T1 ON T.THANG=T1.M AND T.NAM=t1.y
								LEFT JOIN #TONGTG_TEMP tm ON T.thang=TM.M)as v) AS T
								ORDER BY T.NAM,T.THANG FOR XML PATH('')),1,2,'') 	
PRINT 	@Columns
											
	SET @query = N'
	select ROW_NUMBER() OVER (ORDER BY TEN_HT_BT ASC) AS STT,*
	from
	(
	 SELECT (convert(nvarchar,T.thang)+''-''+convert(nvarchar,T.NAM))as ThoiGian,T.TEN_HT_BT,(T1.GIO/tm.TONG_GIO)AS PHAN_TRAM FROM #Thang_Temp T
	LEFT JOIN (SELECT * FROM #TEMP) T1 ON T.THANG=T1.M AND T.NAM=t1.y AND T.MS_HT_BT=T1.MS_HT_BT
	LEFT JOIN #TONGTG_TEMP tm ON T.thang=TM.M
	) d
	pivot
	(
	  max(PHAN_TRAM)
	  for d.ThoiGian in ('+@Columns+')
	) piv ORDER BY TEN_HT_BT;';
	EXEC (@query)
END
