//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomaintSite.Resulst {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emailtemplete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emailtemplete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcomaintSite.Resulst.Emailtemplete", typeof(Emailtemplete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:13pt&quot;&gt;
        ///&lt;b style=&quot;text-align:center&quot;&gt;Yêu cầu bảo trì đã được duyệt&lt;/b&gt;
        ///    &lt;p&gt;Số yêu cầu: {0}&lt;/p&gt;
        ///    &lt;p&gt;User duyệt: {1}&lt;/p&gt;
        ///    &lt;p&gt;Người duyệt: {2}&lt;/p&gt;
        ///    &lt;p&gt;Ngày duyệt: {3}&lt;/p&gt;
        ///    &lt;p&gt;Giờ duyệt: {4}&lt;/p&gt;
        ///    &lt;p&gt;Nội dung duyệt: {5}&lt;/p&gt;
        /// &lt;b style=&quot;text-align:center&quot;&gt;DUYỆT YÊU CẦU BẢO TRÌ&lt;/b&gt;&lt;/br&gt;
        ///    &lt;table border=&quot;1&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; height=&quot;100%&quot; width=&quot;100%&quot; id=&quot;bodyTable&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Ms Máy&lt;/th&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DUYET_YCNSD {
            get {
                return ResourceManager.GetString("DUYET_YCNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot; style=&quot;color: mediumblue; text-decoration:none&quot;&gt;===&gt;Web EcomaintSite&lt;===&lt;/a&gt;.
        /// </summary>
        internal static string LINK_DUYET_YEU_CAU {
            get {
                return ResourceManager.GetString("LINK_DUYET_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///            &lt;td&gt;{0}&lt;/td&gt;
        ///            &lt;td&gt;{1}&lt;/td&gt;
        ///            &lt;td&gt;{2}&lt;/td&gt;
        ///            &lt;td&gt;{3}&lt;/td&gt;
        ///            &lt;td&gt;{4}&lt;/td&gt;
        ///            &lt;td&gt;{5}&lt;/td&gt;
        ///            &lt;td&gt;{6}&lt;/td&gt;
        ///            &lt;td&gt;{7}&lt;/td&gt;
        ///            &lt;td&gt;{8}&lt;/td&gt;
        ///        &lt;/tr&gt;.
        /// </summary>
        internal static string ROW_YEU_CAU_NSD {
            get {
                return ResourceManager.GetString("ROW_YEU_CAU_NSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:13pt&quot;&gt;
        ///    &lt;p&gt;Số yêu cầu: {0}&lt;/p&gt;
        ///    &lt;p&gt;User yêu cầu: {1}&lt;/p&gt;
        ///    &lt;p&gt;Người yêu cầu: {2}&lt;/p&gt;
        ///    &lt;p&gt;Ngày yêu cầu: {3}&lt;/p&gt;
        ///    &lt;p&gt;Giờ yêu cầu: {4}&lt;/p&gt;
        ///    &lt;p&gt;Ngày YC HT: {5}&lt;/p&gt;
        ///    &lt;b style=&quot;text-align:center&quot;&gt;YÊU CẦU BẢO TRÌ&lt;/b&gt;&lt;/br&gt;
        ///    &lt;table border=&quot;1&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; height=&quot;100%&quot; width=&quot;100%&quot; id=&quot;bodyTable&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Ms Máy&lt;/th&gt;
        ///            &lt;th&gt;Tên Máy&lt;/th&gt;
        ///            &lt;th&gt;Mô tả&lt;/th&gt;
        ///            &lt;th&gt;Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YEU_CAU_NSD {
            get {
                return ResourceManager.GetString("YEU_CAU_NSD", resourceCulture);
            }
        }
    }
}
