IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_PHIEUDENGHIXUATKHO')
   exec('CREATE PROCEDURE [dbo].[SP_PHIEUDENGHIXUATKHO] AS BEGIN SET NOCOUNT ON; END')
GO


ALTER PROC SP_PHIEUDENGHIXUATKHO
@MS_DH_XUAT_PT NVARCHAR(50)
AS

SELECT MS_DH_XUAT_PT,TEN_CONG_TY AS TEN_TO,LY_DO_XUAT FROM IC_DON_HANG_XUAT A INNER JOIN 
(
SELECT MS_KH AS MA,TEN_RUT_GON AS TEN ,TEN_CONG_TY, 1 as KH FROM KHACH_HANG 
union 

SELECT     dbo.CONG_NHAN.MS_CONG_NHAN, dbo.CONG_NHAN.HO  + ' ' +  dbo.CONG_NHAN.TEN, dbo.TO_PHONG_BAN.TEN_TO, 2 AS CN
FROM         dbo.CONG_NHAN INNER JOIN
                      dbo.[TO] ON dbo.CONG_NHAN.MS_TO = dbo.[TO].MS_TO1 INNER JOIN
                      dbo.TO_PHONG_BAN ON dbo.[TO].MS_TO = dbo.TO_PHONG_BAN.MS_TO
                      ) B ON A.NGUOI_NHAN = B.MA

WHERE A.MS_DH_XUAT_PT=	@MS_DH_XUAT_PT		

		  				
SELECT     dbo.IC_PHU_TUNG.TEN_PT, dbo.IC_DON_HANG_XUAT_VAT_TU.MS_PT, dbo.DON_VI_TINH.TEN_1, 
                      dbo.IC_DON_HANG_XUAT_VAT_TU.SO_LUONG_CTU, dbo.IC_DON_HANG_XUAT_VAT_TU.SO_LUONG_THUC_XUAT, 					
                      dbo.IC_DON_HANG_XUAT.GHI_CHU					
FROM     IC_DON_HANG_XUAT inner join dbo.IC_DON_HANG_XUAT_VAT_TU  on IC_DON_HANG_XUAT.MS_DH_XUAT_PT=IC_DON_HANG_XUAT_VAT_TU.MS_DH_XUAT_PT INNER JOIN					
                      dbo.IC_PHU_TUNG ON dbo.IC_DON_HANG_XUAT_VAT_TU.MS_PT = dbo.IC_PHU_TUNG.MS_PT INNER JOIN					
                      dbo.DON_VI_TINH ON dbo.IC_PHU_TUNG.DVT = dbo.DON_VI_TINH.DVT	
WHERE dbo.IC_DON_HANG_XUAT_VAT_TU.MS_DH_XUAT_PT=	@MS_DH_XUAT_PT			
