ALTER TABLE CONG_NHAN ALTER COLUMN HO NVARCHAR(50)
ALTER TABLE CONG_NHAN ALTER COLUMN TEN NVARCHAR(50)


ALTER TABLE W_CONG_NHAN ALTER COLUMN HO NVARCHAR(50)
ALTER TABLE W_CONG_NHAN ALTER COLUMN TEN NVARCHAR(50)