
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_IC_PHU_TUNG_HANG_SAN_XUAT]') AND parent_object_id = OBJECT_ID(N'[dbo].[IC_PHU_TUNG]'))
ALTER TABLE [dbo].[IC_PHU_TUNG] DROP CONSTRAINT [FK_IC_PHU_TUNG_HANG_SAN_XUAT]
GO

ALTER TABLE [dbo].[IC_PHU_TUNG]  WITH NOCHECK ADD  CONSTRAINT [FK_IC_PHU_TUNG_HANG_SAN_XUAT] FOREIGN KEY([MS_HSX])
REFERENCES [dbo].[HANG_SAN_XUAT] ([MS_HSX])
ON UPDATE CASCADE
GO


