
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PHIEU_BAO_TRI_CO__3EE99A8F]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO]'))
ALTER TABLE [dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO] DROP CONSTRAINT [FK__PHIEU_BAO_TRI_CO__3EE99A8F]

GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO_IC_PHU_TUNG]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO]'))
ALTER TABLE [dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO] DROP CONSTRAINT [FK_PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO_IC_PHU_TUNG]
GO



ALTER TABLE [dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO]  WITH CHECK ADD  CONSTRAINT [FK_PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO_IC_PHU_TUNG] FOREIGN KEY([MS_PT])
REFERENCES [dbo].[IC_PHU_TUNG] ([MS_PT])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO] CHECK CONSTRAINT [FK_PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO_IC_PHU_TUNG]