
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DS_QUY_TRINH]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[DS_QUY_TRINH](
		[MS_QT] [int] NOT NULL,
		[TEN_QT_V] [nvarchar](250) NULL,
		[TEN_QT_E] [nvarchar](250) NULL,
		[TEN_QT_H] [nvarchar](250) NULL,
	 CONSTRAINT [PK_DS_QUY_TRINH] PRIMARY KEY CLUSTERED 
	(
		[MS_QT] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END

