IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_DANH_GIA_SERVICE]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[PHIEU_BAO_TRI_DANH_GIA_SERVICE](
		[MS_PBT] [nvarchar](20) NOT NULL,
		[STT_EOR] [int] NOT NULL,
		[MS_DANH_GIA] [int] NOT NULL,
		[DIEM] [int] NULL,
	 CONSTRAINT [PK_PHIEU_BAO_TRI_DANH_GIA_SERVICE] PRIMARY KEY CLUSTERED 
	(
		[MS_PBT] ASC,
		[STT_EOR] ASC,
		[MS_DANH_GIA] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
	GO
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_DANH_GIA_SERVICE]') AND type in (N'U'))
BEGIN

	ALTER TABLE [dbo].[PHIEU_BAO_TRI_DANH_GIA_SERVICE]  WITH CHECK ADD  CONSTRAINT [FK_PHIEU_BAO_TRI_DANH_GIA_SERVICE_PHIEU_BAO_TRI_SERVICE] FOREIGN KEY([MS_PBT], [STT_EOR])
	REFERENCES [dbo].[PHIEU_BAO_TRI_SERVICE] ([MS_PHIEU_BAO_TRI], [STT])
	ON UPDATE CASCADE
	ON DELETE CASCADE
END	
	GO
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_DANH_GIA_SERVICE]') AND type in (N'U'))
BEGIN

	ALTER TABLE [dbo].[PHIEU_BAO_TRI_DANH_GIA_SERVICE] CHECK CONSTRAINT [FK_PHIEU_BAO_TRI_DANH_GIA_SERVICE_PHIEU_BAO_TRI_SERVICE]


END
