IF NOT EXISTS(SELECT TOP 1 1  FROM INFORMATION_SCHEMA.COLUMNS  WHERE     [TABLE_NAME] = 'CHUC_NANG'    AND [COLUMN_NAME] = 'MT_CN')
BEGIN
  ALTER TABLE [CHUC_NANG]
    ADD [MT_CN] NVARCHAR(1000) NULL
END

GO

UPDATE DBO.CHUC_NANG SET MT_CN=TEN_CHUC_NANG WHERE ISNULL(MT_CN,'') = ''

go

IF EXISTS (SELECT * FROM LANGUAGES WHERE FORM=N'frmNhomquyen' AND KEYWORD =N'MT_CN') UPDATE LANGUAGES SET VIETNAM=N'Mô tả', ENGLISH=N'Description', VIETNAM_OR=N'Mô tả', ENGLISH_OR=N'Description' WHERE FORM=N'frmNhomquyen' AND KEYWORD=N'MT_CN' ELSE INSERT INTO LANGUAGES(FORM,KEYWORD,VIETNAM,ENGLISH,VIETNAM_OR,ENGLISH_OR) VALUES(N'frmNhomquyen',N'MT_CN',N'Mô tả',N'Description',N'Mô tả',N'Description')
