
-- PHIEU BAO TRI CONG VIEC PHU TRO
if not exists(select * from sys.columns 
            where Name = N'NGAY_BDCV' and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CV_PHU_TRO'))
begin
    ALTER TABLE PHIEU_BAO_TRI_CV_PHU_TRO ADD NGAY_BDCV DATETIME
END   

GO

if not exists(select * from sys.columns 
            where Name = N'NGAY_KTCV' and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CV_PHU_TRO'))
begin
    ALTER TABLE PHIEU_BAO_TRI_CV_PHU_TRO ADD NGAY_KTCV DATETIME
END   



GO
UPDATE PHIEU_BAO_TRI_CV_PHU_TRO SET NGAY_BDCV = T1.NGAY_BD_KH FROM 
PHIEU_BAO_TRI T1 INNER JOIN PHIEU_BAO_TRI_CV_PHU_TRO T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI
WHERE T1.NGAY_BD_KH IS NOT NULL AND NGAY_BDCV IS NULL
GO
UPDATE PHIEU_BAO_TRI_CV_PHU_TRO SET NGAY_KTCV = T1.NGAY_KT_KH FROM 
PHIEU_BAO_TRI T1 INNER JOIN PHIEU_BAO_TRI_CV_PHU_TRO T2 ON T1.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI
WHERE T1.NGAY_KT_KH IS NOT NULL AND  NGAY_KTCV IS NULL



