	
	UPDATE PHIEU_BAO_TRI SET MS_TT_CT = T2.MS_TT_CT FROM PHIEU_BAO_TRI T1 INNER JOIN
	(SELECT * FROM (SELECT TOP 1 * FROM TINH_TRANG_PBT_CT WHERE STT = 1 ORDER BY MS_TT_CT) A
	UNION SELECT * FROM (SELECT TOP 1 * FROM TINH_TRANG_PBT_CT WHERE STT = 2 ORDER BY MS_TT_CT) B
	UNION SELECT * FROM (SELECT TOP 1 * FROM TINH_TRANG_PBT_CT WHERE STT = 3 ORDER BY MS_TT_CT) C
	UNION SELECT * FROM (SELECT TOP 1 * FROM TINH_TRANG_PBT_CT WHERE STT = 4 ORDER BY MS_TT_CT) D
	UNION SELECT * FROM (SELECT TOP 1 * FROM TINH_TRANG_PBT_CT WHERE STT = 5 ORDER BY MS_TT_CT) E) T2
	ON T2.STT = T1.TINH_TRANG_PBT 