

IF NOT EXISTS (SELECT * FROM SYS.COLUMNS
            WHERE NAME = N'CP_VT_NN_NGOAI_DM' AND Object_ID = Object_ID(N'KE_HOACH_TONG_THE'))
BEGIN
    ALTER TABLE KE_HOACH_TONG_THE ADD CP_VT_NN_NGOAI_DM BIGINT NULL
END   
IF NOT EXISTS (SELECT * FROM SYS.COLUMNS
            WHERE NAME = N'CP_VT_NGOAI_DM' AND Object_ID = Object_ID(N'KE_HOACH_TONG_THE'))
BEGIN
    ALTER TABLE KE_HOACH_TONG_THE ADD CP_VT_NGOAI_DM BIGINT NULL
END   
IF NOT EXISTS (SELECT * FROM SYS.COLUMNS
            WHERE NAME = N'CP_THUE_NGOAI' AND Object_ID = Object_ID(N'KE_HOACH_TONG_THE'))
BEGIN
    ALTER TABLE KE_HOACH_TONG_THE ADD CP_THUE_NGOAI BIGINT NULL
END   
