IF NOT EXISTS (SELECT * FROM SYS.COLUMNS
            WHERE NAME = N'UPDATE_NGAY_CUOI' AND Object_ID = Object_ID(N'PHIEU_BAO_TRI'))
BEGIN
    ALTER TABLE PHIEU_BAO_TRI ADD UPDATE_NGAY_CUOI DateTime
END   
