
if not exists(select * from sys.columns 
            where Object_ID = Object_ID(N'TRANSFER_TO'))
begin   
		CREATE TABLE [dbo].[TRANSFER_TO] (
			[ID]         INT           NOT NULL,
			[TRANSFER_TO_NAME]      NVARCHAR (30) NOT NULL,
			
		PRIMARY KEY CLUSTERED ([ID] ASC)
			
		);
END  

go

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_YEU_CAU_NSD_CHI_TIET_BO_PHAN_YEU_CAU_NSD_CHI_TIET]') AND parent_object_id = OBJECT_ID(N'[dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN]'))
ALTER TABLE [dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN] DROP CONSTRAINT [FK_YEU_CAU_NSD_CHI_TIET_BO_PHAN_YEU_CAU_NSD_CHI_TIET]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN]') AND type in (N'U'))
DROP TABLE [dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN](
	[STT] [int] NOT NULL,
	[MS_MAY] [nvarchar](30) NOT NULL,
	[STT_VAN_DE] [int] NOT NULL,
	[STT_BO_PHAN] [int] IDENTITY(1,1) NOT NULL,
	[MS_BO_PHAN] [nvarchar](30) NOT NULL,
	[MS_PT] [nvarchar](30) NOT NULL,
	[MS_VI_TRI_PT] [nvarchar](30) NULL,
 CONSTRAINT [PK_YEU_CAU_NSD_CHI_TIET_BO_PHAN] PRIMARY KEY CLUSTERED 
(
	[STT] ASC,
	[MS_MAY] ASC,
	[STT_VAN_DE] ASC,
	[STT_BO_PHAN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN]  WITH CHECK ADD  CONSTRAINT [FK_YEU_CAU_NSD_CHI_TIET_BO_PHAN_YEU_CAU_NSD_CHI_TIET] FOREIGN KEY([STT], [MS_MAY], [STT_VAN_DE])
REFERENCES [dbo].[YEU_CAU_NSD_CHI_TIET] ([STT], [MS_MAY], [STT_VAN_DE])
GO

ALTER TABLE [dbo].[YEU_CAU_NSD_CHI_TIET_BO_PHAN] CHECK CONSTRAINT [FK_YEU_CAU_NSD_CHI_TIET_BO_PHAN_YEU_CAU_NSD_CHI_TIET]
GO



