IF EXISTS(select * from sys.columns 
            where Name IN (N'NGAY') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		IF EXISTS (SELECT *   FROM sys.objects WHERE type_desc LIKE '%CONSTRAINT'
        AND OBJECT_NAME(OBJECT_ID)='PK_THOI_GIAN_NGUNG_MAY_PHU_TUNG')
        BEGIN 
        ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP CONSTRAINT PK_THOI_GIAN_NGUNG_MAY_PHU_TUNG
        END
        
		IF EXISTS (SELECT *   FROM sys.objects WHERE type_desc LIKE '%CONSTRAINT'
        AND OBJECT_NAME(OBJECT_ID)='FK_THOI_GIAN_NGUNG_MAY_PHU_TUNG_THOI_GIAN_NGUNG_MAY')
        BEGIN 
        ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP CONSTRAINT FK_THOI_GIAN_NGUNG_MAY_PHU_TUNG_THOI_GIAN_NGUNG_MAY
        END		
END

IF EXISTS(select * from sys.columns 
            where Name IN (N'NGAY') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP COLUMN NGAY
END

IF EXISTS(select * from sys.columns 
            where Name IN (N'TU_GIO') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP COLUMN TU_GIO
END

IF EXISTS(select * from sys.columns 
            where Name IN (N'DEN_NGAY') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP COLUMN DEN_NGAY
END

IF EXISTS(select * from sys.columns 
            where Name IN (N'DEN_GIO') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP COLUMN DEN_GIO
END


IF EXISTS(select * from sys.columns 
            where Name IN (N'DEN_GIO') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG DROP COLUMN DEN_GIO
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'NGUOI_GIAI_QUYET') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY ADD NGUOI_GIAI_QUYET NVARCHAR(250) NULL
END


IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'NGUYEN_NHAN') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY ADD NGUYEN_NHAN NVARCHAR(250) NULL
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'NGUYEN_NHAN_CU_THE') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY ADD NGUYEN_NHAN_CU_THE NVARCHAR(255) NULL
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'HIEN_TUONG') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY ADD HIEN_TUONG NVARCHAR(250) NULL
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'MS_LAN') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG ADD MS_LAN VARCHAR(50) NOT NULL DEFAULT ('') 
		ALTER TABLE THOI_GIAN_NGUNG_MAY_PHU_TUNG 
		ADD CONSTRAINT [PK_THOI_GIAN_NGUNG_MAY_PHU_TUNG] PRIMARY KEY CLUSTERED (MS_LAN ASC, [STT] ASC)

END
