
IF NOT EXISTS (SELECT * FROM SYS.COLUMNS
            WHERE NAME = N'MS_LOAI_CV' AND Object_ID = Object_ID(N'THONG_SO_GSTT'))
BEGIN
    ALTER TABLE THONG_SO_GSTT ADD MS_LOAI_CV smallint NULL
END   

GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_THONG_SO_GSTT_LOAI_CONG_VIEC]') AND parent_object_id = OBJECT_ID(N'[dbo].[THONG_SO_GSTT]'))
ALTER TABLE [dbo].[THONG_SO_GSTT] DROP CONSTRAINT [FK_THONG_SO_GSTT_LOAI_CONG_VIEC]
GO


ALTER TABLE [dbo].[THONG_SO_GSTT]  WITH CHECK ADD  CONSTRAINT [FK_THONG_SO_GSTT_LOAI_CONG_VIEC] FOREIGN KEY([MS_LOAI_CV])
REFERENCES [dbo].[LOAI_CONG_VIEC] ([MS_LOAI_CV])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[THONG_SO_GSTT] CHECK CONSTRAINT [FK_THONG_SO_GSTT_LOAI_CONG_VIEC]
GO
