IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'CaID') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_SO_LAN'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_SO_LAN ADD CaID INT NULL
END		
GO
IF NOT EXISTS(select * from sys.columns 
            where Name IN ( N'MS_NGUYEN_NHAN') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_SO_LAN'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_SO_LAN  ADD MS_NGUYEN_NHAN INT  NULL
		
END	
GO
IF NOT EXISTS(select * from sys.columns 
            where Name IN ( N'TRUONG_CA') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_SO_LAN'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_SO_LAN  ADD TRUONG_CA NVARCHAR(250)  NULL
		
END		
GO

IF  EXISTS(select * from sys.columns 
            where Name IN ( N'MS_CONG_NHAN') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY	DROP CONSTRAINT FK_THOI_GIAN_NGUNG_MAY_CONG_NHAN
		ALTER TABLE THOI_GIAN_NGUNG_MAY DROP COLUMN MS_CONG_NHAN
END

IF  EXISTS(select * from sys.columns 
            where Name IN ( N'NGAY_SUA') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN	
		ALTER TABLE THOI_GIAN_NGUNG_MAY DROP COLUMN NGAY_SUA
END
IF  EXISTS(select * from sys.columns 
            where Name IN ( N'GIO_SUA') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN	
		ALTER TABLE THOI_GIAN_NGUNG_MAY DROP COLUMN GIO_SUA
END

IF  EXISTS(select * from sys.columns 
            where Name IN ( N'STT') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN	
	
		ALTER TABLE THOI_GIAN_NGUNG_MAY	DROP CONSTRAINT FK_THOI_GIAN_NGUNG_MAY_NGUYEN_NHAN_HU_HONG
			ALTER TABLE THOI_GIAN_NGUNG_MAY DROP COLUMN STT
END

IF  EXISTS(select * from sys.columns 
            where Name IN ( N'MA_CODE') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN	
	
		ALTER TABLE THOI_GIAN_NGUNG_MAY	DROP CONSTRAINT FK_THOI_GIAN_NGUNG_MAY_THOI_GIAN_NGUNG_MAY_CODE
		ALTER TABLE THOI_GIAN_NGUNG_MAY DROP COLUMN MA_CODE
END


IF NOT EXISTS (select * from sys.columns 
            where Name IN ( N'MS_PHIEU_BAO_TRI') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_SO_LAN'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_SO_LAN ADD MS_PHIEU_BAO_TRI NVARCHAR(20) NULL
END
IF  EXISTS (select * from sys.columns 
            where Name IN ( N'LOCK') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY DROP COLUMN LOCK
END

IF NOT EXISTS (select * from sys.columns 
            where Name IN ( N'LOCK') and Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_SO_LAN'))
BEGIN
		ALTER TABLE THOI_GIAN_NGUNG_MAY_SO_LAN ADD LOCK BIT NULL
END