
if not exists(select * from sys.columns 
            where Object_ID = Object_ID(N'THOI_GIAN_NGUNG_MAY_PHU_TUNG'))
begin   
	CREATE TABLE [dbo].[THOI_GIAN_NGUNG_MAY_PHU_TUNG] (
    [MS_MAY]   NVARCHAR (30) NOT NULL,
    [NGAY]     DATETIME      NOT NULL,
    [TU_GIO]   DATETIME      NOT NULL,
    [DEN_NGAY] DATETIME      NOT NULL,
    [DEN_GIO]  DATETIME      NOT NULL,
    [STT]      INT           IDENTITY (1, 1) NOT NULL,
	[MS_BO_PHAN] NVARCHAR(50) NOT NULL,
    [MS_PT]    NVARCHAR (50) NULL
    CONSTRAINT [PK_THOI_GIAN_NGUNG_MAY_PHU_TUNG] PRIMARY KEY CLUSTERED ([MS_MAY] ASC, [NGAY] ASC, [TU_GIO] ASC, [DEN_NGAY] ASC, [DEN_GIO] ASC, [STT] ASC),
	CONSTRAINT [FK_THOI_GIAN_NGUNG_MAY_PHU_TUNG_THOI_GIAN_NGUNG_MAY] FOREIGN KEY ([MS_MAY], [NGAY], [TU_GIO], [DEN_NGAY], [DEN_GIO]) REFERENCES [THOI_GIAN_NGUNG_MAY] ([MS_MAY], [NGAY], [TU_GIO], [DEN_NGAY], [DEN_GIO]) 	
);
END  


