ALTER TABLE YEU_CAU_NSD_CHI_TIET ALTER COLUMN MO_TA_TINH_TRANG NVARCHAR(MAX)
ALTER TABLE YEU_CAU_NSD_CHI_TIET ALTER COLUMN YEU_CAU NVARCHAR(MAX)
ALTER TABLE YEU_CAU_NSD ALTER COLUMN USER_COMMENT NVARCHAR(MAX)
