IF EXISTS (SELECT * FROM   sys.columns WHERE  object_id = OBJECT_ID(N'PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG') AND name = 'MS_PT_TT')
begin
    ALTER TABLE PHIEU_BAO_TRI_CV_PHU_TRO_PHU_TUNG ALTER COLUMN MS_PT_TT [nvarchar](25) NULL
end 