
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NGAY_NGHI_NX]') AND type in (N'U'))
BEGIN

CREATE TABLE [dbo].[NGAY_NGHI_NX](
	[NGAY_NGHI] [date] NOT NULL,
	[MS_N_XUONG] [nvarchar](50) NOT NULL,
	[TU_GIO] [time](7) NULL,
	[DEN_GIO] [time](7) NULL,
	[SO_PHUT] [FLOAT] NULL,
 CONSTRAINT [PK_NGAY_NGHI_NX] PRIMARY KEY CLUSTERED 
(
	[NGAY_NGHI] ASC,
	[MS_N_XUONG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END


