
ALTER TABLE [dbo].[CAU_TRUC_THIET_BI_PHU_TUNG] DROP CONSTRAINT [DF_CAU_TRUC_THIET_BI_PHU_TUNG_SO_LUONG]
GO
ALTER TABLE CAU_TRUC_THIET_BI_PHU_TUNG ALTER COLUMN SO_LUONG FLOAT
GO
ALTER TABLE [dbo].[CAU_TRUC_THIET_BI_PHU_TUNG] ADD CONSTRAINT [DF_CAU_TRUC_THIET_BI_PHU_TUNG_SO_LUONG]  DEFAULT ((1)) FOR [SO_LUONG]
GO


