ALTER TABLE LANGUAGES ALTER COLUMN VIETNAM NVARCHAR(MAX)

ALTER TABLE LANGUAGES ALTER COLUMN ENGLISH NVARCHAR(MAX)

ALTER TABLE LANGUAGES ALTER COLUMN VIETNAM_OR NVARCHAR(MAX)

ALTER TABLE LANGUAGES ALTER COLUMN ENGLISH_OR NVARCHAR(MAX)