IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'NGAY_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO ADD NGAY_KH DATETIME
END
IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'TU_GIO_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO ADD TU_GIO_KH DATETIME
END
IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'DEN_GIO_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO ADD DEN_GIO_KH DATETIME
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'DEN_NGAY_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO ADD DEN_NGAY_KH DATETIME
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'TONG_GIO_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO ADD TONG_GIO_KH FLOAT
END

IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'NGAY_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET ADD NGAY_KH DATETIME
END
IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'TU_GIO_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET ADD TU_GIO_KH DATETIME
END
IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'DEN_NGAY_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET ADD DEN_NGAY_KH DATETIME
END
IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'DEN_GIO_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET ADD DEN_GIO_KH DATETIME
END
IF NOT EXISTS(select * from sys.columns 
            where Name IN (N'TONG_GIO_KH') and Object_ID = Object_ID(N'PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET'))
BEGIN
		ALTER TABLE PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET ADD TONG_GIO_KH FLOAT
END