
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PHIEU_BAO_TRI_NHAN_SU_PHIEU_BAO_TRI]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_NHAN_SU]'))
ALTER TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU] DROP CONSTRAINT [FK_PHIEU_BAO_TRI_NHAN_SU_PHIEU_BAO_TRI]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PHIEU_BAO_TRI_NHAN_SU_CONG_NHAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_NHAN_SU]'))
ALTER TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU] DROP CONSTRAINT [FK_PHIEU_BAO_TRI_NHAN_SU_CONG_NHAN]
GO

/****** Object:  Table [dbo].[PHIEU_BAO_TRI_NHAN_SU]    Script Date: 13/03/2018 09:21:53 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHIEU_BAO_TRI_NHAN_SU]') AND type in (N'U'))
	DROP TABLE PHIEU_BAO_TRI_NHAN_SU
GO

GO

/****** Object:  Table [dbo].[PHIEU_BAO_TRI_NHAN_SU]    Script Date: 13/03/2018 09:21:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU](
	[STT] [int] IDENTITY(1,1) NOT NULL,
	[MS_PHIEU_BAO_TRI] [nvarchar](20) NOT NULL,
	[MS_CONG_NHAN] [nvarchar](9) NOT NULL,
	[NGAY] [datetime] NULL,
	[TU_GIO] [datetime] NULL,
	[DEN_NGAY] [datetime] NULL,
	[DEN_GIO] [datetime] NULL,
	[HOAN_THANH] [bit] NULL,
	[SO_GIO] [float] NULL,
	[NGAY_KH] [datetime] NULL,
	[TU_GIO_KH] [datetime] NULL,
	[DEN_NGAY_KH] [datetime] NULL,
	[DEN_GIO_KH] [datetime] NULL,
	[TONG_GIO_KH] [float] NULL,
 CONSTRAINT [PK_PHIEU_BAO_TRI_NHAN_SU] PRIMARY KEY CLUSTERED 
(
	[STT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU]  WITH CHECK ADD  CONSTRAINT [FK_PHIEU_BAO_TRI_NHAN_SU_CONG_NHAN] FOREIGN KEY([MS_CONG_NHAN])
REFERENCES [dbo].[CONG_NHAN] ([MS_CONG_NHAN])
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU] CHECK CONSTRAINT [FK_PHIEU_BAO_TRI_NHAN_SU_CONG_NHAN]
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU]  WITH CHECK ADD  CONSTRAINT [FK_PHIEU_BAO_TRI_NHAN_SU_PHIEU_BAO_TRI] FOREIGN KEY([MS_PHIEU_BAO_TRI])
REFERENCES [dbo].[PHIEU_BAO_TRI] ([MS_PHIEU_BAO_TRI])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PHIEU_BAO_TRI_NHAN_SU] CHECK CONSTRAINT [FK_PHIEU_BAO_TRI_NHAN_SU_PHIEU_BAO_TRI]
GO


