

IF NOT EXISTS(SELECT * FROM DS_IMPORT WHERE MS_IMPORT = 90)
	INSERT INTO DS_IMPORT(MS_IMPORT,TEN_IMPORT,TEN_IMPORT_A,SU_DUNG,IMPORT,MS_IMPORT_CHA)
	SELECT 90,N'Danh mục loại thiết bị',N'Danh mục loại thiết bị',1,1,105

IF NOT EXISTS(SELECT * FROM CHUC_NANG WHERE STT = 110)
BEGIN
INSERT INTO CHUC_NANG(STT,TEN_CHUC_NANG,MT_CN)
VALUES (110,N'Import danh mục loại thiết bị',N'Import danh mục loại thiết bị')

INSERT INTO USER_CHUC_NANG(STT,USERNAME)
VALUES (110,N'admin')

INSERT INTO USER_CHUC_NANG(STT,USERNAME)
VALUES (110,N'administrator')

END

IF NOT EXISTS(SELECT * FROM DS_IMPORT WHERE MS_IMPORT = 91)
	INSERT INTO DS_IMPORT(MS_IMPORT,TEN_IMPORT,TEN_IMPORT_A,SU_DUNG,IMPORT,MS_IMPORT_CHA)
	SELECT 91,N'Danh mục nhóm thiết bị',N'Danh mục nhóm thiết bị',1,1,105

IF NOT EXISTS(SELECT * FROM CHUC_NANG WHERE STT = 111)
BEGIN
INSERT INTO CHUC_NANG(STT,TEN_CHUC_NANG,MT_CN)
VALUES (111,N'Import danh mục loại thiết bị',N'Import danh mục loại thiết bị')

INSERT INTO USER_CHUC_NANG(STT,USERNAME)
VALUES (111,N'admin')

INSERT INTO USER_CHUC_NANG(STT,USERNAME)
VALUES (111,N'administrator')
END 


IF EXISTS(SELECT * FROM DS_IMPORT WHERE MS_IMPORT = 6)
	UPDATE DS_IMPORT SET TEN_IMPORT = N'Danh mục dây chuyền',TEN_IMPORT_A = N'Danh mục dây chuyền',TEN_IMPORT_H = N'Danh mục dây chuyền' , MS_IMPORT_CHA = 105 WHERE MS_IMPORT = 6

IF EXISTS(SELECT * FROM CHUC_NANG WHERE STT = 26)
	UPDATE CHUC_NANG SET TEN_CHUC_NANG = N'Import Danh mục dây chuyền',TEN_CHUC_NANG_ANH = N'Import Danh mục dây chuyền' where STT = 26


IF EXISTS(SELECT * FROM DS_IMPORT WHERE MS_IMPORT = 7)
	UPDATE DS_IMPORT SET TEN_IMPORT = N'Danh mục bộ phận chịu phí',TEN_IMPORT_A = N'Danh mục bộ phận chịu phí',TEN_IMPORT_H = N'Danh mục bộ phận chịu phí' , MS_IMPORT_CHA = 105 WHERE MS_IMPORT = 7

IF EXISTS(SELECT * FROM CHUC_NANG WHERE STT = 27)
	UPDATE CHUC_NANG SET TEN_CHUC_NANG = N'Import Danh mục bộ phận chịu phí',TEN_CHUC_NANG_ANH = N'Import Danh mục bộ phận chịu phí' where STT = 27


