IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DON_VI_THOI_GIAN_MAU]') AND type in (N'U'))
BEGIN

CREATE TABLE [dbo].[DON_VI_THOI_GIAN_MAU](
	[MS_DV_TG] [INT] NOT NULL,
	[R] [INT] NULL,
	[G] [INT] NULL,
	[B] [INT] NULL,
 CONSTRAINT [PK_DON_VI_THOI_GIAN_MAU] PRIMARY KEY CLUSTERED 
(
	[MS_DV_TG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[DON_VI_THOI_GIAN_MAU] ADD  CONSTRAINT [DF_DON_VI_THOI_GIAN_MAU_R]  DEFAULT ((0)) FOR [R]


ALTER TABLE [dbo].[DON_VI_THOI_GIAN_MAU] ADD  CONSTRAINT [DF_DON_VI_THOI_GIAN_MAU_G]  DEFAULT ((0)) FOR [G]


ALTER TABLE [dbo].[DON_VI_THOI_GIAN_MAU] ADD  CONSTRAINT [DF_DON_VI_THOI_GIAN_MAU_B]  DEFAULT ((0)) FOR [B]


ALTER TABLE [dbo].[DON_VI_THOI_GIAN_MAU]  WITH CHECK ADD  CONSTRAINT [FK_DON_VI_THOI_GIAN_MAU_DON_VI_THOI_GIAN] FOREIGN KEY([MS_DV_TG])
REFERENCES [dbo].[DON_VI_THOI_GIAN] ([MS_DV_TG])
ON UPDATE CASCADE
ON DELETE CASCADE


ALTER TABLE [dbo].[DON_VI_THOI_GIAN_MAU] CHECK CONSTRAINT [FK_DON_VI_THOI_GIAN_MAU_DON_VI_THOI_GIAN]

INSERT INTO	dbo.DON_VI_THOI_GIAN_MAU(MS_DV_TG)
SELECT MS_DV_TG FROM dbo.DON_VI_THOI_GIAN 
WHERE MS_DV_TG NOT IN(SELECT MS_DV_TG FROM dbo.DON_VI_THOI_GIAN_MAU )
ORDER BY MS_DV_TG
END