if NOT exists(SELECT * FROM CHUC_NANG WHERE STT = 113)
	INSERT INTO CHUC_NANG (STT,TEN_CHUC_NANG) VALUES (113,N'Import phiếu nhập theo ngày.')
GO
if NOT exists(SELECT * FROM DS_IMPORT WHERE MS_IMPORT = 93)
	INSERT INTO DS_IMPORT(MS_IMPORT, TEN_IMPORT,SU_DUNG,IMPORT,MS_IMPORT_CHA)	values (93, N'Thêm phiếu nhập theo ngày',1,1,102)

GO

