
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'TF' AND name = 'MGetUserMayHTCha')
   exec('CREATE FUNCTION  dbo.MGetUserMayHTCha ()returns  @MAY_NGAY_CUOI TABLE ([MS_MAY] [nvarchar](30) NOT NULL) as begin return end')
GO


--	SELECT * FROM [dbo].[MGetUserMayHTCha](2,'admin','01/01/2019',1)  WHERE MS_MAY = 'BUE-01-01'

ALTER FUNCTION [MGetUserMayHTCha]
(
	@MsHeThong NVARCHAR(50),
	@UName NVARCHAR(50),
	@NgayHT DATETIME,
	@NNgu INT
)

returns  @MayHeThong TABLE (MS_MAY NVARCHAR(50),MS_HE_THONG INT,TEN_HE_THONG NVARCHAR(500), NGAY DATETIME,MS_CHA NVARCHAR(50))
as
begin	
	INSERT INTO @MayHeThong(MS_MAY,MS_HE_THONG,TEN_HE_THONG,NGAY, MS_CHA)
		SELECT DISTINCT T1.MS_MAY, T1.MS_HE_THONG,TEN_HE_THONG, MAY_MAX.NGAY_MAX,
			@MsHeThong AS MS_CHA
		FROM         dbo.MAY_HE_THONG T1 INNER JOIN
		(SELECT     MS_MAY, MAX(NGAY_NHAP) AS NGAY_MAX FROM dbo.MAY_HE_THONG AS T1
		WHERE (NGAY_NHAP <= @NgayHT) GROUP BY MS_MAY) AS MAY_MAX 
		ON T1.MS_MAY = MAY_MAX.MS_MAY AND T1.NGAY_NHAP = MAY_MAX.NGAY_MAX INNER JOIN
		(SELECT MS_HE_THONG,TEN_HE_THONG FROM [dbo].[MashjGetHTUser](@MsHeThong,@UName,@NgayHT,@NNgu)) A 
		ON T1.MS_HE_THONG = A.MS_HE_THONG
		ORDER BY T1.MS_MAY

return 
end


GO

