
--IF NOT EXISTS (SELECT * FROM sys.objects WHERE type in (N'FN', N'IF', N'TF', N'FS', N'FT') AND name = 'MashjGetHTUser')
--   exec('CREATE FUNCTION  dbo.MashjGetHTUser () RETURNS @NXTMP TABLE (MS_HE_THONG INT) as Begin return null end')
--GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'TF' AND name = 'MashjGetHTUser')
   exec('CREATE FUNCTION  dbo.MashjGetHTUser ()returns  @MAY_NGAY_CUOI TABLE ([MS_MAY] [nvarchar](30) NOT NULL) as begin return end')
GO

--SELECT * FROM [dbo].[MashjGetHTUser](-1,'ADMIN','01/01/2019',1)

ALTER FUNCTION [dbo].[MashjGetHTUser]
(
	@MsHeThong INT,
	@UName NVARCHAR(50),
	@NgayHT DATETIME,
	@NNgu INT
)
returns  @NXTMP TABLE (MS_HE_THONG INT NULL, TEN_HE_THONG NVARCHAR(500) NULL)
as
begin
DECLARE @HT TABLE (MS_HE_THONG INT NULL, TEN_HE_THONG NVARCHAR(500) NULL)
IF  @MsHeThong = -1
	INSERT INTO @HT (MS_HE_THONG,TEN_HE_THONG)
	SELECT MS_HE_THONG,CASE @NNgu WHEN 0 THEN TEN_HE_THONG WHEN 1 THEN ISNULL(NULLIF(TEN_HE_THONG_ANH,''),TEN_HE_THONG) ELSE ISNULL(NULLIF(TEN_HE_THONG_HOA,''),TEN_HE_THONG) END  AS TEN_HE_THONG FROM dbo.HE_THONG 
ELSE
BEGIN


	DECLARE @NewInsertCount int;
	
	INSERT INTO @HT(MS_HE_THONG,TEN_HE_THONG)
	SELECT MS_HE_THONG,CASE @NNgu WHEN 0 THEN TEN_HE_THONG WHEN 1 THEN ISNULL(NULLIF(TEN_HE_THONG_ANH,''),TEN_HE_THONG) ELSE ISNULL(NULLIF(TEN_HE_THONG_HOA,''),TEN_HE_THONG) END  AS TEN_HE_THONG FROM dbo.HE_THONG WHERE MS_HE_THONG = @MsHeThong ;
	SET @NewInsertCount = @@ROWCOUNT;
	WHILE @NewInsertCount > 0
	BEGIN
		INSERT INTO @HT(MS_HE_THONG,TEN_HE_THONG) 
			SELECT MS_HE_THONG,CASE @NNgu WHEN 0 THEN TEN_HE_THONG WHEN 1 THEN ISNULL(NULLIF(TEN_HE_THONG_ANH,''),TEN_HE_THONG) ELSE ISNULL(NULLIF(TEN_HE_THONG_HOA,''),TEN_HE_THONG) END  AS TEN_HE_THONG FROM dbo.HE_THONG WHERE EXISTS
				   (SELECT MS_HE_THONG  FROM @HT A
					WHERE HE_THONG.MS_CHA = A.MS_HE_THONG)
			 AND  NOT EXISTS
				  (SELECT MS_HE_THONG FROM @HT B
				   WHERE HE_THONG.MS_HE_THONG  = B.MS_HE_THONG);
			 SET @NewInsertCount = @@ROWCOUNT;
	END
END	

IF @UName = '-1'
	INSERT INTO @NXTMP(MS_HE_THONG,TEN_HE_THONG)
	SELECT MS_HE_THONG,TEN_HE_THONG FROM @HT 
ELSE	
	INSERT INTO @NXTMP(MS_HE_THONG,TEN_HE_THONG)
	SELECT MS_HE_THONG,A.TEN_HE_THONG FROM @HT A WHERE MS_HE_THONG IN ( SELECT MS_HE_THONG
	FROM dbo.NHOM INNER JOIN dbo.NHOM_HE_THONG ON dbo.NHOM.GROUP_ID = dbo.NHOM_HE_THONG.GROUP_ID 
	INNER JOIN dbo.USERS ON dbo.NHOM.GROUP_ID = dbo.USERS.GROUP_ID 
	WHERE dbo.USERS.USERNAME =@UName )

return 
end


GO

