

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KHSX_NGAY]') AND type in (N'U'))
BEGIN

CREATE TABLE [dbo].[KHSX_NGAY](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[MS_HE_THONG] [INT] NULL,
	[MS_N_XUONG] [NVARCHAR](50) NULL,
	[NGAY] [DATE] NULL,
	[GIO_KH] [FLOAT] NULL,
	[GHI_CHU] [NVARCHAR](100) NULL,
	[LOAI] [int] NULL,
 CONSTRAINT [PK_KHSX_NGAY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END
