IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GSTT_CV]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[GSTT_CV]
(
[MS_TS_GSTT] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MS_CV] [int] NOT NULL,
[GHI_CHU] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[GSTT_CV] ADD CONSTRAINT [PK_GSTT_CV] PRIMARY KEY CLUSTERED  ([MS_TS_GSTT], [MS_CV]) ON [PRIMARY]

ALTER TABLE [dbo].[GSTT_CV] ADD CONSTRAINT [FK_GSTT_CV_CONG_VIEC] FOREIGN KEY ([MS_CV]) REFERENCES [dbo].[CONG_VIEC] ([MS_CV])

ALTER TABLE [dbo].[GSTT_CV] ADD CONSTRAINT [FK_GSTT_CV_GSTT_CV] FOREIGN KEY ([MS_TS_GSTT]) REFERENCES [dbo].[THONG_SO_GSTT] ([MS_TS_GSTT]) 
END

