

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'TR' AND name = 'DELETE_TON_KHO_X')
   exec('CREATE TRIGGER [dbo].[DELETE_TON_KHO_X] ON  [dbo].[IC_DON_HANG_NHAP_X_VAT_TU_CHI_TIET] AFTER INSERT AS BEGIN SET NOCOUNT ON; SELECT 1  END')
GO
go


ALTER TRIGGER [dbo].[DELETE_TON_KHO_X]
   ON  [dbo].[IC_DON_HANG_NHAP_X_VAT_TU_CHI_TIET]
   FOR DELETE
AS 
BEGIN		
	DELETE dbo.VI_TRI_KHO_VAT_TU_X
	FROM dbo.VI_TRI_KHO_VAT_TU_X INNER JOIN dbo.IC_DON_HANG_NHAP_X ON 
	dbo.VI_TRI_KHO_VAT_TU_X.MS_KHO = dbo.IC_DON_HANG_NHAP_X.MS_KHO AND 
	dbo.VI_TRI_KHO_VAT_TU_X.MS_DH_NHAP_PT = dbo.IC_DON_HANG_NHAP_X.MS_DH_NHAP_PT INNER JOIN DELETED	ON 
	dbo.IC_DON_HANG_NHAP_X.MS_DH_NHAP_PT = DELETED.MS_DH_NHAP_PT 
	AND dbo.VI_TRI_KHO_VAT_TU_X.MS_VI_TRI = DELETED.MS_VI_TRI 
	AND dbo.VI_TRI_KHO_VAT_TU_X.MS_PT = DELETED.MS_PT 
	WHERE dbo.VI_TRI_KHO_VAT_TU_X.SL_VT<=0
END

GO

ALTER TABLE [dbo].[IC_DON_HANG_NHAP_X_VAT_TU_CHI_TIET] ENABLE TRIGGER [DELETE_TON_KHO_X]
GO


