--SELECT * FROM dbo.DON_VI_THOI_GIAN_MAU ORDER BY MS_DV_TG
UPDATE	dbo.DON_VI_THOI_GIAN SET	R = 255 , G = 204 , B = 255 WHERE MS_DV_TG = 1 AND R+G+B <> 0 --NGAY

UPDATE	dbo.DON_VI_THOI_GIAN SET	R = 255 , G = 236 , B = 255 WHERE MS_DV_TG = 2 AND R+G+B <> 0 --TUAN

UPDATE	dbo.DON_VI_THOI_GIAN SET	R = 204 , G = 255 , B = 153 WHERE MS_DV_TG = 3  AND R+G+B <> 0--THANG

UPDATE	dbo.DON_VI_THOI_GIAN SET	R = 255 , G = 255 , B = 153 WHERE MS_DV_TG = 4  AND R+G+B <> 0--NAM


UPDATE	dbo.DON_VI_THOI_GIAN_MAU SET	R = 255 , G = 204 , B = 255 WHERE MS_DV_TG = 1 AND R+G+B <> 0 --NGAY

UPDATE	dbo.DON_VI_THOI_GIAN_MAU SET	R = 255 , G = 236 , B = 255 WHERE MS_DV_TG = 2 AND R+G+B <> 0 --TUAN

UPDATE	dbo.DON_VI_THOI_GIAN_MAU SET	R = 204 , G = 255 , B = 153 WHERE MS_DV_TG = 3  AND R+G+B <> 0--THANG

UPDATE	dbo.DON_VI_THOI_GIAN_MAU SET	R = 255 , G = 255 , B = 153 WHERE MS_DV_TG = 4  AND R+G+B <> 0--NAM
