IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[MENU_OEE]') AND type in (N'U'))

BEGIN

CREATE TABLE [dbo].[MENU_OEE](
	[MENU_ID] [NVARCHAR](255) NOT NULL,
	[MENU_TEXT] [NVARCHAR](255) NULL,
	[MENU_ENGLISH] [NVARCHAR](255) NULL,
	[MENU_CHINESE] [NVARCHAR](255) NULL,
	[MENU_PARENT] [VARCHAR](64) NULL,
	[MENU_LINE] [BIT] NULL,
	[MENU_INDEX] [NUMERIC](10, 0) NOT NULL,
	[SHORT_KEY] [NVARCHAR](150) NULL,
	[DLL_NAME] [VARCHAR](64) NULL,
	[CLASS_NAME] [VARCHAR](64) NULL,
	[FUNCTION_NAME] [VARCHAR](64) NULL,
	[CUSTUMER] [NVARCHAR](512) NULL,
	[NOTE] [NVARCHAR](512) NULL,
	[MENU_IMAGE] [IMAGE] NULL,
	[PROJECT_NAME] [NVARCHAR](128) NULL,
	[MENU_NOTE] [NVARCHAR](255) NULL,
	[MENU_FONT] [VARCHAR](150) NULL,
	[MENU_POSITION] [INT] NULL,
	[MENU_TYPE] [INT] NULL,
	[AN_HIEN] [BIT] NULL,
 CONSTRAINT [PK_MENU_OEE] PRIMARY KEY CLUSTERED 
(
	[MENU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


END