
DECLARE @frmname NVARCHAR(100) = 'frmDDNhom'
DECLARE @frmnameMH NVARCHAR(100) = N'ΐΨΞ͌͌͠Δ΢Ξ'

IF NOT EXISTS (SELECT * FROM CHI_TIET_FORMS WHERE FORM_NAME = @frmname)
BEGIN
	INSERT INTO CHI_TIET_FORMS(FORM_NAME, TEN_FORMS_VIET, TEN_FORMS_ANH ) VALUES (@frmname, N'5.7.4. Nhóm điều độ', N'5.7.4. Nhóm điều độ')
END

IF NOT EXISTS (SELECT * FROM NHOM_FORM  WHERE FORM_NAME = @frmname AND GROUP_ID = 1)
BEGIN
	INSERT INTO NHOM_FORM(GROUP_ID,FORM_NAME) VALUES (1,@frmname)
END


IF NOT EXISTS (SELECT * FROM LIC_FORM WHERE FORM_NAME  = @frmnameMH)
	INSERT INTO LIC_FORM (FORM_NAME,TYPE_LIC) VALUES ( @frmnameMH,N'̦')
	
GO

DECLARE @frmname NVARCHAR(100) = 'frmDDNhomCNhan'
DECLARE @frmnameMH NVARCHAR(100) = N'ΐΨΞ͌͌͠Δ΢Ξ͊͠ΔΆΠ'

IF NOT EXISTS (SELECT * FROM CHI_TIET_FORMS WHERE FORM_NAME = @frmname)
BEGIN
	INSERT INTO CHI_TIET_FORMS(FORM_NAME, TEN_FORMS_VIET, TEN_FORMS_ANH ) VALUES (@frmname, N'5.7.3. Nhóm điều độ công nhân', N'5.7.3. Nhóm điều độ công nhân')
END

IF NOT EXISTS (SELECT * FROM NHOM_FORM  WHERE FORM_NAME = @frmname AND GROUP_ID = 1)
BEGIN
	INSERT INTO NHOM_FORM(GROUP_ID,FORM_NAME) VALUES (1,@frmname)
END

IF NOT EXISTS (SELECT * FROM LIC_FORM WHERE FORM_NAME  = @frmnameMH)
	INSERT INTO LIC_FORM (FORM_NAME,TYPE_LIC) VALUES ( @frmnameMH,N'̦')
	
GO

DECLARE @frmname NVARCHAR(100) = 'frmDDNhomMay'
DECLARE @frmnameMH NVARCHAR(100) = N'ΐΨΞ͌͌͠Δ΢Ξ͞Άζ'

IF NOT EXISTS (SELECT * FROM CHI_TIET_FORMS WHERE FORM_NAME = @frmname)
BEGIN
	INSERT INTO CHI_TIET_FORMS(FORM_NAME, TEN_FORMS_VIET, TEN_FORMS_ANH ) VALUES (@frmname, N'5.7.2. Nhóm điều độ máy', N'5.7.2. Nhóm điều độ máy')
END

IF NOT EXISTS (SELECT * FROM NHOM_FORM  WHERE FORM_NAME = @frmname AND GROUP_ID = 1)
BEGIN
	INSERT INTO NHOM_FORM(GROUP_ID,FORM_NAME) VALUES (1,@frmname)
END

IF NOT EXISTS (SELECT * FROM LIC_FORM WHERE FORM_NAME  = @frmnameMH)
	INSERT INTO LIC_FORM (FORM_NAME,TYPE_LIC) VALUES ( @frmnameMH,N'̦')
	
GO

DECLARE @frmname NVARCHAR(100) = 'frmDieuDo'
DECLARE @frmnameMH NVARCHAR(100) = N'ΐΨΞ͌ΖΎή͌΢'

IF NOT EXISTS (SELECT * FROM CHI_TIET_FORMS WHERE FORM_NAME = @frmname)
BEGIN
	INSERT INTO CHI_TIET_FORMS(FORM_NAME, TEN_FORMS_VIET, TEN_FORMS_ANH ) VALUES (@frmname, N'5.7.1. Điều độ', N'5.7.1. Điều độ')
END

IF NOT EXISTS (SELECT * FROM NHOM_FORM  WHERE FORM_NAME = @frmname AND GROUP_ID = 1)
BEGIN
	INSERT INTO NHOM_FORM(GROUP_ID,FORM_NAME) VALUES (1,@frmname)
END

IF NOT EXISTS (SELECT * FROM LIC_FORM WHERE FORM_NAME  = @frmnameMH)
	INSERT INTO LIC_FORM (FORM_NAME,TYPE_LIC) VALUES ( @frmnameMH,N'̦')
	