IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[DD_LUOI]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DD_LUOI]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ID_FORM] [nvarchar] (50) NULL,
[ID_GRID] [nvarchar] (50) NULL,
[ID_XML]  XML NULL,
[ID_GOC] XML NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
ALTER TABLE [dbo].[DD_LUOI] ADD CONSTRAINT [PK_DD_LUOI] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
END