
DECLARE @Report nvarchar(500)
set @Report = N'ήΊ͌ΆΠΔͪΆΊΔͤΔΖΎή͠ΔΆΤ͚Δ΢'

IF NOT EXISTS (SELECT * FROM LIC_REPORT WHERE REPORT_NAME = @Report)
INSERT INTO LIC_REPORT (REPORT_NAME,TYPE_LIC) VALUES ( @Report,N'̦')
	
GO

IF NOT EXISTS (SELECT * FROM DS_REPORT WHERE REPORT_NAME = N'ucDanhSachPhieuNhapKho')
INSERT INTO DS_REPORT(REPORT_NAME,TEN_REPORT_VIET,TEN_REPORT_ANH, LOAI_REPORT,STT,NOTE,NAMES,[TYPE],REPORT_MAIL)
VALUES(N'ucDanhSachPhieuNhapKho', N'Danh sách phiếu nhập kho',N'List of receipts',10,5, N'Danh sách phiếu nhập kho','ucDanhSachPhieuNhapKho',2,1)

go
IF NOT EXISTS (SELECT * FROM NHOM_REPORT WHERE REPORT_NAME = N'ucDanhSachPhieuNhapKho')
INSERT INTO NHOM_REPORT(REPORT_NAME,GROUP_ID,QUYEN)
VALUES(N'ucDanhSachPhieuNhapKho', 1,N'Access')


	