IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_YEU_CAU_NSD_CHI_TIET_BO_PHAN_XOA')
exec('CREATE PROCEDURE SP_YEU_CAU_NSD_CHI_TIET_BO_PHAN_XOA AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[SP_YEU_CAU_NSD_CHI_TIET_BO_PHAN_XOA]
	@ID int = 12
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @res_code INT = 0
	BEGIN
		DELETE dbo.YEU_CAU_NSD_CHI_TIET_BO_PHAN WHERE STT_BO_PHAN = @ID
		SET @res_code = 1
	END
	SELECT  @res_code ResponseCode
END

